langflow/backend/langflow_backend/__main__.py

Gunicorn is a linux/mac thing and can't run on Windows. This should fix it.
#25

Windows now uses Uvicorn

---

src/frontend/package-lock.json
src/frontend/package.json
src/frontend/src/App.tsx
src/frontend/src/CustomNodes/GenericNode/index.tsx
src/frontend/src/components/CrashErrorComponent/index.tsx
src/frontend/src/components/chatComponent/index.tsx
src/frontend/src/contexts/index.tsx
src/frontend/src/contexts/tabsContext.tsx
src/frontend/src/index.tsx
src/frontend/src/modals/exportModal/index.tsx
src/frontend/src/modals/importModal/buttonBox/index.tsx
src/frontend/src/modals/importModal/index.tsx
src/frontend/src/pages/FlowPage/components/DisclosureComponent/index.tsx
src/frontend/src/pages/FlowPage/components/extraSidebarComponent/index.tsx
src/frontend/src/pages/FlowPage/components/tabsManagerComponent/index.tsx
src/frontend/src/pages/FlowPage/index.tsx
src/frontend/src/types/api/index.ts
src/frontend/src/types/flow/index.ts
src/frontend/src/types/tabs/index.ts
src/frontend/src/utils.ts

- Added descriptions to the flows to provide more context.
- Sorted some context providers to improve readability and organization.
- Implemented error handling for the entire application to ensure smoother operation.
- Added a reset state feature to the application in the event of an error.
- Created new UI components for the export and import flows to enhance user experience.
- Implemented a feature to automatically remove API keys during the export flow for added security.

UI updates

---

src/backend/langflow/config.yaml
src/backend/langflow/custom/customs.py
src/backend/langflow/graph/base.py
src/backend/langflow/graph/graph.py
src/backend/langflow/interface/agents/base.py
src/backend/langflow/interface/agents/custom.py
src/backend/langflow/interface/agents/prebuilt.py
src/backend/langflow/interface/base.py
src/backend/langflow/interface/custom_lists.py
src/backend/langflow/interface/importing/utils.py
src/backend/langflow/interface/prompts/custom.py
src/backend/langflow/interface/run.py
src/backend/langflow/template/base.py
src/backend/langflow/template/constants.py
src/backend/langflow/template/nodes.py
src/backend/langflow/utils/util.py
src/frontend/src/components/dropdownComponent/index.tsx
tests/conftest.py
tests/data/Openapi.json
tests/test_graph.py
tests/test_template.py

This PR adds an implementation of initialize_agent to make it easier to run scenarios like this: [Conversation Agent](https://python.langchain.com/en/latest/modules/agents/agents/examples/conversational_agent.html)
Memories are working too and require testing regarding caching.

Added initialize_agent and Memory

---

README.md

When I was trying to get started with LangFlow I didn't realize the local development setup was in the contributing documentation. I though adding a link in the readme would be a good place to start, but maybe in the future we can bring the local development setup instructions into the readme.

Add contrib link to readme

---

.devcontainer/demo/README.md
.devcontainer/demo/devcontainer.json
.devcontainer/devcontainer.json

Partially resolves #196 (No demo workflow yet, but UI launches successfully.)
**Important:**
1. I've tested this locally in VS Code successfully - the `postCreateCommand` performs _both_ the install of `langflow` from pip (via pipx) and also the launching of `langflow` UI. VS Code also helpfully told me when the new port had been opened and I could simply click the button to open the site in a browser tap.
2. Page functions in the UI seem to be working great.
3. I have **not** yet tested this in Codespaces, but something other than the default 2-CPU image might be warranted here.
4. The new README could use some more work, admittedly, but as of now at least, it tells the audience what to expect from the container.
Can be tested with this link: [Create new …

feat: add demo devcontainer

---

src/frontend/src/pages/FlowPage/hooks/useUndoRedo.ts
src/frontend/src/pages/FlowPage/index.tsx

This Pull Request implements four new features in the langflow Workflow project:
- Copy and Paste feature for multiple nodes
- Undo and Redo feature for node actions
The Copy and Paste feature allows users to select multiple nodes by holding down the `Shift` key and dragging the mouse over the nodes, copy them using the `Ctrl+C` keyboard shortcut, and paste them into a different location within the workflow by leaving the mouse pointer at the desired location and pressing `Ctrl+V`.
The Undo and Redo feature allows users to undo and redo actions on the workflow nodes using the `Ctrl+Z` and `Ctrl+Shift+Z` keyboard shortcuts, respectively. When a user undoes an action, the state of the nodes in the workflow is reverted to the previous state. Similarly, when a user redoes an action, the state …

Copy Paste, Undo and Redo implemented

---

src/frontend/index.html
src/frontend/package-lock.json
src/frontend/package.json
src/frontend/postcss.config.js
src/frontend/src/App.tsx
src/frontend/src/components/chatComponent/chatMessage/index.tsx
src/frontend/src/components/chatComponent/index.tsx
src/frontend/src/components/inputListComponent/index.tsx
src/frontend/src/contexts/alertContext.tsx
src/frontend/src/contexts/tabsContext.tsx
src/frontend/src/index.css
src/frontend/src/index.tsx
src/frontend/src/modals/ApiModal/index.tsx
src/frontend/src/modals/chatModal/chatMessage/index.tsx
src/frontend/src/modals/chatModal/index.tsx
src/frontend/src/modals/codeAreaModal/index.tsx
src/frontend/src/pages/FlowPage/components/tabComponent/index.tsx
src/frontend/src/pages/FlowPage/index.tsx
src/frontend/src/utils.ts
src/frontend/tailwind.config.js
src/frontend/vite.config.ts

This PR implements #264
- Organized package.json for dev only dependencies.
- Removed react-scripts and added Vite and its dependencies.
- Refactored `require` with `import` in few places.
- Most of the development workflow is unchanged with this migration.
- For any API call to backend, the path must be added in the `vite.config.ts` so that vite server can forward it to backend server via proxy. This can be standardized with naming conventions so that we can simply configure regular expressions and forget about it.

migrating to Vite

---

src/frontend/src/contexts/typesContext.tsx

This commit adds retry logic to the getAll API call in the TypesProvider component. The retry logic will attempt to make the API call up to 5 times with an increasing delay between each attempt. If the API call is successful, the state of the component will be updated with the retrieved data. If the component is unmounted before the API call resolves, the state will not be updated.

Retry_get_all

---

src/frontend/src/modals/importModal/buttonBox/index.tsx
src/frontend/src/modals/importModal/index.tsx

The ButtonBox component, which is used in the examples modal, has been enhanced to have a dynamic font size that adjusts based on the length of the text and the dimensions of its parent element. This improvement ensures that the text within the ButtonBox component remains readable and properly fits within its container.
- Added a new `fontSize` state variable to track the font size within the ButtonBox component.
- Utilized the `useEffect` hook to calculate and update the font size dynamically.
- Implemented logic to check for both vertical and horizontal overflow of the text within the parent container.
- Decreased the font size incrementally until the text fits within the parent element's dimensions.
- Updated the component to apply the calculated font size to the text element.
- …

hot fix for dinamic size of font for buttonBox component

---

src/frontend/src/modals/chatModal/index.tsx

**Description:**
This pull request addresses an issue where the chat becomes locked in certain scenarios when the `onClose` method fails. By adding a `useEffect` hook, we can ensure that the chat remains functional even if the `onClose` method encounters an error.
**Changes Made:**
1. Introduced a new `useEffect` hook in the chat component to handle the `onClose` method failure scenario.
2. Added error handling within the `useEffect` hook to prevent the chat from becoming locked.

add useEffect to prevent chat lock on fail of onClose method

---

src/backend/langflow/api/chat_manager.py
src/backend/langflow/graph/nodes.py
src/backend/langflow/interface/loading.py

This PR removes deepcopy from all Node build methods and prevents LLMs of being loaded more than once.
Fixes #340

Hotfix: remove deepcopy, fixes llm rebuilding 

---

src/frontend/src/modals/importModal/buttonBox/index.tsx
src/frontend/src/modals/importModal/index.tsx
src/frontend/tailwind.config.js

Now, the text of the example boxes truncate after 3 lines, and if the word is bigger than the line the word breaks.

Hotfix for Import Flows modal

---

src/frontend/src/contexts/tabsContext.tsx

This pull request focuses on a specific change in the file upload functionality, specifically related to browser storage. Currently, when users upload large files, the system automatically saves the files on the browser's local storage, consuming unnecessary storage space and potentially breaking the app. This pull request introduces a modification to disable the saving of files on browser storage.
By merging this pull request, we ensure that files uploaded by users are no longer saved on the browser's local storage.

fix crash when upload large file, not saving files on browser storage

---

.gitignore
.vscode/launch.json
poetry.lock
pyproject.toml
src/backend/langflow/config.yaml
src/backend/langflow/graph/nodes.py
src/backend/langflow/interface/custom_lists.py
src/backend/langflow/template/nodes.py

This commit extracts common field attributes to variables and sets them accordingly. The basic_fields and advanced_fields variables are used to set the show and advanced attributes of the fields. The API Key field is now displayed as "API Key" and its value is hidden. The location field now has a default value of ":memory:" and its placeholder is also set to ":memory:". The password attribute of the key fields is set to False.
Closes Implement Qdrant #361

Changes to accomodate new vector stores

---

src/backend/langflow/interface/agents/custom.py

First of all, thanks for the nice project. It's perfect for prototyping langchain setup/parameters.
The queryCheckerTool now needs an extra arg with the LLM instance: https://github.com/hwchase17/langchain/blob/master/langchain/tools/sql_database/tool.py#L108
I added it so the SQLAgent can work normally now
Here's a screen shot of the error:
Here's a screen shot of the flow I was testing:

fix: SQLAgent

---

src/backend/langflow/interface/base.py
src/backend/langflow/template/frontend_node/base.py
src/backend/langflow/template/frontend_node/vectorstores.py
src/backend/langflow/template/template/base.py

✨ feat(template): add method to add fields to a template
The VectorStoreFrontendNode now supports adding extra fields to its template. The add_extra_fields method is called after the node is loaded and adds the weaviate_url field to the template if the node is of type Weaviate. The Template class now has a method to add fields to a template. This method is used by the VectorStoreFrontendNode to add the weaviate_url field to its template.

🚀 feat(langflow): add support for extra fields in VectorStoreFrontendNode

---

src/frontend/src/components/inputComponent/index.tsx
src/frontend/src/modals/NodeModal/components/ModalField/index.tsx
src/frontend/src/modals/NodeModal/index.tsx
src/frontend/src/pages/FlowPage/index.tsx
src/frontend/src/utils.ts

Description:
This pull request proposes the addition of a scrollbar to the modal window containing advanced settings when the number of input fields exceeds the limit of the screen. This enhancement aims to improve user experience by providing a convenient way to access all settings, even when the available screen space is limited.
The number of inputs in the screen is limited by a variable on Utils that can be easily changed in the future if It's needed.

Adding scrollbar on overflow itens modal

---

src/backend/langflow/template/frontend_node/prompts.py
src/backend/langflow/utils/util.py
tests/test_prompts_template.py

🔨 refactor(util.py): add format_instructions to the list of fields to format in format_dict function
The suffix and format_instructions fields in the ZeroShotPromptNode class were swapped to improve the readability of the code. The format_instructions field is now above the suffix field, which makes more sense as it is a required field. In the util.py file, the format_instructions field was added to the list of fields to format in the format_dict function. This ensures that the format_instructions field is properly formatted when the function is called.

Added format_instructions to ZeroShotPrompt

---

poetry.lock
pyproject.toml
src/backend/langflow/config.yaml

✨ feat(config.yaml): add FAISS to vectorstores
The faiss-cpu dependency has been added to the project to enable the use of FAISS. FAISS has been added to the list of vectorstores in the config.yaml file to allow for the use of FAISS in the project.

Add FAISS to vectorstores

---

src/frontend/src/pages/FlowPage/components/DisclosureComponent/index.tsx
src/frontend/src/pages/FlowPage/components/extraSidebarComponent/index.tsx
src/frontend/src/types/components/index.ts

This pull request introduces a new feature that enhances the search functionality by displaying menu options when performing a search. Currently, the search results only present a list of relevant items, but with this feature, users will have quick access to additional actions and functionalities directly from the search results.

Bringing the menu options opened on search

---

src/frontend/src/components/dropdownComponent/index.tsx
src/frontend/src/contexts/darkContext.tsx
src/frontend/src/pages/FlowPage/components/tabsManagerComponent/index.tsx

This pull request introduces an enhancement to the existing application by adding persistence to the dark mode feature. Currently, when the page is refreshed, the dark mode setting reverts to the default light mode. With this enhancement, the dark mode state will be maintained even after refreshing the page.
1. Added a new setting in the application to store the user's preference for dark mode.
2. Implemented functionality to persist the dark mode preference in local storage.
3. Modified the page initialization logic to retrieve the dark mode preference from local storage and apply it on page load.

Dark mode after refreshing page

---

pyproject.toml

The version number in the pyproject.toml file has been updated from 0.0.82 to 0.0.83. This commit exists because the release action did not work.

🔖 chore(pyproject.toml): bump up version to 0.0.83

---

src/backend/langflow/config.yaml
src/backend/langflow/interface/custom_lists.py
src/backend/langflow/template/frontend_node/llms.py
tests/test_llms_template.py

There are still some rough edges due to underlying langchain and
openai API limitations, e.g. hwchase17/langchain#3769 and
openai/openai-python#411. Notably, you can't use the Azure and
non-Azure node types in the same server, since there's global openai
configuration needed to choose between the two. So it's probably best
to still leave the Azure node types commented out in the default
config. But with this PR, if you uncomment those nodes and start the
server with OPENAI_API_TYPE=azure, you will have working Azure nodes.
Fixes #332.

Initial support for Azure LLM nodes.

---

poetry.lock
pyproject.toml
src/frontend/src/modals/chatModal/index.tsx

The conditional statement in line 292 was not properly checking for undefined and null values, which could lead to unexpected behavior. The fix ensures that the statement checks for all falsy values, including undefined and null, but False values should be valid.

fix: validation now properly checks for null values

---

src/frontend/src/App.tsx
src/frontend/src/CustomNodes/GenericNode/index.tsx
src/frontend/src/components/intComponent/index.tsx
src/frontend/src/contexts/tabsContext.tsx
src/frontend/src/controllers/API/index.ts
src/frontend/src/modals/EditNodeModal/index.tsx
src/frontend/src/modals/codeAreaModal/index.tsx
src/frontend/src/pages/FlowPage/components/nodeToolbarComponent/index.tsx
src/frontend/src/pages/FlowPage/index.tsx
src/frontend/vite.config.ts

✨ feat(App.tsx): add getVersion function to retrieve app version from API
The fetch call to retrieve the app version has been replaced with a call to the getVersion function. This function retrieves the app version from the API. This change improves the code's readability and reduces the amount of code needed to retrieve the app version.
🐛 fix(GenericNode/index.tsx): replace fetch call with postValidateNode function call to validate node
✨ feat(GenericNode/index.tsx): add postValidateNode function to validate node via API
The fetch call to validate the node has been replaced with a call to the postValidateNode function. This function validates the node via the API. This change improves the code's readability and reduces the amount of code needed to validate the node.
🐛 …

Refactor frontend API use

---

src/backend/langflow/processing/process.py
tests/test_cache.py
tests/test_websocket.py

The prediction still required an old chat_history attirbute. This should fix it.
Tested with Buffer Memory and achieved the correct results.
A more robust approach should be considered, though.
Fixes #500
This script was used to test it:
```python
import requests
from typing import Optional
BASE_API_URL = "http://127.0.0.1:7860/api/v1/predict"
FLOW_ID = "245e1a54-86f9-4934-bf89-bea2c7ab863d" # you should change this to your id
TWEAKS = {
"ConversationBufferMemory-pixS4": {},
"ConversationChain-IxmJV": {},
"ChatOpenAI-7AcF4": {},
}
def run_flow(message: str, flow_id: str, tweaks: Optional[dict] = None) -> dict:
"""
Run a flow with a given message and optional tweaks.
:param message: The message to send to the flow
:param flow_id: The ID of the flow to run
:param tweaks: Optional tweaks to …
```

HotFix 0.1.1: Prediction was not caching correctly

---

poetry.lock
pyproject.toml
src/frontend/src/modals/chatModal/chatInput/index.tsx

Ensure that the chat input maintains focus after sending a message
This pull request addresses an issue where the chat input field loses focus after sending a message. By implementing the requested changes, this PR ensures that the chat input remains focused, allowing for a smoother and more efficient user experience.
The requested improvement was made in response to a specific user, @jimwhite, who encountered the issue and highlighted the need for this enhancement.
With this enhancement, users can seamlessly send consecutive messages without the need to repeatedly click or tap on the input field. By maintaining focus after sending a message, we improve usability and reduce friction, ultimately enhancing the overall user satisfaction.
Please review and merge this pull request to …

Hotfix: keep focus on chat input

---

src/backend/langflow/template/frontend_node/documentloaders.py

I'd noticed that in `0.0.88` the `path` for `NotionDirectoryLoader` and the `file` for `SlackDirectoryLoader` were missing. This PR restores those input fields.

Fix: Restore Notion and Slack directory loaders.

---

src/frontend/src/modals/chatModal/chatMessage/index.tsx

🐛 fix(chatMessage): remove unnecessary text-sm class from message sender name to improve readability

Remove unnecessary text-sm class from message sender name to improve readability

---

poetry.lock
pyproject.toml
src/backend/langflow/interface/agents/custom.py

The `AgentType` enum is added to the `langchain.agents.custom` module to improve readability and type safety. The `InitializeAgent` class now uses the `AgentType` enum to ensure that the `agent` parameter is a valid value from the enum.

Hotfix to AgentInitializer

---

poetry.lock
pyproject.toml
src/frontend/src/pages/FlowPage/components/nodeToolbarComponent/index.tsx

Added attributes to `a` tag to fix openning links.

Fix: docs now open correctly

---

poetry.lock
pyproject.toml
src/backend/langflow/interface/initialize/loading.py

🐛 fix(loading.py): handle case where metadata is an empty dict and document already has metadata
🐛 fix(loading.py): handle case where separator_type is not provided in params
The first fix ensures that if the metadata is an empty dict, it will not be added to the documents if they already have metadata. This prevents overwriting existing metadata.
The second fix handles the case where the separator_type is not provided in the params. In this case, the text_splitter will be instantiated using the class_object and the params as is.

Fix: Metadata now updates existing metadata in documents

---

poetry.lock
pyproject.toml
src/backend/langflow/config.yaml
src/backend/langflow/interface/initialize/loading.py
src/backend/langflow/template/frontend_node/textsplitters.py

📝 docs(config.yaml): update documentation link for ConversationBufferMemory in memories section
The documentation link for ConversationBufferMemory in the memories section has been updated to point to the correct URL "https://python.langchain.com/docs/modules/memory/how_to/buffer". This change ensures that users can access the correct documentation for using ConversationBufferMemory.
Fix RecursiveCharacterTextSplitter bug with "separator_type" variable being used incorrectly,

Hotfix: 0.2.6 -> Docs and TextSplitter bug

---

src/backend/langflow/graph/edge/base.py

There is a recurring intermittent bug, where Chains fail to validate, with an error "Required module ____ for module ____ not found". This happens frequently for all LLMs that inherit from the LLM class (example Cohere's wrapper).
This is caused by this chunk of code.
This also explains why the bug is intermittent and not every time. "in" is matching LLM from source_types with BaseLLM from target_reqs. Also, this doesn't need to be a nested loop, it can be done with one loop.
I'm an avid user of LangFlow, and a first time contributor. Thanks!

Fix: Required input llm for module LLMChain not found

---

src/backend/langflow/api/v1/chat.py
src/frontend/src/App.tsx
src/frontend/src/contexts/alertContext.tsx
src/frontend/src/modals/chatModal/index.tsx

This pull request addresses a bug related to WebSocket functionality that was causing an empty error to be displayed. The bug resulted in incorrect error-handling behavior within the WebSocket implementation, leading to confusion and difficulties in identifying and resolving issues. 
By addressing this bug and improving the WebSocket error handling mechanism, this pull request significantly enhances the overall stability and reliability of the application.

fix web socket bug that display empty error

---

.gitignore
pyproject.toml
tests/test_chains_template.py
tests/test_graph.py
tests/test_websocket.py

The package version has been updated from 0.2.7 to 0.2.8. This change is made to reflect the latest changes and improvements in the package.

🔖 chore(pyproject.toml): update package version to 0.2.8

---

src/backend/langflow/api/v1/chat.py

📝 docs(chat.py): explain the need for building the root node before the rest of the graph
The root node in the graph was not being built before the rest of the graph, which caused issues when certain nodes required parameters that were not connected to them. By adding the missing build step for the root node, we ensure that all necessary connections and parameters are properly set up before building the rest of the graph. This improves the overall functionality and reliability of the chat module.

🔧 chore(chat.py): add build step for root node in graph

---

poetry.lock
pyproject.toml
src/backend/langflow/api/v1/chat.py

📝 docs(chat.py): explain the need for building the root node before the rest of the graph
The root node in the graph was not being built before the rest of the graph, which caused issues when certain nodes required parameters that were not connected to them. By adding the missing build step for the root node, we ensure that all necessary connections and parameters are properly set up before building the rest of the graph. This improves the overall functionality and reliability of the chat module.

🔧 chore(chat.py): add missing build step for root node in graph

---

src/frontend/src/contexts/tabsContext.tsx
src/frontend/src/utils/reactflowUtils.ts

This pull request aims to introduce a new feature to the project that automatically assigns a unique number to the name of a new flow when it is imported from the community examples and a flow with the same name already exists. This improvement will prevent naming conflicts and enhance the user experience by providing a clear distinction between similarly named flows.

Add Auto-numbering for Duplicate Forking Flows

---

src/frontend/src/constants/constants.ts
src/frontend/src/controllers/API/api.tsx
src/frontend/src/controllers/API/index.ts

This pull request introduces a new feature that allows URLs to be excluded from interceptor error retries. The feature enhances the error-handling mechanism and improves the overall resilience of our application when dealing with external resources and services.
🔧 chore(constants.ts): add URL_EXCLUDED_FROM_ERROR_RETRIES constant t…o store URLs excluded from error retries for better error handling
🔧 chore(api.tsx): add logic to exclude certain URLs from error retries in the ApiInterceptor component to improve error handling
🔧 chore(index.ts): update postCustomComponent function to use the api instance instead of axios for consistency and reusability

URLs Excluded from Interceptor Error Retries

---

src/backend/langflow/template/frontend_node/documentloaders.py

As noted in the
[documentation](https://python.langchain.com/docs/integrations/document_loaders/slack) for this integration zip_path is the first named parameter not file_path and workspace_url is the second with zip_path being required and workspace_url being optional.
Fixes #695

Add zip_path and workspace_url fields

---

src/backend/langflow/graph/vertex/types.py
src/backend/langflow/interface/initialize/utils.py

HumanMessagePromptTemplate and some other MessagePromptTemplates were not built correctly.
This fixes SystemMessage Example.

Fix HumanMessagePromptTemplate bug

---

src/frontend/src/constants/constants.ts
src/frontend/src/contexts/tabsContext.tsx

feat(tabsContext.tsx): add support for skipping node updates based on node type defined in the skipNodeUpdate constant to improve performance and prevent unnecessary updates

fix bug that override base classes of customComponent

---

.devcontainer/devcontainer.json

The devcontainer will run `poetry install` upon startup but this will fail because poetry is not installed.

Add poetry to devcontainer

---

docs/docs/guides/langfuse_integration.mdx

📝 docs(langfuse_integration.mdx): update step 3 to remove mention of consulting Langfuse documentation or contacting support for integration issues

📝 docs(langfuse_integration.mdx): remove reference to troubleshooting section in Langfuse documentation as it is not available

---

src/backend/langflow/api/v1/validate.py
src/frontend/package-lock.json
src/frontend/src/CustomNodes/GenericNode/components/parameterComponent/index.tsx
src/frontend/src/components/promptComponent/index.tsx
src/frontend/src/icons/GradientSparkles/index.tsx
src/frontend/src/modals/EditNodeModal/index.tsx
src/frontend/src/modals/baseModal/index.tsx
src/frontend/src/modals/genericModal/index.tsx
src/frontend/src/types/components/index.ts
src/frontend/src/utils/reactflowUtils.ts

🔨 refactor(promptComponent): rename TextAreaComponentType to PromptAreaComponentType for better naming consistency and clarity
🔨 refactor(genericModal): import cloneDeep from lodash to improve code readability and maintainability
🔨 refactor(genericModal): add type annotations to validatePrompt function parameters for better code documentation
🔨 refactor(genericModal): add null check for nodeClass before modifying it in validatePrompt function
🔨 refactor(genericModal): setNodeClass and setModalOpen only if frontend_node is not an empty object in validatePrompt function
🔨 refactor(genericModal): remove console.log statement in catch block of validatePrompt function
🔨 refactor(genericModal): add type annotations to catch block of validatePrompt function for better code documentation
🔨 …

Enabling prompt modal close without variables

---

src/frontend/src/components/floatComponent/index.tsx
src/frontend/src/components/intComponent/index.tsx

As detailed in OpenAI's documentation and GitHub issue #884, two float fields in OpenAI have a range of -2 to 2.
For reference, visit:
Presence Penalty: https://platform.openai.com/docs/api-reference/chat/create#presence_penalty
Frequency Penalty: https://platform.openai.com/docs/api-reference/chat/create#frequency_penalty
Currently, FloatComponent only accepts values within [0-1]. This pull request expands its range to [-2 to 2].

Expand floatComponent Input Range

---

src/backend/langflow/interface/tools/util.py

In recent versions of langchain, some of it's sources are branching based on the version of pydantic, therefore messing with the ast.parse.
Dedenting the source seems to take care of this cases.

fix(util.py): fix IndentationError while parsing from source code.

---

src/frontend/src/modals/genericModal/index.tsx
src/frontend/src/types/api/index.ts

🐛 fix(genericModal/index.tsx): update template value based on field_name instead of hardcoding "template"
✨ feat(api/index.ts): add CustomFieldsType to represent custom fields in APIClassType

🐛 fix(genericModal/index.tsx): set field_name to the first key of custom_fields object if it is an empty string

---

src/frontend/src/utils/reactflowUtils.ts

refactor(reactflowUtils.ts): change display_name of generated group node from "group Component" to "Group" for better clarity and understanding

prevent code fields to show on group node

---

Makefile
src/backend/langflow/interface/utilities/base.py

The code now handles import errors when importing utilities from the `langchain.utilities` module. If an import error occurs, the utility is skipped and not added to the `type_dict` dictionary. This prevents the application from crashing when encountering an invalid or missing utility.

🐛 fix(base.py): handle import errors when importing utilities to prevent application crashes

---

src/backend/langflow/api/v1/chat.py
src/backend/langflow/services/auth/utils.py

Regarding this [feature request](https://github.com/logspace-ai/langflow/issues/1100#issuecomment-1787188525), I've created this PR. It lets the users call all the endpoints with their `api_key`. I updated the `get_current_user` function, and it checks the request headers to see whether the `Bearer token` is provided or `api_key`. Otherwise, it raise 401.

modify get_current_user to accept api_key as authentication method

---

docs/docusaurus.config.js

Related to #1115 
It is nice to allow users to choose light or dark mode based on their own needs, such as sensitivity to bright light.

Allow users to use dark mode

---

docs/docs/guidelines/components.mdx

The LangFlow Components documentation contains a broken link to the LangChain components documentation. This PR fixes the link to point to the LangChain integrations/components docs.

Fix components link (Python integrations documentation)

---

pyproject.toml

This pull request updates the version number in the `pyproject.toml` file to indicate a pre-release version. No other changes were made in this commit.

Bump version to 0.6.0a0

---

src/backend/langflow/processing/process.py

This is to fix the following issue:
- When process a flow using endpoint api, `memory_key` alternates between `history` and `chat_history`, causing success and failure to alternate. This occurs when the langchain_object is an instance of AgentExecutor  
This is similiar to https://github.com/logspace-ai/langflow/commit/67f8bb9dab66151083743e7a2d5833d9d0e69b22

Fix: Avoid fix_memory_inputs when langchain_object is instance of AgentExecutor

---

pyproject.toml
src/backend/langflow/processing/process.py

The "repr" key was not being ignored when processing inputs. This PR updates the process_inputs function to ignore the "repr" key.
Fixes #1171

Ignore "repr" key in process_inputs

---

poetry.lock
pyproject.toml
src/backend/langflow/components/vectorstores/Faiss.py
src/backend/langflow/config.yaml

This pull request pins the bcrypt version to 4.0.1 and updates the package version to 0.5.11. This ensures compatibility with passlib and includes the latest changes in the codebase.

Pin bcrypt version and update package version

---

src/backend/langflow/interface/types.py
src/backend/langflow/template/field/base.py
src/backend/langflow/template/frontend_node/agents.py
src/backend/langflow/template/frontend_node/base.py
src/backend/langflow/template/frontend_node/chains.py
src/backend/langflow/template/frontend_node/custom_components.py
src/backend/langflow/template/frontend_node/formatter/field_formatters.py
src/backend/langflow/template/frontend_node/prompts.py
src/backend/langflow/template/frontend_node/tools.py
src/backend/langflow/template/template/base.py
tests/test_agents_template.py
tests/test_chains_template.py
tests/test_frontend_nodes.py
tests/test_llms_template.py
tests/test_prompts_template.py

This pull request refactors the code to use model serialization in the Template and FrontendNode classes, improving performance and maintainability. The code is also refactored to remove unused to_dict() methods. Finally, the template files are updated with the new fileTypes field. This PR aims to enhance the overall quality and functionality of the codebase.

Remove to_dict method in favor or pydantic implementation

---

docs/docs/components/custom.mdx
src/backend/langflow/field_typing/__init__.py
src/backend/langflow/interface/types.py
src/backend/langflow/template/field/base.py
tests/conftest.py
tests/data/component_with_templatefield.py
tests/test_custom_component.py

Previously, the field configuration in the add_new_custom_field function was not properly sanitized. This PR refactors the function to sanitize the field configuration before adding it to the template.
Update options field in TemplateFieldCreator class
The options field in the TemplateFieldCreator class was previously defined as a list of strings. This PR updates the options field to allow a callable function that returns a list of options.
Add test for custom component with TemplateField
This PR adds a test for a custom component that uses the TemplateField class. The test ensures that the component can be built correctly and that the options field is properly populated.
Add TemplateField to field_typing
The TemplateField class is added to the field_typing module. This class allows for …

Refactor field configuration in add_new_custom_field function

---

docs/docs/components/custom.mdx
src/backend/langflow/field_typing/__init__.py
src/backend/langflow/field_typing/range_spec.py
src/backend/langflow/interface/types.py
src/backend/langflow/template/field/base.py
src/frontend/src/CustomNodes/GenericNode/components/parameterComponent/index.tsx
src/frontend/src/components/codeTabsComponent/index.tsx
src/frontend/src/components/floatComponent/index.tsx
src/frontend/src/components/intComponent/index.tsx
src/frontend/src/modals/EditNodeModal/index.tsx
src/frontend/src/types/components/index.ts
tests/test_llms_template.py

This pull request adds a new class called RangeSpec. The RangeSpec class is used to define a range specification for a field. It has three properties: min, max, and step. The min property specifies the minimum value in the range, the max property specifies the maximum value in the range, and the step property specifies the step size between values in the range. The RangeSpec class also includes validation logic to ensure that the max value is greater than the min value and that the step value is positive. This pull request improves the code by fixing the imports and adding the RangeSpec class.

Add RangeSpec class and functionality in the UI

---

src/frontend/package-lock.json

This pull request updates the frontend dependencies to their latest versions. The following packages have been updated:
- `@adobe/css-tools` has been updated to version 4.3.2 for security and bug fixes.
- `@babel/code-frame` has been updated to version 7.23.5 for bug fixes.
- `@babel/generator` has been updated to version 7.23.6 for bug fixes.
- `@babel/helper-string-parser` has been updated to version 7.23.4 for bug fixes.
- `@babel/highlight` has been updated to version 7.23.4 for bug fixes.
- `@babel/parser` has been updated to version 7.23.6 for bug fixes.
- `@babel/traverse` has been updated to version 7.23.6 for bug fixes.
- `@babel/types` has been updated to version 7.23.6 for bug fixes.
- `vite` has been updated to version 4.5.1 for bug fixes.
These updates include bug fixes, …

Update frontend dependencies

---

.dockerignore
poetry.lock
pyproject.toml

This pull request updates the bcrypt version to 4.0.1 and adds .dockerignore entries for the node_modules and dist directories.

Update bcrypt version to 4.0.1 and add .dockerignore entries for node_modules and dist directories

---

src/backend/langflow/components/retrievers/VectaraSelfQueryRetriver.py

**Description**,
This pull request addresses issue #1246, which proposes the addition of a self-query retriever according to the LangChain Vectara integration. The self-query retriever aims to empower users with the ability to perform queries directly within the Vectara component(vector store).
**Changes Made**
I have added one more file under `src\backend\langflow\components\retrievers` which contains a new VectaraSelfQueryRetriverComponent class
**Files Added:** VectaraSelfQueryRetriever.py
**langchain documentation for this component:**
https://python.langchain.com/docs/integrations/retrievers/self_query/vectara_self_query

Adding Vectara Self Query Retriever - feature request

---

README.md

With this fix the shell will be able to find the right script.

Fix gcp walkthrough tutorial button on README.md

---

poetry.lock
pyproject.toml
src/backend/langflow/components/llms/AmazonBedrock.py
src/backend/langflow/services/chat/service.py
src/backend/langflow/services/chat/utils.py
src/backend/langflow/utils/chat.py
src/backend/langflow/utils/prompt.py

The ChatDefinition allows users to turn any flow into a Chat flow by defining what has to run and what are the inputs and outputs.
The ChatDefinition requires a function, inputs(optional) and output_key(optional).
The function receives a dictionary as input and can output a string or a dict. If the output is a dict, then an output_key must be provided.
Anything can run inside the function. You can also pass methods of pre-built classes like a Chain.
Here's an example of how to use it in a CustomComponent:
```python
from langflow import CustomComponent
from langflow.utils.chat import ChatDefinition
class Component(CustomComponent):
documentation: str = "http://docs.langflow.org/components/custom"
def build(self) -> Data:
def func(inputs, callbacks):
return {"text":'This is a simple …
```

Adds ChatDefinition utility

---

pyproject.toml

This pull request updates the version in the pyproject.toml file to 0.6.5a0.

Bump version to 0.6.5a0 in pyproject.toml

---

poetry.lock
pyproject.toml
src/backend/langflow/services/database/service.py

This pull request updates the `create_engine` method in the `DatabaseService` class to include the `max_overflow` parameter. This allows for better control of connection pooling and prevents connection errors when the pool is full. Additionally, it updates the `weaviate-client` version to `4.0.0` and the `langflow` version to `0.6.5a4`.

Update create_engine method to include max_overflow parameter

---

src/backend/langflow/components/agents/AgentInitializer.py

From the last update, AgentInitializer lost ability to chain another AgentInitializer via tool.
Fix issue: https://github.com/logspace-ai/langflow/issues/1255

Fix AgentInitializer to has last statement of returning base class

---

src/backend/langflow/processing/base.py
src/backend/langflow/services/plugins/langfuse_plugin.py

Fix: 
Error: cannot import name 'CreateTrace' from 'langfuse.callback'
Remove imports of CreateTrace (deprecated in the langfuse 2.x)

Fix: Error: cannot import name 'CreateTrace' from 'langfuse.callback'

---

docs/docs/components/prompts.mdx

This pull request fixes a broken link in the prompts.mdx file. The link to the "Prompt Customization" page was pointing to the wrong location. This PR updates the link to the correct location in the documentation.

Fix broken link in prompts.mdx

---

docs/docs/components/custom.mdx
src/backend/langflow/interface/custom/custom_component/custom_component.py
src/backend/langflow/interface/custom/utils.py
src/backend/langflow/template/template/base.py

This pull request adds a new property called `field_order` to the `CustomComponent` class. The `field_order` property allows developers to define the order in which fields will be displayed in the canvas. This can be useful for customizing the layout of the component.
#1373

Add field_order property to CustomComponent

---

src/backend/langflow/interface/custom/custom_component/component.py
src/backend/langflow/interface/custom/utils.py
src/backend/langflow/template/field/base.py
src/frontend/src/stores/typesStore.ts

If no display_name is provided, the name of the Field is the title case version of the name. (e.g file_path -> File Path)
The user has the option to deactivate this behaviour in a field by field basis by passing `title_case=False`.

Feature: Fields are now converted to title case by default

---

src/backend/langflow/api/v1/login.py

This pull request fixes the issue with the refresh http only variable in the `refresh_token` endpoint. The `httponly` parameter was incorrectly named as `REFRESH_TOKEN_HTTPONLY` instead of `REFRESH_HTTPONLY`. This PR updates the parameter name to `REFRESH_HTTPONLY` to ensure the correct behavior.

Fix refresh http only variable

---

pyproject.toml
src/backend/langflow/api/v1/login.py

This pull request fixes the issue with the refresh http only variable in the `refresh_token` endpoint. The `httponly` attribute is now correctly set to the value specified in the `auth_settings` configuration.

Fix refresh http only variable (#1493)

---

src/backend/langflow/api/v1/login.py
src/frontend/src/controllers/API/api.tsx
src/frontend/src/pages/StorePage/index.tsx

This pull request addresses a critical issue where the refresh token renovation process fails when it expires. Currently, when the refresh token reaches its expiration, the system fails to properly renew it, causing authentication failures for users and disrupting service continuity.

Bugfix: Refresh Token Renovation

---

src/backend/langflow/services/settings/auth.py
src/frontend/src/controllers/API/api.tsx

This pull request addresses a critical bug where the login process enters into a loop when users provide incorrect credentials, specifically when the username or password is invalid. Prior to this fix, the system would repeatedly prompt users to re-enter their credentials without providing any indication of the error, leading to frustration and confusion among users.

Title: Bugfix: Resolve Login Loop for Incorrect Username or Password

---

src/backend/langflow/components/retrievers/VectorStoreRetriever.py
src/backend/langflow/components/tools/RetrieverTool.py
src/backend/langflow/components/vectorstores/MongoDBAtlasVectorSearch.py

First time contributing to this repo, so please let me know if I did something wrong or I need to do something else
I've updated the MongoDB Atlas VectorStore code to allow the creation of the VectorStore without the required documents.
I've also added a tool to get the VectorStore as Retriever and create a tool from that Retriever to use in an Agent.

Use MongoDB Altas without required Documents

---

src/frontend/src/modals/codeAreaModal/index.tsx

✨ (codeAreaModal/index.tsx): add event listener to prevent the Escape key from closing the modal
📝 (codeAreaModal/index.tsx): improve code readability by adding line breaks and indentation for better code organization

Prevent esc to close Code Modal

---

src/backend/langflow/api/v1/chat.py
src/backend/langflow/graph/graph/base.py
src/frontend/src/pages/FlowPage/components/PageComponent/index.tsx
src/frontend/src/stores/flowStore.ts
src/frontend/src/types/zustand/flow/index.ts
src/frontend/src/utils/buildUtils.ts
src/frontend/src/utils/reactflowUtils.ts
src/frontend/src/utils/utils.ts

- Update node and edge IDs in PageComponent and reactflowUtils
- Merge remote-tracking branch 'origin/zustand/io/migration' into fixGroup
- Refactor node ID generation and update node IDs in selection
- Update flowStore.ts and reactflowUtils.ts
- Fix async bug in build_vertex_stream function
- Add check for missing id in vertex data
- Fix exception message for missing vertex id
- Update code: Added VertexLayerElementType type and modified updateIds function

Update node and edge IDs, refactor node ID generation, and fix async bug in build_vertex_stream function

---

src/frontend/src/modals/formModal/chatInput/index.tsx

This pull request addresses an issue where pressing the Enter key during IME (Input Method Editor) composition unintentionally submits the input content.
In the current implementation, when users input text using an IME for languages like Japanese, pressing the Enter key during composition submits the input before the conversion is finalized. This behavior causes frustration for users, as they unintentionally submit the input each time they press Enter to confirm the conversion.
Added `!event.nativeEvent.isComposing` to the condition alongside `event.key === "Enter"`

Fix unintended input submission during IME composition

---

.github/workflows/pre-release-base.yml
.github/workflows/pre-release-langflow.yml

This pull request adds a version check before publishing to PyPI. It ensures that the version of the package being published is not already released. If the version is already released, the release process is skipped. This helps prevent accidental re-releases of the same version.

Add version check before publishing to PyPI

---

src/frontend/src/stores/typesStore.ts

🐛 (typesStore.ts): set loading to false when an error occurs during fetching types to prevent infinite loading state

Bugfix: Fix loop when auto_login = true

---

.github/workflows/pre-release-base.yml
.github/workflows/pre-release-langflow.yml
.github/workflows/release.yml
docker_example/docker-compose.yml
poetry.lock
pyproject.toml
src/backend/base/langflow/__main__.py
src/backend/base/pyproject.toml

This pull request refactors the run_on_mac_or_linux function in __main__.py to remove the open_browser parameter. It also updates the Docker image tags in GitHub workflows to use logspace/langflow instead of langflow/langflow.

Refactor run_on_mac_or_linux function and update Docker image tags

---

poetry.lock
pyproject.toml
src/backend/langflow/alembic/script.py.mako
src/backend/langflow/alembic/versions/1ef9c4f3765d_.py
src/backend/langflow/alembic/versions/7843803a87b5_store_updates.py
src/backend/langflow/alembic/versions/b2fa308044b5_add_unique_constraints.py

This pull request adds the import statement for the logger module in script.py.mako and fixes the error handling during the upgrade process in the alembic scripts.
Fixes #1432

Add logger import and fix error handling during upgrade in alembic scripts

---

src/frontend/src/App.tsx
src/frontend/src/contexts/authContext.tsx
src/frontend/src/types/contexts/auth.ts

🐛 (App.tsx): handle errors when fetching data and log them to the console for debugging purposes
📝 (authContext.tsx): remove unused autoLogin function and refactor getUser function to improve code readability and maintainability
📝 (authContext.tsx): add getUser function to retrieve user data and improve user authentication flow
📝 (auth.ts): add getUser function to AuthContextType to improve type safety and provide a clear API for accessing user data

Feature: The system will prioritize calling the autoLogin endpoint before processing any other requests

---

src/backend/base/langflow/services/database/models/api_key/crud.py
src/backend/base/langflow/services/database/models/api_key/model.py

This pull request updates the `created_at` field in the `api_key/crud.py` and `api_key/model.py` files. The changes ensure that the `created_at` field is set to the current UTC time if it is not provided during the creation of an API key.

Update created_at field in api_key/crud.py and api_key/model.py

---

GCP_DEPLOYMENT.md
docs/docs/deployment/gcp-deployment.md

This fixes the deploy buttons. Adds `gcp` to the `working_dir` parameter, which previously prevented the walkthrough tutorial from starting.

Fix GCP deploy buttons in GCP docs

---

src/backend/base/langflow/api/v1/endpoints.py
src/backend/base/langflow/graph/graph/base.py
src/backend/base/langflow/processing/process.py

This pull request fixes the issue where the input_value was being ignored and not passed into the Chat input node when calling the API endpoint run/<flow_id>. The problem was observed in Langflow v1.0.0a23. The fix includes updating the Graph.from_payload method to include the user_id parameter and fixing the process_tweaks function to handle the stream flag correctly. This resolves issue #1744.
Also fixes global variables not being honored when using the API

Fix API not passing input_value to Chat Input

---

Makefile
src/frontend/.gitignore
src/frontend/package-lock.json
src/frontend/package.json
src/frontend/tests/end-to-end/codeAreaModalComponent.spec.ts
src/frontend/tests/end-to-end/filterEdge.spec.ts
src/frontend/tests/end-to-end/globalVariables.spec.ts
src/frontend/tests/end-to-end/saveComponents.spec.ts
src/frontend/tests/end-to-end/store.spec.ts
src/frontend/tests/end-to-end/textInputOutput.spec.ts

🔧 (Makefile): remove unnecessary kill command for frontend server in run_frontend target
📝 (frontend/.gitignore): add test-results/ directory to .gitignore
⬆️ (frontend/package.json): upgrade @playwright/test dependency to version 1.43.1
💡 (frontend/tests/end-to-end/filterEdge.spec.ts): update expected tooltip test ID from "tooltip-Models" to "tooltip-Model Specs"
💡 (frontend/tests/end-to-end/filterEdge.spec.ts): update expected test ID from "disclosure-models" to "disclosure-model specs"
💡 (frontend/tests/end-to-end/globalVariables.spec.ts): add hover and delete functionality to test for global variables
💡 (frontend/tests/end-to-end/saveComponents.spec.ts): add additional wait times to ensure modal is loaded before interacting with it

Add new tests on global variables and fix old ones

---

src/backend/base/langflow/processing/load.py
src/backend/base/langflow/services/database/models/api_key/model.py
src/backend/base/langflow/services/database/models/variable/model.py
src/backend/base/langflow/services/monitor/utils.py

This pull request fixes the `created_at` field type in the Variable and ApiKey models. Previously, the `created_at` field was defined as `datetime`, but it should be `Optional[datetime]`. This PR updates the field type to `Optional[datetime]` in both models to ensure consistency and avoid potential issues.

Fix created_at field type in Variable and ApiKey models

---

.github/workflows/pre-release-base.yml
.github/workflows/pre-release-langflow.yml
.github/workflows/release.yml
deploy/docker-compose.yml
docker_example/Dockerfile
docker_example/README.md
docker_example/docker-compose.yml
docker_example/pre.Dockerfile
docker_example/pre.docker-compose.yml
src/backend/Dockerfile

This pull request updates the Docker image references in the GitHub workflows and Docker Compose files from "logspace/langflow" to "langflowai/langflow". This ensures that the latest version of the LangFlow image is used and aligns with the new repository name.

Update Docker image references to langflowai in GitHub workflows and Docker Compose files

---

poetry.lock
pyproject.toml
src/backend/langflow/interface/custom/directory_reader/utils.py
src/frontend/src/components/codeTabsComponent/index.tsx

- Added a "?" to prevent a bug when the template has no value
- Refactored the determine_component_name function in utils.py to use the file name
- Bumped the version to 0.6.18 in pyproject.toml
Fixes #1768 and #1780

Fix bugs and make improvements

---

docker-compose.yml

Trailing comma in command prevents backend from starting.

docker-compose: remove trailing comma

---

src/frontend/src/App.tsx
src/frontend/src/components/codeTabsComponent/index.tsx
src/frontend/src/components/genericIconComponent/index.tsx
src/frontend/src/controllers/API/index.ts
src/frontend/src/pages/MainPage/components/components/index.tsx
src/frontend/src/routes.tsx

- Fixed glitch at Main Page: when changing from flows to components, the Empty screen flashes. 
- Fixed glitch at Icons: when lazy loading, a loading component appeared, and if that is super fast, it seems like a glitch. Fixed by adding a timeout to display the loading, displaying a blank screen before that.
- Fixed glitch at refresh: When refreshing, the screen goes to loading state twice. Added a Abort function at the main UseEffect to address that issue.

Fixed glitches that don't affect usability

---

docs/docs/migration/possible-installation-issues.mdx

Fix formatting by:
* Adds a missing empty line following an unordered list.
* Corrects an unclosed backtick.

Docs: Correct Formatting and Syntax

---

src/backend/base/langflow/interface/initialize/loading.py

This pull request fixes the assignment of the custom_repr variable in the instantiate_custom_component function. The previous code used the "not" operator to check if custom_repr was empty, but this caused incorrect behavior when custom_repr was set to an empty string. The fix changes the check to use "is None" instead, ensuring that custom_repr is correctly assigned.

Fix custom_repr assignment in instantiate_custom_component function

---

src/backend/base/langflow/components/data/APIRequest.py

♻️ (APIRequest.py): refactor APIRequest class to improve variable naming and remove unnecessary underscore prefix in headers parameter
💡 (APIRequest.py): update comments in APIRequest class to improve code readability and maintainability

Add headers to API Request component

---

src/backend/base/langflow/api/utils.py
src/backend/base/langflow/api/v1/chat.py
src/backend/base/langflow/components/data/APIRequest.py
src/backend/base/langflow/graph/graph/base.py
src/backend/base/langflow/services/store/service.py
src/frontend/src/utils/buildUtils.ts
tests/test_endpoints.py

This pull request fixes the mark_branch function in the Graph class to properly handle visited vertices. It also refactors the build_and_cache_graph_from_db function in utils.py to simplify the code and remove an unnecessary parameter.

Fix mark_branch function and refactor build_and_cache_graph_from_db function

---

src/frontend/src/components/cardComponent/index.tsx

This pull request refactors the `CollectionCardComponent` to add a playground check before opening it. The `hasPlayground` function is introduced to determine if a flow has a playground. If a flow doesn't have a playground, an error message is displayed. This change improves the user experience by preventing the opening empty playgrounds

"Refactor: Add playground check before opening"

---

poetry.lock
pyproject.toml
src/backend/langflow/components/vectorstores/Pinecone.py

Fixes Pinecone implementation

---

src/backend/base/langflow/base/models/openai_constants.py
src/backend/base/langflow/components/helpers/IDGenerator.py
src/backend/base/langflow/components/model_specs/ChatOpenAISpecs.py
src/backend/base/langflow/components/models/OpenAIModel.py

♻️ (ChatOpenAISpecs.py, OpenAIModel.py): refactor to use MODEL_NAMES constant from openai_constants.py for consistency and easier maintenance

✨ (openai_constants.py): add a new file to define constant MODEL_NAMES for OpenAI models

---

src/backend/base/langflow/components/memories/ZepMessageReader.py
src/backend/base/langflow/components/memories/ZepMessageWriter.py

This pull request updates the ZepMessageReader and ZepMessageWriter to avoid a 404 error. It includes a monkeypatch to the API_BASE_PATH in the zep_python.zep_client module to ensure the correct API path is used.

Update ZepMessageReader and ZepMessageWriter to avoid 404 error

---

src/frontend/src/customNodes/genericNode/components/parameterComponent/index.tsx
src/frontend/src/utils/parameterUtils.ts
src/frontend/tests/end-to-end/chatInputOutput.spec.ts
src/frontend/tests/end-to-end/dragAndDrop.spec.ts

🐛 (index.tsx): fix missing line break after handleUpdateValues function call
✨ (index.tsx): improve performance by debouncing handleUpdateValues function call for certain types of parameters
📝 (parameterUtils.ts): update handleUpdateValues function to use optional chaining for accessing template properties
🚀 (chatInputOutput.spec.ts): remove unused imports and commented code
🚀 (dragAndDrop.spec.ts): fix typo in test description

fix state error when is debouncing changes on integers inputs

---

src/frontend/src/pages/FlowPage/components/PageComponent/index.tsx
src/frontend/src/stores/flowStore.ts
src/frontend/src/utils/reactflowUtils.ts

This pull request fixes a bug where duplicate groups were being created when certain actions were performed. The issue was caused by incorrect handling of selection and node data. This PR includes changes to ensure that only one group is created when necessary and that duplicate groups are avoided.

Fix duplicate group bug

---

poetry.lock
pyproject.toml
src/backend/base/langflow/services/variable/service.py
src/backend/base/poetry.lock
src/backend/base/pyproject.toml
src/frontend/src/components/codeTabsComponent/index.tsx

fix whitespace bug by stripping the value before creating the variable and improve UX

add export flow on API modal and fix .env bug

---

src/backend/base/langflow/components/experimental/SubFlow.py

The `build_records_from_result_data` method in the `SubFlowComponent` class now accepts a `get_final_results_only` parameter. This parameter controls whether the output will contain all outputs from the flow or only the final results. This change allows for more flexibility in handling the result data.

feat: Add get_final_results_only parameter to build_records_from_result_data method

---

src/backend/base/langflow/graph/graph/base.py
src/frontend/src/customNodes/genericNode/index.tsx
src/frontend/src/stores/flowStore.ts

The Graph class had a bug where the visited set was not being properly updated. This pull request fixes that bug by ensuring that the vertex is added to the visited set before marking it.
In addition, the GenericNode component has been refactored to improve the handling of build status. The condition for checking if the build status is inactive has been modified to exclude the check for invalid validation status. This change ensures that the inactive status is properly displayed.

Fix visited set bug in Graph class and refactor GenericNode component

---

src/frontend/src/components/codeTabsComponent/index.tsx
src/frontend/src/modals/apiModal/views/index.tsx
src/frontend/src/types/components/index.ts
src/frontend/src/utils/reactflowUtils.ts

The `allowExport` prop was not properly implemented in the `CodeTabsComponent` and `ApiModal` views. This pull request fixes the issue by adding the `allowExport` prop to the `CodeTabsComponent` and passing it to the `ApiModal` view. Additionally, the `allowExport` prop is now properly validated in the `codeTabsPropsType` type definition. The changes ensure that the ExportModal component is conditionally rendered based on the value of the `allowExport` prop.
Also fix validateSelection that were changing the selection

"Fix allowExport prop in CodeTabsComponent and ApiModal"

---

src/frontend/src/modals/apiModal/views/index.tsx
src/frontend/src/utils/utils.ts

🐛 (ApiModal): remove workaround for the issue with the tweak object being an array as it has been fixed
🐛 (utils.ts): fix the issue with the tweaksBuildedObject being an array instead of an object by accessing the first element of the array

fix tweaks been displayed as an array

---

scripts/gcp/deploy_langflow_gcp.sh

Resolved an issue with installing and running Langflow. The initial installation via pip install langflow and subsequent command langflow --host 0.0.0.0 --port 7860 encountered errors. The solution involved:
- Upgrading pip to the latest version.
- Updating the system packages.
- Reinstalling Langflow with pip3.
- Adjusting the execution command to langflow run --host 0.0.0.0 --port 7860.

fix gcp deployment script

---

pyproject.toml
src/backend/base/pyproject.toml
src/frontend/src/utils/utils.ts

Refactor getCurlCode function to fix JSON formatting issue

fix tweaks problem in curl

---

poetry.lock
pyproject.toml

html2text is GPL 3.0 licensed and this brings deploying and packaging issues as LangFlow is a MIT licensed project.
html2text is only used when using langchain document loader by EverNoteLoader.
The point is that if you wish to use it, you should add this additionally dependency to your application but it shouldn't be imported by default

deps: remove unused dependency html2text (GPL3-0)

---

src/backend/base/langflow/api/v1/endpoints.py

`/custom_component/reload` endpoint reads the directory in the file system without checking the input parameter. 
I'd have added path validation but the endpoint is not used by frontend so I think it's better to remove it completely

backend: remove unsecure and unused endpoint /custom_component/reload

---

src/backend/base/langflow/api/utils.py

while calling custom_component the check for the path to be child of the cache directory is performed after the `path.exists` call which could bring to [security vulnerabilities](https://owasp.org/www-community/attacks/Path_Traversal)

fix uncontrolled data used in path expression from /custom_component

---

src/backend/base/langflow/components/memories/AstraDBMessageReader.py
src/backend/base/langflow/components/memories/AstraDBMessageWriter.py

This Pull Request adds Chat History based on session IDs for Astra DB.

Feature: Updated Chat History for Astra DB

---

docs/docs/administration/custom-component.mdx
docs/docs/administration/langfuse_integration.mdx

super minor doc pr that I ran into when starting to add custom components
previous versions of langflow would only call `langflow` in order to start up the langflow server, but now it is `langflow run`.
this PR updates docs to reflect that change.

Update CLI command in docs

---

poetry.lock
pyproject.toml
src/backend/base/langflow/components/vectorsearch/ChromaSearch.py
src/backend/base/langflow/components/vectorstores/Chroma.py

This pull request updates the import statements for `chromadb` in `ChromaSearch.py` and `Chroma.py` files. The previous import statements were outdated and needed to be updated to the latest version. This change ensures that the code is compatible with the latest version of `chromadb`.
This also fixes #1882

Update chromadb import in ChromaSearch.py and Chroma.py

---

.github/workflows/docker-build.yml
.github/workflows/pre-release.yml
poetry.lock
pyproject.toml
src/backend/base/poetry.lock
src/backend/base/pyproject.toml

- Updated the versions in the `pyproject.toml` files for `langflow` and `langflow-base`.
- Added a new workflow called "Docker Build and Push" to automate building and pushing Docker images based on release type and version.
- Added a new workflow called "Pre-release" to automate releasing Langflow packages based on release type and version.
These changes ensure that the project is up to date with the latest versions and streamline the process of building and releasing Docker images.

Update pyproject.toml versions and add Docker Build and Push workflow

---

src/backend/base/langflow/base/flow_processing/utils.py
src/backend/base/langflow/base/tools/flow_tool.py
src/backend/base/langflow/components/experimental/FlowTool.py
src/backend/base/langflow/components/experimental/RunFlow.py
src/backend/base/langflow/components/experimental/SubFlow.py
src/backend/base/langflow/helpers/flow.py

This pull request adds utility functions `build_records_from_run_outputs` and `build_records_from_result_data` to the codebase. These functions are used to build records from run outputs and result data, improving code organization and reusability.
These functions fix the Sub Flow and Run Flow components.

Fixed Sub Flow, Run Flow and Flow as Tool components

---

src/backend/base/langflow/components/vectorsearch/ChromaSearch.py
src/backend/base/langflow/components/vectorstores/Chroma.py

The code changes in `ChromaSearch.py` and `Chroma.py` import the `chromadb` library and use it to create a `HttpClient` object. This change enables the components to interact with a Chroma server for vector search functionality.
This commit message follows the established convention of starting with a type (feat for feature) and providing a concise summary of the changes.

feat: Update ChromaSearch and ChromaComponent to use chromadb library

---

src/backend/base/langflow/components/experimental/SplitText.py

This pull request refactors the SplitTextComponent to store the parent and text data in a Record object. This change improves the code structure and makes it easier to access and manipulate the data.
#1997

Refactor SplitTextComponent to store parent and text data in Record object

---

src/frontend/src/pages/FlowPage/components/extraSidebarComponent/index.tsx

This pull request updates the parent disclosure title in the ExtraSidebar component from "Core Components" to "Basic Components". Additionally, it changes the key for the ParentDisclosureComponent from "Extended" to "Advanced". These changes improve the clarity and consistency of the component's labels.

Update parent disclosure title in ExtraSidebar component

---

src/backend/base/langflow/api/utils.py
src/backend/base/langflow/api/v1/chat.py
src/backend/base/langflow/api/v1/schemas.py
src/backend/base/langflow/graph/graph/base.py
src/backend/base/langflow/graph/schema.py
src/backend/base/langflow/services/cache/service.py
src/backend/base/langflow/services/cache/utils.py
src/backend/base/langflow/services/chat/service.py
src/frontend/src/customNodes/genericNode/components/parameterComponent/index.tsx
src/frontend/src/customNodes/genericNode/index.tsx
src/frontend/src/pages/FlowPage/components/nodeToolbarComponent/index.tsx
src/frontend/src/style/applies.css
src/frontend/tailwind.config.js

This PR changes how freeze works by caching the result from a built Vertex and reusing it if `frozen` is True. 
It also adds the `used_frozen_result` attribute to the ResultDataResponse model which can be accessed and used in the frontend app.

Fixed freeze implementation

---

src/backend/base/langflow/components/models/OllamaModel.py
src/backend/base/langflow/components/vectorstores/Qdrant.py

This pull request includes several code refactorings to improve the readability and maintainability of the codebase. The changes include reordering and organizing the initialization parameters in the QdrantComponent class, removing unused imports and cleaning up code formatting in the OllamaModel.py file, updating comments and docstrings for clarity and consistency in the OllamaModel.py file, and refactoring the logic for setting the base URL in the get_model method of the OllamaModel.py file to improve maintainability and readability. These changes aim to make the codebase more organized and easier to understand for future development and maintenance.

Fixed Ollama base url handling and Qdrant component

---

src/frontend/src/customNodes/genericNode/index.tsx

This pull request removes the `NATIVE_CATEGORIES` constant and simplifies the logic for checking the template code value in the `GenericNode` component. The logic now checks if the `data.node.template.code.value` exists before proceeding. Additionally, the logic for checking the template code value has been simplified by removing the unnecessary check for `NATIVE_CATEGORIES.includes(types[data.type])`.

(frontend): Remove NATIVE_CATEGORIES constant and simplify logic for checking template code value in GenericNode component

---

src/frontend/src/components/codeTabsComponent/index.tsx
src/frontend/src/components/dictComponent/index.tsx
src/frontend/src/customNodes/genericNode/components/parameterComponent/index.tsx
src/frontend/src/modals/editNodeModal/index.tsx
src/frontend/src/pages/FlowPage/components/nodeToolbarComponent/index.tsx

- Fixed Infinite Render Loop: Removed redundant useEffect hooks that were causing infinite re-renders in React.
- Unified Data Source: Modified the editNodeModal and parametersComponent to pull information from a single source, ensuring synchronized value updates across both components.
- Local Testing: All tests passed successfully on the local environment.

Fix Application Crash with Multiple Nested Dict Components in Flow

---

src/backend/base/langflow/api/v1/login.py
src/backend/base/langflow/initial_setup/setup.py
src/backend/base/langflow/main.py
src/backend/base/langflow/services/auth/utils.py

Currently if auto_login = true, the super user is being initialized when the auto_login endpoint is called the first time. 
This has multiple problems:
1. If two concurrent calls happen, one of the client gets an error
2. since the API auth header is not needed in this mode, without calling auto_login is not possible to call other endpoints.
Changes:
* Moved superuser initialization at the startup
* The auto_login endpoint just generates the long term token

fix: create superuser at startup to avoid concurrency issues

---

.github/workflows/docker-build.yml
scripts/factory_restart_space.py

The code changes include adding a new step in the `.github/workflows/docker-build.yml` file to wait for Docker Hub to propagate. Additionally, a new script `factory_restart_space.py` is added in the `scripts` directory to restart the HuggingFace Spaces build. This script uses the `HfApi` and `rich` libraries to interact with the HuggingFace Hub API and print the space runtime.
Note: The commit message has been generated based on the provided code changes and recent commits.

feat: Add Docker Hub propagation wait and HuggingFace Spaces build restart

---

src/frontend/src/modals/apiModal/utils/get-curl-code.tsx

This pull request fixes an issue in the `getCurlCode` function where the endpoint URL was not being interpolated correctly. The patch updates the URL interpolation to ensure that the correct URL is used when generating the curl command.

Fix endpoint URL interpolation issue in getCurlCode

---

Makefile
pyproject.toml
tests/test_endpoints.py

The Makefile has been modified to update the pytest arguments in the `tests` target. The `--instafail` flag has been replaced with `-ra -n auto -m "not api_key_required"`. This change allows for better test execution by including additional options for reporting, parallelization, and test selection.
(test_endpoints.py) Add pytest marker 'api_key_required' to mark tests that require an API key for authorization

(refactor) Update pytest arguments in Makefile for better test execution

---

src/frontend/src/routes.tsx

✨ (routes.tsx): implement lazy loading for route components to improve performance
✨ (routes.tsx): add Suspense fallback with LoadingComponent for better UX during lazy loading

Add lazy load on router to improve bootstrap application performance

---

poetry.lock
pyproject.toml
src/backend/base/poetry.lock

This pull request upgrades the couchbase dependency to version 4.2.1 and adds it to the couchbase extras section for better organization and management of dependencies. The upgrade includes making the couchbase dependency optional. This change ensures that the project can work with the latest version of couchbase and provides flexibility in choosing whether to include the couchbase dependency.

Upgrade couchbase dependency to version 4.2.1 with extras and make it optional

---

.github/workflows/docker-build.yml
.github/workflows/docker_test.yml
.github/workflows/pre-release-langflow.yml
.github/workflows/release.yml
docker/build_and_push.Dockerfile
docker/build_and_push_backend.Dockerfile
docker/frontend/build_and_push_frontend.Dockerfile
docker/frontend/nginx.conf
docker/frontend/start-nginx.sh

Changes:
* Improved official image
* Added runtime layer to keep only the virtual environement without source code
* Reproducible build by removing poetry lock in the docker image
* Added opencontainers labels
* Add test on CI to verify build is working with correct version of langflow
* Added a new official image langflow-ai/langflow-backend meant to be ran as backend-only
* Start from the official image
* Remove the frontend directory (improve size and reduce vulnerability surface)
* Run with backend-only by default
* Added a new official image langflow-ai/langflow-frontend meant to be ran as frontend-only
* Uses nginx debian official image
* Build NPM and copy the build files into the nginx directory
* Backend url must be provided at runtime via env or via first arg (env BACKEND_URL)
* …

docker: improve image layout and backend-only/frontend-only images

---

src/backend/base/langflow/base/data/utils.py

The original read_text_file method encountered an error when importing a text file containing Chinese characters, specifically:
`Error building vertex File: Error loading file /tmp/test.txt: 'gbk' codec can't decode byte 0xaf in position 7: illegal multibyte sequence`
This error occurred due to incorrect or incompatible character encoding when reading the file.
To resolve this issue, the method was updated to automatically detect the file's encoding using the chardet library. The new implementation reads the file in binary mode to determine the encoding and then reopens the file with the detected encoding to properly read its content.
- The updated method was tested with various text files containing Chinese characters and other encodings to ensure compatibility and proper functionality. …

Correctly Handle Text File Encoding to Avoid 'GBK' Codec Errors

---

src/backend/base/langflow/base/curl/parse.py
src/backend/base/langflow/services/monitor/service.py

Current there are three lint errors that are type mismatch. cc @anovazzi1 @ogabrielluiz 
```
$ make lint
poetry run mypy --namespace-packages -p "langflow"
src/backend/base/langflow/base/curl/parse.py:18: error: First argument to namedtuple() should be "ParsedArgs", not "ParsedContext"  [name-match]
src/backend/base/langflow/memory.py:103: error: Argument 1 to "delete_messages" of "MonitorService" has incompatible type "str"; expected "list[int]"  [arg-type]
src/backend/base/langflow/api/v1/monitor.py:89: error: Argument "message_id" to "update_message" of "MonitorService" has incompatible type "str"; expected "int"  [arg-type]
```

fix lint - type mismatch

---

src/backend/base/langflow/components/model_specs/ChatOpenAISpecs.py

both the openai embeddings and chatOpenAI hide this option in the UI. 99% of the time you want to use the openai service so this option is useless

openai model spec openai_api_base should be an advanced option

---

src/backend/base/langflow/base/tools/base.py

Modified the status to include args_schema when the tool has it.
You can use this translation in your commit message.

refactor: Include Missing Field in Tool Status

---

docker/build_and_push.Dockerfile

After this PR https://github.com/langflow-ai/langflow/pull/2071 curl is nomore available in the container.
curl is very useful to test the endpoints locally and to download flows if needed

docker: add curl to the image

---

src/frontend/src/modals/apiModal/utils/get-python-api-code.tsx
src/frontend/src/modals/apiModal/utils/get-python-code.tsx

Ensures that the tweaks object exists before calling stringify on it. Before this change, attempting to create an empty project would result in an error, prompting us to restart langflow. (@ogabrielluiz perhaps that is a good test to add, creation of empty project?) 
Tweaks correctly showing empty with empty project:
```
TWEAKS = {}
```

fix: ensure tweaks object exists

---

src/backend/base/langflow/services/database/service.py

SQLite can be tuned for performance with PRAGMA command. This has to be performed everytime DB is connected. The PR uses a SQLAlchmey's connect listener.

Improve SQLite performance

---

.gitignore
src/backend/base/langflow/base/io/chat.py
src/backend/base/langflow/components/inputs/ChatInput.py
src/backend/base/langflow/components/outputs/ChatOutput.py
src/backend/base/langflow/initial_setup/starter_projects/Basic Prompting (Hello, world!).json
src/backend/base/langflow/initial_setup/starter_projects/Langflow Blog Writter.json
src/backend/base/langflow/initial_setup/starter_projects/Langflow Document QA.json
src/backend/base/langflow/initial_setup/starter_projects/Langflow Memory Conversation.json
src/backend/base/langflow/initial_setup/starter_projects/Langflow Prompt Chaining.json
src/backend/base/langflow/initial_setup/starter_projects/VectorStore-RAG-Flows.json
tests/test_endpoints.py

This pull request includes two changes. First, the `.gitignore` file is updated to include `*.db-shm` and `*.db-wal` files. Second, the `ChatInput` and `ChatOutput` classes are refactored to include a new `return_message` parameter. This parameter allows the caller to specify whether they want the message to be returned as a `Message` object or just the message text. These changes improve the functionality and maintainability of the code.

Update .gitignore and refactor ChatInput and ChatOutput

---

src/backend/base/langflow/components/vectorsearch/AstraDBSearch.py
src/backend/base/langflow/components/vectorstores/AstraDB.py

All Astra tokens' display_name should be using the same name as `Astra DB Application Token`
cc @erichare @jordanrfrazier

use Astra DB Application Token for all Astra token's display_name

---

docker/frontend/nginx.conf
docker/frontend/start-nginx.sh

currently the frontend image listens always only on port 80. 
Changes:
* added a parameter to configure to change it when running the container
* changed default to 8080 since port <1024 normally requires root access

docker: add customizable port for frontend image

---

.github/workflows/docker_test.yml
docker/build_and_push.Dockerfile
docker/build_and_push_base.Dockerfile
docker/frontend/build_and_push_frontend.Dockerfile

Fixes #2142
After adding langsmith support, the backend throws `TypeError: ForwardRef._evaluate() missing 1 required keyword-only argument: 'recursive_guard'`.
The root cause is pydantic https://github.com/pydantic/pydantic-core/issues/1292
the only workaround is to use <=3.12.3
this PR also fixes a problem running the image on arm64 (Mac M* family) `ModuleNotFoundError: No module named 'pydantic_core._pydantic_core'`

docker: force python version to 3.12.3

---

src/backend/base/langflow/components/embeddings/AzureOpenAIEmbeddings.py
src/backend/base/langflow/components/embeddings/OpenAIEmbeddings.py

Adds support for `dimension` parameters to the openai models (of which I think those are the only that currently support dimensions, per the langchain models). Tested and verified collections are created with the input dimensions. 
Only addition I could add is a "default" or "suggested" value in the UI, though we'd have to do some magic to update that value if the user changes the model. I haven't done much javascript before, so wasn't sure how to go about that. 
Closes https://github.com/langflow-ai/langflow/issues/2145

[feat] add embedding dimensions parameters to openai models

---

src/backend/base/langflow/services/monitor/schema.py
src/backend/base/langflow/services/monitor/service.py

Refactor the MessageModel class in schema.py to include methods for validating and serializing the 'files' field. This ensures that the 'files' field can be properly handled when it is a string or a list.
In service.py, update the query in the MonitorService class to include the 'files' field when retrieving messages from the database. This ensures that the 'files' field is included in the query results.

chore: Update schema.py and service.py to handle file serialization and deserialization

---

src/backend/base/langflow/services/auth/utils.py
tests/test_user.py

This pull request improves the error handling and logging in the `get_current_user_by_jwt` function. It adds better error messages and logs when authentication fails, the token expires, or the user is not found or inactive. This enhances the security and user experience of the application.

Improve error handling and logging in get_current_user_by_jwt function

---

src/backend/base/langflow/custom/custom_component/custom_component.py

This pull request refactors the CustomComponent class to handle the repr_value attribute more efficiently. The changes include updating the custom_repr() method to properly handle different types of repr_value, such as dictionaries and BaseModels. Additionally, the to_json() method is now used when available. This improves the overall performance and functionality of the CustomComponent class.

Refactor CustomComponent repr_value handling

---

src/frontend/src/CustomNodes/GenericNode/components/parameterComponent/index.tsx
src/frontend/src/alerts/alertDropDown/components/singleAlertComponent/index.tsx
src/frontend/src/components/tableComponent/index.tsx
src/frontend/src/modals/IOModal/components/chatView/index.tsx
src/frontend/src/modals/codeAreaModal/index.tsx
src/frontend/src/modals/editNodeModal/index.tsx
src/frontend/src/pages/FlowPage/components/PageComponent/index.tsx
src/frontend/src/style/applies.css
src/frontend/src/style/classes.css
src/frontend/src/style/index.css
src/frontend/tailwind.config.js
src/frontend/tests/end-to-end/actionsMainPage.spec.ts
src/frontend/tests/end-to-end/chatInputOutput.spec.ts
src/frontend/tests/end-to-end/chatInputOutputUser.spec.ts
src/frontend/tests/end-to-end/generalBugs.spec.ts
src/frontend/tests/end-to-end/group.spec.ts
src/frontend/tests/end-to-end/logs.spec.ts

This pull request includes several bug fixes and improvements to the project. Each commit addresses a specific issue or enhancement, ensuring a more robust and user-friendly experience.
1. **Fixed if/else that is not on useEffect**
- Corrected the conditional logic to ensure proper execution flow outside of useEffect.
2. **Fixed badge size on Advanced modal**
- Adjusted the badge size in the Advanced modal for better visual alignment and consistency.
3. **Changed icon of message**
- Updated the message icon to improve user interface clarity and aesthetics.
4. **Fixed grabbing to override children**
- Resolved an issue where grabbing was interfering with child components, ensuring proper functionality and user interaction.
5. **Fixed error color and padding**
- Enhanced the error display …

Fix: General UI Bugs

---

src/backend/base/langflow/api/v1/endpoints.py
src/backend/base/langflow/custom/custom_component/custom_component.py
src/backend/base/langflow/processing/process.py
tests/test_endpoints.py

- Refactored the CustomComponent to improve the handling of repr_value.
- Refactored the simplified_run_flow and webhook_run_flow functions in endpoints.py to remove caching.
- Removed caching from endpoints.py and updated tests accordingly.

Refactor endpoints.py to improve code handling and remove caching

---

src/backend/base/langflow/base/flow_processing/utils.py
src/backend/base/langflow/graph/schema.py

These changes fix the issue in #2061.
* Updated `build_records_from_result_data`, because the SubFlow and RunFlow component uses this function to collect the outputs to return from the build method. The updates make sure that the function handles results that don't contain messages (ResultData.messages)
* Updated the schema to consider the Records output type as an output type. I'm not sure why it wasn't but if you have a subflow that returns records via  records output node, the records aren't considered outputs. This update makes sure they are returned.
* I build a subflow that takes an input, transforms it, then returns each of the output types (text, chat, record, records)
* I build a parent flow that calls the flow using the SubFlow node and tested each case to make sure the outputs …

Support returning sub flow outputs

---

src/backend/base/langflow/graph/graph/base.py
src/backend/base/langflow/graph/graph/runnable_vertices_manager.py

This commit adds a new optional `cache` parameter to the `RunnableVerticesManager` class in the `runnable_vertices_manager.py` file. The `cache` parameter allows controlling whether the graph data should be cached or not when retrieving the next runnable vertices for a given vertex. If `cache` is set to `True`, the graph data will be cached using the `set_cache_coro` function. If `cache` is set to `False`, the graph data will not be cached.
This change was made to try to avoid locks and reused values

feat: Add cache parameter to RunnableVerticesManager

---

tests/unit/conftest.py

All unit tests are relocated to tests/unit but it didn't refer to the data files in the correct ./data/ folder.
The bug might be introduced by this PR #2189

fix path to the unit test data folder

---

src/backend/base/langflow/initial_setup/setup.py

In setup.py, there is one instance still using logging but the rest use `loguru`. This PR removes the one logging import.

remove the default logging use loguru

---

src/backend/base/langflow/api/v1/chat.py
src/backend/base/langflow/graph/graph/base.py
src/backend/base/langflow/graph/graph/runnable_vertices_manager.py
src/backend/base/langflow/graph/vertex/base.py
src/backend/base/langflow/initial_setup/setup.py

Using the Vector Store RAG as example, there are two inputs vertices: the chat input and the embeddings.
They run in parallel. 
Currently the computation of the "next vertex" is done in parallel by both the tasks. The problem is that one task could use the other task as "next task" because it's not completed yet. 
In the Vector Store RAG example, if the embeddings vertex completes as first task, it will schedule the chat input to be built because it's not built yet and it's a predecessor of the chain embeddings chain (both points to the vector store).
Running a vertex with custom inputs (like an API call passing input_value) twice is problematic because the second call will not use the inputs but instead will rely on the default value (this is because the vertex is supposed to run only …

fix: graph could re-run input vertices twice and override the input value

---

src/backend/base/langflow/graph/graph/base.py
tests/unit/conftest.py

Currently when a vertex fails to be processed for an internal problem, the real error is only logged and not raised. Then the exception is `ValueError: The message must be an iterator or an async iterator.`
which is misleading and hard to understand

fix: graph process should raise the actual error when failing

---

src/backend/base/langflow/__main__.py

it makes no sense to open the browser if the service is backend only mode so it's better to automatically turn it off

fix: do not open browser on backend_only mode

---

.github/workflows/pr-checker.yml

add a `pr-checker` ci job to make sure sufficient PR title and description are provided.
For the description, we can use a template. So this job so far just make sure it meets 25 characters.
Sufficient PR description is needed because the repo has enforced merge-squash that only one commit is merged to the dev branch after squashing all the commits under a PR. The history may get lost because of that therefore we enforce the sufficient PR title.

ci pr-checker enforce meaningful pr title and description

---

poetry.lock
pyproject.toml
src/backend/base/langflow/services/settings/base.py
src/backend/base/langflow/services/variable/base.py
src/backend/base/langflow/services/variable/factory.py
src/backend/base/langflow/services/variable/kubernetes_secrets.py
src/backend/base/langflow/services/variable/service.py
tests/unit/test_kubernetes_secrets.py

This PR introduces an alternate backend to store variable in kubernetes secrets.
It addresses these two feature requests
https://github.com/langflow-ai/langflow/issues/2151
https://github.com/langflow-ai/langflow/issues/2150
@ogabrielluiz 
This implementation stores both Credential and Generic variables in Kubernetes secrets when setting_service.variable_store = "kubernetes"
Or the second option is to only store the variable type is `Credential` to Kubernetes secrets while the rest `Generic` still are stored in `db`. For that we can introduce a flag `setting_service.credential_store` 
Let me know which one is more appropriate.

Store variables as Kubernetes Secrets

---

src/backend/base/langflow/custom/custom_component/component.py

This pull request addresses a bug by adding the trace_name parameter to the service tracing method call. This ensures the correct trace handling within the application.
However, I am not entirely sure about the appropriate value for trace_name. Suggestions for the correct value are welcome.

fix: add trace_name parameter to method call

---

poetry.lock
pyproject.toml
src/backend/base/langflow/components/vectorstores/AstraDB.py
src/backend/base/langflow/components/vectorstores/Cassandra.py
src/backend/base/langflow/components/vectorstores/Chroma.py
src/backend/base/langflow/components/vectorstores/Couchbase.py
src/backend/base/langflow/components/vectorstores/FAISS.py
src/backend/base/langflow/components/vectorstores/MongoDBAtlasVector.py
src/backend/base/langflow/components/vectorstores/Pinecone.py
src/backend/base/langflow/components/vectorstores/Qdrant.py
src/backend/base/langflow/components/vectorstores/Redis.py
src/backend/base/langflow/components/vectorstores/SupabaseVectorStore.py
src/backend/base/langflow/components/vectorstores/Upstash.py
src/backend/base/langflow/components/vectorstores/Vectara.py
src/backend/base/langflow/components/vectorstores/Weaviate.py
src/backend/base/langflow/components/vectorstores/pgvector.py
src/frontend/package-lock.json

- CassandraVectorStoreComponent;
- CouchbaseVectorStoreComponent;
- FaissVectorStoreComponent;
- MongoVectorStoreComponent;
- PGVectorStoreComponent;
- PineconeVectorStoreComponent;
- QdrantVectorStoreComponent;
- SupabaseVectorStoreComponent;
- UpstashVectorStoreComponent;
- VectaraVectorStoreComponent;
- WeaviateVectorStoreComponent;
- RedisVectorStoreComponent;
- Chroma DB
- Pinecone
- Qdrant
- FAISS
- AstraDB
- Redis
- MongoDB

Fixes and Tests for VectorStore Default Components

---

src/frontend/package-lock.json
src/frontend/src/App.tsx
src/frontend/src/alerts/displayArea/index.tsx
src/frontend/src/components/stringReaderComponent/index.tsx
src/frontend/src/components/tableComponent/components/tableAutoCellRender/index.tsx
src/frontend/src/components/tableComponent/index.tsx
src/frontend/src/modals/IOModal/components/SessionView/index.tsx
src/frontend/src/modals/textModal/components/textEditorArea/index.tsx
src/frontend/src/modals/textModal/index.tsx
src/frontend/src/pages/FlowPage/components/extraSidebarComponent/index.tsx
src/frontend/src/pages/SettingsPage/pages/messagesPage/hooks/use-updateMessage.tsx
src/frontend/src/pages/SettingsPage/pages/messagesPage/index.tsx
src/frontend/src/shared/components/textOutputView/index.tsx

This pull request updates the TextModal component to use the TextEditorArea component for text input. It also includes several bug fixes and refactors related to text input functionality.

Update TextModal to use TextEditorArea for text input

---

src/backend/base/langflow/services/variable/factory.py

This pull request fixes an issue where the optional import for the variable service was happening even if it wasn't used. The import has been moved inside the conditional block to ensure it only happens when needed.

Fix optional import for variable service

---

src/backend/base/langflow/services/variable/factory.py
src/backend/base/langflow/services/variable/kubernetes.py
src/backend/base/langflow/services/variable/service.py

This pull request includes a fix for making the optional import happen only if used and separates the Variable services. The changes ensure that the import is only performed when necessary and improve the organization of the Variable services.

Fix optional import and separate Variable services

---

src/backend/base/langflow/api/utils.py
src/backend/base/langflow/api/v1/endpoints.py
src/backend/base/langflow/api/v1/validate.py
src/backend/base/langflow/base/prompts/api_utils.py
src/backend/base/langflow/components/prompts/Prompt.py
src/backend/base/langflow/custom/custom_component/component.py
src/backend/base/langflow/custom/utils.py
src/backend/base/langflow/template/utils.py
src/frontend/src/CustomNodes/GenericNode/index.tsx
src/frontend/src/CustomNodes/hooks/use-check-code-validity.tsx

Adds a `post_code_processing` method that runs right after the component code is validated. The previous logic was moved into the `Component` class and classes that override this method should call the `super()` class almost always.  
Components can now define post validation logic such as setting values dynamically when updated.
This PR also fixes the PromptComponent not being allowed to update its code.
Additionally, refactor the prompt validation process in the `validate.py`.

Refactor prompt validation and code processing in Component and PromptComponent classes

---

src/backend/base/langflow/base/vectorstores/model.py
src/backend/base/langflow/components/retrievers/AmazonKendra.py
src/backend/base/langflow/components/retrievers/CohereRerank.py
src/backend/base/langflow/components/retrievers/MetalRetriever.py
src/backend/base/langflow/components/retrievers/VectaraSelfQueryRetriver.py
src/backend/base/langflow/field_typing/constants.py
src/backend/base/langflow/graph/vertex/base.py
src/backend/base/langflow/initial_setup/setup.py
src/backend/base/langflow/schema/artifact.py

Add CohereRerank component.
Additionally, the `post_process_raw` function in `artifact.py` has been updated to set the raw value to "Built Successfully ✨" when the artifact type is unknown. This change improves the clarity of the code and provides a more meaningful message for unknown artifact types.

Add CohereRerank component and update artifact post-processing

---

src/backend/base/langflow/field_typing/constants.py
src/backend/base/langflow/initial_setup/setup.py
src/backend/base/langflow/initial_setup/starter_projects/Langflow Prompt Chaining.json

This pull request refactors the setup.py file to remove the call to the update_new_output function. This change improves the code by eliminating unnecessary function calls and simplifying the codebase.

Refactor setup.py to remove call to update_new_output function and fix Text type

---

src/frontend/src/components/codeTabsComponent/index.tsx
src/frontend/src/modals/apiModal/index.tsx
src/frontend/src/modals/apiModal/utils/get-js-api-code.tsx
src/frontend/src/modals/apiModal/utils/tabs-array.tsx

This commit updates the CodeTabsComponent to handle an additional tab in the code tabs display. The previous implementation had a condition that checked if the active tab index was less than 4, but it has been updated to check if the active tab index is less than 5. This change ensures that the component can handle the new tab and display the corresponding content correctly. The code has been modified in the index.tsx file of the CodeTabsComponent directory.

Adds JS API code example

---

src/backend/base/langflow/custom/directory_reader/directory_reader.py

The code changes in `directory_reader.py` introduce a check to skip files that are located in the `deactivated` folder. This improves the efficiency of the directory reading process by excluding unnecessary files.

refactor: Skip deactivated files in directory_reader.py

---

src/backend/base/langflow/api/v1/endpoints.py
src/backend/base/langflow/api/v1/schemas.py
src/frontend/src/CustomNodes/GenericNode/index.tsx
src/frontend/src/CustomNodes/hooks/use-handle-node-class.tsx
src/frontend/src/CustomNodes/hooks/use-update-node-code.tsx
src/frontend/src/controllers/API/index.ts
src/frontend/src/modals/codeAreaModal/index.tsx
src/frontend/src/types/api/index.ts
src/frontend/src/types/components/index.ts

This pull request includes changes to the codebase that improve the handling of component types in the CustomComponentResponse model and the GenericNode component. The CustomComponentResponse model now includes a "type" field, and the GenericNode component has been updated to handle this field when updating the node code. These changes enhance the consistency and clarity of the API response and ensure that the GenericNode component can correctly handle different types of components.

Refactor CustomComponentResponse and GenericNode to handle component type

---

src/backend/base/langflow/components/data/URL.py

Fix regex validation in URL component

fix regex validation for url

---

.github/workflows/docker-build.yml
.github/workflows/release.yml

This pull request updates the `docker-build.yml` file to include the `pre_release` option and the `base-latest` tag. The `pre_release` option is now included as a boolean type with a default value of `true`. Additionally, the `base-latest` tag is now added to the `tags` field when the `release_type` is set to "base". This ensures that the latest base image is tagged as `langflowai/langflow:base-latest`.

Update docker-build.yml to include pre_release option and base-latest tag

---

src/backend/base/langflow/components/vectorstores/Vectara.py

This pull request refactors the `VectaraVectorStoreComponent` to handle embedding input and add documents to the vector store. It updates the `build_vector_store` method to build the `Vectara` object and adds the `_add_documents_to_vector_store` method to add documents to the vector store. The `search_documents` method is also updated to use the `build_vector_store` method and provide a status message.

Refactor VectaraVectorStoreComponent to handle embedding input and add documents to vector store

---

src/backend/base/langflow/components/embeddings/OllamaEmbeddings.py

This PR sets a default value for the temperature attribute of the Ollama model. The goal is to enhance the user experience.

set default temperature value

---

docs/docs/components/custom.mdx
src/backend/base/langflow/components/deactivated/SplitText.py
src/backend/base/langflow/components/embeddings/AstraVectorize.py
src/backend/base/langflow/components/helpers/IDGenerator.py
src/backend/base/langflow/components/prototypes/__init__.py
src/backend/base/langflow/components/vectorstores/AstraDB.py
src/frontend/src/stores/flowStore.ts

This pull request updates the imports in several files to use the `MessageTextInput` class instead of `TextInput`. It also runs code formatting using `ruff` and `prettier` to ensure consistent code style.

Update imports and run code formatting

---

src/backend/base/langflow/components/agents/ToolCallingAgent.py
tests/unit/test_helper_components.py

Update the `ToolCallingAgentComponent` to use `Dict[str, str]` for values in the `input_dict` type. This ensures consistency and improves code readability.
This pull request also includes the removal of unused tests.

Refactor ToolCallingAgentComponent input_dict type

---

src/frontend/src/App.tsx
src/frontend/src/contexts/authContext.tsx

This pull request introduces a series of updates aimed at enhancing the data fetching mechanism within our application, alongside improvements to code formatting for better readability and maintainability.

Fix fetch data bug and code formatting

---

src/backend/base/langflow/main.py
src/frontend/src/components/headerComponent/components/menuBar/index.tsx

The middleware breaks requests. Another solution should be created to re-enable this feature.
Should fix #2329 #2332

deactivate stop button until we have a better solution

---

src/backend/base/langflow/services/auth/utils.py

This PR uses consistent http error status code in the auth service. If the user is not an active user, the status code should be 401/unauthorized, currently there are both 400 and 401 in the auth.
Also change the code to http status macro to be consistent with the rest of the auth file.

[Fix] use consistent auth http error status code

---

src/backend/base/langflow/api/v1/endpoints.py
src/backend/base/langflow/services/auth/utils.py

In the simple_run_flow function under the endpoint.py, there are unhandled StatementErrors and the simplified_run_flow handler (the route "/run/{flow_id_or_name}") already has a logic to manage different ValueErrors. So change the code to throw ValueError as is.
The second problem is the simple_run_flow is submitted to BackgroundTasks to run in a background. But the FastAPI background task runner does not handle the exception, so this PR introduces a new function to log the exception without throw to BackgroundTask manager. An error reported by the task group
"/app/.venv/lib/python3.11/site-pa ckages/starlette/middleware/base.p y", line 189, in __call__ | with collapse_excgroups(): | -> <function collapse_excgroups at 0x7fe9dfbd00e0> | File "/usr/local/lib/python3.11/context lib.py", line …

[Fix] unhandled http errors in background tasks

---

tests/test_user.py

Fixes tests with new error codes in authorization setup

Fix user authentication and authorization issues

---

src/backend/base/langflow/api/v1/chat.py
src/backend/base/langflow/api/v1/endpoints.py
src/backend/base/langflow/services/telemetry/schema.py

This pull request refactors the field names in the telemetry service payload for consistency. The payload field names have been updated to follow a consistent naming convention, improving code readability and maintainability.

Refactor telemetry service payload field names for consistency

---

src/backend/base/langflow/api/v1/flows.py

- refactor: Ensure flow names are unique by appending a number if necessary

Bug Fix: Correct Function to Increment Flow Names that Already Exist

---

.github/workflows/lint-js.yml
src/frontend/package.json

Remove auto commit from lint-js and add a formatting check.

Add check-format script and update lint-js.yml

---

docs/docs/deployment/kubernetes.md

This pull request renames the Kubernetes deployment file to have a .md extension instead of the previous extension. This change is made to improve the readability and clarity of the file. No other changes are made in this pull request.

Rename Kubernetes deployment file to .md extension

---

docs/docs/deployment/kubernetes.md

This pull request renames the Kubernetes documentation file to use the .md extension. This change ensures consistency with the file extensions used in the repository.

Rename Kubernetes documentation file to use .md extension

---

src/backend/base/langflow/components/embeddings/AstraVectorize.py
src/backend/base/langflow/components/langchain_utilities/FirecrawlScrapeApi.py

* Add ProviderKey as text field since it's the only auth entry available today
* Hide authentication and external key as advanced fields
* Make provider name and model required
* Make provider as dropdown
* Add complete list of models in the help (better to not hardcode models for now)

components: simplify astra vectorize

---

.github/workflows/js_autofix.yml
.github/workflows/py_autofix.yml
.github/workflows/style-check-py.yml

This pull request adds GitHub workflows for JavaScript and Python autofix. The JavaScript workflow is triggered on pull requests and pushes to the main branch for changes in the "src/frontend" directory. It sets up Node.js, caches Node.js dependencies, installs Node.js dependencies, and runs Prettier for code formatting. The Python workflow is also triggered on pull requests and pushes to the main branch for changes in the "poetry.lock", "pyproject.toml", "src/backend", and "tests" directories. It installs Ruff and runs Mypy for type checking and code formatting.

Add GitHub workflows for JavaScript and Python autofix

---

.github/workflows/auto-update.yml

The auto-update workflow has been added to the repository. This workflow will automatically trigger on pushes to the `dev` and `main` branches. It runs on the latest version of Ubuntu and uses the `tibdex/auto-update@v2` action to perform the auto-update process.

chore: Add auto-update workflow

---

src/backend/base/langflow/graph/graph/base.py

This PR makes so that end_all_traces does not block execution.

chore: make calls to end_all_traces run concurrently

---

src/backend/base/langflow/graph/graph/base.py
src/backend/base/langflow/graph/graph/runnable_vertices_manager.py

Fixes an error where inactivated components would be considered runnable.

fix: Refactor RunnableVerticesManager to consider inactivated vertices in is_vertex_runnable and find_runnable_predecessors_for_successors

---

src/backend/base/langflow/api/v1/files.py

This PR addresses the issue of image display on Windows systems by editing the string that determines the image path. By setting a fixed path for the images, we ensure consistent display across different environments.

Fix Image Display Issue on Windows by Setting a Static Path

---

src/backend/base/langflow/api/v1/endpoints.py
tests/test_webhook.py

This PR makes sure webhook can take any type of input.

Fix webhook endpoint not receiving data that is not JSON

---

.github/workflows/lint-py.yml
.github/workflows/python_test.yml
.github/workflows/style-check-py.yml

Now to merge a PR there are required checks. Those are not ran if no meaningful changes has been made by a PR, but now those are not mergeable without enforcing

ci: always run required checks

---

src/backend/base/langflow/api/v1/monitor.py

This PR addresses an issue with the endpoint that was failing to delete messages from the database. The necessary corrections have been made to ensure that messages are now properly removed when the endpoint is called.

Fix Endpoint to Properly Delete Messages from Database

---

src/frontend/src/pages/FlowPage/components/PageComponent/index.tsx

This PR addresses an issue where Ctrl + C was not working correctly within tooltips. This fix ensures that users can copy text from tooltips using the Ctrl + C shortcut without any issues.

Fix: Ctrl + C not working on tooltips

---

src/frontend/src/controllers/API/index.ts
src/frontend/src/pages/SettingsPage/pages/messagesPage/index.tsx
src/frontend/src/types/messages/index.ts

fix bug where messages couldn't be edited.
Change post to put on frontend

fix edit method on messages

---

src/backend/base/langflow/components/prototypes/ConditionalRouter.py
src/backend/base/langflow/components/prototypes/__init__.py

Fixes lint erros related to types and imports.

chore: fix lint errors 

---

src/frontend/tests/end-to-end/decisionFlow.spec.ts

This pull request introduces a new test to cover the extensive flow in the decisionFlow module. 
The purpose of this test is to ensure that the decision-making process handles complex scenarios as expected and maintains the integrity of the flow logic.

add a new test for a huge flow -> decisionFlow

---

.github/workflows/py_autofix.yml

Update ruff command to reflect new version's api.

chore: Update ruff command in py_autofix.yml to use 'ruff check' before 'ruff --fix-only'

---

.github/workflows/docs_test.yml
.github/workflows/lint-js.yml
.github/workflows/lint-py.yml
.github/workflows/python_test.yml
.github/workflows/style-check-py.yml
.github/workflows/typescript_test.yml

Remove the merge_group configuration from the workflows to simplify the CI pipeline.

ci: remove merge_group from workflows

---

src/backend/base/langflow/base/models/model.py
src/backend/base/langflow/components/models/AnthropicModel.py
src/backend/base/langflow/components/models/AzureOpenAIModel.py
src/backend/base/langflow/components/models/BaiduQianfanChatModel.py
src/backend/base/langflow/components/models/CohereModel.py
src/backend/base/langflow/components/models/HuggingFaceModel.py
src/backend/base/langflow/components/models/MistralModel.py
src/backend/base/langflow/components/models/OllamaModel.py
src/backend/base/langflow/components/models/VertexAiModel.py

Fixes #2333
model name is not needed, users just need to refer to the deployment on azure.

fix: azure openai model component: resource not found

---

src/backend/base/langflow/components/langchain_utilities/FirecrawlCrawlApi.py
src/backend/base/langflow/components/models/AmazonBedrockModel.py
src/backend/base/langflow/custom/custom_component/component.py

If you use Bedrock chat, you get `Error building Component Amazon Bedrock: Key cache already exists in AmazonBedrockComponent` with the latest version (1.0.5)

fix(bedrock): fix error 'Key cache already exists'

---

src/frontend/src/components/headerComponent/index.tsx
src/frontend/src/modals/IOModal/components/chatView/fileComponent/index.tsx
src/frontend/src/modals/IOModal/components/chatView/fileComponent/utils/handle-download.tsx
src/frontend/src/pages/SettingsPage/pages/GeneralPage/components/ProfilePictureForm/components/profilePictureChooserComponent/hooks/use-preload-images.tsx
src/frontend/src/pages/SettingsPage/pages/GeneralPage/components/ProfilePictureForm/components/profilePictureChooserComponent/index.tsx

There's already a redirect in place for api calls. 
This affect the user profile and the file react component in general 
Fixes #2408

fix(frontend): do not use backend url in <img>

---

poetry.lock
pyproject.toml
src/backend/base/langflow/components/deactivated/ChatLiteLLMModel.py
src/backend/base/langflow/components/models/AmazonBedrockModel.py
src/backend/base/langflow/components/models/HuggingFaceModel.py

Fixes:
- Add default values to Azure OpenAi mandotory component;
- Add the `model_id` field (auto resolution was broken);
- Add HuggingFace as an extra dependency;
Refact:
- Remove redundant attribution on children of LCModelComponent;

fix: resolve Model Issues and add huggingface dependency

---

src/backend/base/langflow/base/vectorstores/model.py
src/backend/base/langflow/components/langchain_utilities/FirecrawlCrawlApi.py
src/backend/base/langflow/components/vectorstores/AstraDB.py
src/backend/base/langflow/components/vectorstores/Cassandra.py

Added support for:
- Hybrid Search (full text + vector)
- Metadata filter (vector + hard filter on metadata)
- Similarity with min score
Added support for:
- Metadata filter (vector + hard filter on metadata)
- Similarity with min score

feat(cassandra/astradb): hybrid search support

---

.github/workflows/release.yml

This pull request updates the test job in the release.yml file to include both Typescript and Python tests. Previously, only the Typescript tests were being run. Now, the pull request ensures that both Typescript and Python tests are executed when the test job is triggered.

ci: update test job in release.yml to include both Typescript and Python tests

---

src/backend/base/langflow/graph/graph/base.py

This fixes a bug where components were called in the wrong order.

fix(base.py): update get_successors function call to include 'recursive=False' parameter

---

src/backend/base/langflow/api/__init__.py
src/backend/base/langflow/api/health_check_router.py
src/backend/base/langflow/main.py

Since /health is also supported by uvicorn, so until the langflow's router is initialized. `/health` returns the status of uvicorn. That does not reflect the readiness of the langflow. 
This PR introduces a new endpoint `/health_check` that also test key services like chat, session, and variable services that make sure cache , DB, or kubernetes backend are working. It offers more reliable service type of check rather a simple route based `health` check. Only a few selected services to save the health check time.
Once this PR is merged and released, Kubernetes's probe should use the /health_check endpoint.

feat: key components health check

---

src/backend/base/langflow/schema/artifact.py

Handle the case where the artifact type is unknown and the raw value is not None in the post_process_raw function. Set the raw value to "Built Successfully ✨" in this case.

fix: handle unknown artifact type in post_process_raw function

---

src/backend/base/langflow/api/v1/chat.py
src/backend/base/langflow/graph/graph/base.py
src/backend/base/langflow/services/telemetry/service.py
src/backend/base/langflow/services/tracing/service.py

This pull request includes several fixes and improvements to the TelemetryService class.
- The `send_telemetry_data` method now handles HTTPStatusError and RequestError exceptions separately, providing more specific error messages.
- The `stop` method now cancels the worker task and closes the client to ensure proper cleanup and prevent resource leaks. It also handles any exceptions that may occur during the cleanup process.
- An indentation issue in the `await` statement of the `build_vertex` method has been fixed to comply with PEP8 guidelines.
- The `remove_vertex_from_runnables` method has been added to the Graph class to remove a vertex from the runnables list.
- Several fixes have been made in the `chat.py` file to prevent duplication of results and define when the `end_all_traces` …

fix: make end_all_traces be called at the correct moment

---

.github/release.yml
.github/workflows/conventional-labels.yml

This pull request adds a GitHub Actions workflow that automatically labels pull requests based on Conventional Commits. The workflow uses predefined categories for changelog to improve consistency and clarity in release notes. This will help streamline the labeling process and ensure that pull requests are properly categorized.

ci: add GitHub Actions workflow for labeling PRs with Conventional Commits

---

.github/workflows/conventional-labels.yml

Adds auto_merge_enabled so it is easier to get all status checks to work.

feat: add auto_merge_enabled to pull_request_target types in conventional-labels.yml

---

src/frontend/src/pages/MainPage/components/myCollectionComponent/components/inputSearchComponent/index.tsx

♻️ (index.tsx): simplify disableInputSearch logic by removing redundant conditions

fix: remove uneceessary logic to disable button on search components/flows

---

.github/workflows/typescript_test.yml

This pull request adds outputs to the TypeScript test workflow to capture the status of the tests, improving visibility and tracking of test failures. Additionally, a conditional step is added to the merge-reports job in the workflow to prevent execution if the setup-and-test job fails.

ci: add outputs and conditional step to TypeScript test workflow

---

src/frontend/src/pages/FlowPage/components/nodeToolbarComponent/index.tsx
src/frontend/src/stores/flowStore.ts
src/frontend/src/utils/buildUtils.ts
src/frontend/src/utils/parameterUtils.ts
src/frontend/src/utils/reactflowUtils.ts

This PR introduces a refactor to our front-end codebase, specifically changing the terminology from node to component in our constants. This change aims to improve code readability and maintain consistency with the terminology used throughout our application.

refactor: change node to component on FE constants

---

src/frontend/src/App.tsx
src/frontend/src/controllers/API/queries/api-keys/use-post-add-api-key.ts
src/frontend/src/controllers/API/queries/files/use-get-download-images.ts
src/frontend/src/controllers/API/queries/transactions/use-get-transactions.ts
src/frontend/src/controllers/API/queries/version/use-get-version.ts
src/frontend/src/modals/flowLogsModal/index.tsx
src/frontend/src/types/api/index.ts

- Refactored API structure to be default in every component
- Fixed Version query

fix: refactor of api structure

---

poetry.lock
src/backend/base/langflow/main.py
src/backend/base/langflow/services/settings/base.py
src/backend/base/langflow/services/telemetry/opentelemetry.py
src/backend/base/langflow/services/telemetry/service.py
src/backend/base/poetry.lock
src/backend/base/pyproject.toml

This PR introduces as the first phase of OpenTelemetry implementation.
* Opentelemetry in the existing TelemetryService
* Optionally Prometheus can be enabled
* Prometheus port is configured. The default is 9090.
* Metrics collected by OpenTelemetry can be exposed through Prometheus
* A FastAPI middleware that collects all http related metrics
What's not implemented in this PR
* Other exporters such as Console, Jaeger, Zipkin, or any other customer exporters. 
An example of prometheus scraping
```
$curl localhost:9090/metrics
python_gc_objects_collected_total{generation="0"} 59153.0
python_gc_objects_collected_total{generation="1"} 31939.0
python_gc_objects_collected_total{generation="2"} 4232.0
python_gc_objects_uncollectable_total{generation="0"} 0.0 …
```

feat: opentelemetry and prometheus

---

src/backend/base/langflow/api/v1/chat.py
src/backend/base/langflow/graph/graph/runnable_vertices_manager.py

Vertices in the first layer were being removed from runnable vertices at `/build/{flow_id}/vertices` call but they should actually be removed at the `get_next_runnable_vertices` call.
Also, in `get_next_runnable_vertices` they were being remove only from predecessors but should actually be removed from runnable vertices.

fix(ordering): correctly remove vertex from list of runnable vertices

---

src/frontend/src/App.tsx

This pull request fixes the version issue in the code. The useGetVersionQuery hook has been added to ensure the version is retrieved correctly.

fix: version display

---

.github/workflows/typescript_test.yml

Delete reports checks if anything failed and deletes artifacts in case in case it all worked.

ci: add delete-reports job to delete if all jobs succeed

---

src/frontend/src/components/inputFileComponent/index.tsx
src/frontend/src/modals/IOModal/components/IOFieldView/components/FileInput/index.tsx
src/frontend/src/modals/IOModal/components/chatView/chatInput/index.tsx
src/frontend/src/modals/IOModal/components/chatView/index.tsx

This PR addresses an issue where pasting files into the chat input component was not functioning as expected.

fix: pasting files not working

---

src/backend/base/langflow/__main__.py

The process was not being terminated when the user pressed `Ctrl+C`.

fix(langflow): handle KeyboardInterrupt and terminate process in run function for graceful shutdown

---

src/backend/base/langflow/services/auth/utils.py

This pull request includes a refactoring of the auth utils module to add a padding function for strings. Additionally, it fixes an issue in the auth utils module where the `add_padding` function was not being called if the secret key was valid. The `ensure_valid_key` function now properly handles both cases.

fix: make sure old secret keys are handled as before

---

src/frontend/src/App.tsx
src/frontend/src/components/fetchErrorComponent/index.tsx

🐛 (fetchErrorComponent): add onClick handler to Retry button to ensure retry logic is executed
♻️ (App.tsx): remove console.log statement from setRetry function

fix: add click event on button to retry check connection to backend

---

src/backend/base/langflow/api/health_check_router.py

This pull request adds functionality to the `health_check_router.py` file to check if a user with a specific ID exists in the database. If the user does not exist, the code adds the user to the database with the necessary details. This ensures that the user is present in the database for further processing in the health check. Additionally, the code has been formatted for better readability.

fix: add user to database if not present in health_check

---

poetry.lock
pyproject.toml
src/backend/base/poetry.lock
src/backend/base/pyproject.toml

This pull request updates the version to 1.0.7 in the pyproject.toml file for the "langflow" package. Additionally, the version is also updated to 0.0.83 in the pyproject.toml file for the "langflow-base" package.

chore: update version to 1.0.7 in pyproject.toml

---

src/backend/base/langflow/api/v1/chat.py
src/backend/base/langflow/graph/graph/base.py
src/backend/base/langflow/graph/graph/runnable_vertices_manager.py
src/frontend/src/components/headerComponent/components/menuBar/index.tsx

This pull request refactors the `RunnableVerticesManager` class by updating the `build_run_map` method to take `predecessor_map` and `vertices_to_run` as parameters. This improves code readability and maintainability. Additionally, it fixes a bug in the `activate_state_vertices` method where the `vertices_ids` list was incorrectly used instead of a set. The `update_run_state` method is also added to update the run state with the new `run_predecessors` and `vertices_to_run` values.

fix: update run_manager on state changes

---

src/backend/base/langflow/api/health_check_router.py

This PR addresses comments from https://github.com/langflow-ai/langflow/pull/2510 @nicoloboschi 
\health_check will only check db and cache service.
* Remove folder test for redundant test
* Remove Variable test. Kubernetes based test will be added if required later.
* Update chat/cache test to only evaluate the existence of key
Add a note to clarify why exceptions or detailed errors are not replied to the client because we might leak sensitive data. cc @jordanrfrazier

fix: remove redundant and incorrect health check

---

src/backend/base/langflow/components/vectorstores/AstraDB.py

Already fixed by https://github.com/langflow-ai/langflow/pull/2455
but during a conflict resolution it has been partially reverted
Fixes #2552

fix: astradb ingests twice

---

src/backend/base/langflow/services/utils.py
src/frontend/src/controllers/API/api.tsx
src/frontend/src/stores/foldersStore.tsx

The code changes in `utils.py` check if the superuser exists and if it has never logged in. If both conditions are true, the superuser is deleted from the database. This improves the efficiency and security of the application.

fix: remove redundant superuser only if it has never logged in

---

src/backend/base/langflow/base/models/groq_constants.py

Groq now has Gemma 2 available: https://console.groq.com/docs/models

feat: Add Gemma 2 to Groq model list

---

src/backend/base/langflow/api/v1/chat.py
src/backend/base/langflow/graph/graph/base.py
src/backend/base/langflow/graph/graph/runnable_vertices_manager.py

This commit adds a new set called `vertices_being_run` to the `RunnableVerticesManager` class. This set keeps track of vertices that are currently running. The purpose of this set is to prevent a vertex from being considered runnable if it is already being run.

feat: add vertices_being_run set to RunnableVerticesManager

---

src/backend/base/langflow/components/vectorstores/Qdrant.py

fixes the error caused by the same naming assignment.

fix: Qdrant shows Qdrant.from_documents() missing 1 required positional argument: ‘embedding’

---

src/frontend/src/stores/flowStore.ts

This pull request fixes a bug where the chat was not being locked properly during the build process. The bug was causing the chat to remain unlocked even when the build was in progress. This pull request adds the necessary code to properly lock and unlock the chat during the build process.

fix: make chat lock when building

---

src/backend/base/langflow/graph/graph/runnable_vertices_manager.py

Check predecessors recursively when a component is connected to components at the beginning and at the end of the flow.

fix(runnable_vertices_manager.py): add recursive function to find predecessors

---

src/backend/base/langflow/main.py

An exception and error FastAPI middleware that replies the more detailed error message back the client.
This is a step to enable meaningful error messages for the UI or client

feat: exception and error middleware

---

src/backend/base/langflow/api/v1/chat.py

This fixes an error that caused duplicated builds.

fix: add vertices in the first layer to the vertices being run

---

tests/unit/test_validate_code.py

This pull request updates the `test_create_function` in `test_validate_code.py` to use `pathlib.Path` instead of `math.sin` to check if it breaks CI. This change improves the code readability and maintainability.

fix: update test_create_function to use pathlib.Path

---

src/backend/base/langflow/components/vectorstores/AstraDB.py

currently if you're using the key from astra, you get `Error Message: You didn't provide an API key.`

fix: astra vectorize auth error

---

src/backend/base/langflow/graph/graph/base.py
src/backend/base/langflow/graph/graph/runnable_vertices_manager.py
src/backend/base/langflow/graph/vertex/base.py
src/frontend/src/stores/flowStore.ts
tests/unit/test_validate_code.py

This pull request includes several enhancements to the codebase:
- The `is_vertex_runnable` method in the `RunnableVerticesManager` class has been improved to include an additional parameter `activated_vertices` and updated logic to accurately determine if a vertex is runnable.
- The vertex filtering logic in the `useFlowStore` function in `flowStore.ts` has been optimized, resulting in improved performance and accuracy.
- The `is_active` method has been added to the `Vertex` class in `base.py` to check if a vertex's state is set to `ACTIVE`.
These changes improve the accuracy, performance, and readability of the codebase.

fix: Improve vertex filtering and update is_vertex_runnable logic

---

.env.example
.gitignore
.vscode/launch.json
README.md
src/backend/base/langflow/api/utils.py
src/backend/base/langflow/api/v1/chat.py
src/backend/base/langflow/graph/graph/base.py
src/backend/base/langflow/interface/types.py
src/backend/base/langflow/services/chat/service.py
src/backend/base/langflow/services/session/service.py

ThreadingInMemoryCache usage is broken. This commit addresses those issues along with missing documentation about the caching options.

fixing ThreadingInMemoryCache usage 

---

src/backend/base/langflow/components/embeddings/AzureOpenAIEmbeddings.py
src/backend/base/langflow/components/embeddings/OpenAIEmbeddings.py

currently dimensions parameter is always passed as str or int making the langchain integration to fail (it accepts Optional[int]).
In this PR I also add back the dimensions to openai embeddings that has been lost in between the components refactor, originally implemented by @jordanrfrazier with #2146

fix: azure embeddings models with fixed dimensions fail

---

src/backend/base/langflow/graph/graph/base.py
src/backend/base/langflow/graph/graph/utils.py
tests/unit/graph/graph/test_utils.py

This pull request includes a series of commits focused on refactoring and improving the graph code

feat: refactor graph vertex sorting

---

.vscode/launch.json
src/backend/base/langflow/services/telemetry/opentelemetry.py
tests/unit/test_telemetry.py

It's the second PR to add more utility functions for validate and add metrics under OpenTelemetry.
Unlike Prometheus' Gauge, OpenTelemetry requires a callback function to update Gauge type. This PR provides a set function to take care of the callback function for the user.
OpenTelementry meter requires to be a singleton. This PR introduces a thread safe singleton creation.
Add new unit tests.
Also enable the prometheus for the debugger.

feat: add opentelemetry utility functions and unit tests

---

src/backend/base/langflow/api/log_router.py
src/backend/base/langflow/utils/logger.py
tests/unit/test_logger.py

Some improvements: 
- instead of using an ordered dict we use a simple deque. The messages are already ordered by loguru. 
- Locking is necessary for readers too since it could lead to incosistent data view and duplicate data
- /logs endpoint was returning empty with some combinations of parameters
- timestamp are now millis instead of float epoch 
- keepalive is sent every 5 seconds instead of 1 
- /logs always return messages sorted by time desc for consistency

perf: improve /logs concurrent access

---

poetry.lock
pyproject.toml

This commit updates the dependencies for the Google Authentication Library and Google Calendar API. It includes the following changes:
- Upgraded google-auth to version 2.15.0
- Added google-auth-oauthlib version 1.2.1
- Added langchain-google-calendar-tools version 0.0.1
These updates ensure compatibility with the latest versions of the libraries and improve the functionality of the application.

feat: update dependencies for Google Authentication Library and Google Calendar API

---

src/backend/base/langflow/inputs/inputs.py
src/frontend/src/CustomNodes/GenericNode/components/parameterComponent/index.tsx
src/frontend/src/components/multiselectComponent/index.tsx

This commit updates the Multiselect component to use the 'values' prop instead of the 'value' prop. The 'values' prop is more intuitive and aligns with the naming convention used in other components. This change ensures consistency and improves the readability of the code.

fix: update Multiselect component to use 'values' prop instead of 'value'

---

.github/workflows/docker-build.yml

The HuggingFace Spaces build script has been updated to use the correct space name "Langflow/Langflow" instead of "Langflow/Langflow-Preview". This ensures that the correct space is restarted when triggered.

chore: update HuggingFace Spaces build script to use correct space name

---

src/backend/base/langflow/graph/vertex/base.py
src/backend/base/langflow/graph/vertex/types.py

This pull request fixes the handling of the `sender_name` parameter in the `InterfaceVertex` class. It ensures that the `sender_name` is converted to a string before being used in the `ChatOutputResponse` object. This prevents any potential errors or unexpected behavior when using the `sender_name` parameter.

fix: handle sender_name passed as data or message

---

src/backend/base/langflow/services/auth/utils.py

🐛 (utils.py): fix decryption issue by handling string encoding properly

fix: add try catch on fenet decrypt to prevent errors

---

src/backend/base/langflow/interface/types.py

when using redis you get the error `coroutine is not iterable `

fix: coroutine is not iterable when using redis

---

src/backend/base/langflow/base/io/chat.py
src/backend/base/langflow/base/memory/model.py
src/backend/base/langflow/components/helpers/Memory.py
src/backend/base/langflow/components/helpers/StoreMessage.py
src/backend/base/langflow/components/inputs/ChatInput.py
src/backend/base/langflow/components/outputs/ChatOutput.py
src/backend/base/langflow/initial_setup/starter_projects/Memory Chatbot.json
src/backend/base/langflow/memory.py
src/backend/base/langflow/schema/message.py

This PR adds the support for the following use cases:
1. Use the Langflow DB as memory for Chains
2. Use an external memory (e.g. Astra, Cassandra, Zep) for storing chat messages for normal flows
3. Remove the hidden message store from Chat Input and Chat Output via the boolean option

feat: refactor memories

---

src/frontend/src/stores/flowStore.ts

Refactor the filtering logic in the useFlowStore hook to optimize the performance. The code changes ensure that the nextVertices array is filtered correctly by excluding vertices that already exist in the last layer.

fix: optimize filtering of vertices in useFlowStore

---

src/frontend/src/pages/SettingsPage/pages/GeneralPage/components/ProfilePictureForm/components/profilePictureChooserComponent/hooks/use-preload-images.tsx

🐛 (use-preload-images.tsx): add null check for profilePictures to prevent errors when profilePictures is undefined

fix: prevent to loop on keys of object profile pictures when It's not loaded yet

---

src/backend/base/langflow/api/v1/endpoints.py
src/backend/base/langflow/api/v1/schemas.py
src/backend/base/langflow/components/inputs/ChatInput.py
src/backend/base/langflow/components/outputs/ChatOutput.py
src/backend/base/langflow/exceptions/api.py
tests/conftest.py
tests/data/SimpleAPITest.json
tests/test_endpoints.py

This pull request updates the Simple API Test fixture in the conftest.py file and modifies the test endpoints in the test_endpoints.py file. The changes ensure that the tests use the correct API test configuration and reflect the recent updates made to the codebase.
Update test assertions for successful runs with input types
The test assertions in the test_endpoints.py file have been updated to reflect the changes in the code. The assertions now correctly check the number of outputs and the values of the input_value for different input types. This ensures that the tests accurately verify the behavior of the API endpoints.
Remove api_key_required fixture from run endpoint tests
The api_key_required fixture has been removed from the run endpoint tests. This simplifies the test setup and …

feat: add payload validation, update Simple API Test fixture, run tests

---

src/backend/base/langflow/initial_setup/starter_projects/Basic Prompting (Hello, World).json
src/backend/base/langflow/initial_setup/starter_projects/Blog Writer.json
src/backend/base/langflow/initial_setup/starter_projects/Document QA.json
src/backend/base/langflow/initial_setup/starter_projects/Memory Chatbot.json
src/backend/base/langflow/initial_setup/starter_projects/Vector Store RAG.json

This pull request updates the components in the flows stater project

fix: update starter projects

---

docs/docs/components/vector-stores.mdx
poetry.lock
pyproject.toml
src/backend/base/langflow/components/vectorstores/Milvus.py

As request in both discussions:
- https://github.com/milvus-io/milvus/discussions/34465
- https://github.com/langflow-ai/langflow/discussions/2569
This pull request adds Milvus to the vector store component. I've tested it at my local for both doc ingestion & query flow using Milvus vector store, Cohere embedding, and OpenAI chat.

feat: Add milvus vector store

---

docs/static/CNAME

Added a new file `CNAME` to the `docs/static` directory. The file contains the custom domain `docs.langflow.org` for the documentation website.

docs: add CNAME file for custom domain

---

src/backend/base/langflow/api/v1/chat.py
src/backend/base/langflow/graph/graph/base.py
src/backend/base/langflow/graph/graph/runnable_vertices_manager.py

This pull request adds a new method to the codebase that checks if all predecessors of a vertex are fulfilled. This method is used to determine if a vertex can be marked as inactive. Additionally, the code has been updated to remove a vertex from the predecessors when marking it as inactive. This improves the efficiency of the code and ensures that all traces are properly ended when necessary.

fix: update condition to run end_all_traces

---

src/backend/base/langflow/custom/custom_component/component.py
src/backend/base/langflow/custom/custom_component/custom_component.py
src/backend/base/langflow/interface/initialize/loading.py
src/backend/base/langflow/utils/validate.py

Refactor the `build_component_and_get_results` function in `loading.py` to improve code readability and maintainability.
- Move the initialization of `custom_component` to a separate method called `initialize`.
- Set the parameters of `custom_component` using the `set_parameters` method.
- Remove unnecessary warnings filter.
- Simplify the conditional statements for building custom components and components.
This commit addresses the need for better code organization and improves the overall structure of the function.

refactor(CustomComponent): make initialization separate from constructor

---

src/backend/base/langflow/services/telemetry/schema.py

The telemetry schema has been updated to include an optional `componentErrorMessage` field, allowing for the recording of error messages when necessary. This change improves the accuracy and completeness of telemetry data.

fix: Update telemetry schema to allow for optional error message

---

poetry.lock
src/backend/base/poetry.lock
src/backend/base/pyproject.toml

This pull request updates the setuptools dependency in the pyproject.toml file to version 70 or higher. This update ensures compatibility with other dependencies and improves the overall stability of the project.

chore: update setuptools dependency to version 70 or higher

---

src/backend/base/langflow/base/io/chat.py
src/backend/base/langflow/components/inputs/ChatInput.py
src/backend/base/langflow/components/outputs/ChatOutput.py

Restores `store_message` method so chat components stay backwards compatible and rename inputs so they don't collide with the method's name.

fix: update chat components to make them backwards compatible

---

src/backend/base/langflow/custom/utils.py

When attempting to import a non-existent library, the editor reports an import error, suggests a correction, and is supposed to display a traceback. However, the suggested correction is nonsensical, and there is no traceback information available to be returned.
This PR adjusts the error message to be more generic and removes the correction suggestion and traceback data.

chore: make error messages more generic

---

README.md

- fixed invalid hyperlinks (404 not found)
- fixed unavailable branch name

docs: fix invalid hyperlinks in README.md

---

src/frontend/src/components/tagsSelectorComponent/index.tsx

This PR addresses a bug where selecting tags on the share modal would immediately update the store without requiring a confirmation click. The changes ensure that the changes are only dispatched to the store after the user clicks the confirmation button.

Fix: Clicking tags on share modal updates store immediately

---

src/frontend/src/constants/constants.ts
src/frontend/src/modals/IOModal/components/chatView/chatMessage/index.tsx

- Empty message should not contain notice of empty message if the message is coming as a stream

fix: empty input message on empty streaming

---

src/frontend/src/modals/editNodeModal/hooks/use-row-data.tsx

- Order of the fields in the Advanced page should be the same of the code

fix: sorting on advanced modal parameters

---

src/backend/base/langflow/api/v1/chat.py
src/backend/base/langflow/api/v1/schemas.py
src/backend/base/langflow/custom/custom_component/component.py
src/backend/base/langflow/custom/custom_component/custom_component.py
src/backend/base/langflow/graph/schema.py
src/backend/base/langflow/graph/vertex/base.py
src/backend/base/langflow/graph/vertex/types.py
src/backend/base/langflow/schema/schema.py

This pull request adds a `logs` field to the `ResultDataResponse` and `Vertex` classes. The `logs` field will store log messages for better debugging and monitoring.

feat: add logs field to ResultData and Vertex class

---

src/backend/base/langflow/components/helpers/SequentialTask.py

This pull request fixes an issue where new tasks were not being appended to the end of the list in the `SequentialTaskComponent` class. The `build_task` method has been updated to correctly handle appending tasks to the list.

fix:  append new tasks to the end of the list

---

.github/changes-filter.yaml
.github/workflows/ci.yml
.github/workflows/integration_test.yml
.github/workflows/python_test.yml
.github/workflows/scheduled_integration_test.yml

This adds a scheduled integration test to Langflow CI. The appropriate keys will need to be created and added to github secrets.

ci: add astra integration tests to CI

---

.github/workflows/ci.yml
.github/workflows/conventional-labels.yml

CI should run only when a PR is approved or by workflow_dispatch.
Conventional labels was updated as well to run less often.

ci: update conditions at which CI runs

---

Makefile

Updates and changes to the Makefile:
1. Added removal of `frontend` directory inside `src/backend/base/langflow/` and `build` directory inside `src/frontend/` to the `clean_npm_cache` target.
2. Added descriptive comments for the `build_and_install`, `build_and_run`, `fix_codespell`, `setup_poetry`, `unit_tests`, `integration_tests`, and `tests_frontend` targets.
Looking forward to your feedback.

Improvements to Makefile: Directory Cleanup and Descriptive Comments

---

.github/workflows/ci.yml

Add auto_merge_enabled so we can force CI to run more easily.

ci: add auto_merge_enabled to pull_request types in ci.yml

---

src/backend/base/langflow/base/langchain_utilities/model.py
src/backend/base/langflow/components/tools/BingSearchAPI.py
src/backend/base/langflow/components/tools/GoogleSearchAPI.py
src/backend/base/langflow/components/tools/GoogleSerperAPI.py
src/backend/base/langflow/components/tools/SearchAPI.py
src/backend/base/langflow/components/tools/SerpAPI.py
src/backend/base/langflow/components/tools/WikipediaAPI.py
src/backend/base/langflow/components/tools/WolframAlphaAPI.py

This pull request refactors the output type of the tools in the codebase to use the `Tool` class from the `langflow.field_typing` module. This change ensures consistency and improves the readability of the code.

refactor: update tools output type to Tool

---

src/backend/base/langflow/base/agents/agent.py
src/backend/base/langflow/base/agents/callback.py
src/backend/base/langflow/field_typing/constants.py
src/backend/base/langflow/services/tracing/langsmith.py
src/backend/base/langflow/services/tracing/schema.py

This PR improves LCAgentComponent and adds output to all Agents.

feat: add message_output and refactor LCAgentComponent

---

src/backend/base/langflow/services/tracing/langsmith.py

Refactor the LangSmithTracer class in langsmith.py to improve error handling during initialization. The setup_langsmith method now checks for the presence of the LANGCHAIN_API_KEY environment variable before proceeding with the setup. This ensures that the tracer is only initialized when the necessary API key is available. Additionally, the order of operations within the __init__ method has been adjusted to ensure that the setup_langsmith method is called after the necessary attributes are assigned. These changes enhance the reliability and robustness of the LangSmithTracer.

fix: add check before setting up LangSmithTracer

---

src/backend/base/langflow/services/tracing/langwatch.py
src/backend/base/langflow/services/tracing/service.py

- Removed an unused import in langwatch.py.
- Introduced helper functions `_get_langsmith_tracer` and `_get_langwatch_tracer` in tracing/service.py to dynamically import tracers.
These changes improve the development and testing experience and enhance the flexibility of tracer imports in the tracing service.

feat: introduce helper functions for dynamic tracer import

---

.github/workflows/typescript_test.yml

The `hashFiles` function was causing an error  in some instances but it is not needed since it is called by the poetry_caching action.

fix (typescript_test) : change cache-key to avoid errors

---

README.PT.md
README.md

[Fixed all hugginface links in readme files. Which were redirecting to old link which is throwing 404 error right now. Its fixed in all language readme files](https://github.com/langflow-ai/langflow/pull/2794)

fix(readme): correct urls in documentation

---

.github/workflows/ci.yml

The path-filter job condition in ci.yml has been updated to include an additional check for the 'workflow_dispatch' event. This change ensures that the job runs when the event is triggered manually, in addition to when the pull request is approved or when it is not a draft PR. The updated condition improves the flexibility and coverage of the path-filter job.

ci: update path-filter job condition in ci.yml

---

src/backend/base/langflow/load/utils.py
src/frontend/src/modals/apiModal/utils/get-python-api-code.tsx

Fix BASE_API_URL in the python code example.
Closes #2799

fix(get-python-api-code): set the endpoint in the correct variable

---

src/backend/base/langflow/base/tools/flow_tool.py
src/backend/base/langflow/components/tools/PythonCodeStructuredTool.py
src/backend/base/langflow/components/tools/RetrieverTool.py
src/backend/base/langflow/components/tools/WikipediaAPI.py

This pull request fixes the import statements in the following files:
- `flow_tool.py`
- `PythonCodeStructuredTool.py`
- `RetrieverTool.py`
- `WikipediaAPI.py`
The import statements were updated to reflect changes in the package structure. This ensures that the tools can be imported correctly and used without any issues.

refactor: update import statements in tools

---

src/frontend/src/controllers/API/api.tsx
src/frontend/src/controllers/API/index.ts
src/frontend/src/stores/flowsManagerStore.ts
src/frontend/src/types/zustand/flowsManager/index.ts

Fixes an issue where the error count in the interceptor fails to reset when auto-login is disabled, leading to unexpected user logouts.
This pull request addresses a critical issue affecting user sessions when autoLogin is set to false. Currently, the interceptor fails to reset error counts, which triggers premature user logouts without proper handling of error scenarios. By implementing a reset mechanism in the interceptor, this fix ensures that users remain authenticated under all conditions, providing a more reliable and seamless experience.

fix: session error after retries + refactor on interceptor component

---

src/frontend/src/components/headerComponent/index.tsx
src/frontend/src/components/sidebarComponent/index.tsx

This pull request addresses a type error in the component, stemming from poorly organized switch cases.
📝 (headerComponent/index.tsx): Remove unnecessary width styling from header-end-division class
🔧 (sidebarComponent/index.tsx): Ensure correct import of cn function from utils/utils file
💡 (sidebarComponent/index.tsx): Refactor sidebarContent logic to cover all conditions and provide a default case if necessary

fix: add correctly switch case to components on sidebar

---

.github/workflows/ci.yml

This pull request refactors the CI workflow by adding a new job called "check-reviews" and updating the "path-filter" job to depend on the output of the "check-reviews" job. This improves the readability and maintainability of the workflow.

ci: refactor CI workflow conditions to run only when PR is approved

---

src/backend/base/langflow/base/agents/callback.py
src/backend/base/langflow/schema/log.py

Improve typing to avoid TypeError. 
Closes #2792

refactor(callback): simplify import statements and type annotations for better readability

---

.github/workflows/conventional-labels.yml

This pull request removes the unnecessary pull_request_review event type from the workflow configuration file, streamlining the workflow setup.

ci: remove pull_request_review event type from workflow configuration

---

CONTRIBUTING.md

The main point is to remove the `dev` branch references since some users are not up to date with the latest workflow changes. (e.g. #https://github.com/langflow-ai/langflow/issues/2780)

chore: improve contributors guidelines

---

src/frontend/src/CustomNodes/GenericNode/index.tsx
src/frontend/src/icons/freezeAll/freezeAll.jsx
src/frontend/src/pages/FlowPage/components/nodeToolbarComponent/index.tsx

📝 (GenericNode/index.tsx): Remove commented-out code for openWDoubleClick in GenericNode component
🔧 (freezeAll.jsx): Refactor FreezeAllSvg component to use cn utility function for className and spread props
📝 (nodeToolbarComponent/index.tsx): Clean up commented-out code and unused elements in NodeToolbarComponent to improve code readability and maintainability

fix: adjust UI on nodetoolbar caused by svg icon without props

---

src/backend/base/langflow/base/models/openai_constants.py

This pull request adds the "gpt-4o-mini" model to the `MODEL_NAMES` constant in the `openai_constants.py` file. This allows the code to reference the new model in the application.
- Closes #2811

feat: add gpt-4o-mini to MODEL_NAMES constant

---

poetry.lock
pyproject.toml
src/backend/base/poetry.lock
src/backend/base/pyproject.toml

This pull request updates the package versions in the `pyproject.toml` and `poetry.lock` files. The changes include updating the version of `langflow` to `1.0.11`, the version of `langflow-base` to `0.0.87`, the version of `langchain-core` to `0.2.21`, the version of `langsmith` to `0.1.92`, and the version of `setuptools` to `71.0.3`. These updates ensure that the project is using the latest versions of the packages.

chore: update package versions in pyproject.toml and poetry.lock

---

.github/ISSUE_TEMPLATE/bug-report.yaml

Adjust bug-template python version.

fix(issue-template): adjust bug-template python version

---

.github/workflows/typescript_test.yml
src/frontend/src/contexts/authContext.tsx
src/frontend/tests/end-to-end/Basic Prompting.spec.ts
src/frontend/tests/end-to-end/filterEdge-shard-0.spec.ts
src/frontend/tests/end-to-end/filterSidebar.spec.ts
src/frontend/tests/end-to-end/generalBugs-shard-5.spec.ts
src/frontend/tests/end-to-end/inputComponent.spec.ts
src/frontend/tests/end-to-end/store-shard-1.spec.ts

🔧 (typescript_test.yml): Remove unnecessary steps and conditions in GitHub Actions workflow file
🔧 (authContext.tsx): Update cookie key from LANGFLOW_ACCESS_TOKEN to LANGFLOW_API_TOKEN for consistency
🔧 (Basic Prompting.spec.ts): Update test to click on correct dropdown option
🔧 (filterEdge-shard-0.spec.ts): Update test to check for correct element
🔧 (filterSidebar.spec.ts): Update test to check for correct elements
🔧 (generalBugs-shard-5.spec.ts): Update test to interact with correct element
🔧 (inputComponent.spec.ts): Update test to interact with correct elements
🔧 (store-shard-1.spec.ts): Update test to interact with correct elements and remove unnecessary code

test: fix general test and CI

---

src/backend/base/langflow/services/monitor/service.py

To fix runtime error
log_vertex_build Error logging vertex build: IO Error: Cannot open file "/app/data/.cache/langflow/monitor.duckdb": No such file or directory
ls /app/data
ls: cannot access '/app/data': No such file or directory

fix: ensure monitor duckdb cache dir exists

---

src/backend/base/langflow/base/models/model.py
src/backend/base/langflow/components/embeddings/VertexAIEmbeddings.py
src/backend/base/langflow/components/models/AmazonBedrockModel.py
src/backend/base/langflow/components/models/AnthropicModel.py
src/backend/base/langflow/components/models/AzureOpenAIModel.py
src/backend/base/langflow/components/models/BaiduQianfanChatModel.py
src/backend/base/langflow/components/models/CohereModel.py
src/backend/base/langflow/components/models/GoogleGenerativeAIModel.py
src/backend/base/langflow/components/models/GroqModel.py
src/backend/base/langflow/components/models/HuggingFaceModel.py
src/backend/base/langflow/components/models/Maritalk.py
src/backend/base/langflow/components/models/MistralModel.py
src/backend/base/langflow/components/models/NvidiaModel.py
src/backend/base/langflow/components/models/OllamaModel.py
src/backend/base/langflow/components/models/OpenAIModel.py
src/backend/base/langflow/components/models/VertexAiModel.py

currently with vertexai embeddings and llm you can upload the json file but the auth is not well initialized and this makes those components unusable without setting the global environment variable

fix: vertexai authentication via service account

---

src/backend/base/langflow/components/vectorstores/Pinecone.py

When we send the chunks with the embedding component to the Pinecone component, the generated embeddings are being saved three times instead of once.

fix: bug where the pinecone component was inserting embeddings three times instead of once.

---

src/backend/base/langflow/api/v1/api_key.py

Add user to the db just in case this could be causing the api key decryption to fail.

fix: save store API key in database after encryption

---

src/backend/base/langflow/graph/graph/base.py
src/backend/base/langflow/graph/graph/utils.py

This pull request fixes the assignment of `node["frozen"]` in the `add_frozen` function by updating it to `node["data"]["node"]["frozen"]`. Additionally, it removes unnecessary code related to `vertex.parent_node_id` in the Graph class. These changes improve the accuracy and efficiency of the code.

fix: assign frozen flag from group to node correctly

---

pyproject.toml
src/backend/base/langflow/components/models/VertexAiModel.py
src/backend/base/pyproject.toml

Disable type-var error code because it spams errors on all llms and adds boilerplate

refactor: disable type-var error code

---

src/backend/base/langflow/api/v1/chat.py
src/backend/base/langflow/graph/graph/base.py

This pull request fixes two issues in the graph build process. The first commit updates the condition for ending all traces in the `build_vertex` function. The second commit adds the correct vertex ID to the `vertices_being_run` list. These changes ensure that the graph build process runs smoothly and accurately.

fix: add correct id to vertices_being_run and change condition to end traces

---

poetry.lock
pyproject.toml
src/backend/base/pyproject.toml

Update the versions of various dependencies in the poetry.lock and pyproject.toml files to their latest versions. This ensures compatibility and incorporates bug fixes and improvements provided by the updated dependencies.

chore: bump langflow and langflow-base to 1.0.12 and 0.88

---

src/backend/base/langflow/base/agents/agent.py
src/backend/base/langflow/base/agents/crewai/crew.py
src/backend/base/langflow/components/agents/CSVAgent.py
src/backend/base/langflow/components/agents/HierarchicalCrew.py
src/backend/base/langflow/components/agents/JsonAgent.py
src/backend/base/langflow/components/agents/OpenAIToolsAgent.py
src/backend/base/langflow/components/agents/OpenAPIAgent.py
src/backend/base/langflow/components/agents/SQLAgent.py
src/backend/base/langflow/components/agents/SequentialCrew.py
src/backend/base/langflow/components/agents/ToolCallingAgent.py
src/backend/base/langflow/components/agents/XMLAgent.py

Fixes a few bugs in the agent components
* In `LCAgentComponent`, we were attempting to access some fields that weren't `inputs`
* Fix: remove field accesses for inputs that are not explicitly defined within the parent `LCAgentComponent` class
* Moves `chat_history` there as well
* Moves `llm` input to each agent, since some do not have an llm input. 
Testing:
* More should be done, but verified that a `SQLAgent` was able to converse with postgres db.
Fixes https://github.com/langflow-ai/langflow/issues/1427

ref: refactors the agents around and fixes a few bugs

---

.github/workflows/py_autofix.yml
Makefile

Update the dependencies in the py_autofix.yml workflow file to include a new step for checking the Poetry lock file. This ensures that the dependencies are locked and prevents any unintended changes in compatibility or functionality. The lock step is added to the existing workflow to ensure that the Poetry lock file is checked and updated if necessary.

chore: update dependencies and add lock step in py_autofix.yml

---

src/backend/base/langflow/components/astra_assistants/create_assistant.py
src/backend/base/langflow/components/astra_assistants/create_thread.py
src/backend/base/langflow/components/astra_assistants/dotenv.py
src/backend/base/langflow/components/astra_assistants/get_assistant.py
src/backend/base/langflow/components/astra_assistants/list_assistants.py
src/backend/base/langflow/components/astra_assistants/run.py

Refactor the import statements in the run.py file to improve readability and maintainability. Update the import order and add type hints for better code organization. This change ensures consistency with the recent repository commits and follows established conventions.

refactor: update import statements in run.py

---

.github/workflows/scheduled_integration_test.yml

Integration tests didn't check out the code 🙃

fix: add checkout action to integration test workflow

---

src/frontend/tests/end-to-end/freeze-path.spec.ts
src/frontend/tests/end-to-end/generalBugs-shard-5.spec.ts

🐛 (generalBugs-shard-5.spec.ts): fix test to wait for elements to be interactable before performing actions to prevent flakiness

test: fix output group preview test to be interactive

---

docker/frontend/nginx.conf

healthcheck endpoint needs be forwared to the backend

fix: frontend image should forward /health_check to backend

---

src/frontend/tests/end-to-end/generalBugs-shard-6.spec.ts

🐛 (generalBugs-shard-6.spec.ts): fix test assertion to check for error message length greater than 20 instead of 50 for improved accuracy

test: improve test to allow any errors checks

---

.github/ISSUE_TEMPLATE/bug-report.yaml
.github/ISSUE_TEMPLATE/feature-request.yaml
.github/ISSUE_TEMPLATE/work-in-progress.yaml

Adjust the bug report template to allow users to paste their screenshots or flow URLs.
Additionally, include a section where they can share their work-in-progress.

chore(template): adjust bug report template to include screenshot and WIP sections

---

src/backend/base/langflow/graph/vertex/base.py
src/backend/base/langflow/interface/initialize/loading.py

This PR refactors the instantiation of vertices, allowing vertices to optionally contain a reference to a component without breaking the existing behavior of the code.

refactor: vertex instantiation

---

src/frontend/src/modals/apiModal/utils/get-python-api-code.tsx
src/frontend/src/modals/apiModal/utils/get-python-code.tsx

- added regex to change null and undefined to None

fix: python code with null and undefined

---

.github/workflows/ci.yml

This pull request refactors the CI workflow to include a new job called 'set-ci-condition'. This job is responsible for determining if the CI should run based on conditions such as pull request labels and event type. By adding this job, we can improve the efficiency and control of our CI process.

ci: update CI workflow to include new job 'set-ci-condition'

---

src/frontend/tests/end-to-end/generalBugs-shard-6.spec.ts

Update the button role in the end-to-end test to use "Check & Save" instead of "Save".

fix: update button role in end-to-end test

---

src/backend/base/langflow/api/v1/endpoints.py
src/backend/base/langflow/components/prototypes/RunFlow.py
src/backend/base/langflow/custom/custom_component/custom_component.py
src/backend/base/langflow/helpers/flow.py

This pull request refactors the params assignment in the custom_component_update endpoint by using a dictionary comprehension. This simplifies the code and improves readability.
Update input and output definitions for RunFlowComponent

fix: validate params assignment in custom_component_update endpoint

---

src/backend/base/langflow/main.py
src/backend/base/langflow/services/base.py
src/backend/base/langflow/services/database/service.py
src/backend/base/langflow/services/manager.py
src/backend/base/langflow/services/plugins/service.py
src/backend/base/langflow/services/storage/local.py
src/backend/base/langflow/services/storage/service.py
src/backend/base/langflow/services/telemetry/service.py
src/backend/base/langflow/services/utils.py

The `TelemetryService` and `Service` classes have been updated to convert the `teardown` methods to asynchronous functions. TelemetryService payload has been changed to only send existing data.

refactor: update TelemetryService and change Service teardown methods to be async

---

src/backend/base/langflow/inputs/input_mixin.py
src/backend/base/langflow/inputs/inputs.py

The commit adds the `InputTypesMap` dictionary and `_instantiate_input` function to the `inputs.py` file. The `InputTypesMap` is a dictionary that maps input types to their corresponding classes, and the `_instantiate_input` function is used to instantiate an input object based on its type. This change improves the flexibility and extensibility of the codebase.

feat: add InputTypesMap and _instantiate_input function

---

src/backend/base/langflow/components/prototypes/Listen.py
src/backend/base/langflow/components/prototypes/Notify.py
src/backend/base/langflow/graph/vertex/base.py
src/backend/base/langflow/graph/vertex/types.py

This commit adds a new method `_set_successors_ids` to the `ListenComponent` class in `Listen.py`. This method retrieves the successors of the vertex and sets the `successors_ids` attribute accordingly. This change improves the functionality and flexibility of the `ListenComponent` class.
Fixes #2919

refactor: update StateVertex to function like a normal component unless specified not to

---

.github/workflows/ci.yml

This pull request adds a new job called "labeler" to the CI workflow. The labeler job is triggered when a pull request review is approved. It automatically adds the 'lgtm' label to the pull request. Additionally, a dependency has been added to ensure that the labeler job runs before the CI job.

ci: add labeler job to automatically add 'lgtm' label when pull request review is approved

---

src/frontend/package-lock.json
src/frontend/package.json
src/frontend/src/components/dropdownComponent/index.tsx
src/frontend/src/types/components/index.ts

This pull request adds fuzzy search functionality and a custom value option to the Dropdown Component. The fuzzy search allows users to easily find options by typing a partial or misspelled value. The custom value option allows users to enter a value that is not present in the predefined options. These enhancements improve the usability and flexibility of the Dropdown Component.

feat: add custom value on dropown ui

---

src/backend/base/langflow/__main__.py
src/backend/base/langflow/services/settings/factory.py

This PR makes the following changes:
- Change `SettingsServiceFactory` to use the Singleton pattern.
- Remove code that overrides environment variables.
resolve #2717

fix: environment variable initialization issue

---

src/frontend/src/modals/IOModal/components/chatView/chatInput/index.tsx
src/frontend/src/modals/IOModal/components/chatView/index.tsx
src/frontend/src/modals/IOModal/index.tsx

This pull request includes fixes for names and unused parameters in the code. It also adds a refetch of memories, for them to appear even if the flow is build from outside of the modal. These changes improve the overall functionality and maintainability of the codebase.

fix: memories not visible when sending from outside io modal

---

src/backend/base/langflow/base/constants.py
src/backend/base/langflow/inputs/input_mixin.py
src/backend/base/langflow/inputs/inputs.py
src/frontend/src/components/dropdownComponent/index.tsx
src/frontend/src/components/parameterRenderComponent/component/strRenderComponent/index.tsx
src/frontend/src/types/api/index.ts
src/frontend/src/types/components/index.ts

This PR adds the possibility of using a custom value on the DropdownField, by adding the prop combobox=True to the input definition.

feat: dropdown combobox option

---

src/frontend/src/App.tsx
src/frontend/src/controllers/API/queries/health/use-get-health.ts

This pull request will ensure that disconnect modal is showing properly.
🐛 (App.tsx): Fix logic to correctly display error modal when health data is missing or not "ok"
🔧 (use-get-health.ts): Disable retry option in useGetHealthQuery to prevent unnecessary refetching of health data
#2968

bugfix: fix missing condition to open disconnect modal when backend is down

---

src/backend/base/langflow/base/models/model.py

fix: models with system message and prompt input fail

---

src/backend/base/langflow/graph/graph/base.py

Refactor the `find_next_runnable_vertices` method in the `Graph` class to improve readability and simplify the logic. Instead of using a list comprehension, the method now uses a for loop to iterate over the `vertex_successors_ids` and determine if each vertex is runnable. If a vertex is not runnable, it calls the `find_runnable_predecessors_for_successor` method to find the runnable predecessors. The runnable vertices are then added to the `next_runnable_vertices` list. This refactoring improves the clarity and maintainability of the code.

fix: find runnable predecessor for every successor that is not runnable

---

src/backend/base/langflow/schema/message.py

Fix issue with identical timestamps for different messages
resolve #2982

fix: wrong message timestamp

---

src/backend/base/langflow/base/models/openai_constants.py

This pull request updates the model names in `openai_constants.py` to ensure backwards compatibility. The `OPENAI_MODEL_NAMES` and `OPENAI_EMBEDDING_MODEL_NAMES` lists have been modified to include additional models. Additionally, a new `MODEL_NAMES` list has been added for backwards compatibility.

fix: update model names for backwards compatibility

---

src/backend/base/langflow/components/helpers/StoreMessage.py

Store message component overrides the input message sender and sender name to AI. 
This makes hard to configure memory chatbot where the store message component gets the input message from the chat input node

fix: Store message should not override sender by default

---

src/backend/base/langflow/services/database/utils.py

Fixes #3007
This happens with new instances where tables weren't created at all. 
Since this is harmless, it's better to silent the error

fix: hide duckdb table not found error log

---

src/frontend/package-lock.json
src/frontend/src/components/textAreaComponent/index.tsx

Adjust the styling of the TextAreaComponent when password is not undefined

fix: style on password button

---

src/backend/base/langflow/components/astra_assistants/get_assistant.py
src/backend/base/langflow/components/astra_assistants/list_assistants.py
src/backend/base/langflow/components/astra_assistants/run.py

The OpenAI client instantiation was removed from the `AssistantsGetAssistantName` and `AssistantsListAssistants` components. This commit fixes the issue by adding back the OpenAI client instantiation in the `process_inputs` method of both components.

fix: move  client instantiation in AssistantsGetAssistantName and AssistantsListAssistants to inner function

---

src/backend/base/langflow/graph/vertex/types.py

The code changes in `types.py` add support for storing messages in custom components. If a custom component has the attributes `should_store_message` and `store_message`, the `store_message` method will be called to store the message. This enhancement improves the functionality of the interface vertex in the graph.

fix: add support for custom component message storage

---

src/backend/base/langflow/custom/custom_component/component.py
src/backend/base/langflow/schema/artifact.py
src/backend/base/langflow/schema/schema.py

I have refactored the `recursive_serialize_or_str` function in the `schema.py` file to improve its readability and maintainability. The function now uses a try-except block to handle exceptions and returns a string representation of the object if an exception occurs. Additionally, I have added support for serializing arrays in the `build_output_logs` function to handle the `LogType.ARRAY` case. This ensures consistent data handling and improves the code quality and reliability of the serialization process.

fix: serialize array output and logs

---

Makefile

Lock poetry dependencies without updating in the Makefile build_langflow target

refactor: lock poetry dependencies without updating

---

.github/workflows/release.yml

This pull request updates the Python version in the release workflow from 3.10 to 3.12. This ensures that the latest version of Python is used for the release process.

ci: update Python version in release workflow and skip release if already released

---

src/frontend/src/components/ui/textarea.tsx

The Textarea component was updated to have a full height by adding the "h-full" class to the parent div. This ensures that the textarea takes up the entire available vertical space.

fix: Update Textarea component to have full height

---

render.yaml

render.yaml is outdated and it doesn't work with the latest docker image
Fixes #2723

fix: update render.yaml to being compatible with langflow 1.0 

---

src/backend/base/langflow/graph/graph/base.py

if a node has two predecessor and they end up in the same layer of execution, the node is executed twice. This can cause problems for idempotent nodes, such as message memory
Fixes #3028

fix: endpoint /run api call could run same node twice

---

Makefile

Skip without error base if it exists

chore: update Makefile to skip publishing if package already exists

---

.github/workflows/release.yml

This pull request updates the pip installation command in the release workflow to include the `--backend-only` flag when running the CLI test. This ensures that the server starts correctly before running the test.

ci: update cli command

---

README.md

Added instructions to the README for running the project from a cloned repository.
- Step-by-step instructions for cloning the repository.
- Commands to install dependencies.
- Commands to start the project.

docs(readme): add instructions for running from a cloned repo

---

src/frontend/src/pages/MainPage/hooks/use-on-file-drop.tsx
src/frontend/src/stores/foldersStore.tsx

The useFileDrop hook in use-on-file-drop.tsx has been updated to handle multiple file drops. It now accepts an array of files instead of a single file, and processes each file individually. This allows for uploading multiple files at once and improves the user experience.

enhancement: Update useFileDrop hook to handle multiple file drops

---

src/frontend/src/components/parameterRenderComponent/index.tsx

- Added UseMemo for the component to not re-render and lose cursor position

fix: text input jumps to the end of the text after writing one letter

---

src/backend/base/langflow/components/data/URL.py

- Fix description that tells the user that he can put URLs separated by commas

fix: description of url component

---

src/frontend/src/CustomNodes/GenericNode/index.tsx
src/frontend/src/types/api/index.ts

This PR introduces an enhancement to the GenericNode component by adding a new field, `lf_version`, to the node data. This update aims to improve the metadata tracking and version control of nodes within our system.

feat: update GenericNode to include lf_version in node data

---

src/backend/base/langflow/main.py
src/frontend/src/App.tsx
src/frontend/src/utils/buildUtils.ts
src/frontend/src/utils/utils.ts

This pull request fixes the handling of PydanticSerializationError in the JavaScriptMIMETypeMiddleware. Previously, when a serialization error occurred, a generic error message was returned. With this fix, a more detailed error message is provided. This ensures that users can easily identify and troubleshoot serialization errors.

fix: handle PydanticSerializationError that generates generic errors in the UI

---

src/frontend/src/App.tsx
src/frontend/src/components/addNewVariableButtonComponent/addNewVariableButton.tsx
src/frontend/src/components/inputGlobalComponent/index.tsx
src/frontend/src/contexts/authContext.tsx
src/frontend/src/controllers/API/helpers/constants.ts
src/frontend/src/controllers/API/index.ts
src/frontend/src/controllers/API/queries/variables/index.ts
src/frontend/src/controllers/API/queries/variables/use-delete-global-variables.ts
src/frontend/src/controllers/API/queries/variables/use-get-global-variables.ts
src/frontend/src/controllers/API/queries/variables/use-patch-global-variables.ts
src/frontend/src/controllers/API/queries/variables/use-post-global-variables.ts
src/frontend/src/pages/AdminPage/LoginPage/index.tsx
src/frontend/src/pages/SettingsPage/pages/GlobalVariablesPage/index.tsx

This pull request will change globalVariables CRUD to use useQuery.
✨ (App.tsx): Add useGetGlobalVariables hook to fetch global variables data
🔧 (addNeVariableButton.tsx): Replace registerGlobalVariable function with usePostGlobalVariables hook for adding new global variables
🔧 (inputGlobalComponent/index.tsx): Replace deleteGlobalVariable function with useDeleteGlobalVariables hook for deleting global variables
🔧 (authContext.tsx): Remove unused getGlobalVariables function and setGlobalVariables state from authContext
🔧 (constants.ts): Add VARIABLES constant for global variables endpoint
🔧 (index.ts): Remove getGlobalVariables, registerGlobalVariable, and deleteGlobalVariable functions from API index
✨ (variables/index.ts): Add use-delete-global-variables hook for deleting global …

refactor: add useQuery management on globalVariables CRUD

---

src/backend/base/langflow/initial_setup/setup.py

Refactor the `load_starter_projects` function in `setup.py` to close the file once it is loaded. This could fix tests hanging in CI.

refactor: improve file handling in loading starter projects

---

src/backend/base/langflow/services/database/service.py
src/backend/base/langflow/services/settings/base.py
src/backend/tests/unit/test_database.py

SQLite Pragma should not be hardcoded. This PR introduce an env variable to all these PRAGMA statement to be configurable without code changes.
To change the pragams you can set the env variable LANGFLOW_SQLITE_PRAGMAS using a JSON dict
The default value is unchanged and is
```
LANGFLOW_SQLITE_PRAGMAS="{"synchronous": "NORMAL", "journal_mode": "WAL"}"
```

feat: set sqlite pragma by env variable

---

src/frontend/src/App.tsx
src/frontend/src/components/authAdminGuard/index.tsx
src/frontend/src/components/authGuard/index.tsx
src/frontend/src/constants/constants.ts
src/frontend/src/contexts/authContext.tsx
src/frontend/src/controllers/API/api.tsx
src/frontend/src/controllers/API/queries/auth/use-post-logout.ts
src/frontend/src/pages/AdminPage/LoginPage/index.tsx
src/frontend/src/pages/LoginPage/index.tsx
src/frontend/src/stores/authStore.ts
src/frontend/src/types/contexts/auth.ts
src/frontend/vite.config.mts

#3130 
#3132
📝 (App.tsx): Update imports and add new constants for access token expiration time
🔧 (App.tsx): Add support for refreshing access token and setting expiration time
📝 (authAdminGuard/index.tsx): Remove unnecessary logout function and add conditional check for login page
📝 (authGuard/index.tsx): Add conditional check for login page
📝 (constants.ts): Add constants for access token expiration time
📝 (authContext.tsx): Remove logout function and update related logic
📝 (api.tsx): Add conditional check for login page
📝 (use-post-logout.ts): Remove navigate function call
📝 (LoginPage/index.tsx): Add logic to reset flows and selected folder on successful login
✨ (LoginPage/index.tsx): Add support for managing folders in the login page to improve user experience
🔧 (authStore.ts): …

bugfix: automatically refresh user's session

---

src/backend/base/langflow/components/helpers/Memory.py

langchain memories are supposed to return messages in ascending order. Currently the Memory components sort them on the other way around

fix: external memory messages history is reversed

---

src/frontend/src/CustomNodes/GenericNode/index.tsx
src/frontend/src/stores/flowStore.ts
src/frontend/src/types/zustand/flow/index.ts
src/frontend/tests/end-to-end/generalBugs-shard-10.spec.ts

This fixes a regression introduced by https://github.com/langflow-ai/langflow/pull/3112
To reproduce just freeze a component and click run

fix: frozen status is lost after run

---

src/backend/base/langflow/api/v1/chat.py

Freeze requires caching so we need to pass chat_service to build_vertex

fix: add chat_service to build_vertex method call so freeze works

---

src/frontend/src/modals/apiModal/utils/get-curl-code.tsx

Update the curl generated code to identify the componet type for inputs and outptus

fix: update curl code generation

---

src/backend/base/langflow/api/v1/chat.py
src/backend/base/langflow/components/prototypes/FlowTool.py
src/backend/base/langflow/custom/custom_component/base_component.py
src/backend/base/langflow/custom/custom_component/custom_component.py
src/backend/base/langflow/custom/directory_reader/directory_reader.py
src/backend/base/langflow/custom/utils.py
src/backend/base/langflow/schema/message.py
src/backend/base/poetry.lock
src/backend/base/pyproject.toml
src/backend/tests/unit/components/prompts/test_prompt_component.py
src/backend/tests/unit/test_custom_component.py
src/backend/tests/unit/test_data_components.py

Refactored the CustomComponent class to streamline initialization and removed unnecessary imports for better code clarity. Updated the user_id and flow_id parameters to use properties for better encapsulation and code clarity.

refactor: enhance CustomComponent class and updates tests

---

.github/workflows/python_test.yml

This update silences a warning on Github

ci: update nick-fields/retry dependency to v3

---

src/backend/base/langflow/api/v1/chat.py
src/frontend/src/controllers/API/queries/_builds/use-delete-builds.ts

This pull request includes two commits that fix a wrong type and remove an unnecessary split method in the `vertex_id` function that broke the playground in #3020. The changes ensure that the `vertex_id` function works correctly and efficiently.

fix: unnecessary split method in vertex_id that breaks playground

---

src/backend/base/langflow/components/prototypes/FlowTool.py
src/backend/base/langflow/components/prototypes/RunFlow.py
src/backend/base/langflow/components/prototypes/SubFlow.py
src/backend/base/langflow/graph/vertex/base.py
src/backend/base/langflow/graph/vertex/types.py

Added check to ensure flow_name is provided in attributes. 
Fixed some other validation steps.

fix: validate flow_name presence in flow components before retrieving flow data

---

src/frontend/src/components/textAreaComponent/index.tsx
src/frontend/src/components/ui/textarea.tsx

This allows users to paste multiline texts to the input field in a Component

fix: replace Input with Textarea in TextAreaComponent for improved user experience and aesthetics

---

src/backend/base/langflow/graph/utils.py
src/backend/base/langflow/services/settings/base.py
src/backend/tests/unit/graph/test_graph.py

Add setting to not write transactions or vertex_builds. Those option are useful for the UI but not for the runtime part. 
Since they now are written to the SQL db, it's important to make them able to be disabled them to avoid useless writes and costs

feat: flag to disable transaction and vertex_builds writes

---

src/frontend/src/constants/constants.ts
src/frontend/src/hooks/flows/use-upload-flow.ts
src/frontend/src/pages/FlowPage/components/PageComponent/index.tsx
src/frontend/src/utils/layoutUtils.ts
src/frontend/src/utils/reactflowUtils.ts

This PR adds call to processDataFromFlow when pasting and makes sure fitView is called if flows don't have position data.

feat: improve layout options and make sure nodes and flow have position data

---

src/backend/base/langflow/components/models/AIMLModel.py

The current AI ML component only outputs Text, and all other AI Models output `Text` and `Language Model`
With this change, we can use models from AI ML in `Agents` and other components that use the `Language Model` as input.

feat: add LLM output for the AI ML component to use ChatOpenAI base model

---

.github/workflows/python_test.yml

We need this because if there was a version bump the CI will always fail until we release the version.

ci: add version check in workflow to skip jobs for unreleased versions of langflow-base

---

src/backend/base/langflow/api/v1/chat.py
src/backend/base/langflow/graph/graph/base.py
src/backend/tests/unit/graph/graph/test_base.py
src/backend/tests/unit/initial_setup/starter_projects/test_vector_store_rag.py
src/backend/tests/unit/test_database.py

The assertion in the test_create_flows function was modified to check if the name field contains the substring "Flow 1" instead of an exact match. This change allows for more flexibility in the test and ensures that the test passes even if there are additional characters in the name field.
In addition, the Graph class now uses warnings instead of raising a ValueError when there are vertices without edges. This change improves logging and error handling in the class.

fix: change ValueError into Warning to allow disconnected flows to run and other small fixes

---

src/backend/base/langflow/components/models/HuggingFaceModel.py

Sometimes when calling Hugging Face API model, it's failed and don't have any retry implemented, this PR just add the ability to user define a number of retry before the call fails.
https://github.com/langflow-ai/langflow/discussions/3210

feat: add huggingface endpoint retry

---

src/backend/base/langflow/schema/message.py

Refactor the `sync_get_file_content_dicts` method in the `Message` class to use the `get_file_content_dicts` method instead. This change improves the code by using a more descriptive and accurate method name.

fix: change sync_get_file_content_dicts to use get_file_content_dicts

---

src/backend/base/langflow/graph/graph/base.py
src/backend/base/langflow/graph/schema.py
src/backend/base/langflow/graph/vertex/base.py
src/backend/base/langflow/services/cache/disk.py
src/backend/base/langflow/services/cache/factory.py
src/backend/base/langflow/services/cache/service.py
src/backend/base/langflow/services/cache/utils.py
src/backend/base/langflow/services/settings/base.py
src/backend/base/poetry.lock
src/backend/base/pyproject.toml

This pull request includes several commits that improve the caching logic in the codebase. The `Graph` class now handles exceptions and cache updates more reliably. The `ResultData` class has been updated to use key-value pairs in the `outputs` dictionary for better readability. The `get_requester_result` method in the `Vertex` class now uses `async await` for proper asynchronous handling. Additionally, the `cache_type` setting has been restricted to specific literals for enhanced type safety and clarity. The pull request also introduces a new `AsyncDiskCache` class and adds the `diskcache` package version 5.6.3 to the project dependencies for improved disk-based caching functionality.

feat: Improve caching logic and add disk caching option

---

src/backend/base/langflow/__main__.py
src/backend/base/langflow/api/log_router.py
src/backend/base/langflow/custom/custom_component/component.py
src/backend/base/langflow/field_typing/constants.py
src/backend/base/langflow/graph/graph/base.py
src/backend/base/langflow/load/load.py
src/backend/base/langflow/logging/__init__.py
src/backend/base/langflow/logging/logger.py
src/backend/base/langflow/logging/setup.py
src/backend/base/langflow/main.py
src/backend/base/langflow/server.py
src/backend/base/langflow/services/cache/factory.py
src/backend/base/langflow/services/settings/base.py
src/backend/base/langflow/settings.py
src/backend/base/langflow/utils/util.py
src/backend/tests/unit/test_custom_component_with_client.py
src/backend/tests/unit/test_logger.py

This pull request adds a new settings module with a development mode flag and helper functions for setting the development state. It also enhances the logger module with development mode handling and a TypedDict for log configuration settings. The Settings class is updated to include the development mode flag and an associated validator for enhanced configuration management. Additionally, a logging init module is created for improved logger configuration and management. The logger import path is updated to align with recent module restructuring, and the logger module is reorganized. A setup.py file is added for logging configuration.

feat: start using dev mode flag and add exception filter in logger

---

src/backend/base/langflow/api/v1/chat.py
src/frontend/src/utils/buildUtils.ts

This pull request enhances the error handling in the `build_flow` function and adds error handling for the Flow build process. The changes in `buildUtils.ts` include a new case for handling errors in the switch statement, which displays the error message and triggers the `onBuildError` function. This ensures that errors during the Flow build are properly handled and the build process is stopped.

fix: enhance error handling in build_flow and add error handling for Flow build

---

src/backend/base/langflow/api/v1/chat.py

This is needed so that calls from outside the workspace don't affect the playground in the workspace. 
`log_builds` should be used as a query param just like `start_component_id`.

feat: add log_builds parameter to build_flow for optional vertex build logging

---

src/backend/base/langflow/components/prototypes/RunnableExecutor.py
src/backend/base/langflow/components/tools/PythonCodeStructuredTool.py
src/backend/base/langflow/components/tools/SearXNGTool.py
src/backend/base/langflow/components/tools/__init__.py

PythonCodeStructuredTool
- Inputs for function arguments description will be automatically added when updating tool_code.
- Added an input for global variables without having to declare them as arguments of function.
- Types of function arguments can be declared any types.
- If you want to declare custom Enum, you can declare it into tool_code.
SearXNGTool
- Created this tool to search through SearXNG.
RunnableExecutor
- Allowed the output to be streamed (The agent must have chat model such as LLM).
- Changed the build method to asynchronous.

Refactored and improved PythonCodeStructuredTool, SearXNGTool, and RunnableExecutor

---

src/frontend/src/CustomNodes/GenericNode/components/NodeInputField/index.tsx

Issue is attached here -
https://github.com/langflow-ai/langflow/issues/3272
**Bug Description**
We have noticed that a check is missing when displaying edge dots on the left side of the component. As a result, an unnecessary dot appears, causing confusion for users.
**Reproduction**
Open Langflow.
Click on "Add New Project."
Select the "Basic Prompting" template.
You'll notice that the OpenAI node displays an unused edge dot on the left side.
https://github.com/user-attachments/assets/e768b9d6-9633-480c-b43c-4becabdb0a30
**Expected behaviour**

fix: correct issue with The "No suitable component" error is appearing on the OpenAI component and other components due to a missing check

---

poetry.lock
src/backend/base/langflow/components/langchain_utilities/SpiderTool.py

Upgrade spider-client and make it functional

fix: update parameters in spider components

---

src/backend/base/langflow/services/database/models/vertex_builds/model.py

fixes message sorting bug caused by missing timezone information in the build structures of the flows

fix: message sorting in playground

---

src/backend/base/langflow/components/langchain_utilities/SQLDatabase.py

- Changed import from `langchain_experimental.sql.base.SQLDatabase` to `langchain_community.utilities.sql_database.SQLDatabase`
- Updated `build` method to create an SQLAlchemy engine with StaticPool for better connection management
- Removed `clean_up_uri` method as it's no longer needed

fix: Corrected URI handling in SQLDatabaseComponent

---

src/backend/base/langflow/custom/custom_component/component.py
src/backend/base/langflow/graph/graph/base.py
src/backend/base/langflow/graph/graph/state_model.py
src/backend/base/langflow/graph/state/model.py
src/backend/tests/unit/graph/graph/state/test_state_model.py
src/backend/tests/unit/graph/graph/test_graph_state_model.py

This pull request includes several refactorings and feature additions to the Component class in the custom_component module. The visibility of the method `_get_output_by_method` has been changed to public by renaming it to `get_output_by_method`, improving accessibility and clarity. Additionally, state model management has been implemented with lazy initialization and dynamic instance getter in the custom_component class. The `_reset_all_output_values` method has been added to initialize component outputs. The Graph class has been enhanced with lazy loading for state model creation from the graph, and a new method `create_state_model_from_graph` has been added to the graph state_model module. Unit tests and functional tests have been added to validate the state model creation and graph …

feat:  add dynamic state model creation and update

---

src/backend/base/langflow/api/v1/variable.py
src/backend/base/langflow/services/variable/base.py
src/backend/base/langflow/services/variable/kubernetes.py
src/backend/base/langflow/services/variable/service.py
src/backend/tests/unit/api/v1/test_variable.py
src/backend/tests/unit/services/variable/test_service.py

This PR focuses on enhancing code cohesion in the management of global variables by removing the logic from the API and utilizing the existing interface for this purpose. Unit tests were added to ensure that the refactoring did not alter the current behavior of the code.

feat: centralize global variable management

---

src/backend/tests/unit/services/variable/test_service.py

adds two new tests for the new delete_variable_by_id method to improve test coverage

test: adds new tests for new variable service

---

README.KR.md
README.ja.md
README.md
docs/docs/Getting-Started/getting-started-installation.md

- Update Astra link in README.md

Update Astra link in README.md

---

src/frontend/src/App.tsx
src/frontend/src/components/headerComponent/components/menuBar/index.tsx
src/frontend/src/components/headerComponent/index.tsx
src/frontend/src/index.tsx
src/frontend/src/pages/AppWrapperPage/index.tsx
src/frontend/src/routes.tsx

This pull request includes several fixes to address dark mode not starting with the browser saved variable and the addition of the "Last saved at" text on the header. It also fixes some CSS issues related to the header display.

fix: dark mode and header text display issues

---

docs/docs/Components/components-vector-stores.md
src/backend/base/langflow/components/vectorstores/Upstash.py

I was planning to add Upstash support to Langflow, but I noticed that you already have it implemented, and it works quite well.
We now support [namespaces](https://upstash.com/docs/vector/features/namespaces) and [metadata filtering](https://upstash.com/docs/vector/features/filtering). We’ve added these features to the Langchain integration, and it would be great to see them in Langflow as well.
I also updated the documentation, as Upstash Vector was missing from the vector stores page.
Please let me know if any changes are needed.

feat: Add support for metadata filtering and namespaces for the Upstash Vector component

---

src/frontend/src/modals/apiModal/utils/get-curl-code.tsx

This PR addresses an issue where the generated curl commands were missing double quotes around certain arguments. 
Fixes  #3320

fix: add double quotes to curl command generation

---

src/backend/base/langflow/graph/graph/utils.py
src/backend/tests/unit/graph/graph/test_utils.py
src/backend/tests/unit/services/variable/test_service.py

Add utility functions for cycles

feat: add functions to detect cycles in Graph

---

src/backend/base/langflow/custom/custom_component/component.py

This method allows users to set parameters on specific outputs

feat: Add method to set specific parameters on output object.

---

src/backend/base/langflow/graph/graph/base.py
src/backend/base/langflow/graph/graph/schema.py

Implement max_iterations in start method

feat: Add maximum iterations limit in Graph start method.

---

src/backend/base/langflow/graph/graph/base.py

This PR makes sure the vertex that calls `Graph.mark_branch` does not get marked with the rest of the branch.
Also refactors the mark_branch method into a private method.

fix: do not mark self.stop caller

---

src/backend/base/langflow/processing/process.py

Updated `apply_tweaks` function to correctly process tweak values that are dictionaries.
Fixes #3320

fix: handle case where tweak values are nested dicts

---

poetry.lock
src/backend/base/langflow/custom/custom_component/component.py
src/backend/base/poetry.lock
src/backend/tests/unit/initial_setup/starter_projects/test_vector_store_rag.py

Adds outputs to getattr which helps access to outputs.
Refactors _build_results to for consistency

feat: update output attribute handling

---

.github/workflows/typescript_test.yml

This adds a condition to skip merge-reports job if there was no error in the frontend tests

ci: Refactor report merge step to only run if necessary.

---

src/frontend/src/components/intComponent/index.tsx
src/frontend/src/components/parameterRenderComponent/index.tsx
src/frontend/src/types/components/index.ts
src/frontend/src/utils/reactflowUtils.ts

The number of fieds in "Create Data" component was taking value from input field as string however it should be number because of that update component API was failing as backend was expecting value as number.
Issue was reported here: https://github.com/langflow-ai/langflow/issues/3303 
@lucaseduoli Kindly review and merge as it is an important fix.

fix: Corrected Changed the data type of number field from string to number

---

src/backend/base/langflow/graph/graph/base.py
src/backend/base/langflow/graph/vertex/schema.py

Add a description attribute to graph

feat: add description on graph

---

.github/workflows/ci.yml
.github/workflows/python_test.yml

Update CI to limit the python versions running on every PR.
Reason we need to use `fromJson`: https://developer-friendly.blog/2024/03/09/github-actions-dynamic-matrix/#step-3-build-the-docker-images

ci: allow specifying python versions and limit ci to 3.10 only

---

src/backend/base/langflow/graph/vertex/base.py
src/backend/base/langflow/graph/vertex/types.py

This adds a `target_handle_name` param to `get_result` so edges can be correctly selected when getting result.

fix: makes outputs be correctly retrieved from edge

---

src/frontend/src/App.tsx
src/frontend/src/components/headerComponent/components/menuBar/index.tsx
src/frontend/src/controllers/API/helpers/constants.ts
src/frontend/src/controllers/API/queries/config/use-get-config.ts
src/frontend/src/hooks/flows/use-autosave-flow.ts
src/frontend/src/hooks/use-save-config.ts
src/frontend/src/modals/flowSettingsModal/index.tsx
src/frontend/src/pages/FlowPage/index.tsx
src/frontend/src/stores/flowsManagerStore.ts
src/frontend/src/types/zustand/flowsManager/index.ts
src/frontend/vite.config.mts

This pull request adds an auto-saving feature to the application. It includes several commits that introduce the necessary changes. The `useSaveConfig` hook is added to handle the configuration settings related to auto-saving. The `useFlowsManagerStore` is used to manage the `autoSaving` state. The `MenuBar` component is updated to disable the save button when auto-saving is enabled. The `FlowSettingsModal` component is updated to save the flow automatically when auto-saving is enabled. The `FlowPage` component is updated to enable auto-saving based on the configuration settings. The `FlowsManagerStoreType` is updated to include the `autoSaving` property and the `setAutoSaving` function. The `vite.config.js` file is updated to remove the `LANGFLOW_AUTO_SAVING` environment variable.

fix: auto saving config

---

src/backend/base/langflow/io/schema.py
src/backend/tests/unit/io/test_io_schema.py

This PR adds a function to create a BaseModel from a list of inputs

feat: add function to create input schema from component inputs

---

src/backend/base/langflow/base/tools/component_tool.py
src/backend/base/langflow/custom/custom_component/component.py
src/backend/tests/unit/base/tools/test_component_tool.py
src/backend/tests/unit/custom/component/test_component_to_tool.py

This allows Components to me converted to Tool. 
This PR should be merged after #3411

feat: add ComponentTool to support converting Component to Tool

---

src/frontend/src/hooks/flows/use-save-flow.ts

This PR fixes an issue where an unnecessary error was being returned when all components were removed from a flow. The error handling logic has been adjusted to ensure that removing all components does not trigger an error response.
🔧 (use-save-flow.ts): remove unnecessary error data setting when saving an empty flow to improve code readability and maintainability

fix: Remove unnecessary error return when all components are erased from a flow

---

src/backend/base/langflow/components/toolkits/ComposioAPI.py
src/frontend/src/CustomNodes/GenericNode/index.tsx
src/frontend/tests/scheduled-end-to-end/generalBugs-shard-11.spec.ts

This PR addresses a bug in the ComposIO application where users encountered an api_key missing error when attempting to add a new flow. The issue was caused by the incorrect handling of API keys during the flow creation process.

fix: Fix api_key missing error when adding a flow in ComposIO + tests

---

src/backend/base/langflow/components/models/AIMLModel.py

This PR removes the `json_mode` and `output_schema` parameters from the AIMLModel component. The changes include:
1. Removal of the `json_mode` Dictionary from the component definition.
2. Removal of the `output_schema` Dictionary from the component definition.
3. Deletion of the `json_mode` variable assignment in the `build_model` method.
4. Removal of the `output_schema_dict` variable and its usage in the `build_model` method.
These changes simplify the AIMLModel component by removing unused or redundant features. The PR aligns with issue #3385, which called for the removal of these parameters.
Importantly, this PR fixes errors related to unsupported features in AI ML. Specifically, it addresses the error:
"Error building Component Tool Calling Agent: AsyncCompletions.create() got an …

fix: remove json_mode and output_schema

---

src/frontend/src/components/textAreaComponent/index.tsx

This pull request removes the feature that automatically adjusts the rows of a text area based on its content within a node, resulting in a cleaner and more consistent user interface.

fix: remove autosize on textArea inside nodes

---

src/backend/base/langflow/custom/custom_component/custom_component.py
src/backend/base/langflow/initial_setup/starter_projects/Complex Agent.json
src/backend/base/langflow/initial_setup/starter_projects/Hierarchical Agent.json
src/backend/base/langflow/initial_setup/starter_projects/Sequential Agent.json
src/backend/base/langflow/type_extraction/type_extraction.py
src/backend/tests/test_schema.py

This PR updates the post_process_type function to extract inner types of inner types. 
This mainly fixes an error in which extra types were passed in the component's output leading to invalid handles.
#3445

fix: update type extraction to extract inner types correctly

---

src/frontend/src/CustomNodes/GenericNode/components/NodeStatus/index.tsx
src/frontend/src/CustomNodes/GenericNode/index.tsx

The commit "fix: set node size directly in the nodeComponent" addresses an issue where the node size was not being set correctly in the nodeComponent. This caused incorrect rendering of the node border. The commit fixes this issue by setting the node size directly in the nodeComponent.

Fix node size in nodeComponent

---

src/backend/tests/integration/astra/test_astra_component.py

Just some refactor to minimize error messages

test(astra): Refactor AstraDB imports in test_astra_component

---

src/frontend/src/CustomNodes/GenericNode/components/NodeStatus/index.tsx
src/frontend/src/CustomNodes/GenericNode/index.tsx

This pull request includes a single commit that moves a CSS class for the purpose of improving the UI/UX. The commit modifies the class placement in two files, resulting in a more streamlined and organized code structure.

fix: move css class for improve of the UI/UX

---

src/backend/base/langflow/custom/custom_component/component.py
src/backend/tests/unit/custom/custom_component/test_component.py

Improves errors and kwargs handling in Component

refactor: improve attribute compatibility and error messages

---

src/frontend/src/controllers/API/helpers/constants.ts
src/frontend/src/controllers/API/index.ts
src/frontend/src/controllers/API/queries/nodes/use-post-validate-code.ts
src/frontend/src/modals/codeAreaModal/index.tsx
src/frontend/src/types/api/index.ts

This pull request adds code validation functionality to the project. It includes the following changes:
- Added a new endpoint for code validation.
- Added a new API code validation type.
- Added a post validate code hook.
- Replaced an API call with a mutation for code validation.
- Removed the validate code API call.
These changes enable the user to validate their code before submitting it.

refactor: add code validation functionality on tanstack mutation

---

src/frontend/src/controllers/API/index.ts
src/frontend/src/controllers/API/queries/nodes/use-post-validate-prompt.ts
src/frontend/src/modals/promptModal/index.tsx

This pull request refactors the prompt validation functionality by introducing a new mutation for validating prompts. The `postValidatePrompt` function has been removed from the API file and replaced with the `usePostValidatePrompt` hook. The prompt modal component has been updated to use the new mutation for validating prompts. This refactor improves code organization and separates concerns related to prompt validation.

refactor: prompt validation functionality

---

src/frontend/src/controllers/API/index.ts
src/frontend/src/controllers/API/queries/flows/use-get-refresh-flows.ts
src/frontend/src/controllers/API/queries/folders/use-get-folders.ts
src/frontend/src/hooks/flows/use-upload-flow.ts
src/frontend/src/pages/FlowPage/index.tsx
src/frontend/src/pages/ViewPage/index.tsx
src/frontend/src/stores/flowsManagerStore.ts
src/frontend/src/types/zustand/flowsManager/index.ts

This pull request adds a new mutation called `useGetRefreshFlows` and updates the code to use this mutation instead of the old `refreshFlows` function. The `useGetRefreshFlows` mutation is used in multiple places throughout the codebase. It retrieves flows from the database and processes them to update the state. This change improves the code by using a more efficient and centralized approach for refreshing flows.

refactor: add useGetRefreshFlows mutation and update code to use it

---

src/backend/base/langflow/components/models/OpenAIModel.py

As when the input temperature is 0, the condition would become False , so this expressing set it to 0.1, it become impossible to set it to 0.

fix: allow setting temperature to 0 in OpenAIModel.py

---

src/backend/base/langflow/base/vectorstores/model.py
src/backend/base/langflow/components/retrievers/CohereRerank.py
src/backend/base/langflow/components/retrievers/NvidiaRerank.py
src/backend/base/langflow/components/vectorstores/AstraDB.py
src/backend/base/langflow/components/vectorstores/Cassandra.py
src/backend/base/langflow/components/vectorstores/Chroma.py
src/backend/base/langflow/components/vectorstores/Couchbase.py
src/backend/base/langflow/components/vectorstores/FAISS.py
src/backend/base/langflow/components/vectorstores/Milvus.py
src/backend/base/langflow/components/vectorstores/MongoDBAtlasVector.py
src/backend/base/langflow/components/vectorstores/Pinecone.py
src/backend/base/langflow/components/vectorstores/Qdrant.py
src/backend/base/langflow/components/vectorstores/Redis.py
src/backend/base/langflow/components/vectorstores/SupabaseVectorStore.py
src/backend/base/langflow/components/vectorstores/Upstash.py
src/backend/base/langflow/components/vectorstores/Vectara.py
src/backend/base/langflow/components/vectorstores/Weaviate.py
src/backend/base/langflow/components/vectorstores/pgvector.py

Prevents multiple `build_vector_store` calls from embedding the input multiple times. 
Closes https://github.com/langflow-ai/langflow/issues/3376

fix: moves caching of vector store to LCModelComponent level

---

src/backend/base/langflow/graph/graph/base.py
src/backend/base/langflow/services/tracing/service.py

This is an attempt at fixing a weird bug that causes the build loop to freeze and the logging to break.

fix: improve end_traces so it doesn't block the build loop

---

.github/workflows/docker-build.yml

Versions were mismatched causing prefix in the tags to be set incorrectly

refactor: Fix version extraction in GitHub Actions workflow

---

src/frontend/tests/scheduled-end-to-end/dropdownComponent.spec.ts

This pull request fixes the Dropdown Component test, which broke due to recent updates to the component.
The tests have been updated accordingly.

tests: fix dropdown components test

---

src/backend/base/langflow/api/v1/starter_projects.py
src/backend/base/langflow/components/models/AnthropicModel.py
src/backend/base/langflow/custom/directory_reader/directory_reader.py

Makes sure components are not imported at startup.

refactor: move import statement inside function to avoid unnecessary imports

---

src/backend/base/langflow/base/models/model.py
src/backend/base/langflow/custom/custom_component/component.py

Return the project name using get_project_name method in both classes.

feat: Update project name retrieval in LCModelComponent and CustomComponent

---

src/backend/base/langflow/api/utils.py
src/backend/base/langflow/api/v1/endpoints.py

Small improvement for better maintainability

fix: check if variable is valid before converting

---

src/backend/base/langflow/__main__.py

Implemented a try/except block in the function that notifies users of new build versions to handle potential errors gracefully and ensure the application continues running smoothly even if the notification process fails.
Fixes #3523

fix: build version notification function

---

src/backend/base/langflow/services/telemetry/opentelemetry.py

This pull request refactors the metric creation logic in the `opentelemetry.py` file and improves the handling methods for metrics. It enhances warnings and ensures that the key in the mapping and metric's name are the same. Additionally, it simplifies the metric creation process by using a helper method `_create_metric()`.

refactor: improve metric creation logic and silence ot warnings

---

src/backend/base/langflow/api/v1/chat.py
src/backend/base/langflow/api/v1/schemas.py
src/backend/base/langflow/graph/utils.py

This PR improves error handling to make sure errors don't get silenced.

fix: update serialization and improve error handling

---

src/backend/base/langflow/api/v1/chat.py

added a condition to set the cache for the graph when it is built.
this ensures that the latest graph state is stored in the chat service.
#3515 may be related

fix: ensure cache is set for graph in build flow

---

src/backend/base/langflow/components/toolkits/ComposioAPI.py

Currently, the connection status and app name are not updating correctly on refresh button click

fix: composio ux flow

---

docker/build_and_push.Dockerfile
poetry.lock
pyproject.toml

Re-added psycopg2 dependency.
This PR fixes the following issues:
- Fixes #3517
- Fixes #3524
- Fixes #3417

fix: no module named 'psycopg2'

---

src/frontend/src/components/folderSidebarComponent/components/sideBarFolderButtons/index.tsx

🐛 (index.tsx): Fix issue where setEditFolderName was being called with undefined or empty folders array, causing a crash. Added a check to ensure folders array is not empty before setting edit folder names.

fix: remove depth loop calls on folder's useEffect

---

src/frontend/src/controllers/API/queries/auth/use-post-add-user.ts

🐛 (use-post-add-user.ts): fix API endpoint URL to include trailing slash for consistency and to ensure correct routing

fix: user not been able to add new user on langflow docker

---

src/backend/base/langflow/main.py
src/frontend/package-lock.json
src/frontend/package.json
src/frontend/src/controllers/API/api.tsx

Reverts langflow-ai/langflow#3484 because of streaming problems

revert: add compression support to frontend and backend

---

src/backend/base/langflow/api/v1/files.py
src/backend/tests/unit/test_files.py

The file name generation in the `upload_file` function has been improved to prevent files with the same name. Previously, the function used the received file name, but now it also includes the file extension. This ensures that each file has a unique name.
fix #3400

fix: improve file name generation in upload_file function to prevent files with the same name

---

.github/workflows/nightly_build.yml

Allows me to actually run the workflow, whoops!

ci: add workflow dispatch to empty nightly build workflow

---

src/frontend/src/CustomNodes/GenericNode/components/NodeStatus/index.tsx
src/frontend/src/style/index.css
src/frontend/tailwind.config.mjs

Update the border class for the selected node status in the NodeStatus component to "border-2 border-node-selected hover:shadow-node". This change improves the visual representation of the selected node status.

fix: update border class for selected node status

---

src/backend/base/langflow/utils/connection_string_parser.py

In version 1.0.14, a connection string that includes a port, like the following example, works without any issues: `test_connection_string = 'postgresql://postgres:password!!@pgdatabase.hosts:5432'`
However, in version 1.0.15, using this connection string causes an error. 
"Error building Component PGVector: invalid literal for int() with base 10"
This is because "5432", which is the result of parsing the password_url, is being used as the last element in the password_url list.

fix: connection_string_parser.py

---

src/backend/base/langflow/services/tracing/langfuse.py
src/backend/base/langflow/services/tracing/service.py

This PR implements the Langfuse trace service using the low-level SDK.

feat: implement LangfuseTracer

---

src/backend/base/langflow/__main__.py

This PR removes a function that is not being used by any other part of the code. It was identified during the analysis of issue #3477, where it was found that the problem had already been resolved in PR #3527. The issue only occurred in v1.0.16, where the removed code was not removed

chore: remove-unused-code

---

src/frontend/src/components/headerComponent/components/menuBar/index.tsx
src/frontend/src/controllers/API/api.tsx
src/frontend/src/stores/flowStore.ts
src/frontend/src/utils/buildUtils.ts

This PR addresses two problems: 
1. the current client implementation to read chunks from the response using Fetch API is not standard and not compatible with Safari (and probably others). The right way is to use `body.getReader()` which has much larger support
2. The Stop button stops the build but it appears to not be working since no feedback is given to users

fix: building vertices not working on Safari and improve stop button

---

src/frontend/src/pages/FlowPage/index.tsx

This fixes the version display not being removed with ENABLE_BRANDING=False

fix: surround a tag with feature flag for ENABLE_BRANDING

---

src/backend/base/langflow/components/tools/GleanAPI.py
src/backend/base/langflow/components/tools/GleanSearchAPI.py
src/backend/base/langflow/components/tools/__init__.py

This pull requests adds a Tool component for the Glean Search API

feat: Add Glean Search API Component

---

src/frontend/src/modals/IOModal/components/chatView/chatInput/components/textAreaWrapper/index.tsx
src/frontend/src/pages/AppWrapperPage/index.tsx

- This pull request addresses an issue where the Playground's chat input was not consistently receiving focus when it should. The focus behavior is now managed using useEffect to ensure the input field receives focus under the appropriate conditions.
✨ (textAreaWrapper/index.tsx): add useEffect hook to focus on input when conditions are met
♻️ (AppWrapperPage/index.tsx): remove unnecessary console.log statement

fix: Ensure Correct Focus on Playground Chat Input

---

src/frontend/tests/scheduled-end-to-end/generalBugs-shard-1.spec.ts

🐛 (generalBugs-shard-1.spec.ts): Fix timing issues in end-to-end test by adding explicit waits for elements to be visible before interacting with them

tests: improve delete rows from table message test

---

Makefile

This pull request refactors the Makefile commands to improve readability and efficiency. The changes include redirecting the output of certain commands to /dev/null to reduce noise, updating the build_frontend target to include copying built files to the backend directory for deployment, and refactoring the lint target to depend on the install_backend task for better dependency management. Additionally, the Makefile commands have been updated to use the "@" symbol to suppress command output and improve readability. Finally, a command to delete empty directories has been added to the clean_python_cache target.

refactor: update Makefile commands for improved readability and efficiency

---

src/backend/base/langflow/api/log_router.py
src/backend/base/langflow/api/utils.py
src/backend/base/langflow/api/v1/base.py
src/backend/base/langflow/api/v1/callback.py
src/backend/base/langflow/api/v1/chat.py
src/backend/base/langflow/api/v1/endpoints.py
src/backend/base/langflow/api/v1/flows.py
src/backend/base/langflow/api/v1/folders.py
src/backend/base/langflow/api/v1/monitor.py
src/backend/base/langflow/api/v1/schemas.py
src/backend/base/langflow/api/v1/starter_projects.py
src/backend/base/langflow/api/v1/store.py

refactor(utils.py): change variable type annotation from Dict to dict for better consistency
refactor(base.py): change variable type annotation from Optional to Union for better clarity
refactor(callback.py): change variable type annotation from Dict to dict for better consistency
refactor(chat.py): change variable type annotation from Optional to Union for better clarity
refactor(endpoints.py): change variable type annotation from Optional to Union for better clarity
refactor(flows.py): change variable type annotation from List to list for better consistency
refactor(api): update response_model annotations to use lowercase list for consistency and improve readability
refactor(store.py): update type annotations for query parameters in get_components endpoint to improve code readability …

refactor(api): change variable type annotations

---

src/backend/base/langflow/custom/custom_component/component.py
src/backend/tests/unit/custom/custom_component/test_component.py
src/backend/tests/unit/graph/graph/test_base.py

This pull request includes a feature in the Component class, adding the `_find_matching_output_method` method to handle finding the appropriate output method for a given Component. It also includes a test for the graph set method with a valid component. These changes improve the functionality and reliability of the codebase.

feat: allow passing a Component to the set method

---

src/backend/base/langflow/inputs/input_mixin.py
src/backend/base/langflow/inputs/inputs.py
src/backend/base/langflow/io/schema.py
src/backend/base/langflow/template/field/base.py
src/backend/base/langflow/template/frontend_node/base.py
src/backend/base/langflow/template/frontend_node/custom_components.py
src/backend/base/langflow/template/template/base.py
src/backend/tests/unit/io/test_io_schema.py

Ran `uvx --from pyupgrade-directories pyup-dirs --py310-plus src/backend/base/langflow/io/*`, `uvx --from pyupgrade-directories pyup-dirs --py310-plus src/backend/base/langflow/template/*` and `uvx --from pyupgrade-directories pyup-dirs --py310-plus src/backend/base/langflow/inputs/*`

chore: update type annotations in template, io and inputs modules

---

src/backend/base/langflow/api/log_router.py
src/backend/base/langflow/api/utils.py
src/backend/base/langflow/api/v1/base.py
src/backend/base/langflow/api/v1/callback.py
src/backend/base/langflow/api/v1/chat.py
src/backend/base/langflow/api/v1/endpoints.py
src/backend/base/langflow/api/v1/flows.py
src/backend/base/langflow/api/v1/folders.py
src/backend/base/langflow/api/v1/monitor.py
src/backend/base/langflow/api/v1/schemas.py
src/backend/base/langflow/api/v1/starter_projects.py
src/backend/base/langflow/api/v1/store.py
src/backend/base/langflow/inputs/input_mixin.py
src/backend/base/langflow/inputs/inputs.py
src/backend/base/langflow/io/schema.py
src/backend/base/langflow/template/field/base.py
src/backend/base/langflow/template/frontend_node/base.py
src/backend/base/langflow/template/frontend_node/custom_components.py
src/backend/base/langflow/template/template/base.py
src/backend/tests/integration/utils.py
src/backend/tests/test_schema.py
src/backend/tests/unit/graph/test_graph.py
src/backend/tests/unit/io/test_io_schema.py
src/backend/tests/unit/test_custom_component.py
src/backend/tests/unit/test_helper_components.py
src/backend/tests/unit/test_kubernetes_secrets.py
src/backend/tests/unit/test_template.py

Ran `uvx --from pyupgrade-directories pyup-dirs --py310-plus src/backend/base/langflow/tests/**/*`

refactor: change typing annotations in tests folder

---

src/backend/base/langflow/custom/utils.py
src/backend/base/langflow/helpers/custom.py
src/backend/base/langflow/services/settings/base.py
src/backend/base/langflow/template/field/base.py
src/backend/tests/unit/io/test_io_schema.py

This pull request fixes type comparison issues in the codebase. The changes ensure that type comparisons are done correctly using the `is` operator instead of the `==` operator. This improves the accuracy and reliability of the code.

style: Fix type comparison issues in codebase

---

src/frontend/src/CustomNodes/GenericNode/components/NodeInputField/index.tsx
src/frontend/src/components/cardComponent/index.tsx
src/frontend/src/components/chatComponent/index.tsx
src/frontend/src/controllers/API/queries/auth/use-post-add-user.ts
src/frontend/src/customization/components/custom-parameter.tsx
src/frontend/src/customization/utils/analytics.ts
src/frontend/src/modals/baseModal/index.tsx
src/frontend/src/pages/FlowPage/components/PageComponent/index.tsx
src/frontend/src/pages/MainPage/pages/mainPage/index.tsx
src/frontend/src/pages/Playground/index.tsx
src/frontend/src/pages/SignUpPage/index.tsx

This pull request includes several changes:
- Added an analytics track function to track events in the application.
- Added support for custom parameters in the NodeInputField component.
- Changed the post add user functionality to use a function instead of an async call.
- Added tracking in various components to track user interactions.
- Added a centered option to the Footer component for better alignment.

refactor: added analytics track and custom parameter support

---

poetry.lock
pyproject.toml

This pull request removes the "pdf" extra from the unstructured dependency in the pyproject.toml file. This change ensures that the "pdf" extra is no longer included when installing the unstructured package.
@erichare FYI, this is a PR for us to test if pytorch is breaking CI due to its size and also to know what you think about removing it since installing pytorch is something we avoid since it makes the installation take a very long time and increases the size of docker images

chore: Remove PDF extra from unstructured dependency because of pytorch

---

src/frontend/src/components/authSettingsGuard/index.tsx
src/frontend/src/controllers/API/api.tsx
src/frontend/src/controllers/API/queries/health/use-get-health.ts
src/frontend/src/customization/components/custom-api-generator.tsx
src/frontend/src/customization/config-constants.ts
src/frontend/src/modals/apiModal/index.tsx
src/frontend/src/pages/AppInitPage/index.tsx
src/frontend/src/pages/FlowPage/index.tsx
src/frontend/src/pages/Playground/index.tsx
src/frontend/src/pages/ViewPage/index.tsx
src/frontend/src/stores/globalVariablesStore/globalVariables.ts
src/frontend/src/types/zustand/globalVariables/index.ts

The health check endpoint has been changed to `/health_check` and the URL has been modularized using the `HEALTH_CHECK_URL` constant. This improves code organization and makes it easier to update the health check URL in the future.

refactor: health check endpoint

---

src/frontend/src/components/headerComponent/index.tsx
src/frontend/src/customization/config-constants.ts

This pull request updates the docs link in the header component to be modular. Previously, the link was hard-coded, but now it is sourced from the `config-constants` file. This allows for easier customization and configuration of the docs link.

refactor: update docs link to be modular

---

src/backend/base/langflow/graph/graph/base.py
src/backend/base/langflow/graph/vertex/base.py
src/backend/base/langflow/graph/vertex/types.py
src/backend/tests/unit/graph/graph/test_cycles.py
src/backend/tests/unit/initial_setup/starter_projects/test_memory_chatbot.py
src/backend/tests/unit/initial_setup/starter_projects/test_vector_store_rag.py

This pull request adds cycle detection and handling functionality to the graph processing module. It introduces the `is_cyclic` property to check for cycles in the graph and modifies the `layered_topological_sort` method to handle cyclic graphs by starting from a specified start component. Additionally, it refactors tests and components for improved caching and data handling, updates the `VertexStates` enum values to uppercase, and improves error handling in the `Vertex` class. Unit tests for detecting cycles in the graph are also included.

fix: add tests to cycles in Graph and improve error handling

---

src/frontend/src/components/headerComponent/components/menuBar/index.tsx
src/frontend/src/controllers/API/api.tsx
src/frontend/src/stores/flowStore.ts
src/frontend/src/types/zustand/flow/index.ts

This pull request adds the `buildController` and `stopBuilding` controllers to the codebase. The `stopBuilding` controller is used in the header's Stop button, and the `buildController` is set in the API `performStreamingRequest` function. Additionally, the `setBuildController` function is added to the types. These changes enhance the control and management of the build process in the application.

fix: stop building with abort controller

---

poetry.lock
pyproject.toml
src/backend/base/langflow/components/retrievers/SelfQueryRetriever.py

🔧 (pyproject.toml): add lark dependency to support parsing and processing of grammars in the project
♻️ (SelfQueryRetriever.py): refactor input types in metadata fields to improve clarity and maintainability

fix: update Self Query Retriever Component

---

src/frontend/src/components/folderSidebarComponent/components/sideBarFolderButtons/index.tsx

🐛 (sideBarFolderButtons/index.tsx): fix success message not being set when files array is empty

fix: success dialog popping wrong

---

Makefile

This pull request updates the Makefile to conditionally disable the reload and workers options based on the presence of the workers variable. This ensures that the reload and workers options are only enabled when the workers variable is specified.

refactor: conditionally disable reload and workers in Makefile based on the presence of the workers variable

---

src/frontend/src/modals/IOModal/components/SessionView/index.tsx
src/frontend/src/modals/IOModal/index.tsx
src/frontend/src/pages/MainPage/components/myCollectionComponent/index.tsx
src/frontend/tests/end-to-end/auto-login-off.spec.ts

Fixed an issue where the IOModal was calling the getMessages API again unnecessarily. Also fixed an issue where the folders API was being called twice. These changes ensure that the API calls are made only when necessary, improving performance and reducing unnecessary network requests.

fix: iomodal and folders api calls

---

Makefile

This pull request updates the Makefile to conditionally enable the --reload flag based on the worker count. It also handles backend port kill errors.

fix: update Makefile to conditionally enable --reload based on worker count

---

poetry.lock
pyproject.toml
src/backend/base/langflow/components/documentloaders/Unstructured.py
src/backend/base/langflow/initial_setup/setup.py
src/backend/base/langflow/main.py

This pull request enforces the use of the Unstructured Serverless API in the component, avoiding the need for the OSS PDF parsing libraries and NLTK downloads.

feat: Switch to API for Unstructured Component

---

src/frontend/src/controllers/API/queries/folders/use-get-folders.ts
src/frontend/src/pages/FlowPage/index.tsx
src/frontend/src/pages/Playground/index.tsx
src/frontend/src/pages/ViewPage/index.tsx
src/frontend/src/stores/typesStore.ts

This PR addresses an issue where the /getall endpoint was being called unnecessarily every time a user accessed the 'My Collection' page. This redundant API call could lead to increased load times and unnecessary server strain.
✨ (use-get-folders.ts): Update useGetFoldersQuery to check if types are empty before calling getTypes to avoid unnecessary API calls
♻️ (typesStore.ts): Remove unnecessary useAlertStore setState call to improve code readability and maintainability

fix: getall is being called unnecessarily every time the user accesses the My Collection page

---

src/frontend/src/controllers/API/queries/folders/use-delete-folders.ts

This pull request includes a commit that adds functionality to delete a folder from the cache after a successful deletion. The commit modifies the `useDeleteFolders` function to return the folder ID, which is then used in the `onSuccess` callback to remove the folder from the cache. This ensures that the cache is updated correctly after a folder is deleted.

fix: Delete folder from cache after successful deletion

---

src/backend/base/langflow/api/v1/endpoints.py
src/backend/base/langflow/helpers/user.py

This pull request adds a `user` parameter to the `webhook_run_flow` endpoint in `endpoints.py`. It also introduces a new helper function, `get_user_by_flow_id_or_endpoint_name`, in `user.py` to retrieve user details based on flow ID or endpoint name. These changes allow for API key association with the user when running a flow through the webhook endpoint.
Fixes #3407

fix: add user dependency to webhook endpoint for flow execution

---

src/frontend/src/modals/buildInProgressModal/index.tsx
src/frontend/src/pages/FlowPage/index.tsx
src/frontend/src/stores/flowStore.ts

This pull request adds a new modal component called BuildInProgressModal, which is displayed when a build is in progress and the user tries to exit. The modal allows the user to stop the build process. Additionally, the stopBuilding function in the FlowStore has been updated to set the isBuilding state to false after aborting the build.

feat: add build in progress modal when trying to exit

---

src/frontend/src/controllers/API/queries/auth/use-get-autologin.ts
src/frontend/src/controllers/API/queries/config/use-get-config.ts
src/frontend/src/controllers/API/queries/health/use-get-health.ts
src/frontend/src/controllers/API/queries/store/use-get-tags.ts
src/frontend/src/controllers/API/queries/transactions/use-get-transactions.ts
src/frontend/src/controllers/API/queries/variables/use-get-global-variables.ts
src/frontend/src/controllers/API/queries/version/use-get-version.ts

This pull request updates all queries to set the `refetchOnWindowFocus` option to `false`. This ensures that the queries will not automatically refetch data when the window gains focus, improving performance and reducing unnecessary network requests.

fix: set refetch on window focus to false for all queries on flow page

---

src/frontend/src/components/headerComponent/components/menuBar/index.tsx
src/frontend/src/pages/FlowPage/components/PageComponent/index.tsx
src/frontend/src/stores/flowStore.ts

I have made the following changes:
- Removed the viewport setting on resetFlow and setReactflowInstance functions.
- Removed the onMoveEnd function and its usage.
- Added the fitView prop to the ReactFlow component to make it start with a fit view.
These changes ensure that the ReactFlow canvas starts with a fit view, providing a better initial visualization of the flow.

fix: remove saving on flow pan and add fit view to reactflow

---

src/backend/base/langflow/custom/custom_component/component.py
src/backend/base/langflow/graph/graph/base.py
src/backend/base/langflow/template/field/base.py
src/backend/tests/unit/test_custom_component.py
src/backend/tests/unit/test_database.py

This was a bug that @edwinjosechittilappilly noticed in the linked issue. Outputs of subsequently created components were overriding outputs of previously created components of the same name - i.e. two Model outputs may interchange their `Outputs`, regardless of where in the flow they were. 
This is due to how the class variable `Outputs` is structured -- as class variables, it gives us this potential for cross-component leakage, but I have no better ideas at the moment on how to allow initializing the component with Outputs and then allowing for dynamic updates to that variable to provide the `result`. 
Closes https://github.com/langflow-ai/langflow/issues/3619

fix: deepcopy component output to avoid overriding previous outputs

---

src/backend/base/langflow/interface/types.py

This PR fixes a bug in the request to the `/all` endpoint, where the backend would stop responding under certain conditions. For some reason, the backend's response is being altered between flow executions, causing the endpoint to return something that is not serializable.

fix: use permanent cache for all types dict and build only once

---

src/frontend/src/modals/IOModal/components/chatView/chatMessage/index.tsx
src/frontend/src/modals/IOModal/index.tsx
src/frontend/src/stores/utilityStore.ts
src/frontend/src/types/components/index.ts
src/frontend/src/types/zustand/utility/index.ts

This pull request adds the `useUtilityStore` hook to the `IOModal` component for managing the scroll behavior of the playground in the application. It also includes the `setPlaygroundScrollBehaves` function to update the `playgroundScrollBehaves` property in the `UtilityStoreType`. This allows for setting the scroll behavior of the playground to either "instant" or "smooth".

feat: add a better scroll behave on playground's chat

---

src/backend/tests/unit/test_database.py

This pull request refactors the test cases to use unique flow names with UUIDs. Previously, the test cases used hardcoded flow names, which could lead to conflicts and inaccurate test results. By generating unique flow names with UUIDs, we ensure that each test case operates on distinct flows, improving the reliability and accuracy of the tests.

refactor: update test cases to use unique flow names with UUIDs

---

poetry.lock
pyproject.toml
src/backend/base/langflow/components/vectorstores/HCD.py
src/frontend/src/icons/HCD/Favicon.svg
src/frontend/src/icons/HCD/HCD.jsx
src/frontend/src/icons/HCD/index.tsx
src/frontend/src/utils/styleUtils.ts

Added support for [DataStax Hyper-Converged Database (HCD)](https://www.datastax.com/products/hyper-converged-database-hcd) backed vector store.

feat: add support for DataStax HCD vector store

---

src/backend/base/langflow/components/astra_assistants/create_assistant.py
src/frontend/src/CustomNodes/GenericNode/components/NodeOutputfield/index.tsx
src/frontend/src/CustomNodes/GenericNode/index.tsx
src/frontend/src/pages/FlowPage/components/nodeToolbarComponent/index.tsx
src/frontend/src/types/components/index.ts

This pull request removes unused code and fixes an issue where the node status was still being displayed when the node was minimized. It also fixes a bug where the node wouldn't expand after being minimized if an output was hidden. Additionally, some linting has been done to improve code quality.

fix: node status display when node minimized

---

src/backend/base/langflow/components/tools/PythonREPLTool.py
src/backend/base/langflow/components/tools/YfinanceTool.py
src/backend/base/langflow/custom/attributes.py
src/backend/base/langflow/graph/edge/base.py
src/backend/base/langflow/initial_setup/starter_projects/Agent Flow.json
src/backend/base/langflow/initial_setup/starter_projects/Complex Agent.json
src/backend/base/langflow/initial_setup/starter_projects/Sequential Agent.json
src/backend/base/langflow/template/frontend_node/base.py
src/backend/tests/unit/components/tools/test_python_repl_tool.py
src/backend/tests/unit/components/tools/test_yfinance_tool.py
src/backend/tests/unit/graph/graph/test_base.py
src/backend/tests/unit/test_custom_component.py

This pull request includes refactoring of the YfinanceToolComponent and PythonREPLToolComponent. The changes involve updating the inheritance of YfinanceToolComponent to inherit from LCToolComponent and removing unused outputs. The PythonREPLToolComponent has been refactored to use the new input configuration and update method signatures. Additionally, functions have been added to handle dict values in ATTR_FUNC_MAPPING for '_outputs_maps' and '_inputs'. The error message has been updated to use display_name instead of vertex_type in edge validation. Unit tests have been added for custom component subclassing from LCToolComponent, YfinanceToolComponent template output validation, and PythonREPLToolComponent template validation. The tool components have been updated to include 'Data' …

refactor: update ATTR_FUNC_MAPPING and tools to match other tools

---

poetry.lock
pyproject.toml
src/backend/base/langflow/main.py
src/backend/base/langflow/services/settings/base.py

This PR disables the old langfuse_plugin code. In PR #3398, a Langfuse tracer service was implemented

fix: disables langfuse_plugin code

---

src/backend/base/langflow/base/agents/agent.py
src/frontend/tests/extended/regression/generalBugs-shard-1.spec.ts

This PR resolve bug on langchain: TypeError: object LangfuseResponseGeneratorSync can't be used in 'await'

fix: bug langchain await

---

src/backend/base/langflow/initial_setup/starter_projects/Agent Flow.json

This PR will change the default value of the InputComponent on the Simple Agent flow.

fix: change the default value of inputComponent on Simple Agent

---

docs/docs/Getting-Started/getting-started-quickstart.md

When we go to https://docs.langflow.org/ => Getting Started => Quick Start => Next Steps.
There are three links which give 404 when we try to open them.
Fixed the links with this PR.

Docs: Update getting-started-quickstart.md

---

src/frontend/src/components/editFlowSettingsComponent/index.tsx
src/frontend/src/modals/flowSettingsModal/index.tsx
src/frontend/tests/extended/regression/generalBugs-shard-13.spec.ts

This pull request includes changes to improve the name validation and the invalid name list functionality. The commit "Changed text warning name invalid" updates the text warning for invalid names to include the message "Name invalid or already exists". The commit "Change invalidNameList to include components" modifies the invalid name list to include components as well. These changes aim to enhance the user experience and ensure accurate validation of names.

fix: update flow name validation and label

---

src/backend/base/langflow/base/agents/agent.py

♻️ (agent.py): refactor the code to remove unnecessary 'await' keyword before agent.invoke() method to improve code readability and maintainability
#3778

fix: adjust invoke agent to work sync

---

src/backend/base/langflow/components/agents/CSVAgent.py

✨ (CSVAgent.py): Add support for MessageTextInput input type and Output for building agent response
📝 (CSVAgent.py): Update input descriptions and add info for better understanding of inputs
📝 (CSVAgent.py): Update build_agent_response method to handle input and return response as a Message object
📝 (CSVAgent.py): Update build_agent method to return Union[AgentExecutor, Agent] for flexibility and handle parsing errors

fix: update csvAgent to work as expected

---

src/frontend/src/CustomNodes/GenericNode/components/NodeStatus/index.tsx
src/frontend/src/style/applies.css

Fix border on frozen node not appearing

fix: frozen border

---

src/frontend/src/App.css
src/frontend/src/CustomNodes/GenericNode/components/NodeInputField/index.tsx
src/frontend/src/CustomNodes/GenericNode/components/NodeOutputfield/index.tsx
src/frontend/src/components/dictComponent/index.tsx
src/frontend/src/components/parameterRenderComponent/component/refreshParameterComponent/index.tsx
src/frontend/src/modals/dictAreaModal/index.tsx
src/frontend/src/style/classes.css

This pull request includes changes to fix the dark mode colors on the jsonView component and to improve the button view of the dict component. The dark mode colors on the jsonView component have been adjusted to match the desired style. Additionally, the button in the dict component has been updated to include an icon and a label for better clarity. These changes improve the overall user experience and visual consistency of the application.

fix: json dark mode colors and dict component button view

---

src/frontend/src/components/pageLayout/index.tsx
src/frontend/src/customization/components/custom-banner.tsx

This pull request adds a custom banner component and refactors the pageLayout component to include the custom banner. The custom banner is imported from the "@/customization/components/custom-banner" module. This change enhances the visual appearance of the page layout.

refactor: add custom banner and refactor pagelayout to include it

---

src/frontend/package-lock.json
src/frontend/package.json
src/frontend/src/controllers/API/api.tsx
src/frontend/src/routes.tsx
src/frontend/vite.config.mts

Fix vite config and routes to support only /, fix API interceptor to intercept fetch

fix: vite config and routes to support no slashes, and api interceptor for fetch

---

src/backend/base/langflow/base/tools/flow_tool.py
src/backend/base/langflow/custom/custom_component/custom_component.py
src/backend/base/langflow/helpers/flow.py

This pull request adds the `run_id` parameter to the `load_and_run_flow` function, `run_flow` call in `FlowTool`, and `CustomComponent`'s `run_flow` method. The `run_id` parameter allows for setting the run ID in the graph and tracking runs. This enhancement improves the functionality and tracking capabilities of the code.

feat: Add run_id parameter to run_flow function

---

src/backend/base/langflow/base/textsplitters/model.py

It seems the change in https://github.com/langflow-ai/langflow/pull/3757 creates some kind of conflicts and the Data output of text splitters cannot be linked anymore.
This PR fixes this and also makes the code simpler.

fix: Fix Text Splitters

---

src/frontend/src/alerts/alertDropDown/components/singleAlertComponent/index.tsx
src/frontend/src/constants/constants.ts
src/frontend/src/hooks/flows/use-add-flow.ts
src/frontend/src/hooks/flows/use-delete-flow.ts
src/frontend/src/pages/FlowPage/components/extraSidebarComponent/sideBarDraggableComponent/index.tsx
src/frontend/src/pages/MainPage/components/componentsComponent/index.tsx
src/frontend/src/pages/MainPage/components/myCollectionComponent/index.tsx

Refactored the `useDeleteFlow` hook to return an object with `deleteFlow` and `isDeleting` properties. This allows for better handling of the delete flow functionality. Additionally, updated the project description to remove the word "personal" from "Manage your personal projects" and replaced it with "projects" for better clarity.

fix: update project description, update alerts animation, fix delete and duplicate loading

---

src/backend/base/langflow/components/agents/XMLAgent.py

📝 (XMLAgent.py): Add support for chat history data input in XMLAgentComponent to enhance agent functionality and interaction with Language Model.

fix: xml component working properly

---

.github/workflows/nightly_build.yml

The `ref` checkout failed because the `langflow-base-nightly` tag was not yet pushed to pypi, but the project dependency has already been updated to point to the new base nightly version from main nightly. 
I realize that we don't need to checkout out the main tag for testing. The `github.ref` default will point to the same ref that triggered the workflow, so it will test the same code that we are tagging. The only risk is if our scripts actually modify the codebase itself, but that's low-risk and shouldn't happen.

ci: remove unnecessary ref checkout for nightly tests

---

src/frontend/src/components/dropdownButtonComponent/index.tsx
src/frontend/src/components/folderSidebarComponent/components/sideBarFolderButtons/index.tsx
src/frontend/src/pages/MainPage/pages/mainPage/index.tsx
src/frontend/src/types/components/index.ts

This pull request addresses an issue where the application enters a build loop after renaming a folder, opening a new flow, and running the flow. The build loop caused unnecessary rebuilds and performance issues when these actions were performed in sequence.
#3823

fix: fix building loop when renaming a folder and opening a new flow and running It

---

src/backend/base/langflow/base/tools/flow_tool.py

This pull request refactors the `FlowTool` class to use the `run_until_complete` function for executing async flows. This improves the flow execution process by ensuring that the flow is fully completed before moving on to the next task.
Fixes #3807

fix: refactor FlowTool to use run_until_complete for async flow execution

---

src/backend/base/langflow/base/tools/flow_tool.py
src/backend/base/langflow/components/prototypes/FlowTool.py

This pull request adds a `run_id` parameter to the `set_run_id` method in the `Graph` class and handles exceptions when setting the `run_id` in the `FlowTool` class. The `run_id` parameter allows for tracking runs in the graph, and the exception handling ensures that the code does not break if there is an error in setting the `run_id`.

fix: add run_id parameter to set run ID in graph and handle exceptions in FlowTool

---

src/backend/base/langflow/graph/graph/base.py

Ensure the variable has a value before invoking its method to prevent potential error.
Fixes #3854

fix: add check for variable value before calling method

---

src/frontend/src/components/inputFileComponent/index.tsx
src/frontend/src/constants/alerts_constants.tsx
src/frontend/src/constants/constants.ts

This PR addresses an issue where file uploads larger than 10MB would cause the application to crash due to limitations in the data render component.
*** **While this isn't a comprehensive solution, it will prevent Langflow from crashing during use, ensuring a more stable experience for users.**

fix: limit file upload size to 10mb to prevent LF crashing due data render component limitations

---

src/backend/base/langflow/graph/utils.py
src/backend/base/langflow/graph/vertex/types.py
src/backend/base/langflow/services/database/models/message/model.py
src/backend/tests/unit/utils/test_rewrite_file_path.py
src/frontend/tests/core/features/chatInputOutputUser-shard-0.spec.ts
src/frontend/tests/extended/regression/general-bugs-shard-3836.spec.ts

#3836
This PR addresses the issue by ensuring that the image is properly sent when using the ChatInputComponent in runtime scenarios. This fix allows the flow to correctly pass the image file for analysis, enabling LLM image processing without errors.

fix: image not been sent on ChatInputComponent during runtime of building a flow

---

src/backend/base/langflow/components/astra_assistants/__init__.py
src/backend/base/langflow/components/astra_assistants/create_assistant.py
src/backend/base/langflow/components/astra_assistants/create_thread.py
src/backend/base/langflow/components/astra_assistants/get_assistant.py
src/backend/base/langflow/components/astra_assistants/list_assistants.py
src/backend/base/langflow/components/astra_assistants/run.py
src/backend/base/langflow/template/template/base.py
src/backend/tests/integration/components/assistants/test_assistants_components.py

A couple of the assistants components were broken due to the way the OpenAI sdk client was being set up so I fixed and added integration tests.

fix: update assistants components and add integrations tests

---

src/backend/base/langflow/api/v1/chat.py

`_build_vertex` is `async`, so we should make it `sync` by `asyncio.run` before passing it to `asyncio.to_thread` 
```python
asyncio.create_task(asyncio.to_thread(asyncio.run, _build_vertex(vertex_id, graph, event_manager)))
```

fix: Server is busy (#3878)

---

src/backend/base/langflow/components/prompts/LangChainHubPrompt.py

This pull request makes two important fixes:
1. It supports Langchain Hub Templates that don't have messages, but rather just a simple prompt.
2. It gives a better error message when an API key is not provided.

bugfix: Handle prompts with no Chat messsages

---

docs/docs/Components/components-embedding-models.md
docs/docs/Components/components-helpers.md
docs/docs/Components/components-vector-stores.md

Components updates for 1.0.18:
* JSON Parse Helper, Filter Data, Merge Data
* Vector stores: Cassandra graph, HCD, Clickhouse, and update Astra DB parameters to current state
* Embeddings: embedding similarity, google genai embeddings, text embeddings, hugging face local is deprecated.
* Minor cleanup

Docs: update components to v1.0.18

---

src/backend/base/langflow/components/vectorstores/AstraDB.py
src/backend/tests/integration/components/astra/test_astra_component.py

This pull request fixes some references to vectorize option parameters

FIX: proper parameters in Astra DB Vectorize options

---

poetry.lock
pyproject.toml
src/backend/base/langflow/components/vectorstores/MongoDBAtlasVector.py
uv.lock

`pymongo` includes a `bson` implementation built-in. installing bson explicitly will cause conflicts. https://pymongo.readthedocs.io/en/stable/installation.html
Closes https://github.com/langflow-ai/langflow/issues/3912

fix: remove bson import

---

pyproject.toml
uv.lock

This PR makes the project run in the project folder instead of the venv allowing debugging

fix: update pyproject.toml to use workspace configuration for langflow-base

---

src/frontend/src/pages/FlowPage/components/extraSidebarComponent/sidebarFilterComponent/index.tsx

🔧 (index.tsx): improve layout of sidebarFilterComponent to display type in a more readable way

fix: truncate text on filter to x icon fits the parent div

---

src/frontend/src/stores/flowStore.ts

This pull request fixes an issue where the animation of building edges would continue even after the build was stopped. The `stopBuilding` function now includes a call to `updateEdgesRunningByNodes` to update the edges running status for all nodes to false. This ensures that the animation stops when the build is stopped.

fix: animation of building edges on build stop

---

src/frontend/src/controllers/API/queries/flows/use-patch-update-flow.ts
src/frontend/src/pages/FlowPage/components/PageComponent/index.tsx
src/frontend/src/pages/MainPage/pages/mainPage/index.tsx

This pull request fixes the usePatchUpdateFlow function to only refetch queries when the browser URL do not contains "/flow". This prevents unnecessary requests and improves performance.

fix: usePatchUpdateFlow to conditionally refetch queries based on the browser URL

---

src/backend/base/langflow/graph/graph/base.py
src/backend/base/langflow/graph/graph/utils.py
src/backend/tests/unit/graph/graph/test_utils.py
src/frontend/src/CustomNodes/GenericNode/components/NodeStatus/index.tsx
src/frontend/src/CustomNodes/GenericNode/index.tsx
src/frontend/src/CustomNodes/hooks/use-icons-status.tsx

- Added `get_root_of_group_node` function to identify the root of a group node.
- Updated `sort_up_to_vertex` to use `get_root_of_group_node` for handling group nodes.
- Modified `__filter_vertices` to pass `parent_node_map` to `sort_up_to_vertex`.

fix: Handle group nodes in graph sorting

---

.github/workflows/nightly_build.yml
.github/workflows/release.yml
.github/workflows/release_nightly.yml
Makefile
uv.lock

This pull request updates the dependency management in the release and nightly build workflows to use 'uv' instead of Poetry. It replaces the installation and caching steps with 'uv' commands and modifies the Python setup to use the version specified in 'pyproject.toml'. The Node.js setup steps are also removed. This change improves the efficiency and consistency of the dependency management process.

ci: update release workflows to use uv

---

src/backend/base/langflow/components/helpers/StoreMessage.py

📝 (StoreMessage.py): Change StrInput to MessageInput for sender, sender_name, and session_id inputs to improve clarity and consistency in the code.
#3873

fix: update storeMessageComponent input types

---

src/frontend/src/components/inputFileComponent/index.tsx
src/frontend/src/modals/IOModal/components/IOFieldView/components/FileInput/index.tsx
src/frontend/src/modals/IOModal/components/chatView/chatInput/index.tsx
src/frontend/src/shared/hooks/use-file-size-validator.tsx

This pull request will create a new custom hook to validate the file sizes besides validate on each component.

feat: improve file uploader size validation - custom hook

---

src/backend/base/langflow/api/v1/flows.py
src/backend/tests/conftest.py
src/backend/tests/unit/test_database.py

This pull request adds a new `components_only` parameter to the `read_flows` API endpoint. When set to `True`, this parameter allows filtering the returned flows to only include components. This is useful when you only want to retrieve flows that are components and exclude other types of flows.
The changes include adding the `components_only` parameter to the function signature, updating the database query to filter flows based on the parameter value, and adding a test case to ensure the correct behavior.

feat: Add `components_only` parameter to filter flows by components in API endpoint

---

src/frontend/src/components/floatComponent/index.tsx

🔧 (floatComponent/index.tsx): update handleChange function to convert input value to a number before passing it to onChange function
This was causing an error because when the field was empty, it sent a string beside a number.
It is causing error on pydantic.
#2862

fix: force floatInputComponent to send Number

---

src/backend/base/langflow/components/vectorstores/AstraDB.py

Small fix to vectorize auth params

fix: vectorize authentication params

---

.gitignore
src/backend/base/langflow/api/v1/files.py
src/backend/base/langflow/main.py
src/frontend/tests/core/unit/tableInputComponent.spec.ts

This PR fixes security vulnerabilities:
- File uploads without user authentication
- check boundary

fix: security file upload

---

src/frontend/src/customization/config-constants.ts

The docs link in the code was pointing to the wrong URL. This PR updates the docs link to the correct URL.

fix: update docs link

---

src/backend/base/langflow/api/v1/flows.py

🐛 (flows.py): fix logic to remove example flows based on condition to improve data consistency and prevent errors
#3918

fix: consider remove_example_flows param on query on GET flows endpoint

---

.github/workflows/nightly_build.yml
.github/workflows/python_test.yml
.github/workflows/release.yml
.github/workflows/release_nightly.yml
.github/workflows/style-check-py.yml

Adds back some checkout actions and fixes commit tag steps. Workflow is working! https://github.com/langflow-ai/langflow/actions/runs/11147254720

ci: small nightly fixes

---

src/backend/base/langflow/base/models/model.py

The system message should be inserted into the first position of the message list instead of being appended at the last position.

fix: message list order

---

src/backend/base/langflow/base/tools/component_tool.py
src/backend/base/langflow/components/prototypes/RunnableExecutor.py
src/backend/base/langflow/services/database/models/user/crud.py
src/backend/base/langflow/services/telemetry/opentelemetry.py
src/backend/base/langflow/services/variable/kubernetes_secrets.py
src/backend/base/langflow/utils/util.py
src/backend/base/pyproject.toml

Add ruff rules for builtins (A)

ref: Add ruff rules for builtins (A)

---

src/backend/base/langflow/components/vectorstores/Qdrant.py

fix: modified QdrantVectorStoreComponent to use server_kwargs correctly

---

pyproject.toml
uv.lock

This will (probably) make it so we don't have to pass `--prerelease=allow` to install langflow with `uvx`

chore: Update zep-python dependency to stable version 2.0.0 in pyproject.toml

---

src/backend/base/langflow/components/tools/TavilyAISearch.py

This pull request adds a type annotation for the 'status' variable in the TavilyAISearch tool and formats the multiline string in the TavilySearchToolComponent description for better readability.

chore: Add type annotation for 'status' and format multiline string in TavilyAISearch tool

---

src/backend/base/langflow/components/memories/RedisChatMemory.py

This PR is about including the Redis component as a cache for chat memory.

feat: Add Redis Chat Memory

---

src/backend/base/langflow/initial_setup/setup.py
src/backend/base/langflow/services/database/models/folder/utils.py
src/backend/tests/unit/test_database.py

Using `LANGFLOW_LOAD_FLOWS_PATH` to import flows on startup did not set the `folder_id` correctly, causing flows to be orphaned in the frontend, with no way to display them. The `api/v1/flows` still lists them, which is why it originally was considered working. 
This PR adds `folder_id` to both existing orphaned flows and newly created flows. 
Note that the current behavior just uses the default_folder as the folder. Ideally, as per #4010, we'd have the ability to scope flows to folders and users. This PR is the first step so as to unblock users from the basic functionality.

fix: set folder id on flows imported on startup

---

src/backend/base/langflow/services/database/models/transactions/model.py
src/backend/base/langflow/services/database/models/vertex_builds/model.py

🔧 (model.py): Remove unused imports and functions related to truncating long strings in database models to clean up the code and improve readability.

fix: remove truncate to save data on DB

---

src/backend/base/langflow/services/variable/service.py
src/backend/tests/unit/services/variable/test_service.py

This PR fixes the update of global variables

fix: update variable fields

---

src/backend/base/langflow/base/data/utils.py
src/backend/base/langflow/components/agents/JsonAgent.py
src/backend/base/langflow/components/agents/OpenAPIAgent.py
src/backend/base/langflow/components/assemblyai/AssemblyAIStartTranscript.py
src/backend/base/langflow/components/documentloaders/GitLoader.py
src/backend/base/langflow/components/helpers/CSVtoData.py
src/backend/base/langflow/components/helpers/JSONtoData.py
src/backend/base/langflow/components/vectorstores/Redis.py
src/backend/base/langflow/custom/code_parser/code_parser.py
src/backend/base/langflow/custom/directory_reader/directory_reader.py
src/backend/base/langflow/initial_setup/setup.py
src/backend/base/langflow/interface/utils.py
src/backend/base/langflow/load/load.py
src/backend/base/langflow/load/utils.py
src/backend/base/langflow/services/cache/utils.py
src/backend/base/langflow/services/database/service.py
src/backend/base/langflow/services/plugins/service.py
src/backend/base/langflow/services/settings/base.py
src/backend/base/langflow/services/settings/manager.py
src/backend/base/langflow/services/settings/utils.py
src/backend/base/langflow/services/storage/local.py
src/backend/base/pyproject.toml

Add ruff rules for Pathlib (PTH)

ref: Add ruff rules for Pathlib (PTH)

---

src/backend/base/langflow/base/tools/flow_tool.py

Debugging and Fix for NameError
This PR addresses a NameError related to the `Vertex` and `Graph` classes not being defined. The issue arose because both imports were placed within the TYPE_CHECKING block, which prevents them from being available at runtime.
- Moved the imports for `Vertex` and `Graph` outside of the TYPE_CHECKING block to ensure they are accessible during execution.
- Added additional debugging to further investigate the underlying issue.
- Further debugging is needed to fully resolve the issue and ensure stability.

fix: NameError for Vertex and Graph Imports in Flow Tool

---

pyproject.toml
uv.lock

This PR update duckduckgo-search to the 6.3.0

chore: update duckduckgo-search to the 6.3.0

---

src/backend/base/langflow/components/models/OllamaModel.py

fix: missing 'field' argument in get_variable

---

src/frontend/src/CustomNodes/hooks/use-handle-node-class.tsx

This pull request adds the `useUpdateNodeInternals` hook from the `reactflow` library to handle changes in the node class. Previously, the node class changes were not being reflected properly in the UI. With this hook, the node internals are updated correctly, ensuring that the UI reflects the updated node class.

fix: Add useUpdateNodeInternals hook to handle node class changes
