src/backend/langflow/__main__.py
src/backend/langflow/utils/util.py
src/frontend/public/index.html
src/frontend/src/controllers/NodesServices/index.ts

Now the user can define the host and the port from the CLI and it is respected by the frontend.

version with dinamic port

---

Makefile
dev.Dockerfile
docker-compose.yml
src/frontend/dev.Dockerfile

This should fix both of these issues. 
#21 
#46

fix: new frontend dev.dockerfile

---

pyproject.toml
src/frontend/public/index.html

replace_port function is not required anymore.

Release 0.0.45

---

src/frontend/package.json
src/frontend/public/index.html
src/frontend/src/contexts/tabsContext.tsx
src/frontend/src/pages/FlowPage/components/tabsManagerComponent/index.tsx

updated some UI issues and tabs default name, also changed development proxy to work when using `make dev build=1` for development

UI updates

---

src/frontend/src/pages/FlowPage/components/DisclosureComponent/index.tsx

Updated sidebar dropdown clickable area

full dropdown clickable

---

src/backend/langflow/interface/run.py
src/frontend/package-lock.json
src/frontend/package.json
src/frontend/src/components/chatComponent/chatMessage/index.tsx
src/frontend/src/components/chatComponent/index.tsx

This PR adds ANSI to HTML conversion for colorized output in chat think. Feedback and suggestions are welcome.

colorized think with ANSI to HTML

---

src/frontend/src/components/chatComponent/index.tsx
src/frontend/src/utils.ts

fixed validation error when required fields are empty

fixed validation error

---

src/frontend/src/pages/FlowPage/components/tabComponent/index.tsx
src/frontend/src/utils.ts

Ui improvement

---

src/frontend/src/CustomNodes/GenericNode/components/parameterComponent/index.tsx
src/frontend/src/components/promptComponent/index.tsx
src/frontend/src/controllers/API/index.ts
src/frontend/src/modals/promptModal/index.tsx
src/frontend/src/types/api/index.ts

- Text area for editing prompts.
- Backend validation to ensure prompt accuracy.
- Customizable error messages in case of validation errors.
- Intuitive and user-friendly interface.

Prompt component

---

src/frontend/src/pages/FlowPage/index.tsx

This pull request adds two new features: removable edges and draggable edges. Removable edges allow users to delete unwanted connections without using the keyboard, while draggable edges enable the repositioning of connections

removable edges implemented

---

src/backend/langflow/graph/graph.py
src/backend/langflow/interface/run.py
src/backend/langflow/utils/payload.py

Fix bug when running LLM alone

---

src/backend/langflow/config.yaml
src/backend/langflow/custom/customs.py
src/backend/langflow/graph/base.py
src/backend/langflow/graph/nodes.py
src/backend/langflow/interface/custom_lists.py
src/backend/langflow/interface/importing/utils.py
src/backend/langflow/interface/listing.py
src/backend/langflow/interface/loading.py
src/backend/langflow/interface/tools/base.py
src/backend/langflow/interface/tools/constants.py
src/backend/langflow/interface/tools/util.py
src/backend/langflow/interface/types.py
src/backend/langflow/interface/utilities/base.py
src/backend/langflow/settings.py
src/backend/langflow/template/nodes.py
src/frontend/src/utils.ts

- Add utilities (Beta version)
- Add extra tools (Beta version)
- Add SQLDatabaseChain

Refactor tools

---

src/frontend/src/modals/importModal/index.tsx

Github button now in the middle.

Change button placement

---

src/backend/langflow/interface/agents/custom.py
src/backend/langflow/interface/run.py

style(langflow): fix formatting and add type hinting to custom.py and run.py files

---

pyproject.toml
src/backend/langflow/interface/tools/base.py
src/backend/langflow/template/base.py
src/backend/langflow/template/nodes.py

Fixes to nodes being displayed incorrectly.

Layout hotfixes

---

poetry.lock
pyproject.toml
src/backend/langflow/interface/agents/custom.py
src/backend/langflow/interface/agents/prebuilt.py
src/backend/langflow/interface/tools/util.py
src/backend/langflow/interface/utils.py
src/backend/langflow/template/nodes.py

Fix LangChain imports

---

src/frontend/src/components/inputComponent/index.tsx

Fix [bug#179](https://github.com/logspace-ai/langflow/issues/179#issuecomment-1518679297) by disable copy operation.

disable password copy

---

src/backend/langflow/__init__.py
src/backend/langflow/api/callback.py
src/backend/langflow/api/chat_manager.py
src/backend/langflow/api/schemas.py
src/backend/langflow/cache/base.py
src/backend/langflow/cache/manager.py
src/backend/langflow/interface/agents/custom.py
src/backend/langflow/interface/agents/prebuilt.py
src/backend/langflow/interface/loading.py
src/backend/langflow/interface/run.py
src/backend/langflow/interface/utils.py
src/backend/langflow/main.py
src/backend/langflow/template/base.py
src/backend/langflow/utils/util.py
src/frontend/src/contexts/tabsContext.tsx
src/frontend/src/utils.ts
tests/conftest.py
tests/test_agents_template.py
tests/test_cache_manager.py
tests/test_llms_template.py
tests/test_websocket.py

hot fix for update node templates

Fix auto update

---

src/frontend/src/App.tsx
src/frontend/src/CustomNodes/GenericNode/index.tsx
src/frontend/src/components/inputComponent/index.tsx
src/frontend/src/modals/NodeModal/index.tsx
src/frontend/src/modals/chatModal/index.tsx
src/frontend/src/modals/importModal/index.tsx
src/frontend/src/pages/FlowPage/components/tabsManagerComponent/index.tsx
src/frontend/src/utils.ts

some UI improvements:
- fixed password toggle button
- extend conversion to kebab case
- fixed outside click on the alert dropdown
- update logspace ui reference

UI improvements

---

docs/javascripts/mendablesearch.js
docs/stylesheets/custom.css
mkdocs.yml

Implemented Mendable search button on Docs page.

Implementation of Mendable on docs done

---

src/backend/langflow/api/endpoints.py
src/backend/langflow/api/schemas.py
src/backend/langflow/interface/run.py
src/frontend/src/contexts/tabsContext.tsx

Predict endpoint now better suited for outside use.

Better_predict

---

pyproject.toml
src/backend/langflow/interface/run.py

Intermediate steps were using Stdout but with logging this becomes an issue. This uses the steps LangChain provides which are limited and don't give the full scope. 
A better implementation will come soon.

Hotfix: Temporary fix for intermediate steps

---

src/frontend/src/contexts/tabsContext.tsx
src/frontend/src/modals/chatModal/index.tsx

This pull request addresses a small bug related to saving flows in the browser. The bug was causing failures and inconsistent behavior.

Hotfix: Save Flow Bug in Browser

---

src/backend/langflow/main.py

This pull request introduces a new /health endpoint to the backend, which allows us to monitor the application's status and ensure it is running as expected. This change is particularly important for Kubernetes (k8s) deployments, where health checks play a crucial role in managing the application lifecycle.

Add health check endpoint

---

src/backend/langflow/api/endpoints.py
src/backend/langflow/api/validate.py
src/backend/langflow/interface/run.py
src/frontend/src/CustomNodes/GenericNode/index.tsx

Improvement for validation output and visuals

Validation_fix

---

src/backend/langflow/__main__.py

Fix [lint failure](https://github.com/logspace-ai/langflow/actions/runs/5011620535/jobs/8985811820) on CI

chore: lint fix

---

src/frontend/src/contexts/tabsContext.tsx

This pull request updates the base classes and enhances the node description for improved functionality. The changes include refactoring the node update process to utilize updated base classes, improving the description for better understanding, and ensuring compatibility with the existing codebase. These updates enhance reusability and promote efficient code sharing. Please review and merge this pull request to incorporate these improvements.

node updating template, base classes and description

---

poetry.lock
pyproject.toml
src/backend/langflow/config.yaml
src/backend/langflow/graph/base.py
src/backend/langflow/interface/custom_lists.py
src/backend/langflow/interface/vector_store/base.py
src/backend/langflow/template/nodes.py
src/backend/langflow/utils/util.py

Small refactor and addition of other field formatting to allow implementation/testing of other vectorstores.

Refactor Vector stores creator to help implementing others

---

src/frontend/src/components/promptComponent/index.tsx
src/frontend/src/components/textAreaComponent/index.tsx
src/frontend/src/modals/genericModal/index.tsx

Description:
This pull request introduces the first version of a generic modal input model. The model has been developed to provide a standardized and flexible approach to modal input handling.
This is the first version of a Generic Modal that will handle all the modal callbacks in the future. For now on It's possibile to substitute the PromptModal and InputTextModal to this new one.

Add First Version of Generic Modal Input Model

---

poetry.lock
pyproject.toml
src/backend/langflow/config.yaml
src/backend/langflow/template/frontend_node/llms.py

🚀 feat(config.yaml): add HuggingFaceEmbeddings to embeddings
The Jina and sentence-transformers dependencies were added to the project to improve the functionality of the application. The HuggingFaceEmbeddings was added to the embeddings in the config.yaml file to improve the quality of the embeddings used in the application.
Closes #375

Activating HuggingFaceEmbeddings, adding Jina deps

---

src/frontend/src/components/promptComponent/index.tsx
src/frontend/src/components/textAreaComponent/index.tsx
src/frontend/src/modals/genericModal/index.tsx
src/frontend/src/utils.ts

This pull request resolves a bug related to error handling when components attempt to call the same modals within different flows. The issue occurs due to a lack of proper validation and error handling in the existing codebase. This bugfix aims to provide a comprehensive solution to mitigate the problem and ensure a smoother user experience.

Error Handling for Modal Calls in Different Flows Prompt/Text

---

src/frontend/src/CustomNodes/GenericNode/index.tsx
src/frontend/src/components/chatComponent/chatTrigger/index.tsx
src/frontend/src/modals/NodeModal/index.tsx
src/frontend/src/pages/FlowPage/components/extraSidebarComponent/index.tsx
src/frontend/src/utils.ts
src/frontend/tailwind.config.js

Description:
This pull request implements several UI feature enhancements to improve the user experience. The changes include title casing on names and titles, fixing and changing icons, and adding a cursor pointer on the chat interface.
Changes Made:
Title case on names and titles: Modified the code to convert names and titles to title case. This ensures consistent capitalization and enhances readability throughout the application.
Fixing/Changing icons: Replaced outdated or inconsistent icons with updated versions to provide a more visually appealing and cohesive user interface. 
Cursor on chat: Added a cursor pointer to the chat interface to indicate interactivity and enhance user engagement. The cursor appears when hovering over the chat area, making it clear that the chat is …

Pull Request: UI Feature Enhancements

---

src/frontend/src/components/ExtraSidebarComponent/index.tsx
src/frontend/src/pages/FlowPage/components/extraSidebarComponent/index.tsx

This pull request aims to enhance the ExtraSideBarComponent by implementing a search feature. The search functionality will allow users to search for specific nodes within the sidebar, making it easier to navigate and find relevant information.
Modified ExtraSideBarComponent to include a search input field.
Implemented search logic to filter nodes based on user input.
Added a search results display section to show the filtered nodes.
Integrated search functionality with the existing node navigation.
Updated relevant tests to ensure proper functionality and coverage.
Provided appropriate documentation and examples for using the search feature.

Adding search functionality to ExtraSideBarComponent

---

src/frontend/src/modals/chatModal/index.tsx

fix(chatModal/index.ts) updated validation condition for required properties of nodes, to allow False values to be accepted

---

src/frontend/src/modals/chatModal/chatMessage/index.tsx
src/frontend/src/modals/chatModal/index.tsx

This pull request adds a new feature to the chat interface, specifically targeting the chat icon. The proposed feature makes the chat icon animate and move in correspondence with the last message generated by the AI. This enhancement aims to provide a visually engaging experience and draw the user's attention to the latest AI response.

Add Chat Icon Animation to the Last AI Message

---

src/frontend/src/index.css

This pull request introduces a new feature that allows users to change the mouse cursor on Canva's React Flow. By updating the CSS and JavaScript code, the cursor behavior can be modified to provide a customized experience for users.
The ability to change the mouse cursor provides a way to enhance user interaction and personalize the user experience within Canva's React Flow. This feature can be particularly useful for applications or websites that require specific cursor styles to match the overall design or functionality.

Changing the mouse cursor on Canva's React Flow

---

src/frontend/src/contexts/tabsContext.tsx

This improves the user experience for issues like #283.

Surface an error message when a flow has an unknown node type.

---

src/backend/langflow/config.yaml
src/backend/langflow/custom/customs.py
src/backend/langflow/interface/loading.py
src/backend/langflow/interface/tools/constants.py
src/backend/langflow/interface/tools/custom.py
src/backend/langflow/template/frontend_node/llms.py
src/backend/langflow/template/frontend_node/tools.py
tests/test_custom_types.py
tests/test_llms_template.py

🚀 feat(loading.py): add support for PythonFunction node type
🚀 feat(constants.py): add PythonFunction to CUSTOM_TOOLS
🚀 feat(custom.py): add PythonFunction class
🚀 feat(frontend_node/tools.py): add PythonFunctionNode class
🧪 test(test_custom_types.py): add test for PythonFunction class
🧪 test(test_llms_template.py): comment out tests for AzureOpenAI and AzureChatOpenAI
The changes add support for a new node type, PythonFunction, which allows users to define a Python function to be executed. The node type is added to CUSTOM_NODES in customs.py, and support for the node type is added to loading.py. The node type is also added to CUSTOM_TOOLS in constants.py, and the PythonFunction class is added to custom.py. The PythonFunctionNode class is added to frontend_node/tools.py. Tests for the new …

🚀 feat(customs.py): re-add PythonFunction to CUSTOM_NODES

---

Makefile
poetry.lock
pyproject.toml
src/backend/langflow/__main__.py
src/frontend/src/App.tsx
src/frontend/src/contexts/tabsContext.tsx
src/frontend/src/controllers/API/index.ts

When the CLI starts now we are greeted with a better looking text.
🚀 feat(__main__.py): add optional open_browser argument to serve function to specify whether to open browser after starting server
The serve function now accepts an optional path argument to specify the path to the frontend directory containing build files. This is useful for development purposes only. The function also accepts an optional open_browser argument to specify whether to open the browser after starting the server. This is useful when running the server locally.

Better serrver start

---

poetry.lock
pyproject.toml
src/backend/langflow/__main__.py

Fallback to previous launch if on Windows.
Fixes #502

Fix to launching on Windows

---

Dockerfile
pyproject.toml

this will help deploy the langflow on render using docker.

dockerfile update

---

Makefile
README.md
poetry.lock
pyproject.toml
src/backend/langflow/graph/graph/base.py
src/backend/langflow/processing/process.py
src/frontend/src/components/headerComponent/index.tsx
src/frontend/src/constants.tsx
src/frontend/src/controllers/API/index.ts
tests/test_loading.py

This Pull Request includes several code improvements, refactoring, feature additions, and documentation updates mainly focused on enhancing the functionality and maintainability of the codebase.
- **Commit (5ea20aa) by @ogabrielluiz**: Unnecessary indentation in the `getPythonCode` function within `constants.tsx` has been removed to improve code readability.
- **Commit (6886828) by @ogabrielluiz**: 
- Changed the `load_flow_from_json` function signature in `process.py` to accept either a JSON file path or a JSON object.
- Updated the import statement for `Chain` in `base.py` to be more explicit by importing it from `langchain.chains.base` instead of `langflow.graph.vertex.types`.
- Removed a print statement from the `process_tweaks` function in `process.py`.
- Added an optional `tweaks` …

Small bugfixes and improvements

---

src/frontend/src/pages/FlowPage/components/PageComponent/index.tsx

increase the zoom out limit of the flow

zoom out 10x bigger

---

poetry.lock
pyproject.toml
src/backend/langflow/api/v1/flows.py

Fix remove api key condition

---

pyproject.toml
src/backend/langflow/template/frontend_node/documentloaders.py
src/frontend/src/components/headerComponent/index.tsx
src/frontend/src/controllers/API/index.ts
src/frontend/src/modals/chatModal/chatInput/index.tsx

The version number has been updated from 0.1.6 to 0.1.7 to reflect the changes made in the package. This is a chore commit as it does not add any new features or fix any bugs, but rather updates the version number.

🔖 chore(pyproject.toml): bump version to 0.1.7

---

src/frontend/package-lock.json
src/frontend/src/CustomNodes/GenericNode/components/parameterComponent/index.tsx
src/frontend/src/components/headerComponent/components/menuBar/index.tsx
src/frontend/src/components/ui/card.tsx
src/frontend/src/pages/FlowPage/components/extraSidebarComponent/index.tsx
src/frontend/src/utils.ts

🐛 fix(parameterComponent): fix key prop warning by generating rando key using new function getRandomKeyByssmm
✨ feat(parameterComponent): add support for dynamic rendering of parameter component by grouping data by family
🐛 fix(menuBar): fix DropdownMenuTrigger component by adding asChild prop
🐛 fix(card.tsx): change p tag to div tag to fix accessibility issue
🐛 fix(extraSidebarComponent): fix key prop warning by adding key prop to Tooltip component
✨ feat(utils.ts): add new function getRandomKeyByssmm to generate random keys for components

General BugFixes

---

src/frontend/src/pages/FlowPage/components/extraSidebarComponent/index.tsx

🐛 fix(extraSidebarComponent): fix key prop in DisclosureComponent and TooltipComponent to use unique values

Fix key prop in DisclosureComponent and TooltipComponent to use unique values

---

src/backend/langflow/chat/config.py
src/backend/langflow/chat/manager.py
src/backend/langflow/interface/initialize/loading.py
src/backend/langflow/interface/utils.py
src/backend/langflow/template/field/base.py
src/backend/langflow/template/frontend_node/constants.py
src/backend/langflow/template/frontend_node/llms.py
src/frontend/src/CustomNodes/GenericNode/components/parameterComponent/index.tsx
src/frontend/src/CustomNodes/GenericNode/index.tsx
src/frontend/src/types/components/index.ts

The `info` field is added to the `TemplateField` class to provide additional information about the field. The `OPENAI_API_BASE_INFO` constant is added to the `constants.py` file to provide information about the base URL of the OpenAI API and how it can be changed to use other APIs like Prem and LocalAI. The `info` field is set to `OPENAI_API_BASE_INFO` for the `openai_api_base` field in the `LLMFrontendNode` class in `llms.py`.

Added info parameter to fields

---

pyproject.toml

The package version has been updated from 0.2.6 to 0.2.7. This change is made to reflect the latest changes and improvements in the package.

🔖 chore(pyproject.toml): update package version to 0.2.7

---

src/backend/langflow/__main__.py
src/backend/langflow/config.yaml
src/backend/langflow/database/base.py
src/backend/langflow/settings.py
src/backend/langflow/template/frontend_node/documentloaders.py
src/frontend/src/App.tsx
src/frontend/src/modals/chatModal/index.tsx

Adding PyPDFDirectoryLoader and improving fields of DirectoryLoader

Add PyPDFDirectoryLoader and improving DirectoryLoader

---

src/frontend/src/components/codeAreaComponent/index.tsx
src/frontend/src/components/dropdownComponent/index.tsx
src/frontend/src/components/floatComponent/index.tsx
src/frontend/src/components/inputComponent/index.tsx
src/frontend/src/components/inputFileComponent/index.tsx
src/frontend/src/components/inputListComponent/index.tsx
src/frontend/src/components/intComponent/index.tsx
src/frontend/src/components/promptComponent/index.tsx
src/frontend/src/components/textAreaComponent/index.tsx
src/frontend/src/constants.tsx
src/frontend/src/index.css
src/frontend/src/modals/ApiModal/index.tsx
src/frontend/src/modals/chatModal/chatInput/index.tsx
src/frontend/src/modals/genericModal/index.tsx
src/frontend/src/modals/textAreaModal/index.tsx
src/frontend/src/pages/FlowPage/components/extraSidebarComponent/index.tsx

This pull request introduces a new feature that enhances our CSS architecture by adding support for @layer components. With this feature, we can now organize and manage our CSS more efficiently, making it easier to work with and maintain.

Implementing @layer components for CSS

---

src/frontend/src/CustomNodes/GenericNode/index.tsx
src/frontend/src/constants.tsx
src/frontend/src/index.css
src/frontend/src/pages/FlowPage/components/extraSidebarComponent/index.tsx
src/frontend/src/pages/MainPage/index.tsx

Improves code verbosity and organization of Tailwind classes.

Add style constants to index.css file

---

src/frontend/src/index.css
src/frontend/src/pages/FlowPage/components/extraSidebarComponent/index.tsx

Improves code verbosity and organization of Tailwind classes.

Add extra side bar constants classes

---

.env.example
README.md
poetry.lock
pyproject.toml
src/backend/langflow/__init__.py
src/backend/langflow/__main__.py
src/backend/langflow/database/base.py
src/backend/langflow/interface/utils.py
src/backend/langflow/lcserve.py
src/backend/langflow/main.py
src/backend/langflow/settings.py

Added more logging messages and options in the CLI.

Added better CLI docs in README and bumps langchain-serve

---

src/backend/langflow/__main__.py

The load_params() function is added to load the parameters from the environment variables. This allows for more flexibility and configurability of the application by allowing the parameters to be set via environment variables.

🔧 chore(__main__.py): add load_params() function to load parameters from environment variables

---

src/backend/langflow/api/v1/base.py
src/frontend/package-lock.json
src/frontend/package.json
src/frontend/src/components/ShadTooltipComponent/index.tsx
src/frontend/src/constants.tsx
src/frontend/src/modals/codeAreaModal/index.tsx
src/frontend/src/modals/genericModal/index.tsx
src/frontend/src/types/components/index.ts
src/frontend/src/utils.ts

This pull request introduces a new feature that implements a prompt modal with variables, enhancing the user experience and providing more flexibility in generating dynamic prompts. The following changes have been made:
Added a new prompt modal component: A new React component, PromptModal, has been created to handle the display and management of the prompt modal. This component is responsible for rendering the modal UI, capturing user input, and providing access to the selected variables.
Variable selection functionality: The PromptModal component includes a variable selector, allowing users to choose from a list of available variables. These variables are dynamically populated based on the context of the application and can be customized as needed.

Implementing Prompt Modal with Variables

---

src/frontend/src/CustomNodes/GenericNode/components/parameterComponent/index.tsx
src/frontend/src/CustomNodes/GenericNode/index.tsx
src/frontend/src/components/textAreaComponent/index.tsx
src/frontend/src/constants.tsx
src/frontend/src/modals/ApiModal/index.tsx
src/frontend/src/modals/genericModal/index.tsx
src/frontend/src/utils.ts
src/frontend/tailwind.config.js

🐛 fix(parameterComponent): set disabled prop to false in TextAreaComponent to enable editing
✨ feat(GenericNode): import Zap icon from lucide-react to use in validation status tooltip
🐛 fix(textAreaComponent): import classNames from utils to fix missing import error
🐛 fix(constants): update HIGHLIGH_CSS constant to add overflow-y-hidden and max-w-[75vw] classes
🐛 fix(ApiModal): add condition to check if tweak.current exists before calling startTweaks()
✨ feat(ApiModal): import Variable icon from lucide-react to use in input variables section
🐛 fix(genericModal): import Variable icon from lucide-react to use in input variables section
🐛 fix(utils): add newline character to INVALID_CHARACTERS array
🐛 fix(tailwind.config.js): set height property to "8px" for scrollbar in custom-scroll class

General UI Fixes

---

src/frontend/src/components/inputComponent/index.tsx

Fix characters passing through password icon

---

src/frontend/src/icons/HuggingFace/index.tsx
src/frontend/src/utils.ts

HugginFaceIcon -> HuggingFaceIcon

🐛 fix(utils.ts): fix typo in utils.ts

---

src/backend/langflow/graph/graph/base.py
src/frontend/src/constants.tsx
src/frontend/src/contexts/tabsContext.tsx
src/frontend/src/index.css
src/frontend/src/modals/formModal/chatMessage/index.tsx
src/frontend/src/modals/genericModal/index.tsx

This pull request includes bug fixes and style updates for the repository. The changes made in this pull request address the following issues:
🎨 style(index.css): update color variables for chat bot and user icon
The color variables for the chat bot and user icons have been updated in the index.css file to improve the visual appearance.
🔧 chore(constants.tsx): add constant MAX_WORDS_HIGHLIGHT with a value
🐛 fix(index.css): swap colors for chat bot and chat user icons to match design

Bug Fixes and Style Updates

---

docs/docs/guides/chatprompttemplate_guide.mdx
docs/docs/guides/loading_document.mdx
docs/sidebars.js
docs/src/theme/Footer.js

This PR adds the docs for the release of the improved prompt and chat experience.

Adding docs for release

---

poetry.lock
pyproject.toml
src/frontend/src/constants.tsx
src/frontend/src/controllers/API/index.ts
src/frontend/src/modals/formModal/chatMessage/index.tsx
src/frontend/src/modals/genericModal/index.tsx

Fixes langflow_examples URL and TWEAKS  being shown incorrectly in the Code export section.

Hotfix: 0.3.1

---

src/frontend/package-lock.json
src/frontend/src/components/AccordionComponent/index.tsx
src/frontend/src/components/ui/accordion.tsx
src/frontend/src/index.css
src/frontend/src/modals/ApiModal/index.tsx
src/frontend/src/modals/formModal/chatMessage/index.tsx
src/frontend/src/modals/formModal/index.tsx
src/frontend/src/modals/genericModal/index.tsx
src/frontend/src/types/components/index.ts
src/frontend/tailwind.config.js

This pull request aims to refactor the Accordion Component to enable its shared usage by both the formModal (chat) component and the Tweaks component. By making the necessary modifications, we can eliminate code duplication and improve maintainability across the application.

Refactor Accordion Component for Shared Usage

---

src/frontend/src/components/AccordionComponent/index.tsx
src/frontend/src/components/ui/accordion.tsx
src/frontend/src/index.css
src/frontend/src/modals/formModal/chatMessage/index.tsx
src/frontend/src/modals/genericModal/index.tsx
src/frontend/tailwind.config.js

This pull request addresses a bug related to the open/close animation in the accordion component. Currently, there is a glitch where the animation stutters or fails to complete when expanding or collapsing accordion sections. This bug fix aims to resolve the issue and provide smooth and consistent animations.

Accordion Open/Close Animation Bug Fix

---

src/frontend/src/CustomNodes/GenericNode/components/parameterComponent/index.tsx
src/frontend/src/components/floatComponent/index.tsx
src/frontend/src/components/headerComponent/index.tsx
src/frontend/src/components/inputComponent/index.tsx
src/frontend/src/components/inputFileComponent/index.tsx
src/frontend/src/components/intComponent/index.tsx
src/frontend/src/components/textAreaComponent/index.tsx
src/frontend/src/components/toggleComponent/index.tsx
src/frontend/src/modals/codeAreaModal/index.tsx
src/frontend/src/pages/CommunityPage/index.tsx
src/frontend/src/pages/FlowPage/components/extraSidebarComponent/index.tsx
src/frontend/src/pages/FlowPage/index.tsx
src/frontend/src/pages/MainPage/index.tsx

Add better inline code documentation

Improve code documentation

---

src/frontend/src/CustomNodes/GenericNode/components/parameterComponent/index.tsx
src/frontend/src/components/chatComponent/chatTrigger/index.tsx
src/frontend/src/components/headerComponent/index.tsx
src/frontend/src/components/promptComponent/index.tsx
src/frontend/src/components/textAreaComponent/index.tsx
src/frontend/src/constants/constants.ts
src/frontend/src/constants/enums.ts
src/frontend/src/modals/ApiModal/index.tsx
src/frontend/src/modals/EditNodeModal/index.tsx
src/frontend/src/modals/NodeModal/index.tsx
src/frontend/src/modals/codeAreaModal/index.tsx
src/frontend/src/modals/exportModal/index.tsx
src/frontend/src/modals/flowSettingsModal/index.tsx
src/frontend/src/modals/formModal/chatMessage/codeBlock/index.tsx
src/frontend/src/modals/formModal/chatMessage/index.tsx
src/frontend/src/modals/formModal/index.tsx
src/frontend/src/modals/genericModal/index.tsx
src/frontend/src/modals/importModal/index.tsx
src/frontend/src/pages/MainPage/index.tsx
src/frontend/src/types/components/index.ts
src/frontend/src/utils/styleUtils.ts
src/frontend/src/utils/utils.ts

Remove functions, enums, icons and interfaces from the frontend/src/constants/constans.ts file

Refactor constants file

---

pyproject.toml
src/backend/langflow/template/frontend_node/constants.py

Added google_cse_id on GoogleSearchAPIWrapper component.
Updated list of maintainers with @igorrCarvalho , @carlosrcoelho and @rodrigosnader

Hotfix: 0.3.3

---

src/frontend/src/CustomNodes/GenericNode/components/parameterComponent/index.tsx
src/frontend/src/modals/codeAreaModal/index.tsx
src/frontend/src/utils/utils.ts

This pull request introduces a new feature that implements the capability of displaying custom tooltips for custom components in our application. Custom tooltips provide enhanced user experience by offering contextual information and guidance when interacting with various components.

Implementing Custom Tooltips for Custom Components Feature

---

src/backend/langflow/config.yaml
src/backend/langflow/template/frontend_node/memories.py

Motorhead memory can be used remotely or locally.

Adds motorhead memory

---

docs/docs/guides/loading_document.mdx
docs/static/CNAME
poetry.lock
pyproject.toml
src/backend/langflow/api/utils.py
src/backend/langflow/api/v1/endpoints.py
src/backend/langflow/interface/initialize/vector_store.py
src/backend/langflow/interface/types.py
src/backend/langflow/template/frontend_node/utilities.py
src/backend/langflow/template/frontend_node/vectorstores.py
src/frontend/src/modals/ApiModal/index.tsx

This PR adds more settings to Chroma and allows for connection to remote Chroma instances.

Adds more settings to ChromaDB and fixes Chat not being runnable without chat variables

---

src/backend/langflow/api/v1/chat.py
src/backend/langflow/chat/manager.py
src/backend/langflow/chat/utils.py
src/backend/langflow/interface/initialize/vector_store.py
src/frontend/src/components/chatComponent/buildTrigger/index.tsx
src/frontend/src/components/chatComponent/index.tsx
src/frontend/src/modals/formModal/index.tsx
src/frontend/src/utils/utils.ts

Reverts logspace-ai/langflow#727

Revert "Fixes flows without input_keys not being runnable"

---

src/frontend/package-lock.json
src/frontend/package.json
src/frontend/src/App.tsx
src/frontend/src/components/PaginatorComponent/index.tsx
src/frontend/src/components/genericIconComponent/index.tsx
src/frontend/src/components/ui/select.tsx
src/frontend/src/controllers/API/api.tsx
src/frontend/src/modals/ConfirmationModal/index.tsx
src/frontend/src/modals/UserManagementModal/index.tsx
src/frontend/src/modals/baseModal/index.tsx
src/frontend/src/pages/AdminPage/LoginPage/index.tsx
src/frontend/src/pages/AdminPage/index.tsx
src/frontend/src/routes.tsx
src/frontend/src/style/applies.css
src/frontend/src/types/components/index.ts
src/frontend/src/utils/styleUtils.ts

This pull request introduces a new admin login page to the application, enhancing the user management experience by implementing a user table with pagination. This will allow administrators to efficiently manage users, edit passwords, delete accounts, and apply filters through a user-friendly table interface.
/login/admin - Just click login

Add Admin Login Page with User Management

---

src/frontend/src/components/headerComponent/index.tsx
src/frontend/src/style/applies.css

🎉  Introducing the Waitlist Button Integration
This PR introduces a fantastic new addition, the **Waitlist Button Integration** on our platform's header. 🎈🚀
👉 **Instant Access:** Located right on the header, the Waitlist Button provides a direct gateway to our exclusive waitlist website. Now, you can secure your spot for upcoming releases with just a click.

add waitlist button on header

---

src/backend/langflow/interface/custom/custom_component.py
src/backend/langflow/interface/custom/directory_reader.py
src/backend/langflow/interface/initialize/loading.py

Improves error handling and display for Custom Components.

Improves CustomComponents Errors

---

src/frontend/src/components/EditFlowSettingsComponent/index.tsx
src/frontend/src/modals/exportModal/index.tsx
src/frontend/src/modals/flowSettingsModal/index.tsx

Export modal not changing name and description. Fixed.

Fixed bug on Export Modal

---

poetry.lock
src/backend/langflow/api/v1/endpoints.py
src/backend/langflow/settings.py

The issue was related to how the CLI adds Components Path that are already in the list and they are processed two times because of that.

Fix Duplicated CustomComponents

---

src/frontend/src/App.tsx
src/frontend/src/contexts/alertContext.tsx
src/frontend/src/contexts/index.tsx
src/frontend/src/contexts/typesContext.tsx
src/frontend/src/style/applies.css

Added spinning wheel when all components are still loading.

Added spinning wheel when /all is loading

---

docs/src/theme/Footer.js

Mendable authentication adjusted.

fix mendable

---

src/frontend/src/components/codeTabsComponent/index.tsx

This pull request addresses an issue with the non-functional tweaks section in the codebase. The tweaks section is a crucial part of our application, allowing users to customize their experience and make small adjustments to settings. However, due to a bug in the existing code, the tweaks section has been rendered ineffective and users have been unable to modify settings as intended.

Fix: Tweak section and tweaks inputs not working

---

src/frontend/src/App.tsx
src/frontend/src/components/fetchErrorComponent/index.tsx
src/frontend/src/components/genericIconComponent/index.tsx
src/frontend/src/components/loadingComponent/index.tsx
src/frontend/src/constants/constants.ts
src/frontend/src/contexts/typesContext.tsx
src/frontend/src/types/components/index.ts
src/frontend/src/types/typesContext/index.ts
src/frontend/src/utils/styleUtils.ts

This pull request addresses an issue with the retry mechanism for failed requests within a loop. The current implementation lacks proper handling of failed requests, leading to potential data loss and inconsistent behavior. This bugfix aims to improve the retry logic and ensure that requests are appropriately retried when they fail within a loop.

Bugfix - Retry Mechanism for Failed Requests in Loop

---

poetry.lock
pyproject.toml
src/backend/langflow/components/retrievers/MetalRetriever.py

🔀 merge(MetalRetriever.py): merge changes from metal_sdk/metal to langchain/schema to keep codebase up to date
🐛 fix(MetalRetriever.py): change BaseRetriever import from langchain.schema.retriever to langchain.schema to match updated codebase
✨ feat(MetalRetriever.py): add error handling to MetalRetriever build method to raise ValueError if connection to Metal API fails

Adds Metal Retriever Component

---

src/backend/langflow/components/llms/HuggingFaceEndpoints.py

Added component to use an LLM model from Hugging Face Inference API.

Hg endpoints

---

src/frontend/src/components/inputListComponent/index.tsx

🐛 fix(inputListComponent): fix type error when value is a string by converting it to an array

Bugfix - InputListComponent expect an array as Input()

---

poetry.lock
pyproject.toml
src/backend/langflow/__main__.py
src/backend/langflow/api/v1/base.py
src/backend/langflow/api/v1/chat.py
src/backend/langflow/api/v1/users.py
src/backend/langflow/main.py
src/backend/langflow/services/auth/utils.py
src/backend/langflow/services/base.py
src/backend/langflow/services/database/manager.py
src/backend/langflow/services/manager.py
src/backend/langflow/services/settings/auth.py
src/backend/langflow/services/settings/manager.py
src/backend/langflow/services/settings/utils.py
tests/test_user.py

🔧 chore(manager.py): remove default superuser if auto_login is enabled during teardown to ensure clean database state

Adds teardown logic for database and other services

---

src/backend/langflow/alembic/versions/260dbcc8b680_adds_tables.py
src/frontend/src/controllers/API/index.ts

added missing backslashes to api key request definition and bugfix to migration script

---

Makefile
src/backend/langflow/api/v1/base.py
src/backend/langflow/api/v1/chat.py
src/backend/langflow/api/v1/endpoints.py
src/backend/langflow/api/v1/flows.py
src/backend/langflow/api/v1/login.py
src/backend/langflow/api/v1/users.py
src/backend/langflow/api/v1/validate.py
src/backend/langflow/services/utils.py
src/frontend/src/components/DropdownButtonComponent/index.tsx
src/frontend/src/contexts/tabsContext.tsx
src/frontend/src/pages/MainPage/index.tsx
src/frontend/src/types/components/index.ts

Services are now passed to the endpoints through dependency injection.

Improves endpoint dependency usage

---

Makefile

bugfix: updated Makefile to use langflow run

---

src/backend/langflow/api/v1/chat.py
src/frontend/src/components/codeTabsComponent/index.tsx
src/frontend/src/components/headerComponent/index.tsx
src/frontend/src/components/ui/dialog.tsx
src/frontend/src/contexts/darkContext.tsx

This related to lint error for https://github.com/logspace-ai/langflow/pull/879

Fix lint error

---

src/backend/langflow/__main__.py
src/backend/langflow/interface/utils.py
src/backend/langflow/services/plugins/langfuse.py
src/backend/langflow/settings.py
src/frontend/src/components/inputListComponent/index.tsx

🐛 fix(utils.py): handle ImportError when importing cache class and log a warning message
🔧 chore(settings.py): change default value of CACHE option to None for better flexibility
Fixes #880

🔧 chore(__main__.py): change default value of cache option to None for better flexibility

---

src/backend/langflow/api/v1/users.py
src/backend/langflow/components/textsplitters/LanguageRecursiveTextSplitter.py
src/backend/langflow/components/textsplitters/RecursiveCharacterTextSplitter.py
src/backend/langflow/services/database/models/user/crud.py
src/backend/langflow/services/plugins/langfuse.py
src/frontend/src/CustomNodes/GenericNode/components/parameterComponent/index.tsx
src/frontend/src/CustomNodes/GenericNode/index.tsx

Fixed https://github.com/logspace-ai/langflow/issues/904
Fixed https://github.com/logspace-ai/langflow/issues/916
/cc @ogabrielluiz

Fixed Lint error and no module error

---

src/backend/langflow/interface/types.py
src/frontend/src/modals/codeAreaModal/index.tsx
src/frontend/src/style/classes.css

When adding List:True on some field without “, the application was crashing.
An error handler on back end was added and some error presentation was improved on frontend.

Bug fix on error detail of customComponent code - Release

---

src/frontend/src/components/ui/dialog.tsx
src/frontend/src/modals/codeAreaModal/index.tsx

🔧 chore(codeAreaModal/index.tsx): add additional class names to CodeMirror component for better control and customization

Bugfix on DEV - Copy and Paste on CodeEditModal

---

src/backend/langflow/services/plugins/langfuse.py

🔧 chore(langfuse.py): add support for configurable Langfuse host to improve flexibility and maintainability

---

Makefile
poetry.lock
pyproject.toml
tests/test_llms_template.py

Bumps Langchain to 0.271 for now.

Bump version to 0.4.21

---

src/frontend/src/CustomNodes/GenericNode/components/parameterComponent/index.tsx
src/frontend/src/CustomNodes/GenericNode/index.tsx
src/frontend/src/contexts/typesContext.tsx
src/frontend/src/pages/FlowPage/components/PageComponent/index.tsx
src/frontend/src/pages/FlowPage/components/extraSidebarComponent/index.tsx
src/frontend/src/types/typesContext/index.ts

This branch implements the edge filtering feature.

Filter Menu Components on Click Edge

---

src/backend/langflow/interface/custom/custom_component.py
src/backend/langflow/interface/types.py
src/backend/langflow/services/settings/auth.py

🐛 fix(types.py): re-raise HTTPException when encountered during building langchain template custom component to propagate the error and provide more informative error message

Fixes type hint "prompt"

---

src/frontend/src/contexts/tabsContext.tsx
src/frontend/src/pages/FlowPage/components/PageComponent/index.tsx
src/frontend/src/types/tabs/index.ts

This pull request introduces the "Auto Save Flow" feature into the project. The primary goal of this feature is to provide automatic saving of user data and progress, enhancing the overall user experience by reducing the risk of data loss due to accidental refreshes or browser crashes.
In this PR, the following changes have been made:
1. Added a new "Auto Save" to save the flow every 30 seconds.
2. Implemented client-side logic to periodically save flow.

Feature - Auto Save Flow

---

Makefile
src/backend/langflow/__main__.py
src/backend/langflow/interface/custom/custom_component.py
src/backend/langflow/services/database/manager.py
src/backend/langflow/services/task/manager.py
src/backend/langflow/utils/logger.py

🔧 chore(__main__.py): update Typer configuration to treat no arguments as help to improve usability
🔧 chore(__main__.py): update docstring for run() function to improve clarity
🔧 chore(__main__.py): update docstring for superuser() function to improve clarity
🔧 chore(__main__.py): update migration() function to default to test mode
🔧 chore(manager.py): remove unnecessary logging of database URL in run_migrations() function
🔧 chore(manager.py): add missing import statement for logger in check_celery_availability() function
🔧 chore(manager.py): update configure() function to be called in check_celery_availability() function
🔧 chore(logger.py): update configure() function to use environment variable for log level if available
🔧 chore(logger.py): update configure() function to use default log …

Make Celery check less verbose

---

src/backend/langflow/api/v1/chat.py
src/backend/langflow/services/cache/utils.py

🔧 chore(utils.py): add update_build_status function to update build status in cache_service dictionary

🐛 fix(chat.py): replace direct assignment with update_build_status function to update build status in cache_service dictionary

---

src/backend/langflow/services/chat/manager.py
src/frontend/src/contexts/authContext.tsx
src/frontend/src/modals/EditNodeModal/index.tsx
src/frontend/src/modals/formModal/index.tsx
src/frontend/src/pages/AdminPage/LoginPage/index.tsx
src/frontend/src/pages/loginPage/index.tsx

fix web socket and some chat bugs

Fix ws bug 

---

src/backend/langflow/services/database/utils.py
src/backend/langflow/services/settings/auth.py

🐛 fix(utils.py): handle exception when running migrations to ignore if migrations already ran
✨ feat(auth.py): set AUTO_LOGIN to True to enable automatic login as a super user

🐛 fix(utils.py): handle exception when creating DB and tables to ignore if tables already exist

---

src/backend/langflow/services/utils.py

🔧 chore(utils.py): add type hinting to the session parameter in the get_or_create_super_user function to improve code readability and maintainability
🔧 chore(utils.py): add type hinting to the session parameter in the setup_superuser function to improve code readability and maintainability

Fixes super user creation

---

poetry.lock
pyproject.toml
src/backend/langflow/api/v1/chat.py
src/backend/langflow/interface/initialize/utils.py
src/backend/langflow/interface/utilities/base.py
src/backend/langflow/interface/wrappers/base.py
src/backend/langflow/services/database/manager.py
tests/test_setup_superuser.py

✨ feat(manager.py): improve table creation process by checking if tables already exist before creating them

Fixes table creation

---

pyproject.toml
src/backend/langflow/api/v1/endpoints.py
src/backend/langflow/services/task/backends/anyio.py
src/backend/langflow/services/task/backends/celery.py
src/backend/langflow/services/task/manager.py

✨ feat(anyio.py): add name attribute to AnyIOBackend class to identify the backend by name
✨ feat(celery.py): add name attribute to CeleryBackend class to identify the backend by name
✨ feat(manager.py): add backend_name property to TaskService class to get the name of the backend

🐛 fix(endpoints.py): replace backend type string with backend name to improve readability and semantics

---

.github/workflows/ci.yml
.github/workflows/lint.yml
.github/workflows/test.yml

🔧 chore(ci.yml): update CI configuration to include specific paths for push and pull_request events

Makes workflows run only when needed

---

src/frontend/src/components/DropdownButtonComponent/index.tsx
src/frontend/src/components/floatComponent/index.tsx
src/frontend/src/components/keypairListComponent/index.tsx
src/frontend/src/components/toggleShadComponent/index.tsx
src/frontend/src/modals/EditNodeModal/index.tsx
src/frontend/src/pages/FlowPage/components/PageComponent/index.tsx
src/frontend/src/pages/FlowPage/components/extraSidebarComponent/index.tsx
src/frontend/src/pages/FlowPage/components/nodeToolbarComponent/index.tsx
src/frontend/src/types/components/index.ts
src/frontend/tests/keypair.spec.ts

🔧 fix(DropdownButtonComponent): add id attribute to Button component to improve accessibility and testing capabilities
🔧 fix(floatComponent): add id attribute to Input component to improve accessibility and testing capabilities
🔧 fix(keypairListComponent): add id attribute to Input components to improve accessibility and testing capabilities
🔧 fix(keypairListComponent): add id attribute to Plus and Minus buttons to improve accessibility and testing capabilities
🔧 fix(toggleShadComponent): add id attribute to Switch component to improve accessibility and testing capabilities
🔧 fix(EditNodeModal): add id attribute to ToggleShadComponent component to improve accessibility and testing capabilities
🔧 fix(PageComponent): add id attribute to div element to improve accessibility and testing …

Test Components

---

src/backend/langflow/template/frontend_node/base.py
src/backend/langflow/template/frontend_node/formatter/field_formatters.py
src/backend/langflow/utils/util.py
src/frontend/src/CustomNodes/GenericNode/components/parameterComponent/index.tsx
src/frontend/src/contexts/tabsContext.tsx
src/frontend/src/pages/MainPage/index.tsx

Fix Filter edges and unknown handle showing up when node are minimized

Minimize node fixes

---

src/backend/langflow/processing/base.py

Fixed https://github.com/logspace-ai/langflow/issues/1042

added trace name

---

src/frontend/src/pages/ViewPage/index.tsx
src/frontend/src/routes.tsx

- Implemented route view/dark to display the flows in Dark Mode automatically

Feature: Dark Mode View

---

src/backend/langflow/components/vectorstores/Vectara.py

does not require embedding
Adding specific "source" value with new version of Vectara constructor in LangChain

update of Vectara component

---

src/frontend/tests/onlyFront/assets/collection.json
src/frontend/tests/onlyFront/assets/flow.json
src/frontend/tests/onlyFront/dragAndDrop
src/frontend/tests/onlyFront/dragAndDrop.spec.ts

create drag and drop flow and collection test  files

Drag and drop test

---

src/frontend/src/utils/reactflowUtils.ts

fix(reactflowUtils.t): modify convertValuesToNumbers function to correctly handle values that are numbers represented as strings
feat(reactflowUtils.ts): add check to convertValuesToNumbers function to only convert values that are valid numbers represented as strings

Fix no space no keyPairList

---

src/frontend/src/utils/reactflowUtils.ts

fix(reactflowUtils.ts): modify convertValuesToNumbers function to correctly handle values that are numbers represented as strings
feat(reactflowUtils.ts): add check to convertValuesToNumbers function to only convert values that are valid numbers represented as strings

RELEASE - Bugfix - Allowing space on keypairlist (dict) value

---

src/backend/langflow/interface/agents/custom.py

Hello!
Thank you for your project 
Fixes https://github.com/logspace-ai/langflow/issues/557

bugfix: patched csv agent

---

src/frontend/src/pages/FlowPage/components/DisclosureComponent/index.tsx
src/frontend/src/pages/FlowPage/components/extraSidebarComponent/index.tsx

Fixed sidebar not closing when searching for a component

Bug - sidebar opening

---

docker_example/Dockerfile
docker_example/docker-compose.yml

Update Dockerfile 
1) Remove unnecessary dependency after install
2) Use subcommand 'run' in CMD to match with the newer release of langflow.
Fixes #1097

fix(Dockerfile): Update dockerfile and docker-compose

---

src/backend/langflow/components/vectorstores/Redis.py

This pull request introduces the `RedisComponent`, a custom component for LangFlow that allows users to implement a Vector Store utilizing Redis. This integration facilitates the storage and retrieval of vector representations of documents in a Redis database.
**Key Features Introduced:**
- **Redis Support**: The component enables the usage of Redis as a backend for storing vector representations of documents, which is a robust and performant in-memory data structure store.
- **Configuration Method**: A `build_config` method has been added, allowing users to specify configuration options such as index name, documents, and Redis connection details.
- **Component Building**: The `build` method assembles the `VectorStore` object using the provided embeddings, documents, and Redis server …

feat: redis vector store client

---

src/backend/langflow/services/database/manager.py
src/backend/langflow/services/utils.py

This fixes a problem with tearing down super user when AUTO_LOGIN is True.

Release 0.5.8

---

src/backend/langflow/components/llms/AnthropicLLM.py

Native Anthropic components do not work. Just add it as AnthropicLLM

add AnthropicLLM by CustomComponent

---

poetry.lock
pyproject.toml
src/backend/langflow/interface/initialize/vector_store.py

This pull request fixes the embedding function name in the FAISS module and updates the dependencies in the pyproject.toml file. The changes include:
- Changing the embedding name to embedding_function in FAISS.
- Updating the version to 0.5.9 in the pyproject.toml file.

Fix embedding function name in FAISS and update dependencies

---

src/backend/langflow/components/vectorstores/Faiss.py
src/backend/langflow/config.yaml

🚀 feat(Faiss.py): add FAISSComponent custom component for implementing a Vector Store using FAISS
🔧 chore(config.yaml): comment out FAISS vector store integration documentation link

Hotfix: Solves Issue 791

---

src/frontend/src/controllers/API/index.ts
src/frontend/src/modals/shareModal/index.tsx

feat(API): add updateFlowStore function to update an existing flow in the Store
feat(shareModal): add functionality to update a shared component or flow

update an existing flow/component in the Store is now possible

---

poetry.lock
pyproject.toml
src/backend/langflow/api/v1/chat.py
src/backend/langflow/graph/graph/base.py
src/backend/langflow/graph/graph/constants.py

This pull request refactors the vertex class selection in the Graph class to improve code readability and maintainability. It also adds a new time_elapsed variable to track the elapsed time during the stream_build() function. Additionally, it bumps the version to 0.6.1 in the pyproject.toml file and includes a new poetry.lock file.

Hotfix: 0.6.1 

---

pyproject.toml

This pull request updates the version in the pyproject.toml file to 0.6.3a0.

Update version to 0.6.3a0 in pyproject.toml

---

pyproject.toml

This pull request updates the version in the pyproject.toml file from 0.6.3a0 to 0.6.3a1.

Update version to 0.6.3a1 in pyproject.toml

---

pyproject.toml

This pull request updates the version in pyproject.toml to 0.6.3a2.

Update version to 0.6.3a2 in pyproject.toml

---

pyproject.toml

This pull request updates the version in pyproject.toml to 0.6.3a3.

Update version to 0.6.3a3 in pyproject.toml

---

pyproject.toml

This pull request updates the version in the pyproject.toml file to 0.6.3a4.

Update version to 0.6.3a4 in pyproject.toml

---

pyproject.toml
src/backend/langflow/api/v1/endpoints.py
src/backend/langflow/processing/process.py

This pull request updates the type hints for the inputs parameter in the process_graph_data and process functions. It also refactors the result handling in the generate_result function. Additionally, it updates the version to 0.6.3a5 in pyproject.toml.

Update type hints and refactor result handling in process.py

---

src/backend/langflow/custom/customs.py
src/backend/langflow/interface/agents/custom.py
src/backend/langflow/template/frontend_node/agents.py

Cleanup AgentInitializer component

---

src/backend/langflow/components/llms/AzureChatOpenAI.py
src/frontend/src/utils/styleUtils.ts

Added AzureChatOpenAI Custom Component

---

src/frontend/src/pages/FlowPage/components/extraSidebarComponent/index.tsx

fix(extraSidebarComponent): update condition to show ExportMemo buttun based on hasApiKey and validApiKey variables
Github Issue: https://github.com/logspace-ai/langflow/issues/1227

BUGFIX: Issue GITHUB #1227

---

pyproject.toml

This is test to make sure the workflow is updating the release notes

Update version to 0.6.3a7 in pyproject.toml

---

pyproject.toml

This pull request updates the version in pyproject.toml to 0.6.4a0.

Release 0.6.4a0

---

.dockerignore
.github/workflows/release.yml

- Update .dockerignore file
- Add QEMU, Docker Buildx, and Docker Hub integration

Update .dockerignore file and add QEMU, Docker Buildx, and Docker Hub integration

---

.gitignore

Update .gitignore file for Pycharm IDE

Update .gitignore for Pycharm

---

src/backend/langflow/components/embeddings/AzureOpenAIEmbeddings.py

I have added AzureOpenAIEmbeddings component on Embeddings.

Added AzureOpenAIEmbeddings component

---

src/backend/langflow/__main__.py
src/backend/langflow/api/v1/endpoints.py
src/backend/langflow/api/v1/schemas.py
src/backend/langflow/main.py
src/backend/langflow/processing/process.py
src/backend/langflow/server.py
src/backend/langflow/services/session/service.py

This endpoint allows the Graph to be kept preprocessed in a session.

Add experimental preload endpoint

---

pyproject.toml
src/backend/langflow/__main__.py

This pull request adds support for running the application on Linux using gunicorn. It also updates the version number in the pyproject.toml file.

Add support for running on Linux using gunicorn

---

pyproject.toml
src/backend/langflow/processing/process.py

Refactor process_graph_cached function
Update version to 0.6.5a2 in pyproject.toml

Fix memory inputs and update function arguments

---

pyproject.toml
src/backend/langflow/__main__.py

This pull request refactors the run_on_mac_or_linux function by removing unused imports and updating the function signature. This improves the code readability and maintainability.

Refactor run_on_mac_or_linux function and remove unused imports

---

pyproject.toml

This pull request updates the version in the pyproject.toml file from 0.6.5a4 to 0.6.5a5.

Update version to 0.6.5a5 in pyproject.toml

---

pyproject.toml
src/backend/langflow/api/v1/login.py

This pull request refactors the import order and removes the unnecessary samesite attribute in the set_cookie() calls. This change improves the code readability and removes redundant code.

Refactor import order and remove unnecessary samesite attribute in set_cookie() calls

---

pyproject.toml
src/backend/langflow/api/v1/login.py

This pull request updates the cookie settings in the login.py file. Specifically, it removes the "secure" and "samesite" attributes from the response.set_cookie() function calls. This change ensures that the cookies are not restricted to secure connections only and are not limited to same-site requests.

Update cookie settings in login.py

---

src/backend/langflow/api/v1/chat.py
src/backend/langflow/services/auth/utils.py

Currently, chat interfaces do not support x-api-key authentication. In this modification, token or x-api-key authentication is supported

chat websocket api support param token and x-api-key

---

pyproject.toml
src/backend/langflow/components/embeddings/OpenAIEmbeddings.py
src/backend/langflow/components/textsplitters/CharacterTextSplitter.py
src/backend/langflow/components/vectorstores/Chroma.py

This pull request fixes the disallowed_special parameter in the OpenAIEmbeddingsComponent and refactors the CharacterTextSplitterComponent to use typing and update the return value. It also updates the ChromaComponent configuration and bumps the version to 0.6.7a1 in pyproject.toml.

Fix disallowed_special parameter and refactor CharacterTextSplitterComponent

---

pyproject.toml
src/backend/langflow/processing/base.py
src/backend/langflow/services/plugins/langfuse_plugin.py

Update version to 0.6.7a2 in pyproject.toml
- Refactoring of langflow processing and langfuse callback initialization
- Updating the version to 0.6.7a2 in pyproject.toml

Refactor langflow processing and langfuse callback initialization

---

src/backend/langflow/components/embeddings/HuggingFaceInferenceAPIEmbeddings.py
src/backend/langflow/components/vectorstores/Qdrant.py

Adds a new HuggingFaceInferenceAPIEmbeddingsComponent component class

Add HuggingFaceInferenceAPIEmbeddingsComponent class

---

src/backend/langflow/interface/custom/custom_component/component.py
src/frontend/src/CustomNodes/GenericNode/index.tsx

This pull request introduces a significant enhancement to our project, specifically aimed at empowering developers to seamlessly integrate icons into custom components. The goal is to provide a flexible and intuitive way to enhance UI elements with visual cues, thereby improving user experience and interface aesthetics.

Feature Enhancement: Enable Icon Integration for Custom Components

---

docs/docs/contributing/community.md
docs/docusaurus.config.js
src/frontend/src/components/headerComponent/index.tsx

Update URL Twitter documentation.

Url twitter update

---

src/backend/langflow/components/llms/ChatLiteLLM.py
src/backend/langflow/components/llms/LiteLLM.py

Added ChatLiteLLMComponent providing support to its large library of LLMs: https://litellm.ai/

Add LiteLLM support

---

src/frontend/src/pages/FlowPage/components/PageComponent/index.tsx
src/frontend/src/stores/flowStore.ts
src/frontend/src/types/zustand/flow/index.ts
src/frontend/src/utils/utils.ts

This pull request introduces the "Control X" command to our application's flow, aiming to enhance user control and improve the overall user experience. The "Control X" command allows users to execute a crop shortcut.

Add controlX Feature on Flow

---

pyproject.toml
src/backend/langflow/api/v1/login.py
src/backend/langflow/components/llms/ChatLiteLLM.py
src/backend/langflow/interface/custom/custom_component/component.py
src/backend/langflow/services/settings/auth.py
src/frontend/src/stores/typesStore.ts

This pull request updates the version to 0.6.7a3 in pyproject.toml and fixes formatting and import issues.

Update version to 0.6.7a3 and fix formatting and import issues

---

docs/docs/contributing/community.md

Update the Twitter handle in the community.

Update Twitter handle in community.md

---

src/backend/langflow/api/utils.py
src/backend/langflow/api/v1/chat.py
src/backend/langflow/components/io/ChatInput.py
src/backend/langflow/components/io/ChatOutput.py
src/backend/langflow/graph/graph/base.py
src/backend/langflow/graph/vertex/base.py
src/backend/langflow/services/chat/service.py
src/frontend/src/controllers/API/api.tsx
src/frontend/src/stores/flowStore.ts
src/frontend/src/types/zustand/flow/index.ts
src/frontend/src/utils/buildUtils.ts

This pull request introduces a new feature aimed at updating the build flow status for each vertex when the backend is shut down. Additionally, a minor refactor has been implemented in the interceptor to enhance code readability.

Bugfix: add build status on backend shutdown

---

README.md

Update Langflow README

---

.github/workflows/lint.yml
.github/workflows/test.yml

This pull request adds linting and testing workflows for the backend code. The workflows are triggered on changes to the "poetry.lock", "pyproject.toml", and "src/backend/**" files.

Add linting and testing workflows for backend code

---

src/frontend/src/contexts/authContext.tsx
src/frontend/src/stores/typesStore.ts

🔧 fix(authContext.tsx): add import statement for useFlowsManagerStoreto fix missing import error
🔧 fix(authContext.tsx): set isLoading to false in useFlowsManagerStore after setLoading to false to fix loading state inconsistency
🔧 fix(typesStore.ts): add null check for response.data to fix potential null reference error

Fix autologin = false loading loop

---

src/backend/langflow/components/data/APIRequest.py
src/backend/langflow/components/data/FileLoader.py
src/backend/langflow/components/embeddings/AmazonBedrockEmbeddings.py
src/backend/langflow/components/embeddings/OllamaEmbeddings.py
src/backend/langflow/components/experimental/ClearMessageHistory.py
src/backend/langflow/components/experimental/ExtractDataFromRecord.py
src/backend/langflow/components/experimental/GetNotified.py
src/backend/langflow/components/experimental/ListFlows.py
src/backend/langflow/components/experimental/MergeRecords.py
src/backend/langflow/components/experimental/MessageHistory.py
src/backend/langflow/components/experimental/Notify.py
src/backend/langflow/components/experimental/RunFlow.py
src/backend/langflow/components/experimental/RunnableExecutor.py
src/backend/langflow/components/experimental/SQLExecutor.py
src/backend/langflow/components/experimental/TextToRecord.py
src/backend/langflow/components/inputs/Prompt.py
src/backend/langflow/components/langchain_utilities/JSONDocumentBuilder.py
src/backend/langflow/components/retrievers/VectaraSelfQueryRetriver.py
src/backend/langflow/components/vectorstores/Chroma.py
src/backend/langflow/components/vectorstores/ChromaSearch.py
src/backend/langflow/components/vectorstores/Redis.py
src/backend/langflow/components/vectorstores/RedisSearch.py
src/backend/langflow/components/vectorstores/Vectara.py
src/backend/langflow/components/vectorstores/VectaraSearch.py
src/backend/langflow/components/vectorstores/Weaviate.py
src/backend/langflow/components/vectorstores/WeaviateSearch.py
src/backend/langflow/components/vectorstores/base/model.py
src/backend/langflow/template/frontend_node/custom_components.py

Update sidebar order

---

src/frontend/src/utils/utils.ts

📝 (utils.ts): add support for retrieving output IDs from flow data to include in the curl code
📝 (utils.ts): update getCurlCode function to include the arrayOfOutputs in the curl code

Fix cURL on Api Modal

---

src/frontend/src/pages/FlowPage/components/nodeToolbarComponent/index.tsx
src/frontend/src/pages/FlowPage/components/nodeToolbarComponent/toolbarSelectItem/index.tsx

♻️ (index.tsx): remove unused import of useEffect to improve code cleanliness and readability
📝 (index.tsx): refactor toolbarSelectItem component to improve code formatting and readability

Fix toolbar UI - Icons views

---

src/frontend/package-lock.json
src/frontend/package.json
src/frontend/playwright.config.ts
src/frontend/run-tests.sh
src/frontend/src/components/NewFLowCard2/index.tsx
src/frontend/src/pages/FlowPage/components/nodeToolbarComponent/index.tsx
src/frontend/src/pages/FlowPage/components/nodeToolbarComponent/toolbarSelectItem/index.tsx
src/frontend/src/types/components/index.ts
src/frontend/tests/end-to-end/auto_login.spec.ts
src/frontend/tests/end-to-end/codeAreaModalComponent.spec.ts
src/frontend/tests/end-to-end/dragAndDrop.spec.ts
src/frontend/tests/end-to-end/dropdownComponent.spec.ts
src/frontend/tests/end-to-end/floatComponent.spec.ts
src/frontend/tests/end-to-end/flowPage.spec.ts
src/frontend/tests/end-to-end/group.spec.ts
src/frontend/tests/end-to-end/inputComponent.spec.ts
src/frontend/tests/end-to-end/intComponent.spec.ts
src/frontend/tests/end-to-end/keyPairListComponent.spec.ts
src/frontend/tests/end-to-end/langflowShortcuts.spec.ts
src/frontend/tests/end-to-end/nestedComponent.spec.ts
src/frontend/tests/end-to-end/promptModalComponent.spec.ts
src/frontend/tests/end-to-end/saveComponents.spec.ts
src/frontend/tests/end-to-end/toggleComponent.spec.ts

🔧 fix(NewFlowCard2): add missing data-testid attribute to the NewFlowCardComponent to improve testability
🔧 fix(nodeToolbarComponent): add missing data-testid attribute to the save button to improve testability
🔧 fix(nodeToolbarComponent): add missing data-testid attribute to the edit button to improve testability
🔧 fix(nodeToolbarComponent): add missing data-testid attribute to the duplicate button to improve testability
🔧 fix(codeAreaModalComponent.spec): add click on the blank-flow element before performing other actions to ensure proper test setup
🔧 fix(dropdownComponent.spec): add click on the blank-flow element before performing other actions to ensure proper test setup
🔧 fix(floatComponent.spec): add click on the blank-flow element before performing other actions to ensure proper …

Add tests to shortcuts

---

src/backend/langflow/components/outputs/CSVOutput.py
src/frontend/src/CustomNodes/GenericNode/components/parameterComponent/index.tsx
src/frontend/src/components/IOOutputView/index.tsx
src/frontend/src/components/IOview/index.tsx
src/frontend/src/components/csvOutputComponent/helpers/convert-data-function.ts
src/frontend/src/components/csvOutputComponent/index.tsx
src/frontend/src/components/inputFileComponent/index.tsx
src/frontend/src/components/ui/select.tsx
src/frontend/src/constants/constants.ts
src/frontend/src/style/classes.css
src/frontend/src/types/components/index.ts
src/frontend/src/types/zustand/flow/index.ts

📝 (index.ts): add support for passing nodeToChange prop to InputFileComponent to update the node data with the selected file
📝 (inputFileComponent/index.tsx): update InputFileComponent to save the selected file to the node data and update the node using setNode function
📝 (csvOutputComponent/index.tsx): update CsvOutputComponent to use the file from the csvNode prop to convert and display the CSV data
📝 (IOOutputView/index.tsx): remove unused import of cloneDeep function from lodash
📝 (parameterComponent/index.tsx): add nodeToChange prop to InputFileComponent to pass the data node to the component

Add the file on node to view on chat.

---

src/frontend/src/components/IOOutputView/index.tsx
src/frontend/src/components/IOview/index.tsx
src/frontend/src/components/csvOutputComponent/index.tsx
src/frontend/src/style/classes.css

📝 (IOOutputView/index.tsx): import lodash's cloneDeep function to be used later in the code
✨ (IOOutputView/index.tsx): add support for Select component to choose CSV separator
♻️ (IOOutputView/index.tsx): refactor handleChangeSelect function to update flowPoolNode data and setFlowPool state
📝 (csvOutputComponent/index.tsx): import useFlowStore from flowStore to access flowPool state
♻️ (csvOutputComponent/index.tsx): refactor CsvOutputComponent to use flowPool state instead of csvNode prop

Add possibility to change csv separator on chat modal.

---

src/backend/langflow/interface/initialize/utils.py

fix ChatMessagePromptTemplate init issue:https://github.com/logspace-ai/langflow/issues/1351

fix init ChatMessagePromptTemplate error issue #1351

---

src/frontend/src/CustomNodes/GenericNode/index.tsx

♻️ (GenericNode/index.tsx): refactor showNode state initialization and update logic to use useState and useEffect hooks for better readability and maintainability

Fix minimize

---

docs/docusaurus.config.js
docs/package-lock.json
docs/package.json
pyproject.toml

- Added Google Analytics tag for analyzing Docs website.

Added Google Analytics tags on Docs

---

LICENSE
README.md

- Update getting started instructions
- Reorganize sections to improve readability
- Update license year to 2024

README Improvements

---

pyproject.toml
src/backend/base/pyproject.toml
src/frontend/src/pages/FlowPage/index.tsx

This pull request updates the Logspace link in the FlowPage component to point to a Medium article about Langflow and DataStax. It also updates the package versions in the pyproject.toml file to 1.0.0a7 for langflow and 0.0.20 for langflow-base.

Update Logspace link and package versions

---

README.md

- Add docs and discord links to the top of the readme

Add docs and discord links to the top of the readme

---

src/backend/base/langflow/graph/vertex/base.py

issue 1614: fix os path separator dependency

---

docs/docs/index.mdx

This pull request updates the Langflow documentation to include installation instructions, running Langflow using the command-line interface (CLI), and information about Langflow 1.0. It also adds a cautionary note about the documentation being under construction.

Update Langflow documentation

---

.github/workflows/pre-release-langflow.yml
docker_example/Dockerfile
docker_example/docker-compose.yml

- Update Dockerfile to use logspace/langflow:latest image
- Update docker-compose.yml with new version and add PostgreSQL service
- Add langflow 1.0-alpha tag

Update Dockerfile, docker-compose.yml, and add langflow 1.0-alpha tag

---

README.md

- Improve getting started instructions

Improve getting started instructions

---

docs/docs/index.mdx

This pull request updates the installation instructions for Langflow. It includes changes to the pip installation commands and adds imports for ThemedImage, useBaseUrl, ZoomableImage, and Admonition.

Update installation instructions for Langflow

---

poetry.lock
pyproject.toml
src/backend/base/poetry.lock
src/backend/base/pyproject.toml

This pull request updates the package versions in the pyproject.toml file. Specifically, it updates the versions of fastapi, uvicorn, langchain, sqlmodel, and typer to their latest versions. This ensures that the project is using the most up-to-date dependencies.

Update package versions in pyproject.toml

---

poetry.lock
pyproject.toml
src/backend/base/poetry.lock
src/backend/base/pyproject.toml

This pull request updates the package versions in pyproject.toml and adds new dependencies. The changes include adding chromadb, langchain-anthropic, langchain-astradb, langchain-openai, and langchain-cohere to the Langflow dependencies and removing them from langflow-base

Update package versions and add new dependencies

---

.github/workflows/pre-release-base.yml
.github/workflows/pre-release-langflow.yml
.github/workflows/release.yml
README.md
docker_example/docker-compose.yml
poetry.lock
pyproject.toml
src/backend/base/poetry.lock
src/backend/base/pyproject.toml

This pull request updates the package versions in the pyproject.toml file and fixes the dependencies.

Update package versions in pyproject.toml and fix dependencies

---

src/frontend/src/App.tsx
src/frontend/src/contexts/authContext.tsx
src/frontend/src/types/contexts/auth.ts

✨ (App.tsx): refactor code to use async/await syntax for fetching data when the user is authenticated
🐛 (App.tsx): handle errors when fetching data and log them to the console for debugging purposes

Bugfix: make request on auto_login endpoint first when application starts

---

README.md

Fix readme license link

---

src/backend/base/langflow/api/v1/validate.py
src/backend/base/langflow/base/prompts/api_utils.py
src/backend/base/langflow/base/prompts/utils.py
tests/test_loading.py

This pull request updates the langflow base prompts API utils. It includes changes to the validate_prompt function, get_old_custom_fields function, add_new_variables_to_template function, remove_old_variables_from_template function, and update_input_variables_field function. These changes improve the functionality and reliability of the API utils.

Update langflow base prompts API utils

---

src/backend/base/langflow/components/models/OpenAIModel.py

Add gpt-4-turbo-2024-04-09 new OpenAI model.

Update OpenAIModel.py: new model

---

.github/workflows/pre-release-base.yml
.github/workflows/pre-release-langflow.yml

This pull request updates the release job names and adds outputs in the pre-release-base.yml and pre-release-langflow.yml files.

Update release job names and add outputs in pre-release-base.yml and pre-release-langflow.yml

---

container-cmd-cdk.sh
dev.Dockerfile
docker-compose.debug.yml
docker-compose.yml

Update Uvicorn command in Dockerfiles and shell script to use langflow.main:create_app instead of src.backend.langflow.main:create_app

---

src/backend/base/langflow/processing/load.py
src/backend/base/langflow/processing/process.py

This pull request applies the nest_asyncio library to enable asyncio event loop nesting in the process.py file. This allows for better handling of nested event loops and improves the overall performance and stability of the code.

Apply nest_asyncio to enable asyncio event loop nesting in process.py

---

src/frontend/src/components/cardComponent/index.tsx
src/frontend/src/modals/IOModal/index.tsx
src/frontend/src/pages/Playground/index.tsx

This pull request addresses a bug where modals are erroneously opening when they are not intended to.
The issue occurs when certain conditions are met, such as clicking on specific elements or navigating to particular pages. This behavior disrupts the user experience and may lead to confusion.

Fix modal opening bug when not supposed to

---

.pre-commit-config.yaml
Makefile
poetry.lock
pyproject.toml
scripts/setup/update_poetry.sh
src/frontend/package-lock.json
src/frontend/package.json

This pull request adds Simple Git Hooks for better code quality and consistency. It also updates the pre-commit-config.yaml and Makefile, and refactors the pre-commit installation in the Makefile. Additionally, the update_poetry.sh script is refactored to not install pipx anymore.

Refactor store_message function and add Simple Git Hooks

---

src/frontend/src/components/addNewVariableButtonComponent/addNewVariableButton.tsx
src/frontend/src/components/inputComponent/index.tsx
src/frontend/src/components/tableComponent/index.tsx
src/frontend/src/pages/SettingsPage/pages/GlobalVariablesPage/index.tsx
src/frontend/src/pages/SettingsPage/pages/ShortcutsPage/index.tsx

Fixed height and resizability of Global Variables table, made value of credentials variable as password field

Bugs - Global Variables

---

src/backend/base/langflow/components/experimental/Pass.py
src/backend/base/langflow/components/experimental/TextOperator.py

This pull request refactors the TextOperatorComponent to include a new parameter called true_output. This parameter allows the user to specify the output to return or display when the comparison is true. The refactoring also includes some code improvements and error handling.

Refactor TextOperatorComponent to include true_output parameter

---

src/backend/base/langflow/api/v1/chat.py
src/backend/base/langflow/api/v1/endpoints.py
src/backend/base/langflow/api/v1/files.py

It's good practice to validate the flow_id to be uuid since sometimes it's used as directory/filename and it could lead to uncontrolled data used in path expression

backend: validate flow_id on api

---

src/backend/base/langflow/services/database/models/api_key/model.py
src/backend/base/langflow/services/settings/auth.py
src/backend/base/langflow/services/store/schema.py

Hi,
This PR migrates the deprecated pydantic v1 syntax to the v2 version.

Update deprecated pydantic validator

---

README.md
docs/docs/administration/cli.mdx
src/backend/base/langflow/__main__.py
src/backend/base/langflow/api/v1/endpoints.py
src/backend/base/langflow/api/v1/flows.py
src/backend/base/langflow/initial_setup/setup.py
src/backend/base/langflow/interface/listing.py
src/backend/base/langflow/interface/utils.py
src/backend/base/langflow/services/cache/factory.py
src/backend/base/langflow/services/database/factory.py
src/backend/base/langflow/services/database/service.py
src/backend/base/langflow/services/plugins/langfuse_plugin.py
src/backend/base/langflow/services/settings/base.py
src/backend/base/langflow/services/settings/manager.py
src/backend/base/langflow/services/settings/service.py
src/backend/base/langflow/services/storage/factory.py
src/backend/base/langflow/services/storage/local.py
src/backend/base/langflow/services/store/service.py
src/backend/base/langflow/services/task/service.py
src/backend/base/langflow/utils/util.py
tests/test_cli.py
tests/test_endpoints.py

This pull request updates the settings attributes in multiple files to use the correct naming convention. It also removes references to the `config.yaml` file, which is no longer used.

Update settings attributes and remove config.yaml references

---

README.md
docs/docs/administration/cli.mdx
src/backend/base/langflow/__main__.py
src/backend/base/langflow/api/v1/endpoints.py
src/backend/base/langflow/api/v1/flows.py
src/backend/base/langflow/api/v1/store.py
src/backend/base/langflow/initial_setup/setup.py
src/backend/base/langflow/interface/listing.py
src/backend/base/langflow/interface/utils.py
src/backend/base/langflow/services/cache/factory.py
src/backend/base/langflow/services/database/factory.py
src/backend/base/langflow/services/database/service.py
src/backend/base/langflow/services/plugins/langfuse_plugin.py
src/backend/base/langflow/services/settings/base.py
src/backend/base/langflow/services/settings/manager.py
src/backend/base/langflow/services/settings/service.py
src/backend/base/langflow/services/storage/factory.py
src/backend/base/langflow/services/storage/local.py
src/backend/base/langflow/services/store/service.py
src/backend/base/langflow/services/task/service.py
src/backend/base/langflow/utils/util.py
tests/test_cli.py
tests/test_endpoints.py

This pull request includes two commits. The first commit ensures that flows always have a folder by checking if the flow's folder ID is None and assigning a default folder if available. The second commit updates the store attribute in the check_if_store_is_enabled function to use the correct casing.

Ensure flows always have a folder

---

docker/build_and_push.Dockerfile
docker/build_and_push_base.Dockerfile

This pull request updates the Dockerfiles to create a "langflow" directory and grant write permissions to it. This change ensures that the user inside the Docker container has the necessary permissions to write to the "langflow" directory.

Update Dockerfiles to create langflow directory and grant write permissions

---

docs/docs/administration/api.mdx
docs/docs/administration/cli.mdx
src/frontend/src/components/headerComponent/index.tsx
src/frontend/src/modals/apiModal/utils/get-curl-code.tsx
src/frontend/src/modals/secretKeyModal/index.tsx

This PR gives access to create API keys to AUTO_LOGIN=True mode and fixed Cancel button being the default form button.

Added API key access to AUTO_LOGIN=True and fixed SecretKeyModal

---

docs/docs/index.mdx

* Update docs gif to align with readme

[Docs] - Update gif

---

README.md
docs/docs/integrations/notion/add-content-to-page.md
docs/docs/integrations/notion/list-users.md

Docs - Update README.md

---

.github/workflows/lint-js.yml
.github/workflows/lint-py.yml
.github/workflows/matchers/ruff.json
.github/workflows/style-check-py.yml
.pre-commit-config.yaml

This pull request updates the linting workflows for both frontend and Python code. The changes include:
- Updating pre-commit hooks and dependencies
- Adding a linting workflow for frontend code
- Updating the linting workflow for Python code to include tests in pull requests
- Adding a Ruff style check workflow for Python code
These updates will improve the code quality and maintainability of the project.

Update linting workflows for frontend and Python code

---

src/frontend/src/App.tsx
src/frontend/src/components/sidebarComponent/components/sideBarFolderButtons/index.tsx
src/frontend/src/components/sidebarComponent/hooks/use-on-file-drop.tsx
src/frontend/src/components/sidebarComponent/index.tsx
src/frontend/src/components/tableComponent/index.tsx
src/frontend/src/contexts/authContext.tsx
src/frontend/src/controllers/API/api.tsx
src/frontend/src/controllers/API/helpers/check-duplicate-requests.ts
src/frontend/src/controllers/API/index.ts
src/frontend/src/pages/AdminPage/LoginPage/index.tsx
src/frontend/src/pages/LoginPage/index.tsx
src/frontend/src/pages/MainPage/components/myCollectionComponent/components/headerTabsSearchComponent/index.tsx
src/frontend/src/pages/MainPage/hooks/use-delete-folder.tsx
src/frontend/src/pages/MainPage/pages/mainPage/index.tsx
src/frontend/src/stores/foldersStore.tsx
src/frontend/src/types/zustand/folders/index.ts

This pull request addresses several improvements and fixes to enhance the overall functionality and user experience. The key changes include:
- Improved Folders Behavior Context
- Enhanced Duplicate Request Blocker
- Bug Fix: Folders Compatibility with AutoLogin = False

Fix error on React Flow with Auto Login = False

---

.github/workflows/docker-build.yml
.github/workflows/pre-release.yml
poetry.lock
src/backend/base/poetry.lock
src/backend/base/pyproject.toml

This pull request updates the chardet package to version 5.2.0 and includes changes to the Docker build workflow and pre-release workflow. The Docker build workflow now supports multiple platforms and includes container testing. The pre-release workflow has been updated to include CLI testing.

Update dependencies and workflows

---

docs/docs/getting-started/canvas.mdx
docs/docs/migration/migrating-to-one-point-zero.mdx

Update "Guide Coming Soon" to links to related docs on new features (from user feedback)

[Docs] - Link to new features from migration page

---

.github/workflows/docker-build.yml

Last alpha version .59 used the wrong dockerfile resulting in only containing the base package

fix docker tags on release process

---

src/backend/base/langflow/api/v1/chat.py

fix: got unexpected 'lock'

---

src/backend/base/langflow/api/utils.py
src/backend/base/langflow/api/v1/chat.py
src/backend/base/langflow/main.py
src/frontend/src/components/headerComponent/components/menuBar/index.tsx
src/frontend/src/modals/IOModal/index.tsx
src/frontend/src/stores/flowStore.ts
src/frontend/src/types/zustand/flow/index.ts

This PR introduces a feature that allows users to cancel ongoing API requests without affecting other operations.

Stop building

---

docs/docs/administration/settings.mdx
docs/sidebars.js

- Settings
- Shortcuts
- Global and project settings

[Docs] - Global and Project Settings

---

poetry.lock
src/backend/base/langflow/api/utils.py
src/backend/base/langflow/components/vectorstores/AstraDB.py
src/backend/base/langflow/components/vectorstores/Cassandra.py
src/backend/base/langflow/components/vectorstores/Couchbase.py
src/backend/base/langflow/components/vectorstores/Pinecone.py
src/backend/base/langflow/components/vectorstores/Qdrant.py
src/backend/base/langflow/components/vectorstores/Redis.py
src/backend/base/langflow/components/vectorstores/SupabaseVectorStore.py
src/backend/base/langflow/components/vectorstores/Upstash.py
src/backend/base/langflow/components/vectorstores/Vectara.py
src/backend/base/langflow/components/vectorstores/Weaviate.py
src/backend/base/langflow/components/vectorstores/pgvector.py

Update and Test Default Component Formations for Vector Stores
We have successfully tested and updated the configurations for all default vector store components, please check if the format is okay.
- CassandraVectorStoreComponent (tested in AstraDB environment)
- CouchbaseVectorStoreComponent
- FaissVectorStoreComponent
- MongoVectorStoreComponent
- PGVectorStoreComponent
- PineconeVectorStoreComponent
- QdrantVectorStoreComponent
- SupabaseVectorStoreComponent
- UpstashVectorStoreComponent
- VectaraVectorStoreComponent
- WeaviateVectorStoreComponent
- RedisVectorStoreComponent

Updated Default Component Formations for Vector Stores

---

src/backend/base/langflow/services/monitor/utils.py

We have repeated DuckDB transaction errors when a user choose and update a template from the starter project. This looks like the code block to drop a table, create a squence and a table in the drop_and_create_table_if_schema_mismatch is being called simultaneously. The PR adds a lock on the entire code block. 
The other two options can be retry on these multiple drop table, create sequence and table but these steps should be in one locked step to avoid multiple threads access duckDB's transaction. That's why we tested with the lock of the code block is more robust.
```
File "/app/src/backend/base/langflow/services/monitor/utils.py", line 81, in drop_and_create_table_if_schema_mismatch conn.execute(create_table_sql) | | -> "CREATE TABLE IF NOT EXISTS vertex_builds (index INTEGER PRIMARY …
```

prevent race condition on drop_and_create_table_if_schema_mismatch

---

src/backend/base/langflow/initial_setup/starter_projects/Basic Prompting (Hello, world!).json

This PR updates the basic prompt example to fix a warning that was being displayed. The changes ensure that the prompt example is now warning-free.

update basic prompt example

---

src/frontend/src/components/paginatorComponent/index.tsx

💄 (paginatorComponent): remove fixed height and width from paginator buttons for better responsiveness

fix icons not displaying

---

src/backend/base/langflow/services/database/models/folder/constants.py
src/frontend/src/constants/constants.ts
src/frontend/src/modals/IOModal/components/chatView/chatMessage/index.tsx

Removed LaTeX from markdown to not cause problems when sending symbols as "$".

Removed LaTeX to not cause problems

---

poetry.lock
pyproject.toml
src/backend/base/langflow/api/v1/endpoints.py
src/backend/base/langflow/services/tracing/service.py
src/backend/base/pyproject.toml
tests/test_user.py

This pull request includes updates to the package versions in the `pyproject.toml` files and refactors the code to stop the tracing service gracefully and update the `dict` method to `model_dump` in the user API endpoints.

Update package versions and refactor code

---

docs/docs/contributing/telemetry.mdx
docs/sidebars.js
src/backend/base/langflow/__main__.py
src/backend/base/langflow/api/v1/chat.py
src/backend/base/langflow/api/v1/endpoints.py
src/backend/base/langflow/main.py
src/backend/base/langflow/services/deps.py
src/backend/base/langflow/services/schema.py
src/backend/base/langflow/services/settings/base.py
src/backend/base/langflow/services/telemetry/factory.py
src/backend/base/langflow/services/telemetry/schema.py
src/backend/base/langflow/services/telemetry/service.py
src/backend/base/langflow/utils/version.py

Add the TelemetryService and TelemetryServiceFactory classes to the langflow.services.telemetry module. These additions enable the application to collect and analyze telemetry data. The TelemetryService is responsible for handling telemetry-related functionality, such as logging package run time and tracking auto login.
These are optional and can be turned off by setting environment variables like `DO_NOT_TRACK` and `LANGFLOW_DO_NOT_TRACK`.

Add TelemetryService and docs

---

docs/docs/components/embeddings.mdx
docs/docs/components/vector-stores.mdx
src/backend/base/langflow/components/embeddings/AstraVectorize.py
src/backend/base/langflow/components/vectorstores/AstraDB.py
src/backend/base/langflow/initial_setup/starter_projects/VectorStore-RAG-Flows.json
src/backend/base/langflow/services/telemetry/service.py
src/frontend/package-lock.json
src/frontend/src/CustomNodes/GenericNode/components/parameterComponent/index.tsx

Adding Astra vectorize components and let the AstraDB VectorStore to be connected with it.
Also adding docs as embeddings

components: add Astra vectorize

---

src/backend/base/langflow/components/models/ChatLiteLLMModel.py
src/frontend/src/alerts/notice/index.tsx
src/frontend/src/pages/FlowPage/components/PageComponent/index.tsx
src/frontend/src/stores/flowStore.ts
src/frontend/src/utils/reactflowUtils.ts

Add a warning to the user whenever a component with an old CustomComponent Class is added to the screen

Add warning to components with old codes

---

docs/docs/components/custom.mdx
src/backend/base/langflow/components/deactivated/SplitText.py
src/backend/base/langflow/components/deactivated/__init__.py
src/backend/base/langflow/components/helpers/IDGenerator.py
src/backend/base/langflow/components/prototypes/__init__.py
src/backend/base/langflow/initial_setup/starter_projects/VectorStore-RAG-Flows.json

This PR fixes errors reported by mypy

fix erros reported by mypy

---

docs/static/data/AstraDB-RAG-Flows.json
src/backend/base/langflow/initial_setup/starter_projects/VectorStore-RAG-Flows.json
src/frontend/src/components/headerComponent/index.tsx

Updates references to pre-release.langflow.org to docs.langflow.org

Update project documentation URLs to use the main domain

---

docs/docs/administration/prompt-customization.mdx

Fixed error which prevented docs to build

Fix documentation build errors

---

docs/docs/getting-started/install-langflow.mdx
docs/docs/migration/migrating-to-one-point-zero.mdx

Fixed problems that prevents docs to build

---

.github/workflows/lint-js.yml
.github/workflows/lint-py.yml
.github/workflows/python_test.yml
.github/workflows/style-check-py.yml

This pull request updates the linting workflows to include the dev branch in the merge_group. This ensures that the linting workflows are triggered only when changes are made to the dev branch, reducing unnecessary workflow runs.

Update linting workflows to include dev branch in merge_group

---

README.md
src/backend/base/langflow/alembic/versions/2ac71eb9c3ae_adds_credential_table.py
src/backend/base/langflow/components/agents/ToolCallingAgent.py
src/backend/base/langflow/main.py
tests/unit/test_helper_components.py

Fix type not correctly set in migration script.

Refactor "created_at" column type for consistency and fix cancel middleware

---

.vscode/launch.json
src/backend/base/langflow/__main__.py
src/backend/base/langflow/api/v1/endpoints.py
src/backend/base/langflow/components/models/GoogleGenerativeAIModel.py
src/backend/base/langflow/main.py
src/backend/base/langflow/services/auth/utils.py
src/frontend/src/components/headerComponent/components/menuBar/index.tsx

This commit updates the import statement for the `dotenv` module in the `__main__.py` file. It adds the `dotenv_values` function to the import statement to enable loading environment variables from a file. Additionally, it introduces a new section of code that maps environment variables to their corresponding variables and types, allowing for more flexible and dynamic configuration. The commit also updates the `run` function to update variables based on environment variables, if they are present. This change improves the handling of environment variables and enhances the configurability of the application.
Closes #2324

Fix .env values not being honored in CLI

---

.github/workflows/docs_test.yml
.github/workflows/python_test.yml
.github/workflows/release.yml
poetry.lock
pyproject.toml
src/backend/base/poetry.lock
src/backend/base/pyproject.toml

This pull request includes updates to the GitHub Actions workflows and dependencies. It adds a new workflow for testing documentation build, fixes the server start command in the workflows, and bumps the versions of langflow and langflow-base packages.

Update GitHub Actions workflows and dependencies

---

pyproject.toml
src/backend/base/pyproject.toml

Bump versions for a new release

chore: Update package versions in pyproject.toml files

---

src/backend/base/langflow/components/vectorstores/Cassandra.py

* Added support for Contact points
* Reworded some parameters depending on astra / local cassandra usage
* Added username
Successor of https://github.com/langflow-ai/langflow/pull/2206 but with the new framework

Cassandra: support for non-AstraDB databases

---

.github/workflows/docker-build.yml
docker/build_and_push.Dockerfile
docker/build_and_push_backend.Dockerfile
docker/build_and_push_base.Dockerfile
docker_example/docker-compose.yml

Update docker-build to fix tag for backend and frontend images, update dockerfiles to set env variables instead of CMD and update docker-compose.yml

Update dockerfiles and docker-build.yml

---

.github/workflows/typescript_test.yml

🔧 (typescript_test.yml): Update job name to "Run Playwright Tests" for clarity and consistency
🔧 (typescript_test.yml): Remove unnecessary 'ref' input from 'actions/checkout' step

Reactivate frontend tests 

---

src/frontend/src/CustomNodes/GenericNode/index.tsx
src/frontend/src/CustomNodes/helpers/get-node-input-colors.ts
src/frontend/src/CustomNodes/helpers/get-node-output-colors.ts
src/frontend/src/components/ImageViewer/index.tsx
src/frontend/src/components/horizontalScrollFadeComponent/index.tsx
src/frontend/src/modals/BundleModal/hooks/submit-folder.tsx
src/frontend/src/modals/foldersModal/hooks/submit-folder.tsx

cherry pick from #2340 which adds more types to frontend code.

Feat: Add types to functions, components and hooks that are missing it

---

src/frontend/src/CustomNodes/hooks/use-icons-status.tsx
src/frontend/src/utils/buildUtils.ts

Fixed nodes having the previous build status while waiting for other nodes to build

Fix Build Status

---

src/frontend/src/components/codeTabsComponent/index.tsx
src/frontend/src/modals/apiModal/index.tsx
src/frontend/src/modals/apiModal/utils/get-tabs-order.tsx
src/frontend/src/types/components/index.ts

This pull request addresses an issue where the tweaks tab on ApiModal disappears when using a webhook component.

Fix: Tweaks tab dissapearing with hook component

---

src/frontend/src/components/tableComponent/components/tableNodeCellRender/index.tsx

This PR fixes an error that crashed Langflow when the advanced opened.

bugfix: fix crashing langflow when keypairlistcomponent advanced opens

---

src/backend/base/langflow/components/langchain_utilities/FirecrawlCrawlApi.py
src/backend/base/langflow/components/vectorstores/AstraDB.py
src/backend/base/langflow/components/vectorstores/Cassandra.py

While running the search, the documents are indexed again

fix (astra/cassandra): avoid duplicated ingestion

---

.github/workflows/ci.yml
.github/workflows/docs_test.yml
.github/workflows/js_autofix.yml
.github/workflows/lint-js.yml
.github/workflows/lint-py.yml
.github/workflows/python_test.yml
.github/workflows/release.yml
.github/workflows/style-check-py.yml
.github/workflows/typescript_test.yml
src/frontend/tests/end-to-end/deleteComponents.spec.ts
src/frontend/tests/end-to-end/deleteFlows.spec.ts
src/frontend/tests/end-to-end/logs.spec.ts
src/frontend/tests/end-to-end/store-shard-1.spec.ts
src/frontend/tests/end-to-end/store-shard-2.spec.ts
src/frontend/tests/end-to-end/store-shard-3.spec.ts
src/frontend/tsconfig.json

This pull request updates the CI workflows to include support for the `workflow_call` and `workflow_dispatch` events with an optional branch input for checking out specific branches. It also adds a new CI workflow for automated testing and linting of backend, frontend, and documentation code.
With this PR we'll be able to more easily set required checks for merging.

ci: update CI workflows and add CI workflow

---

src/frontend/src/constants/constants.ts

fix: restore button for all native components

---

Makefile
docker/build_and_push.Dockerfile
docker/build_and_push_backend.Dockerfile
docker/build_and_push_base.Dockerfile
docker_example/docker-compose.yml

This PR creates new shortcuts to help users build Docker images for Langflow locally and aims to simplify its usage somewhat. 
Initially, I wanted it to be more comprehensive, but to maintain the brevity that PRs should have, this will be left for future opportunities.

chore: simplify docker

---

.github/release.yml
.github/workflows/conventional-labels.yml

Updates PR validation to label only user created PRs.

feat(PR): add conditions to label pr

---

.github/workflows/conventional-labels.yml

Removes output in validate job.

chore: remove unnecessary output in validate-pr job

---

src/frontend/src/constants/enums.ts
src/frontend/src/modals/IOModal/components/IOFieldView/index.tsx

This pull request enhances code readability and maintainability by centralizing type definitions for switch cases into a dedicated constants file.

refactor: add types to constant on IO

---

src/frontend/src/controllers/API/queries/health/use-get-health.ts

This pull request updates ise-get-health.ts request to use options instead of onFetch callback function

fix: update use-get-health.ts

---

src/backend/base/langflow/components/prompts/Prompt.py
src/backend/base/langflow/template/utils.py
src/frontend/src/CustomNodes/hooks/use-check-code-validity.tsx

- Fixed code being "updatable" when user edits the code and changes the class name.
- Fixed global variable disappearing when editing code on StrComponents and appearing when editing code on SecretStrComponents by @ogabrielluiz

fix: outdated code conditions and global variable

---

src/backend/base/langflow/api/v1/endpoints.py

This commit updates the `custom_component_update` endpoint in `endpoints.py` to include the logic for updating custom component attributes with load from DB fields. The `cc_instance` is checked for the presence of a `set_attributes` method, and if it exists, the template and parameters are extracted from the code request. The load from DB fields are identified and used to update the parameters. Finally, the `set_attributes` method is called with the updated parameters. This enhancement improves the flexibility and functionality of custom components.

feat: update custom component attributes on /update endpoint

---

src/backend/base/langflow/base/vectorstores/model.py
src/backend/base/langflow/components/embeddings/AstraVectorize.py
src/backend/base/langflow/components/embeddings/__init__.py
tests/integration/astra/test_astra_component.py

Fixes the astra integration tests and adds a couple more for vectorize.
Next PR(s) will add checks to CI to run astra tests when these files are touched. We'l supply an astra org and credentials.

tests: fix up the astra integ tests and add vectorize tests

---

src/frontend/src/CustomNodes/GenericNode/components/parameterComponent/index.tsx

this pull request fix an issue with the freeze node after refreshing the flow

fix: issue with freeze value on page refresh

---

src/backend/base/langflow/components/vectorstores/Qdrant.py

fix: qdrant with ingest not working

---

poetry.lock
pyproject.toml
src/backend/base/langflow/initial_setup/starter_projects/Memory Chatbot.json
src/backend/base/poetry.lock
src/backend/base/pyproject.toml

chore: update package versions

---

src/backend/base/langflow/graph/graph/runnable_vertices_manager.py

Fixes a bug that caused components to more times than it should.

fix: check if vertex is in vertices_being_run to check if it is runnable

---

.github/workflows/deploy_gh-pages.yml

This pull request adds a path for deploying documentation updates. The changes include updating the workflow file to trigger the deployment when changes are made to the 'docs' directory. This will ensure that any updates to the documentation are automatically deployed.

chore: add path for deploying documentation updates

---

.github/workflows/fetch_docs_notion.yml

- Fixes date step on GH workflow

docs: fix gh workflow date step

---

.github/workflows/fetch_docs_notion.yml

- Fixed bad character on date step of gh workflow

docs: fix gh workflow date step bad character

---

.github/workflows/fetch_docs_notion.yml

- Git Workflow commands to push changes to repository fixed

fix: git workflow commands to push to repository

---

.github/workflows/fetch_docs_notion.yml

- Fixes notion fetch workflow push origin on github command

fix: fetch notion docs workflow origin on push

---

.github/workflows/fetch_docs_notion.yml

- Fix date on push command on fetch notion workflow

fix: date on push command on fetch notion workflow

---

.github/workflows/fetch_docs_notion.yml

- Fixed git commands that were useless on the process of creating a branch

fix: useless git commands on workflow

---

.github/workflows/fetch_docs_notion.yml

fix: added checkout to workflow

---

src/backend/base/langflow/api/v1/chat.py
src/backend/base/langflow/services/telemetry/schema.py
src/backend/base/langflow/services/telemetry/service.py

This pull request adds a new `package` field to the `VersionPayload` class in the telemetry schema. This field will be used to specify the package name when sending telemetry data. Additionally, the telemetry service is updated to include the `package` field in the `VersionPayload` class. This change enhances the telemetry tracking capabilities. The `build_vertex` function in the `chat.py` file is also refactored to improve error handling. The function now includes a new `error_message` variable to store the error message when an exception occurs. The telemetry service is updated to include the error message in the `ComponentPayload`. This change enhances the reliability and debugging capabilities of the function.

fix: update telemetry schema and fix telemtry calls

---

.github/workflows/python_test.yml

Makes Test CLI run in another job.

chore: move test-cli job to run separately from unit tests

---

src/backend/base/langflow/api/v1/schemas.py

Fixes the type in ResultDataResponse

fix: correct type of logs attribute in ResultDataResponse

---

src/backend/base/langflow/template/utils.py

- Fix bug where the Update icon appeared when submitting the same code as before.
Help: @anovazzi1

fix: update appearing when sending the same code

---

poetry.lock
pyproject.toml
src/backend/base/poetry.lock
src/backend/base/pyproject.toml

This pull request updates the package versions for langflow and langflow-base to 1.0.10 and 0.0.86 respectively.

chore(pyproject.toml): update package versions for langflow and langflow-base to 1.0.10 and 0.0.86 respectively

---

src/frontend/src/modals/newFlowModal/index.tsx

This commit adds new examples to the newFlowModal component for Sequential Agent, Hierarchical Agent, and Complex Agent. Each example is rendered as an UndrawCardComponent with the corresponding flow data. This enhancement provides users with more options when creating new flows.

feat: Add newFlowModal examples for Sequential Agent, Hierarchical Agent, and Complex Agent

---

src/backend/base/langflow/components/agents/CrewAIAgent.py
src/backend/base/langflow/components/helpers/HierarchicalTask.py
src/backend/base/langflow/components/helpers/SequentialTask.py

The code changes modify the `SequentialTaskComponent` in the `SequentialTask.py` file. The `MessageTextInput` inputs are replaced with `MultilineInput` inputs to allow for multiline descriptions and expected outputs. This change improves the user experience and provides more flexibility in input handling.

fix(crewai): replace MessageTextInput with MultilineInput

---

poetry.lock
pyproject.toml
src/backend/base/langflow/components/tools/YfinanceTool.py

feat: Add YFinanceTool component for interacting with Yahoo Finance News

---

src/backend/base/langflow/initial_setup/starter_projects/Complex Agent.json

This pull request includes two commits. The first commit updates the project, while the second commit adds a new complex agent starter project. These changes aim to improve the functionality and provide a starting point for more advanced agent development.

feat: add new complex agent starter project

---

src/backend/base/langflow/initial_setup/starter_projects/Hierarchical Agent.json
src/frontend/src/components/ui/button.tsx

- Fix issue where loading button is misaligned in smaller buttons

fix: loading on small buttons

---

src/backend/base/langflow/initial_setup/starter_projects/Complex Agent.json
src/backend/base/langflow/initial_setup/starter_projects/Sequential Agent.json

Updates Agent starter projects

fix: update projects with new components

---

poetry.lock
pyproject.toml

chore: Update langwatch to 0.1.10

---

src/backend/base/langflow/services/tracing/langwatch.py

Adds conditions to not run Langwatch trace if it isn't ready

fix: return in case langwatch is not ready

---

README.PT.md
README.ja.md
README.md
README.zh_CN.md

I created Japanese translated README.

docs: add Japanese README

---

docs/docs/Integrations/integrations-langwatch.md

Fixing the link to Langwatch.
Updated link from langwatch.com to langwatch.ai

docs: Fixing integrations-langwatch.md

---

.github/workflows/ci.yml

ci: update path-filter job condition in ci.yml

---

src/backend/base/langflow/services/cache/service.py

Change base class to support cache refactor.

fix(cache): change base class of RedisCache from CacheService to AsyncBaseCacheService

---

src/frontend/src/modals/apiModal/utils/get-widget-code.tsx

This PR updates the langflow-embedded-chat dependency to version 1.0.4. This update includes markdown support

chore: Update langflow-embedded-chat to v1.0.4

---

src/backend/base/langflow/components/models/GroqModel.py

This PR adds a fetch method in Groq component to check for all available models in their API, the component will check for changes in the `groq_api_key` `model_name` and `groq_api_base` as triggers to fetch the API.

feat: add method and refresh button to fetch Groq models

---

.github/workflows/ci.yml

ci: fix set-ci-condition job

---

src/backend/base/langflow/components/models/OllamaModel.py

fix: Ollama model component parameter

---

.github/workflows/ci.yml

Adds debug info in the ci condition.

ci: add debug info

---

Makefile
poetry.lock
pyproject.toml
src/backend/base/pyproject.toml

Also add a new command in Makefile to patch versions.

chore: bump langflow and langflow-base versions to 1.0.13 and 0.0.89 respectively

---

docs/docs/Workspace/workspace-api.md
docs/docusaurus.config.js

This pull request fixes the issue where videos were not showing on the documentation page. The problem was caused by a missing configuration in the code. This PR adds the necessary configuration to ensure that videos are displayed correctly.

fix: videos not showing on docs

---

README.KR.md

The term "Flow" should be transliterated for smoother communication, and an explanation of the unfamiliar term "흐름 (Flow)" has been added for Koreans.

docs: update korean readme

---

src/backend/base/langflow/api/v1/users.py

This pull request includes
* improved http response messages on the api

fix: log messages

---

src/backend/base/langflow/components/prototypes/CreateData.py

Update to generate data correctly

fix: update CreateData.py

---

poetry.lock
src/backend/base/pyproject.toml

chore: update package version to 0.0.91

---

src/backend/base/langflow/base/agents/agent.py
src/backend/base/langflow/components/agents/OpenAIToolsAgent.py
src/backend/base/langflow/components/agents/ToolCallingAgent.py

fix: tool calling and openai tools do not include chat history

---

poetry.lock
src/backend/base/pyproject.toml

chore: update package version to 0.0.92

---

.github/workflows/python_test.yml
.github/workflows/typescript_test.yml

Improve readability of workflow test titles

ci: improve test jobs titles

---

.github/workflows/release.yml

fix: update curl command in release workflow to use correct endpoint

---

src/frontend/src/icons/athena/athena.jsx
src/frontend/src/icons/athena/index.tsx
src/frontend/src/utils/styleUtils.ts

Add a new component called AthenaComponent that renders an SVG icon for Athena. This component is imported from the newly created file "athena.jsx" in the "icons/athena" directory. Additionally, an export for the AthenaIcon component is added in the "icons/athena/index.tsx" file.

feat: Add Athena icon component

---

src/backend/base/langflow/api/v1/endpoints.py
src/backend/base/langflow/custom/custom_component/base_component.py
src/backend/base/langflow/custom/custom_component/custom_component.py
src/backend/base/langflow/custom/directory_reader/directory_reader.py
src/backend/base/langflow/custom/utils.py
src/backend/tests/unit/test_custom_component.py
src/backend/tests/unit/test_helper_components.py

Update code to be a private variable

refactor: update code references to use _code instead of code

---

src/frontend/src/pages/MainPage/components/componentsComponent/index.tsx

fix: select all checkbox not changing when changing folders

---

src/backend/base/langflow/api/v1/flows.py

- Fix flow export endpoint exporting a folder-like structure when the payload is just one flow

fix: flow export endpoint exporting folder

---

src/backend/base/langflow/components/helpers/__init__.py
src/backend/base/langflow/components/helpers/component_code_validator.py
src/backend/base/langflow/components/tools/ValidateComponentTool.py
src/backend/base/langflow/custom/utils.py
src/backend/base/langflow/io/__init__.py
src/backend/base/langflow/schema/data.py

This pull request adds the `ComponentCodeValidator` class to the `helpers` module in the `langflow/components` package. The `ComponentCodeValidator` class is responsible for validating the code of a component. It enhances the functionality of the application by providing code validation capabilities.

feat: add Component Code Validator component and Tool

---

.github/workflows/typescript_test.yml

This should fix flaky frontend tests

ci: integrate retry mechanism in Playwright tests to improve stability and handle potential failures

---

README.md

Minor changes to text as submitted by Scott based on feedback

docs: minor changes on readme text

---

docs/docs/Settings/settings-global-variables.md

Added a section to the documentation explaining how global variables should be handled

docs:  variable global precautions

---

src/backend/base/langflow/services/database/models/vertex_builds/crud.py

Function was not calling db.exec on the statement.

fix: correct vertex build delete function

---

src/backend/base/langflow/components/embeddings/OllamaEmbeddings.py
src/backend/base/langflow/components/models/OllamaModel.py

Ollama changed from ollama.ai to ollama.com

refactor: Update Ollama Model + Links

---

.github/workflows/py_autofix.yml

Adds a step that adds a comment to a PR that changes the poetry lock file

chore: Add step to diff poetry.lock in py_autofix workflow.

---

.github/workflows/release.yml

Adds condition to avoid running CI tests unnecessarily.

ci: Add condition to execute CI workflow for release package.

---

poetry.lock
src/backend/base/poetry.lock

chore: update lock files with new versions

---

src/backend/base/langflow/graph/edge/base.py

Small improvement for consistency

refactor: Simplify __repr__ method in Edge and ContractEdge classes.

---

src/backend/base/langflow/graph/graph/base.py
src/backend/base/langflow/graph/graph/utils.py

add stop condition in recursive function

refactor: Prevent infinite loop in get_successors function.

---

src/backend/base/langflow/graph/edge/base.py
src/backend/base/langflow/graph/graph/base.py
src/backend/base/langflow/graph/vertex/base.py
src/backend/base/langflow/graph/vertex/types.py

This PR also adds the `is_cycle` attribute to the Edge classes

refactor: rename ContractEdge to CycleEdge

---

src/backend/base/langflow/services/store/service.py

Adds a timeout to the StoreService so that it does not fail unexpectedly

feat: Add timeout parameter to HTTP request in StoreService.

---

src/frontend/src/components/objectRender/index.tsx
src/frontend/src/components/parameterRenderComponent/index.tsx
src/frontend/src/constants/constants.ts
src/frontend/src/types/api/index.ts
src/frontend/src/utils/utils.ts

this pull request adds back a table field type that were removed by mistake by a merge conflict, it also adds a default formatter to columns

fix: Add TableNodeComponent and set default formatter type

---

src/backend/tests/test_endpoints.py

Makes test less prone to errors

test: Fix assertion in test_get_vertices function.

---

src/backend/base/langflow/__main__.py
src/backend/base/langflow/api/v1/schemas.py
src/backend/base/langflow/services/settings/base.py
src/backend/base/langflow/utils/util.py

Adds auto save option that works with `LANGFLOW_AUTO_SAVE` env var and by setting it through the cli

feat: add auto_save option to Settings and CLI

---

src/backend/base/langflow/initial_setup/load.py
src/backend/base/langflow/initial_setup/starter_projects/__init__.py
src/backend/base/langflow/initial_setup/starter_projects/basic_prompting.py
src/backend/base/langflow/initial_setup/starter_projects/blog_writer.py
src/backend/base/langflow/initial_setup/starter_projects/complex_agent.py
src/backend/base/langflow/initial_setup/starter_projects/document_qa.py
src/backend/base/langflow/initial_setup/starter_projects/hierarchical_tasks_agent.py
src/backend/base/langflow/initial_setup/starter_projects/memory_chatbot.py
src/backend/base/langflow/initial_setup/starter_projects/sequential_tasks_agent.py
src/backend/base/langflow/initial_setup/starter_projects/vector_store_rag.py
src/backend/tests/unit/test_data_components.py

Add starter projects functions and graphs

feat: add starter project graphs

---

src/backend/base/langflow/api/router.py
src/backend/base/langflow/api/v1/__init__.py
src/backend/base/langflow/api/v1/flows.py
src/backend/base/langflow/api/v1/starter_projects.py
src/backend/base/langflow/graph/vertex/base.py
src/backend/tests/test_endpoints.py

Adds an endpoint to get starter projects. This is to be merged after #3369 and is to be used to create tests only for now

feat: add endpoint to get starter projects

---

src/backend/tests/unit/graph/graph/test_runnable_vertices_manager.py

test: Add client fixture override for runnable vertices manager unit test.

---

src/backend/base/langflow/initial_setup/starter_projects/Sequential Agent.json
src/backend/base/langflow/initial_setup/starter_projects/sequential_tasks_agent.py

Update starter project to use the new SequentialTaskAgentComponent

feat: update sequential tasks agent starter project

---

docs/docs/Settings/settings-global-variables.md

Update old term 'Variables and Secrets' to 'Global Variables'
This PR addresses an aspect of issue #3462

docs: update deprecated term 'variables and secrets'

---

poetry.lock
pyproject.toml
src/backend/base/pyproject.toml

build: Update langflow-base and langflow versions to 0.0.94 and 1.0.16 respectively.

---

src/frontend/src/style/applies.css

Fix update button appearing on the bototm of the node title instead of on the side

fix: appearance of update button on title

---

.github/workflows/ci.yml

Fix formatting that might be causing issues

ci: Simplify needs array in ci_success job

---

.github/workflows/ci.yml
.github/workflows/python_test.yml

Make sure a version is passed to the workflow_call

ci: add python-versions input parameter to workflow

---

.github/workflows/nightly_build.yml

adds empty nightly workflow build so I can test it from https://github.com/langflow-ai/langflow/pull/3553

ci: add empty nightly workflow

---

src/backend/base/langflow/api/v1/chat.py
src/backend/base/langflow/services/tracing/service.py

This fixes missing await to trace_context

fix: add await to to_thread call

---

src/backend/base/langflow/api/v1/endpoints.py
src/backend/base/langflow/helpers/flow.py
src/backend/base/langflow/services/auth/utils.py

Release Session after using it to release the database.

refactor: release session after select

---

Makefile
docker/dev.Dockerfile
docker/dev.docker-compose.yml
docker/dev.start.sh

This PR aims to provide developers with a simple way to develop using containers, making it easy to install packages, add new services, and switch between Python versions.

build: update docker for dev environment

---

src/backend/base/langflow/components/embeddings/GoogleGenerativeAIEmbeddings.py

Error in name of the component.
fixes #3576

fix: Component name Corrected

---

src/backend/base/langflow/__main__.py
src/backend/base/langflow/services/settings/base.py
src/backend/base/langflow/utils/util.py

Fix the auto_saving_interval type
Also this is not a real time application we don't need to save sub second so the default interval is set to 1 second

fix: auto_saving_interval type

---

src/backend/base/langflow/components/tools/RetrieverTool.py
src/frontend/tests/scheduled-end-to-end/generalBugs-shard-12.spec.ts

This pull request will add retriever input types so it can be connected again. 
Additionally, frontend tests will be added as well.

fix: add retriever input_type on RetrieverToolComponent + tests

---

.github/workflows/conventional-labels.yml

remove the message from each PR. If the check fails, the reason is in the action logs

ci: make validate pull request action less verbose

---

src/frontend/src/pages/FlowPage/components/ParentDisclosureComponent/index.tsx
src/frontend/src/pages/FlowPage/components/extraSidebarComponent/SidebarCategoryComponent/index.tsx
src/frontend/src/pages/FlowPage/components/extraSidebarComponent/index.tsx
src/frontend/src/types/components/index.ts

Modularized the categories to reduce code

refactor: modularized categories

---

src/frontend/src/customization/components/custom-api-generator.tsx
src/frontend/src/customization/hooks/use-custom-api-code.ts
src/frontend/src/modals/IOModal/components/chatView/chatInput/components/buttonSendWrapper/index.tsx
src/frontend/src/modals/IOModal/components/chatView/chatInput/components/textAreaWrapper/index.tsx
src/frontend/src/modals/IOModal/components/chatView/chatInput/index.tsx
src/frontend/src/modals/apiModal/index.tsx
src/frontend/src/modals/apiModal/utils/get-curl-code.tsx
src/frontend/src/modals/apiModal/utils/get-js-api-code.tsx
src/frontend/src/modals/apiModal/utils/get-python-api-code.tsx
src/frontend/src/modals/apiModal/utils/get-python-code.tsx
src/frontend/src/modals/apiModal/utils/get-widget-code.tsx
src/frontend/src/modals/apiModal/utils/tabs-array.tsx
src/frontend/src/stores/tweaksStore.ts
src/frontend/src/types/tweaks/index.ts
src/frontend/src/types/zustand/tweaks/index.ts

Refactored the API code to improve readability and maintainability. Added new types for `getCodes` and `initialSetup` on the Tweaks store. Created a custom API generator component on top of the CodeTabsComponent. The custom API generator component allows users to generate different API codes based on their needs. Updated the tabs array to receive an object instead of individual codes. Updated every code to get the correct props. Updated the Tweaks store to handle the refactored `getCodes` and `createTabsArray` functions. Removed the `saveLoading` variable from the chat and the `initialSetup` function that couldn't be null.

refactor: custom api code generator and fix chat locking when saving

---

docs/docusaurus.config.js
docs/package-lock.json
docs/package.json
docs/yarn.lock

This pull request adds Google Tag Manager to the project. It includes the necessary dependencies and configuration changes to integrate Google Tag Manager into the project.

feat: add gtm to docs

---

.github/workflows/lint-py.yml

Small change to maybe fix lint ci

chore: Update lint workflow to use poetry for running Mypy

---

src/frontend/tests/end-to-end/filterEdge-shard-0.spec.ts
src/frontend/tests/end-to-end/filterSidebar.spec.ts
src/frontend/tests/scheduled-end-to-end/filterEdge-shard-1.spec.ts
src/frontend/tests/scheduled-end-to-end/tableInputComponent.spec.ts

This pull request includes refactoring some tests to improve readability. 
Additionally, an end-to-end test has been added to ensure proper interaction with the table input component.

tests: add new tests to tableComponent

---

src/backend/tests/integration/components/inputs/test_text_input.py
src/backend/tests/integration/components/outputs/test_text_output.py
src/backend/tests/integration/utils.py

Added new components tests for input and output text

ci: add tests for text input/output components

---

src/frontend/src/App.css

The transition property in App.css has been updated to only transition the color property instead of all properties. This change improves performance by reducing unnecessary transitions.

fix: remove edges glitch

---

src/frontend/tests/end-to-end/decisionFlow.spec.ts

✨ (decisionFlow.spec.ts): Remove unnecessary code related to connection 4 and improve flow by adding a new connection for prompt input user message
📝 (decisionFlow.spec.ts): Update test to fill in a different message in the chat playground and verify a different emoji response

tests: fix decision flow tests - conditional router component

---

src/frontend/tests/core/integrations/Vector Store.spec.ts

✨ (Vector Store.spec.ts): Add AstraVectorStoreComponent to support Astra DB integration for vector storage and search capabilities.

tests: update astraDB integration test

---

src/frontend/tests/core/integrations/Vector Store.spec.ts

📝 (Vector Store.spec.ts): Remove unnecessary code block related to AstraVectorStoreComponent class and its methods
♻️ (Vector Store.spec.ts): Refactor test file to remove unused imports and clean up unnecessary code blocks
🔧 (Vector Store.spec.ts): Refactor code to include conditional logic based on the presence of "dev" in ASTRA_DB_API_ENDPOINT environment variable
🔧 (Vector Store.spec.ts): Add function extractAndCleanCode to extract and clean code content from HTML element

tests: update astraDB test to ensure will run dev mode only when necessary

---

src/frontend/package-lock.json
src/frontend/package.json

this pull request fix a bug on radix primitives:
https://github.com/radix-ui/primitives/issues/2122

fix: Update @radix-ui/react-dialog to version 1.1.1

---

poetry.lock
pyproject.toml
src/backend/base/pyproject.toml

chore: bump langflow versions

---

.github/workflows/docker-build.yml
.github/workflows/nightly_build.yml
.github/workflows/release_nightly.yml

Adds step to push to ghcr as well as docker.
https://github.com/langflow-ai/langflow/pkgs/container/langflow-nightly

ci: adds step to push to ghcr 

---

.github/workflows/docker-build.yml
.github/workflows/nightly_build.yml
.github/workflows/python_test.yml
.github/workflows/release_nightly.yml
.github/workflows/typescript_test.yml
poetry.lock
scripts/ci/pypi_nightly_tag.py
scripts/ci/update_lf_base_dependency.py
scripts/ci/update_pyproject_version.py
scripts/update_dependencies.py
src/backend/base/pyproject.toml

Fixes some tag issues, prepends `v` to tags, makes more robust to partial workflows failures. 
Successful run (though, tests failed, and I had it such that release didn't depend on tests) https://github.com/langflow-ai/langflow/actions/runs/10910359241

ci: tag fixes and robustness to workflow failures

---

poetry.lock
pyproject.toml

This PR fixes the duckduckgo-search dependency
Fixes: #3856

fix: duckduckgo-search

---

src/backend/base/langflow/initial_setup/starter_projects/Vector Store RAG.json

https://docs.langflow.org/tutorials/rag-with-astradb -> https://docs.langflow.org/starter-projects-vector-store-rag

docs: fix link in vector store rag description

---

src/frontend/src/pages/FlowPage/components/PageComponent/index.tsx

This pull request fixes an issue in the PageComponent where unnecessary re-renders were occurring. The `edgeTypes` in the PageComponent have also been updated to use a constant object instead of hardcoding the value. This improves code readability and maintainability.

fix: unnecessary re-renders in PageComponent and update edgeTypes

---

src/backend/base/langflow/components/memories/AstraDBChatMemory.py
src/backend/base/langflow/components/vectorstores/AstraDB.py

reorder parameters for Astra components and hide the token for DS users (when ASTRA_ENHANCED is true)

refactor: Update parameter order and hide token for DS users

---

pyproject.toml

This is so that debugging works properly

fix: Add 'langflow' to workspace configuration

---

src/frontend/tests/extended/features/store-shard-1.spec.ts
src/frontend/tests/extended/features/store-shard-3.spec.ts

✨ (store-shard-1.spec.ts): Improve test case for liking and adding components and flows by adding more specific selectors and reducing timeout durations for better performance and reliability
✨ (store-shard-3.spec.ts): Enhance test case for filtering by type by adding more specific selectors and reducing timeout durations for better performance and reliability

tests: improve tests of store

---

CONTRIBUTING.md
Makefile

This pull request updates the CONTRIBUTING.md file to reflect the new development setup and remove docker-compose instructions. It also removes the Poetry check, updates the uv command, and removes the dev target from the Makefile.
Removed docker mentions until we update the setup.

docs: Update CONTRIBUTING.md to mention uv

---

src/backend/base/langflow/components/output_parsers/OutputParser.py

This pull request refactors the error handling in the OutputParser component to improve code readability. The changes include updating the error messages and removing unnecessary else statements. These improvements enhance the maintainability of the codebase and make it easier to understand and debug any potential issues.

chore: Refactor error handling in OutputParser for improved readability

---

.pre-commit-config.yaml

chore: Add 'types' field to pre-commit hooks for ruff check and format

---

src/backend/base/langflow/api/v1/chat.py

Fixes component build by adding user_id to parameters

fix: add user_id to component parameters to fix build

---

.github/workflows/docker-build.yml
.github/workflows/integration_tests.yml
.github/workflows/typescript_test.yml
Makefile
pyproject.toml
scripts/factory_restart_space.py
src/backend/base/pyproject.toml
src/frontend/playwright.config.ts

This pull request removes the '--no-update' flag from the 'uv lock' commands in the Makefile, allowing dependencies to be updated. It also removes Poetry references from pyproject.toml and updates the project metadata, including maintainers and repository URLs.

chore: removes Poetry references from pyproject.toml and updates the project metadata

---

pyproject.toml
src/backend/base/pyproject.toml
uv.lock

release: bump main 1.0.19 and base 0.0.97

---

src/backend/base/langflow/components/data/Directory.py
src/backend/tests/unit/test_data_components.py

Fixes https://github.com/langflow-ai/langflow/issues/4012
- fix: modified DirectoryDataComponent to support user defined custom file types
- test_data_components.py: Updated 'test_directory_component_build_with_multithreading' to expect an extra argument

fix: modified DirectoryDataComponent to support user defined custom file types

---

pyproject.toml
src/backend/base/pyproject.toml
uv.lock

Reverts langflow-ai/langflow#4029 until workflow is fixed

Revert "release: bump main 1.0.19 and base 0.0.97"

---

src/backend/base/langflow/components/prompts/LangChainHubPrompt.py

This pull request fixes an error message that occurs when the component is first added to the canvas, due to a lack of API key available.

FIX: don't error in Langchain Hub Component when adding to canvas

---

src/backend/base/langflow/services/tracing/langfuse.py

Prevents the langfuse from raising exceptions when it shouldn't be initialized.

fix: prevent langfuse initialization

---

src/backend/base/langflow/base/vectorstores/utils.py
src/backend/base/langflow/components/deactivated/SplitText.py
src/backend/base/langflow/components/helpers/CSVtoData.py
src/backend/base/langflow/components/helpers/SplitText.py
src/backend/base/langflow/components/prompts/LangChainHubPrompt.py
src/backend/base/langflow/components/tools/GleanSearchAPI.py
src/backend/base/langflow/components/tools/PythonCodeStructuredTool.py
src/backend/base/langflow/components/tools/SearXNGTool.py
src/backend/base/langflow/custom/code_parser/code_parser.py
src/backend/base/langflow/custom/custom_component/component.py
src/backend/base/langflow/custom/utils.py
src/backend/base/langflow/graph/graph/utils.py
src/backend/base/langflow/helpers/flow.py
src/backend/base/langflow/logging/logger.py
src/backend/base/langflow/memory.py
src/backend/base/langflow/services/factory.py
src/backend/base/pyproject.toml

Add ruff rules for perf (PERF)

ref: Add ruff rules for perf (PERF)

---

src/backend/base/langflow/components/astra_assistants/util.py

refactor: change model name extraction to use list comprehension

---

src/backend/base/langflow/components/deactivated/MergeData.py
src/backend/base/langflow/components/helpers/MergeData.py

This PR addresses a functionality issue in the Merge Data component. Previously, the component was not functioning as intended. The changes implement the following improvements:
1. Common Data fields are now correctly merged.
2. Unique rows from a different Data sample are properly added as new rows.
Here is an example of usage:

fix: refactoring Merge Data component 

---

src/backend/base/langflow/graph/graph/base.py
src/backend/base/langflow/graph/vertex/base.py
src/backend/base/langflow/graph/vertex/types.py
src/backend/base/langflow/main.py
src/backend/base/langflow/services/telemetry/service.py
src/backend/base/langflow/services/tracing/base.py
src/backend/base/langflow/services/tracing/service.py
src/backend/base/pyproject.toml

Add ruff rules for asyncio tasks references (RUF006)

ref: Add ruff rules for asyncio tasks references (RUF006)

---

pyproject.toml
src/backend/base/pyproject.toml
uv.lock

version: upgrade to 1.0.19 and 0.0.97

---

docker/build_and_push.Dockerfile

Adds missing readme file to dockerfile

build: add readme to dockerfile

---

src/backend/tests/unit/api/v1/test_variable.py
src/backend/tests/unit/base/tools/test_component_toolkit.py
src/backend/tests/unit/components/models/test_ChatOllama_component.py
src/backend/tests/unit/graph/edge/test_edge_base.py
src/backend/tests/unit/graph/graph/test_callback_graph.py
src/backend/tests/unit/test_api_key.py
src/backend/tests/unit/test_cli.py
src/backend/tests/unit/test_database.py
src/backend/tests/unit/test_files.py
src/backend/tests/unit/test_frontend_nodes.py
src/backend/tests/unit/test_messages_endpoints.py
src/backend/tests/unit/test_process.py
src/backend/tests/unit/test_user.py

ref: Fix unused args in tests

---

src/backend/tests/integration/components/output_parsers/test_output_parser.py

Add missing `__init__.py` files in tests

ref: Add missing __init__.py files in tests

---

src/backend/base/langflow/components/prototypes/CreateData.py

- Replaced global variables with local variables or class attributes.
- Enhanced code readability and reduced potential side effects.

Refactor: Eliminate Global Variables for Improved Code Maintainability_fix_release

---

src/backend/base/langflow/initial_setup/starter_projects/Blog Writer.json

This pull request updates the blog writer starter project

fix: Update example

---

src/backend/base/langflow/custom/utils.py

Fix add_extra_fields() issue introduced by https://github.com/langflow-ai/langflow/pull/4126

fix: Fix add_extra_fields()

---

src/backend/base/langflow/components/langchain_utilities/SQLDatabase.py
src/backend/base/langflow/components/prototypes/SQLExecutor.py

🔧 (SQLDatabase.py): update build method signature to accept additional keyword arguments for future extensibility
🔧 (SQLExecutor.py): update method signature to accept additional keyword arguments for future extensibility
#4223

fix: unexpected keyword argument 'code' -> SQLExecutor and SQLDatabase

---

pyproject.toml
uv.lock

chore: apply changes to pyproject.toml from v1.0.19.1

---

src/backend/base/pyproject.toml
src/backend/tests/conftest.py
uv.lock

Update Fastapi and add http2 support in httpx

chore: update dependencies and enable HTTP/2 support for AsyncClient in tests

---

src/frontend/src/style/index.css
src/frontend/tailwind.config.mjs

new colors:
```json
{
"colors": {
"light": {
"foreground": "hsl(0, 0, 0)",
"background": "hsl(0, 0, 100)",
"muted": "hsl(240, 5, 96)",
"mutedForeground": "hsl(240, 4, 46)",
"card": "hsl(0, 0, 100)",
"cardForeground": "hsl(0, 0, 0)",
"popover": "hsl(0, 0, 100)",
"popoverForeground": "hsl(0, 0, 0)",
"border": "hsl(240, 6, 90)",
"input": "hsl(240, 6, 90)",
"primaryForeground": "hsl(0, 0, 100)",
"primary": "hsl(0, 0, 0)",
"secondary": "hsl(0, 0, 100)",
"secondaryForeground": "hsl(240, 4, 16)",
"accent": "hsl(240, 5, 96)",
"accentForeground": "hsl(0, 0, 0)",
"destructive": "hsl(0, 72, 51)",
"destructiveForeground": "hsl(0, 0, 100)",
"ring": "hsl(0, 0, 0)",
"primaryHover": "hsl(240, 4, 16)",
"secondaryHover": "hsl(240, 6, 90)",
"placeholderForeground": "hsl(240, 5, 65)",
"canvas": "hsl(240, 5, …
```

feat: theme color updates

---

src/frontend/src/style/index.css

fix: restore radius

---

src/backend/base/langflow/graph/graph/base.py
src/backend/base/langflow/load/load.py
src/backend/base/langflow/processing/process.py

Remove sync `Graph.run()` and do asyncio loop creation in `run_flow_from_json`.

fix: Remove sync Graph.run()

---

src/backend/base/langflow/events/event_manager.py
src/backend/base/langflow/schema/artifact.py

This pull request includes several changes to enhance the encoding of callable objects and improve logging for JSON conversion errors. The most important changes involve the introduction of custom encoders for callable objects and the application of these encoders in various functions.
Enhancements to encoding and logging:
* [`src/backend/base/langflow/schema/artifact.py`](diffhunk://#diff-543016d7d5efb105bfb8a0d45338bca17317c2c2f2aed95b5aed00aaffacbd0dR54-R60): Added `encode_callable` function and `CUSTOM_ENCODERS` dictionary to handle the encoding of callable objects.
* [`src/backend/base/langflow/events/event_manager.py`](diffhunk://#diff-6943c2990f2f92bbca27d299999e2044355cf34a348fea63f172846e6dbdd88eL56-R57): Updated `jsonable_encoder` calls to use the new `CUSTOM_ENCODERS` for …

fix: make JSON serialization work with Callable objects

---

src/backend/base/langflow/components/embeddings/util/__init__.py
src/backend/base/langflow/components/tools/__init__.py
src/backend/base/langflow/utils/validate.py

This PR suppresses LangChainDeprecationWarning messages to reduce log noise.

fix: suppress LangChainDeprecationWarning messages

---

.vscode/launch.json
.vscode/tasks.json

This PR introduces a new task for installing the backend in the VSCode tasks configuration and updates the launch configuration to include a pre-launch task for backend installation. This streamlines the development process by ensuring the backend is installed before launching the application.

chore: Add backend installation tasks to VSCode configuration

---

src/frontend/tests/core/integrations/decisionFlow.spec.ts

This pull request enhances the stability and error handling of the test functions in `src/frontend/tests/core/integrations/decisionFlow.spec.ts`. The most important changes include improving the `waitForElement` function, adding retries and stability checks to the `moveElementByX` function, and making adjustments to mouse movement steps.
Enhancements to test functions:
* [`waitForElement`](diffhunk://#diff-32cfd0432ab2aec3f25fcbd2135eee6c67de9270c07de115b71f57b7ec39a321L4-R54): Enhanced with better error handling, retries, and stability checks, ensuring elements are fully rendered and interactive before proceeding.
* [`moveElementByX`](diffhunk://#diff-32cfd0432ab2aec3f25fcbd2135eee6c67de9270c07de115b71f57b7ec39a321L105-R160): Added retries, stability checks, and more granular mouse …

test: fix decision flow test

---

src/backend/tests/integration/backward_compatibility/test_starter_projects.py
src/backend/tests/integration/components/assistants/test_assistants_components.py
src/backend/tests/integration/components/astra/test_astra_component.py
src/backend/tests/integration/components/helpers/test_parse_json_data.py
src/backend/tests/integration/components/inputs/test_chat_input.py
src/backend/tests/integration/components/inputs/test_text_input.py
src/backend/tests/integration/components/output_parsers/test_output_parser.py
src/backend/tests/integration/components/outputs/test_chat_output.py
src/backend/tests/integration/components/outputs/test_text_output.py
src/backend/tests/integration/components/prompts/test_prompt.py
src/backend/tests/integration/flows/test_basic_prompting.py
src/backend/tests/unit/components/agents/test_agent_component.py
src/backend/tests/unit/components/agents/test_tool_calling_agent.py
src/backend/tests/unit/components/prototypes/test_create_data_component.py
src/backend/tests/unit/components/prototypes/test_update_data_component.py
src/backend/tests/unit/events/test_event_manager.py
src/backend/tests/unit/graph/graph/test_base.py
src/backend/tests/unit/schema/test_schema_message.py
src/backend/tests/unit/test_data_components.py
src/backend/tests/unit/test_database.py
src/backend/tests/unit/test_initial_setup.py
src/backend/tests/unit/test_process.py

Remove useless pytest.mark.asyncio

ref: Remove useless pytest.mark.asyncio

---

.github/workflows/codspeed.yml

This PR modifies the Codspeed workflow to exclude tests that require an API key and allows the tests to run in parallel. This change aims to improve the efficiency of the testing process by reducing unnecessary test executions and speeding up the overall workflow.

ci: Update Codspeed workflow to exclude api_key_required tests and enable parallel execution

---

src/frontend/src/components/codeTabsComponent/ChatCodeTabComponent.tsx
src/frontend/src/components/codeTabsComponent/index.tsx
src/frontend/src/components/ui/tabs.tsx
src/frontend/src/style/index.css

refactor: Design updates to API Dialog and Code Block for uplift sweep

---

docs/docusaurus.config.js
docs/package-lock.json
docs/package.json

Add the [Docusaurus Client Redirect Plugin](https://docusaurus.io/docs/api/plugins/@docusaurus/plugin-client-redirects) to handle redirects for deleted docs pages.
Tested and works:

Feat: Add Docusaurus redirect capability

---

src/backend/base/langflow/__main__.py

Adds a new CLI option to show the current langflow version.
```
uv run langflow --version
```

feat: add cli option to display version

---

src/frontend/src/components/codeTabsComponent/components/tweakComponent/index.tsx

makes it so there is no longer the black on black

fix: Fix tweaks text color

---

src/frontend/src/pages/FlowPage/components/PageComponent/index.tsx

The cursor highlighting feature was removed from the PageComponent in order to simplify the code and improve performance.

refactor: Remove cursor highlighting feature

---

.github/changes-filter.yaml
.github/workflows/ci.yml

This pull request updates the CI configuration to include new path filters for frontend and component changes, ensuring that the appropriate tests are triggered based on the modified files. The changes also refine the conditions under which backend tests and linting are executed, improving the overall efficiency of the CI process.

ci: Update CI path filters for frontend tests

---

README.md

New Logo is not updated in README

Fix: New Logo is not updated in README.md

---

README.md

Reverts langflow-ai/langflow#4589

Revert "Fix: New Logo is not updated in README.md"

---

src/frontend/src/CustomNodes/GenericNode/components/NodeDescription/index.tsx
src/frontend/src/CustomNodes/NoteNode/index.tsx
src/frontend/src/components/codeTabsComponent/index.tsx
src/frontend/src/style/classes.css
src/frontend/src/style/index.css
src/frontend/tailwind.config.mjs

This pull request includes several updates to the frontend codebase, focusing on improving the styling and consistency of the application. The most important changes include updates to CSS classes, modifications to the Tailwind configuration, and adjustments to the component styles.
* [`src/frontend/src/style/classes.css`](diffhunk://#diff-20389fa3f9c927b863b7941b7a81e87d4d6d8f53f049354aaf1863fa1a3ac5ebR252-R263): Added color styling for code blocks and list markers.
* [`src/frontend/src/style/index.css`](diffhunk://#diff-90e2b07b21bd53ac0fe04b56353e8b37e8ba1f3034f51e66306a1ff010ab4437L102-R104): Updated CSS variables for code background, description background, and foreground colors. [[1]](diffhunk://#diff-90e2b07b21bd53ac0fe04b56353e8b37e8ba1f3034f51e66306a1ff010ab4437L102-R104) …

fix: update notes border color, update node and notes code block background

---

src/frontend/src/components/appHeaderComponent/components/FlowMenu/index.tsx

This pull request includes a small but important change to the `src/frontend/src/components/appHeaderComponent/components/FlowMenu/index.tsx` file. The change updates the CSS class for the `DropdownMenuContent` component to ensure proper theming.
* [`src/frontend/src/components/appHeaderComponent/components/FlowMenu/index.tsx`](diffhunk://#diff-42746641fae2fdd25fdcc62f3cad904bc33ee6f528ef69f20cc56c6ff35ddb95L151-R151): Changed the `DropdownMenuContent` class from `dark:bg-black` to `dark:bg-background` to improve dark mode theming.

fix: Update background color in FlowMenu dropdown

---

src/frontend/tests/core/features/componentHoverAdd.spec.ts
src/frontend/tests/core/features/folders.spec.ts

this pull request improves the performance of the folder related tests

refactor: Improve time and use waitForSelector in folder tests

---

src/frontend/tests/core/features/group.spec.ts
src/frontend/tests/core/features/keyboardComponentSearch.spec.ts

remove timeouts to improve performance

refactor: improve tests for group and keyBoardComponentSearch tests

---

src/frontend/tests/core/features/logs.spec.ts

This pull request includes commits that improve the performance in the logs test and format the code. The changes optimize the code execution in the logs and ensure consistent code formatting throughout the project.

refactor: Improve performance in logs.spec.ts and format code

---

Makefile

This PR remove unnecessary target from Makefile to simplify it.

chore: remove unnecessary target from makefile

---

src/backend/base/langflow/api/utils.py
src/backend/base/langflow/api/v1/store.py
src/backend/base/langflow/services/store/utils.py

Make check_langflow_version async

ref: Make check_langflow_version async

---

src/frontend/src/pages/FlowPage/components/nodeToolbarComponent/index.tsx

this pr fix a tool mode related bug that keeps the tool mode active after updating the component code

fix: reset tool mode after update component code

---

src/backend/base/langflow/components/processing/update_data.py
src/frontend/src/utils/styleUtils.ts

this pr adds an Icon to the UpdateDataComponent

feat: Add FolderSync icon to UpdateDataComponent in update_data.py

---

docs/docs/Configuration/configuration-custom-database.md

This pull request adds comprehensive instructions for configuring external databases, specifically PostgreSQL, in Langflow. The new documentation includes environment variable setup, connection string formats, and an example Docker setup for ease of use.

docs: add documentation for external database configuration

---

src/frontend/tests/core/integrations/decisionFlow.spec.ts

this pull tequst reduces the time of the test by more han 60%

refactor: Improve decision flow and remove timeouts

---

pyproject.toml
uv.lock

Better support for debugging in Cursor.

feat: Bump blockbuster to v1.1.1

---

src/frontend/tests/core/integrations/Blog Writer.spec.ts

refactor test code to improve test speed

refactor: improve test speed for Blog Writer integration

---

pyproject.toml

This pull request updates the `langflow-base` dependency in the `pyproject.toml` file from version 0.1.0 to 0.1.1, ensuring compatibility with the latest features and fixes.

chore: Update langflow-base dependency to version 0.1.1

---

src/backend/base/langflow/services/database/service.py

chore: set log level to debug

---

src/backend/base/langflow/components/notdiamond/notdiamond.py
src/frontend/package-lock.json

Hey Langflow team 👋 Thank you for approving previously the NotDiamond LLM router feature. This PR is a very small improvement on top of that to also expose the chosen model by the LLM router.
I've just extended the existing component with a new output field that's being populated after the LLM routing logic has run.
*If you’d like to learn more about our routing, check out [this example walkthrough video with Tomas](https://x.com/tomas_hk/status/1818296673749328199), our CEO. You can also
see how we work by using [our Chat app](https://chat.notdiamond.ai/),
learn more at [our website](https://www.notdiamond.ai/), or
[read our docs](https://notdiamond.readme.io/).

fix: Expose chosen model by NotDiamond router

---

.github/actions/install-playwright/action.yml
.github/workflows/python_test.yml
.github/workflows/typescript_test.yml
src/frontend/src/pages/SignUpPage/index.tsx

This pull request enhances the TypeScript test workflow by introducing a container image for Playwright, ensuring a consistent testing environment. It modifies the method of retrieving the Playwright version for accuracy and improves the caching strategy for Playwright binaries with restore keys. Additionally, the installation steps for Playwright have been refactored to handle dependencies more efficiently based on the cache status. These changes aim to streamline the testing process and reduce setup time.

ci: Update TypeScript test workflow for improved Playwright integration

---

.github/workflows/typescript_test.yml
src/frontend/tests/core/integrations/starter-projects.spec.ts

this pr fix an error generated by a merge commit with main

fix: starter-project was broken in main

---

src/frontend/tests/core/regression/generalBugs-shard-9.spec.ts

This pull request removes unnecessary wait timeouts in the regression test. The wait timeouts were causing delays in the test execution. Removing them improves the efficiency and speed of the test.

refactor: remove regression test timeouts

---

.github/workflows/typescript_test.yml
src/frontend/tests/core/unit/intComponent.spec.ts

This pull request includes refactoring of the `IntComponent` test and the `inputListComponent.spec.ts` test. The changes aim to improve the search reliability and performance of the tests.

Refactor: update intComponent tests for improved reliability and performance

---

src/frontend/tests/core/unit/codeAreaModalComponent.spec.ts

update test to improve performance

Refactor: improve codeAreaModalComponent.spec.ts

---

src/backend/base/langflow/api/v1/chat.py
src/backend/base/langflow/graph/utils.py

This commit fix the serialize_field function in utils.py to handle additional data types. It now properly serializes BaseModel objects and dictionaries by recursively calling the serialize_field function on their values. Additionally, it ensures that all other data types are converted to strings before returning.
#4862

Fix: prevent infinity bug on agent

---

.github/workflows/typescript_test.yml
src/frontend/tests/core/unit/inputListComponent.spec.ts
src/frontend/tests/core/unit/intComponent.spec.ts

this pr improves the test performance by removing unecessary timeouts

Refactor: inputListComponent.spec.ts to improve test reliability and performance

---

src/backend/base/langflow/initial_setup/starter_projects/Custom Component Maker.json
src/backend/tests/unit/test_initial_setup.py

Some URLs being used as context for the LLM were removed. 
Adjusted the URLs and added a few extra to enhance the LLM context.

fix: add missing component URLs in Component Maker 

---

.github/workflows/typescript_test.yml

This pull request enhances the clarity and consistency of the CI workflow by updating job and step names in the TypeScript test workflow file. The changes aim to provide clearer descriptions of each step's purpose, making the workflow easier to understand and maintain.

chore: Update CI workflow job and step names for clarity and consistency

---

src/frontend/src/components/core/parameterRenderComponent/components/inputListComponent/index.tsx
src/frontend/tests/core/unit/codeAreaModalComponent.spec.ts

This pull request refactors the `inputListComponent` to improve the ability to delete the first item. It adds a new `inputRef` reference and updates the rendering logic to handle the deletion of the first item properly. The changes include modifications to the input element, addition of a new button for adding new inputs, and updates to the click event handling for removing inputs.

Refactor: improve inputListComponent to enable deletion of the first item

---

src/backend/base/langflow/initial_setup/setup.py

fix: Fix get_default_folder_id

---

src/backend/base/langflow/initial_setup/starter_projects/Blog Writer.json
src/backend/base/langflow/initial_setup/starter_projects/Custom Component Maker.json
src/backend/base/langflow/initial_setup/starter_projects/Document Q&A.json
src/backend/base/langflow/initial_setup/starter_projects/Image Sentiment Analysis.json
src/backend/base/langflow/initial_setup/starter_projects/Market Research.json
src/backend/base/langflow/initial_setup/starter_projects/Vector Store RAG.json

This pull request includes various changes to the `Blog Writer.json` file to format array values consistently across the file. The most important changes include formatting adjustments for `output_types`, `inputTypes`, and `base_classes` arrays, as well as updates to code and method definitions.
Formatting adjustments:
* [`src/backend/base/langflow/initial_setup/starter_projects/Blog Writer.json`](diffhunk://#diff-9de3a1d797d0862ac56ae021ec51c8c9a28b5be0aafae1aad2bc307711b9bb0aL12-R21): Formatted `output_types` arrays to have each element on a new line. [[1]](diffhunk://#diff-9de3a1d797d0862ac56ae021ec51c8c9a28b5be0aafae1aad2bc307711b9bb0aL12-R21) [[2]](diffhunk://#diff-9de3a1d797d0862ac56ae021ec51c8c9a28b5be0aafae1aad2bc307711b9bb0aL35-R49) …

fix: auto fix starter projects

---

src/frontend/src/CustomNodes/GenericNode/components/NodeStatus/index.tsx
src/frontend/src/CustomNodes/GenericNode/index.tsx

This pull request includes several changes to the `NodeStatus` and `GenericNode` components in the `src/frontend/src/CustomNodes/GenericNode` directory. The main focus is on conditionally rendering elements based on the `showNode` property to improve the user interface.
Conditional rendering updates:
* [`src/frontend/src/CustomNodes/GenericNode/components/NodeStatus/index.tsx`](diffhunk://#diff-a82985ebdf968b3b9ff88582d46208ef24ade91024f7e4bcdddc9451bfede45eL193-R193): Modified the return statement to conditionally render the component based on the `showNode` property. [[1]](diffhunk://#diff-a82985ebdf968b3b9ff88582d46208ef24ade91024f7e4bcdddc9451bfede45eL193-R193) [[2]](diffhunk://#diff-a82985ebdf968b3b9ff88582d46208ef24ade91024f7e4bcdddc9451bfede45eR287-R288)
* …

fix: update minimized component outdated design

---

src/frontend/src/components/core/parameterRenderComponent/components/tableComponent/components/TableOptions/index.tsx
src/frontend/tests/core/unit/tableInputComponent.spec.ts

this pr improves the tableComponent test to increase its performance

Refactor: Update TableOptions component to add data-testid attributes for buttons

---

src/frontend/tests/core/unit/sliderComponent.spec.ts

this pull request enhances the slidercomponentTest to improves the performance

Refactor: Improve performance of sliderComponent tests

---

src/backend/base/langflow/api/v1/endpoints.py
src/backend/base/langflow/custom/directory_reader/directory_reader.py
src/backend/base/langflow/initial_setup/setup.py
src/backend/base/langflow/services/storage/local.py

Use async_open in a few places

fix: Use async_open in a few places

---

src/backend/base/langflow/inputs/__init__.py
src/backend/base/langflow/schema/artifact.py
src/backend/base/langflow/schema/dataframe.py

This pull request introduces a new `DataFrameInput` type and integrates it into the existing system. The changes include updates to the input initialization, artifact schema, and the handling of raw data post-processing. Additionally, a truth value testing method is added to the `DataFrame` class.
* [`src/backend/base/langflow/inputs/__init__.py`](diffhunk://#diff-1ca6e822d88bfd3e30c1ed1af9d1d86627b43d0657995fb0e31468e9964c55a0R4): Added `DataFrameInput` to the list of imports and the `__all__` list. [[1]](diffhunk://#diff-1ca6e822d88bfd3e30c1ed1af9d1d86627b43d0657995fb0e31468e9964c55a0R4) [[2]](diffhunk://#diff-1ca6e822d88bfd3e30c1ed1af9d1d86627b43d0657995fb0e31468e9964c55a0R55)
* [`src/backend/base/langflow/schema/artifact.py`](diffhunk://#diff-543016d7d5efb105bfb8a0d45338bca17317c2c2f2a …

fix: adds better boolean check for DataFrame and fixes output display

---

src/backend/tests/unit/graph/graph/state/test_state_model.py

This PR re-enables a test that was temporarily disabled due to PR #4437

test: re-enable unit test

---

src/frontend/tests/core/unit/linkComponent.spec.ts

This pull request fixes timeouts and selectors in the `linkComponent.spec.ts` file. It updates the timeouts for waiting on selectors and adds new selectors to ensure the tests run smoothly.

Refactor: remove timeouts and update selectors in linkComponent.spec.ts

---

src/frontend/tests/extended/features/actionsMainPage-shard-0.spec.ts

This pull request includes a refactoring of the actionsMainPage-shard-0.spec.ts file to improve test readability and maintainability. The changes include adding the 'expect' import, updating the 'waitForSelector' timeout, and replacing 'waitForTimeout' with 'expect' assertions for visibility.

Refactor: actionsMainPage-shard-0.spec.ts for improved test readability and maintainability

---

src/backend/base/langflow/graph/graph/base.py

This pull request addresses the handling of cycle scenarios in the graph sorting logic by adjusting the stop component logic. When a cycle is detected, the stop component is converted into a start component, allowing for proper processing without ambiguity regarding input or output. This change enhances the robustness of the graph sorting functionality.

fix: update sort logic to handle cycles when running component

---

src/frontend/src/components/common/pageLayout/index.tsx
src/frontend/src/modals/IOModal/components/chatView/chatMessage/newChatMessage.tsx

This pull request includes changes to improve the layout and customization options in the frontend components. The most important changes include adjustments to the `PageLayout` component and the introduction of a feature flag for a custom profile icon in chat messages.
Layout adjustments:
* [`src/frontend/src/components/common/pageLayout/index.tsx`](diffhunk://#diff-38c9bb3973db5e736c6ffecae4f2bb1915f449b82f06dac022de4b78a925b327L27-R29): Modified padding values in the `PageLayout` component to improve spacing and alignment.
Customization options:
* [`src/frontend/src/modals/IOModal/components/chatView/chatMessage/newChatMessage.tsx`](diffhunk://#diff-a5c2764955c9d507dd134f3add3fec7958daa183ee41cfabe54f5c5702a483e7R5-R6): Added imports for `CustomProfileIcon` and …

refactor: Feature flag custom chat icons and custom banner spacing changes to stay in sync with DataStax Langflow

---

docs/docs/Components/components-loaders.md

This pull request updates some language in the Unstructured documentation to more accurately reflect the current state of the Langflow component.

fix: Update components-loaders.md for accuracy with Unstructured

---

README.md
docs/docs/Get-Started/get-started-installation.md
docs/docs/Get-Started/get-started-quickstart.md

Add uv as an installation and run method.

docs: add uv installation

---

pyproject.toml
uv.lock

Add sseclient-py to fix sambanova streaming

fix: sambanova streaming

---

src/backend/base/langflow/components/vectorstores/astradb.py

This pull request handles the situation where a user provides an incorrect token, correctly wiping out the list of possible collections from the dropdown.

fix: handle incorrect token in AstraDB

---

docker/build_and_push.Dockerfile
docker/build_and_push_base.Dockerfile
docker/build_and_push_ep.Dockerfile
src/backend/base/langflow/components/git/git.py

This PR includes two changes:
Add Git to Dockerfiles: Git has been added to the Dockerfile dependencies to ensure proper functionality within the containers. This resolves the issue where Git was missing in containerized environments.
Make input optional: The required property of a specific input has been set to False. This allows the input to accept a URL instead of requiring a local path, enabling the component to function in hosted environments.
Both changes are aimed at improving the usability and compatibility of the system when deployed.

fix: adjust GitLoader to work in a hosted environment

---

src/backend/base/langflow/api/health_check_router.py
src/backend/base/langflow/api/v1/endpoints.py
src/backend/base/langflow/api/v1/users.py
src/backend/base/langflow/services/socket/utils.py

Use AsyncSession in some API endpoints

fix: Use AsyncSession in some API endpoints

---

.github/workflows/ci.yml
.github/workflows/nightly_build.yml
.github/workflows/typescript_test.yml
src/frontend/src/CustomNodes/GenericNode/index.tsx
src/frontend/src/components/core/codeTabsComponent/ChatCodeTabComponent.tsx
src/frontend/src/modals/templatesModal/components/TemplateCardComponent/index.tsx
src/frontend/src/pages/FlowPage/components/UpdateAllComponents/index.tsx
src/frontend/tests/core/integrations/Custom Component Generator.spec.ts
src/frontend/tests/core/integrations/Image Sentiment Analysis.spec.ts
src/frontend/tests/core/integrations/Instagram Copywriter.spec.ts
src/frontend/tests/core/integrations/Market Research.spec.ts
src/frontend/tests/core/integrations/Prompt Chaining.spec.ts
src/frontend/tests/core/integrations/SEO Keyword Generator.spec.ts
src/frontend/tests/core/integrations/SaaS Pricing.spec.ts
src/frontend/tests/core/integrations/Travel Planning Agent.spec.ts
src/frontend/tests/core/integrations/Twitter Thread Generator.spec.ts
src/frontend/tests/utils/add-new-api-keys.ts
src/frontend/tests/utils/adjust-screen-view.ts
src/frontend/tests/utils/await-bootstrap-test.ts
src/frontend/tests/utils/build-data-transfer.ts
src/frontend/tests/utils/get-all-response-message.ts
src/frontend/tests/utils/initialGPTsetup.ts
src/frontend/tests/utils/remove-old-api-keys.ts
src/frontend/tests/utils/select-gpt-model.ts
src/frontend/tests/utils/update-old-components.ts
src/frontend/tests/utils/wait-for-open-modal.ts

This pull request includes several updates to the frontend components and the addition of new integration tests. The most important changes include adding `data-testid` attributes to various components for better testability, importing utilities for test name conversion, and creating new integration tests for different functionalities.
* [`src/frontend/src/components/core/codeTabsComponent/ChatCodeTabComponent.tsx`](diffhunk://#diff-8ce41c2128c463f03a37bcb819dddc54c0078285609da848b3650a8b4e10eb70L34-R37): Added `data-testid="chat-code-tab"` to the main div for better testability.
* [`src/frontend/src/modals/templatesModal/components/TemplateCardComponent/index.tsx`](diffhunk://#diff-1643e0ff92f1725e30e22c7126de047d2a2bc79af6097ef5e6191801e42bfbb2R28): Added `data-testid` attribute to the …

test: Enhance frontend testability with data attributes and integration tests

---

src/frontend/tests/extended/regression/generalBugs-shard-12.spec.ts

Fix: update broken test generalBugs-shard-12.spec

---

src/frontend/src/hooks/flows/use-upload-flow.ts
src/frontend/src/pages/MainPage/hooks/use-on-file-drop.tsx
src/frontend/tests/assets/flow_test_drag_and_drop.json
src/frontend/tests/extended/features/dragAndDrop.spec.ts
src/frontend/tests/utils/simulate-drag-and-drop.ts

the drag and drop test is broken

fix: update drag and drop test

---

src/frontend/src/CustomNodes/NoteNode/index.tsx

This pull request refactors the NoteNode component by updating the inputClassName to remove unnecessary ring and focus styles. The changes ensure that the input element has a border, ring, and focus styles set to 0, resulting in a cleaner and more streamlined appearance.

Refactor: update NoteNode inputClassName to remove unnecessary ring and focus styles

---

pyproject.toml
src/backend/base/langflow/main.py
src/backend/tests/conftest.py
src/backend/tests/performance/test_server_init.py
uv.lock

Fix test_get_and_cache_all_types_dict

fix: Fix test_get_and_cache_all_types_dict

---

src/frontend/tests/extended/features/pythonApiGeneration.spec.ts

The code changes update the flow creation test in the pythonApiGeneration.spec.ts file. The test now waits for the modal title to appear before proceeding. This ensures that the test is more reliable and avoids any timing issues.

improve: improve pythonGenerationCodeAPI

---

.github/changes-filter.yaml
src/frontend/src/components/core/parameterRenderComponent/components/inputComponent/components/popover/index.tsx
src/frontend/src/components/core/parameterRenderComponent/components/inputFileComponent/index.tsx
src/frontend/tests/core/integrations/Vector Store.spec.ts

This pull request includes several changes to the frontend components and test files to improve functionality and maintainability. The most important changes include updates to the test categories, adjustments to the input component styles, and modifications to the test files to enhance test reliability.
* [`.github/changes-filter.yaml`](diffhunk://#diff-1b2ef07bf2b24cfe900fb2d2b36e0ca604e96b38cd48e00c82d21d64a9c06697R23): Added a new path to the `starter-projects` category to include components in `src/backend/base/langflow/components/**`.
* [`src/frontend/src/components/core/parameterRenderComponent/components/inputComponent/components/popover/index.tsx`](diffhunk://#diff-6dd2f8aa520258e6efb0482b5419536b2eb345b1cccdcf29c1b4562971c4f0e4L137-R137): Adjusted the padding for password inputs …

fix: improve vector store test

---

src/backend/base/langflow/services/database/utils.py
src/backend/tests/conftest.py
src/backend/tests/unit/services/variable/test_service.py
src/backend/tests/unit/test_database.py
src/backend/tests/unit/test_initial_setup.py
src/backend/tests/unit/test_login.py
src/backend/tests/unit/test_user.py

Use AsyncSession in some tests

ref: Use AsyncSession in some tests

---

src/backend/base/langflow/api/health_check_router.py
src/backend/base/langflow/api/utils.py
src/backend/base/langflow/api/v1/api_key.py
src/backend/base/langflow/api/v1/chat.py
src/backend/base/langflow/api/v1/endpoints.py
src/backend/base/langflow/api/v1/files.py
src/backend/base/langflow/api/v1/flows.py
src/backend/base/langflow/api/v1/folders.py
src/backend/base/langflow/api/v1/login.py
src/backend/base/langflow/api/v1/monitor.py
src/backend/base/langflow/api/v1/users.py
src/backend/base/langflow/api/v1/variable.py
src/backend/base/langflow/services/auth/utils.py
src/backend/base/langflow/services/database/models/flow/utils.py
src/backend/base/langflow/services/deps.py
src/backend/base/langflow/services/socket/utils.py

Remove sync get_session and DbSession

ref: Remove sync get_session and DbSession

---

src/backend/tests/conftest.py
src/backend/tests/unit/test_login.py
src/backend/tests/unit/test_messages.py

Add sqlite to blocking call detection

feat: Add sqlite to blocking call detection

---

docker/frontend/build_and_push_frontend.Dockerfile

- Updated the Dockerfile to use consistent uppercase casing for 'FROM' and 'AS'.
- Resolved 'FromAsCasing' warnings that were flagged during the Docker build.
- Improves readability and adheres to Dockerfile best practices.

fix(Dockerfile): standardize casing for 'FROM' and 'AS' keywords

---

src/backend/tests/conftest.py

Activate blockbuster Lock.aquire detection

feat: Activate blockbuster Lock.aquire detection

---

src/frontend/tests/extended/features/integration-side-bar.spec.ts

This pull request removes unnecessary code and comments in the `integration-side-bar.spec.ts` file. The removed code includes a timeout and a test case that is currently commented out. This cleanup improves the readability and maintainability of the codebase.

Refactor: Remove unnecessary code and comments in integration-side-bar.spec.ts

---

src/backend/base/langflow/initial_setup/setup.py
src/backend/base/langflow/main.py
src/backend/tests/integration/test_misc.py
src/backend/tests/performance/test_server_init.py
src/backend/tests/unit/graph/test_graph.py
src/backend/tests/unit/test_database.py
src/backend/tests/unit/test_initial_setup.py
src/backend/tests/unit/test_loading.py

Make `create_or_update_starter_projects` async

ref: Make create_or_update_starter_projects async

---

src/frontend/tests/extended/features/dragAndDrop.spec.ts
src/frontend/tests/extended/regression/generalBugs-shard-12.spec.ts
src/frontend/tests/extended/regression/generalBugs-shard-3.spec.ts
src/frontend/tests/extended/regression/generalBugs-shard-7.spec.ts

This pull request includes several changes to the frontend test files, primarily focusing on updating file paths and improving the stability of drag-and-drop and regression tests by adjusting mouse movements and adding wait conditions.
File path updates:
* [`src/frontend/tests/extended/features/dragAndDrop.spec.ts`](diffhunk://#diff-b9839b9273615451795233816b37fb37abbb06550b928812d3137b6294d14139L15-R19): Updated file paths from `assets/` to `tests/assets/` in multiple instances. [[1]](diffhunk://#diff-b9839b9273615451795233816b37fb37abbb06550b928812d3137b6294d14139L15-R19) [[2]](diffhunk://#diff-b9839b9273615451795233816b37fb37abbb06550b928812d3137b6294d14139L48-R52) [[3]](diffhunk://#diff-b9839b9273615451795233816b37fb37abbb06550b928812d3137b6294d14139L60-R64)
Improvements to …

test: enhance drag-and-drop reliability and update test asset paths

---

src/backend/base/langflow/api/utils.py
src/backend/base/langflow/api/v1/endpoints.py
src/backend/base/langflow/base/curl/parse.py
src/backend/base/langflow/base/data/base_file.py
src/backend/base/langflow/components/composio/composio_api.py
src/backend/base/langflow/components/deactivated/merge_data.py
src/backend/base/langflow/components/helpers/structured_output.py
src/backend/base/langflow/components/processing/merge_data.py
src/backend/base/langflow/components/processing/update_data.py
src/backend/base/langflow/components/tools/astradb_cql.py
src/backend/base/langflow/components/tools/youtube_transcripts.py
src/backend/base/langflow/components/unstructured/unstructured.py
src/backend/base/langflow/custom/custom_component/component.py
src/backend/base/langflow/custom/directory_reader/directory_reader.py
src/backend/base/langflow/logging/logger.py
src/backend/base/langflow/services/tracing/arize_phoenix.py
src/backend/tests/unit/components/helpers/test_structured_output_component.py
src/backend/tests/unit/initial_setup/starter_projects/test_vector_store_rag.py

Fix some ruff preview rules (auto-fix)

ref: Fix some ruff preview rules

---

src/backend/tests/conftest.py

Sqlite detection has been mistakenly deactivated during a conflict resolution (my bad)...

feat: Activate sqlite blocking detection again

---

README.md
docs/docs/Get-Started/get-started-installation.md

This pull request includes updates to the installation and usage instructions for Langflow, emphasizing the use of `uv` for package management. The most important changes include modifications to the `README.md` and `get-started-installation.md` files.

docs: Swap pip and uv installation instructions in README and install

---

CODE_OF_CONDUCT.FR.md
CONTRIBUTING.FR.md
README.ES.md
README.FR.md
README.KR.md
README.PT.md
README.ja.md
README.md
README.zh_CN.md

I have added a README.FR.md file to provide documentation for French-speaking users. This file is a translation of the existing README files, with a focus on ensuring clarity and readability in French.
- To make the project more accessible to French speakers by offering a localized version of the documentation.
- To maintain consistency with the existing README files while adapting for linguistic and cultural nuances in French.
- The content has been carefully translated to ensure it remains accurate and easy to understand.
- I also verified that all links, instructions, and code examples work correctly in this file.
Feel free to share any feedback or suggestions to further improve this translation!

feat: add README.FR.md for French speakers

---

src/frontend/src/pages/FlowPage/components/nodeToolbarComponent/index.tsx

This pull request includes updates to the `NodeToolbarComponent` in the `src/frontend/src/pages/FlowPage/components/nodeToolbarComponent/index.tsx` file. The changes focus on enhancing the user interface and user experience by adding new properties to the `ConfirmationModal` component.
UI/UX Enhancements:
* Added `cancelText` property with the value "Create New" to provide a clearer action label for users.
* Added `confirmationText` property with the value "Replace" to make the confirmation action more explicit.
* Set the `size` property to "x-small" to adjust the modal size for better visual fit.
* Included an `icon` property with the value "SaveAll" to visually indicate the action of saving all changes.
* Added an `index` property with the value 6 to manage the order of elements within …

fix: enhance confirmation modal with new UI properties

---

src/frontend/package-lock.json
src/frontend/package.json

This pull request addresses audit vulnerabilities by updating key dependencies, including "shadcn-ui" from version 0.8.0 to 0.9.4 and "@swc/cli" from version 0.3.12 to 0.5.2. Additionally, various other dependency updates and removals in package-lock.json have been made to ensure compatibility and improve performance. These changes enhance the project's overall dependency management and incorporate the latest features and fixes.

chore: Fix audit vulnerabilities and update dependencies

---

src/backend/base/langflow/services/settings/base.py
src/backend/base/langflow/utils/util_strings.py
src/backend/tests/unit/utils/test_util_strings.py

Ensure database connection URLs are properly validated and tested to prevent runtime errors

fix: validate and test database connection URLs

---

pyproject.toml
src/backend/tests/conftest.py
uv.lock

Bump blockbuster version to 1.5.2

feat: Bump blockbuster version to 1.5.2

---

src/backend/base/langflow/services/database/service.py

Fix missing await in `initialize_alembic_log_file`

fix: Fix missing await in initialize_alembic_log_file

---

src/backend/base/langflow/__main__.py
src/backend/base/langflow/api/utils.py
src/backend/base/langflow/api/v1/chat.py
src/backend/base/langflow/custom/custom_component/custom_component.py
src/backend/base/langflow/helpers/flow.py
src/backend/base/langflow/helpers/user.py
src/backend/base/langflow/initial_setup/setup.py
src/backend/base/langflow/memory.py
src/backend/base/langflow/services/auth/utils.py
src/backend/base/langflow/services/database/models/message/crud.py
src/backend/base/langflow/services/database/service.py
src/backend/base/langflow/services/database/utils.py
src/backend/base/langflow/services/deps.py
src/backend/base/langflow/services/utils.py
src/backend/tests/conftest.py
src/backend/tests/unit/test_database.py
src/backend/tests/unit/test_initial_setup.py
src/backend/tests/unit/test_login.py
src/backend/tests/unit/test_messages.py
src/backend/tests/unit/test_messages_endpoints.py

Remove unused sync session_scope, with_session and engine

ref: Remove unused sync session_scope, with_session and engine

---

src/backend/base/langflow/components/processing/json_cleaner.py

- **Speed Increase:** 📈 **`1,491%`** (**`14.91x` faster**)
- **Runtime Reduction:** ⏱️ From **`2.92 milliseconds`** down to **`183 microseconds`** (best of `232` runs)
---
To optimize the function `_remove_control_characters`, we can use the `translate` method with a translation table to remove control characters. This method is generally faster than using regular expressions for character replacement/removal tasks.
Here is the optimized version of the program.
By precompiling the translation table in the `__init__` method, we're reducing the repeated overhead of creating this table every time `_remove_control_characters` is called. Using `str.translate` with this precompiled table significantly improves the performance compared to using a regular expression substitution.
---
The new …

refactor:  (codeflash)⚡️ Speed up method `JSONCleaner._remove_control_characters` by 1,491%

---

src/backend/base/langflow/components/processing/json_cleaner.py
src/backend/base/langflow/components/tools/calculator.py

Ref PR https://github.com/langflow-ai/langflow/pull/5322 https://github.com/langflow-ai/langflow/pull/5323
This pull request includes changes to the constructors of classes in two files to allow for additional arguments and keyword arguments. This improves the flexibility and reusability of these classes.
Constructor modifications for flexibility:
* [`src/backend/base/langflow/components/processing/json_cleaner.py`](diffhunk://#diff-fb7a201f70c86b2045ceccae73171258e8ddc4850e327166246ffd4f15ebdb9cL100-R102): Modified the `__init__` method to accept `*args` and `**kwargs`, and passed them to the superclass constructor.
* [`src/backend/base/langflow/components/tools/calculator.py`](diffhunk://#diff-9e5e21486437724cadfa4fb3fcd27a293f1211870ea4c8e9ea48224be1233e1eL94-R95): Modified the …

fix: code flash pr issues in Calculator and JSONCleaner Components

---

src/frontend/tests/extended/features/deleteComponents.spec.ts
src/frontend/tests/extended/features/deleteFlows.spec.ts
src/frontend/tests/extended/features/store-shard-1.spec.ts
src/frontend/tests/extended/features/store-shard-3.spec.ts
src/frontend/tests/extended/regression/generalBugs-shard-13.spec.ts

This pull request updates the descriptions of several tests to clarify that they require a store API key to run. This change enhances the documentation within the test cases, making it clear to developers that the tests cannot be executed without the appropriate API key.

test: Update test descriptions to indicate requirement for store API key

---

src/backend/base/langflow/api/v1/flows.py

Missing mapping in read_flows api. Added mapping

fix: add endpoint_name to read_flows endpoint

---

src/backend/base/langflow/components/tools/astradb_cql.py

Tool part is working fine but the direct Data output fails cause of partition key issue.

fix: fix partition error in AstraDBCQLToolComponent

---

src/backend/base/langflow/base/agents/events.py

This pull request simplifies the construction of agent input text content. The `build_agent_input_text_content` function has been refactored to remove unnecessary code and improve readability. The function now only includes the final user input in the content, prefixed with "**HUMAN**: ". This change ensures that the agent input text content is correctly generated.

refactor: Simplify agent input text content construction

---

pyproject.toml
src/backend/tests/conftest.py
uv.lock

Bump blockbuster version to 1.5.5

feat: Bump blockbuster version to 1.5.5

---

pyproject.toml
uv.lock

Bump blockbuster version to 1.5.7

feat: Bump blockbuster version to 1.5.7

---

src/frontend/src/components/core/GlobalVariableModal/GlobalVariableModal.tsx

This pull request includes a change to the `GlobalVariableModal` component to update the description text for better clarity.
* [`src/frontend/src/components/core/GlobalVariableModal/GlobalVariableModal.tsx`](diffhunk://#diff-a6b0be4fdc4019758cda029a162a55f4fc0cff94ecef635aca1b50ff27008ce4L139-R139): Updated the description text in the `BaseModal.Header` to remove the reference to encryption.

refactor: update GlobalVariableModal description text

---

Makefile

This pull request updates the Makefile to improve the frontend build command by adding detailed logging and error handling. The changes ensure that the build process provides clear output, including directory checks and error messages if the build fails, enhancing the overall developer experience during the build process.

refactor: Enhance frontend build process with detailed logging and error handling

---

pyproject.toml
uv.lock

Bump blockbuster version to 1.5.8

fix: Bump blockbuster version to 1.5.8

---

DEVELOPMENT.md

Improve developer docs with minor changes

docs: Improve developer docs with minor changes

---

.github/workflows/docker_test.yml

This PR adds a `workflow_dispatch` trigger to the `docker_test.yml` file, allowing for manual execution of the Docker test workflow. This enhancement provides greater flexibility in running tests as needed.

chore: Add manual trigger for Docker test workflow

---

docker/build_and_push.Dockerfile
docker/build_and_push_base.Dockerfile
docker/build_and_push_ep.Dockerfile
docker/cdk.Dockerfile
docker/dev.Dockerfile

This pull request refines the Dockerfiles by replacing `ADD` commands with `COPY` for better clarity and consistency. It also includes `apt-get upgrade` commands to ensure that packages are up to date and reduce image size through cleanup steps. Additionally, user creation commands have been updated to include necessary cleanup, ensuring all Dockerfiles maintain a similar structure for enhanced maintainability.
Closes #5510

refactor: run upgrade in dockerfiles to update dependencies

---

src/backend/base/langflow/base/models/model.py
src/backend/base/langflow/initial_setup/starter_projects/Basic Prompting.json

This pull request includes changes to the `src/backend/base/langflow/base/models/model.py` file, focusing on input types and model components. The most important changes include updating imports and modifying the input type for the `system_message`.
Changes to input types and model components:
* [`src/backend/base/langflow/base/models/model.py`](diffhunk://#diff-7f05be33af0d7c390019c835f3473dd4e5aa8a73bb723fc382bb1b04b2874632L13-R14): Updated imports to include `MultilineInput` and removed `MessageTextInput` import.
* [`src/backend/base/langflow/base/models/model.py`](diffhunk://#diff-7f05be33af0d7c390019c835f3473dd4e5aa8a73bb723fc382bb1b04b2874632L29-R29): In `LCModelComponent` class, replaced `MessageTextInput` with `MultilineInput` for the `system_message` input.

feat(model): replace MessageTextInput with MultilineInput for system_message

---

docs/docs/Configuration/configuration-objects.md
docs/sidebars.js

Remove duplicate component section in sidebar.js.

fix: remove duplicate Components section from sidebar

---

src/backend/base/langflow/initial_setup/starter_projects/Simple Agent.json

This PR updates the basic example Simple Agent to use the most recent version of Calculator, improving consistency with our current implementation.
Changes:
Updates Simple Agent example to align with latest Calculator version
Ensures example code maintains best practices and readability
Maintains backwards compatibility with existing functionality
This update helps keep our examples current and provides users with the most up-to-date reference implementation.

feat: Update Simple Agent example with latest Calculator version

---

src/backend/base/langflow/graph/graph/base.py
src/backend/base/langflow/graph/graph/utils.py
src/backend/base/langflow/services/socket/utils.py
src/backend/tests/data/WebhookTest.json
src/backend/tests/unit/graph/graph/test_utils.py
src/backend/tests/unit/test_chat_endpoint.py
src/backend/tests/unit/test_endpoints.py
src/backend/tests/unit/test_webhook.py

This pull request improves the testing framework for graph utilities by adding cycle detection and sorting functionality. New tests have been introduced to validate these features, including a fixture for graphs with cycles. Additionally, sorting methods have been refactored into separate functions, enhancing the graph processing capabilities and ensuring efficient handling of complex graph structures. The changes also include improved error messages for failed tests, which will aid in debugging. Overall, these updates contribute to a more robust and maintainable graph utility module.

refactor: add graph utility tests and refactor sorting methods

---

src/frontend/src/components/core/parameterRenderComponent/components/inputFileComponent/index.tsx

This pull request includes several changes to the `InputFileComponent` in `index.tsx` to improve file handling and error management. The most important changes include adding a ref for the file input, refactoring file type checking, and enhancing error handling during file selection and upload.
Enhancements to file handling and error management:
* [`src/frontend/src/components/core/parameterRenderComponent/components/inputFileComponent/index.tsx`](diffhunk://#diff-68cd26e922bccf5191323c0f9ed58160ce8528c3479e556151c1ce4d4258a6caL5-R5): Added `useRef` to manage the file input reference.
* [`src/frontend/src/components/core/parameterRenderComponent/components/inputFileComponent/index.tsx`](diffhunk://#diff-68cd26e922bccf5191323c0f9ed58160ce8528c3479e556151c1ce4d4258a6caR27-L88): Refactored …

fix: simplify InputFileComponent to use native file picker

---

src/backend/base/langflow/utils/validate.py

Fix memory leak when creating components

fix: Fix memory leak when creating components

---

src/backend/base/langflow/main.py

This pull request refactors the bundle loading process to include error handling for HTTP exceptions. It introduces a new function that gracefully handles exceptions when loading bundles from URLs, ensuring that errors such as timeouts and HTTP errors are logged appropriately without disrupting the overall flow. This enhancement improves the robustness of the application when dealing with external resources.

fix: don't raise error if bundle loading fails

---

src/backend/base/langflow/initial_setup/starter_projects/Instagram Copywriter.json
src/backend/base/langflow/initial_setup/starter_projects/Market Research.json
src/backend/base/langflow/initial_setup/starter_projects/SaaS Pricing.json
src/backend/base/langflow/initial_setup/starter_projects/Simple Agent.json

Changes:
Updated all component dependencies in starter project templates to their latest stable versions
Ensures new projects begin with the most recent component implementations
Maintains compatibility across template projects

feat: update starter projects with latest component versions (nightly fix)

---

src/backend/base/langflow/initial_setup/starter_projects/Instagram Copywriter.json
src/backend/base/langflow/initial_setup/starter_projects/Market Research.json
src/backend/base/langflow/initial_setup/starter_projects/SaaS Pricing.json
src/backend/base/langflow/initial_setup/starter_projects/Simple Agent.json

This pull request includes updates to the starter projects, enhancing their functionality and ensuring they are aligned with the latest standards and practices. These improvements aim to provide a better foundation for new users and developers starting with the project.

chore: Update starter projects

---

src/backend/base/langflow/initial_setup/starter_projects/Instagram Copywriter.json
src/backend/base/langflow/initial_setup/starter_projects/Market Research.json
src/frontend/tests/core/integrations/Instagram Copywriter.spec.ts
src/frontend/tests/core/integrations/Market Research.spec.ts

This pull request includes several changes to the `Market Research.json` file in the `src/backend/base/langflow/initial_setup/starter_projects` directory. The changes primarily involve updating various IDs, adjusting dimensions, and updating the version of `lf_version`.
* Changed the `id` values for `OpenAIModel`, `StructuredOutputComponent`, `ParseData`, `ChatInput`, `ChatOutput`, `Agent`, and `TavilySearchComponent` to new identifiers. [[1]](diffhunk://#diff-633ea36314515f61aad893da1d70ebba0cecf77783d084343b43ca94c0e1849aL10-R177) [[2]](diffhunk://#diff-633ea36314515f61aad893da1d70ebba0cecf77783d084343b43ca94c0e1849aL468-R470) [[3]](diffhunk://#diff-633ea36314515f61aad893da1d70ebba0cecf77783d084343b43ca94c0e1849aL860-R862) [[4]](diffhunk://#diff-633ea36314515f61aad893da1d70ebba0cecf77783 …

fix: update Tavily component in Instagram Copywriter and Market Research projects and tests

---

pyproject.toml
src/backend/base/langflow/components/tools/duck_duck_go_search_run.py
uv.lock

This pull request includes updates to dependencies and modifications to the `DuckDuckGoSearchComponent` class in the `src/backend/base/langflow/components/tools/duck_duck_go_search_run.py` file. The most important changes are as follows:
* [`pyproject.toml`](diffhunk://#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711L87-R87): Updated the `duckduckgo_search` dependency from version 6.3.7 to 7.2.1.
Code modifications:
* [`src/backend/base/langflow/components/tools/duck_duck_go_search_run.py`](diffhunk://#diff-72f0c3503beef3b2e19a0c41cb1fd167e993a586019e3127381a087fc7919f1bL24): Removed the `required=True` attribute from the `MessageTextInput` component's `input_value` field.

feat: update duckduckgo search component version

---

src/backend/base/langflow/initial_setup/starter_projects/Instagram Copywriter.json
src/backend/base/langflow/initial_setup/starter_projects/Research Agent.json
src/backend/base/langflow/initial_setup/starter_projects/SaaS Pricing.json
src/backend/base/langflow/initial_setup/starter_projects/Sequential Tasks Agents .json
src/backend/base/langflow/initial_setup/starter_projects/Simple Agent.json
src/backend/base/langflow/initial_setup/starter_projects/Travel Planning Agents.json

This PR updates outdated components in the flow to align with the latest versions and maintain compatibility with the current system.
Changes
Replaced outdated components with their updated versions.
Verified the flow for consistency and functionality after the updates.
Addressed any potential compatibility issues related to the updates.

feat: update starter projects templates

---

src/backend/base/langflow/custom/directory_reader/directory_reader.py
src/frontend/src/pages/FlowPage/components/flowSidebarComponent/components/categoryGroup/index.tsx
src/frontend/src/pages/FlowPage/components/flowSidebarComponent/index.tsx

this pr unhide components that are not originally from langflow on the sidebar and fix the LANGFLOW_COMPONENTS_PATH behavior.
fix #5256

fix: update LANGFLOW_COMPONENTS_PATH env variable behavior

---

src/backend/tests/base.py
src/backend/tests/unit/components/agents/test_agent_component.py

This pull request updates the component test setup to support asynchronous operations. The `component_setup` and `test_latest_version` methods in `ComponentTestBase` have been refactored to be asynchronous, allowing for non-blocking execution. This change improves test performance and responsiveness by leveraging asyncio for component initialization, ensuring that the testing framework is better equipped for future asynchronous operations. Additionally, the `TestAgentComponent` class has been updated to maintain compatibility with these changes.

refactor: update component test method and Agent component test for be asynchronous

---

pyproject.toml

chore: bump langflow-base in langflow

---

src/backend/base/langflow/components/data/csv_to_data.py

Enhance CSV to Data component by introducing a configurable text key parameter, allowing users to specify the column used for text extraction when converting CSV data to Data objects.

feat: Add text key option to CSVToDataComponent

---

src/backend/base/langflow/base/models/groq_constants.py

This pull request adds support for the deepseek-r1-distill-llama-70b model to the Groq integration, expanding the available model options for users.

feat: add deepseek-r1-distill-llama-70b to Groq

---

docs/package-lock.json
docs/yarn.lock

chore(deps): upgrade Docusaurus and related dependencies

---

src/backend/base/langflow/api/v2/files.py

This pull request fixes the file delete to ensure its handling properly the duplicate () notation.

Fix: properly handle duplicate files on delete

---

DEVELOPMENT.md
docs/css/custom.css
docs/docs/Components/components-data.md
docs/docs/Components/components-processing.md
docs/docs/Get-Started/get-started-quickstart.md
docs/docusaurus.config.js
docs/sidebars.js

* Increase image size in custom css (also for mobile)
* Swap API nav location
* Disable nav hide
* Update development.md to use yarn instead of npm

docs: ui improvements

---

src/frontend/src/customization/utils/analytics.ts
src/frontend/src/stores/flowStore.ts

Adds new event tracking for flow run for all flows and for templates and for data loading in astra db

feat: Add new tracking events for flow and data load executions

---

.github/changes-filter.yaml
.github/workflows/ci.yml
src/backend/base/langflow/custom/custom_component/component.py
src/backend/base/langflow/graph/graph/base.py
src/backend/base/langflow/graph/graph/runnable_vertices_manager.py
src/backend/base/langflow/graph/graph/utils.py
src/backend/base/langflow/graph/vertex/base.py
src/backend/base/langflow/graph/vertex/vertex_types.py
src/frontend/tests/core/features/group.spec.ts
src/frontend/tests/core/integrations/Basic Prompting.spec.ts
src/frontend/tests/core/integrations/Blog Writer.spec.ts
src/frontend/tests/core/integrations/Custom Component Generator.spec.ts
src/frontend/tests/core/integrations/Document QA.spec.ts
src/frontend/tests/core/integrations/Dynamic Agent.spec.ts
src/frontend/tests/core/integrations/Hierarchical Agent.spec.ts
src/frontend/tests/core/integrations/Image Sentiment Analysis.spec.ts
src/frontend/tests/core/integrations/Instagram Copywriter.spec.ts
src/frontend/tests/core/integrations/Market Research.spec.ts
src/frontend/tests/core/integrations/Memory Chatbot.spec.ts
src/frontend/tests/core/integrations/Prompt Chaining.spec.ts
src/frontend/tests/core/integrations/SEO Keyword Generator.spec.ts
src/frontend/tests/core/integrations/SaaS Pricing.spec.ts
src/frontend/tests/core/integrations/Sequential Task Agent.spec.ts
src/frontend/tests/core/integrations/Simple Agent.spec.ts
src/frontend/tests/core/integrations/Travel Planning Agent.spec.ts
src/frontend/tests/core/integrations/Twitter Thread Generator.spec.ts
src/frontend/tests/core/integrations/Vector Store.spec.ts
src/frontend/tests/core/integrations/starter-projects.spec.ts
src/frontend/tests/core/regression/generalBugs-prompt.spec.ts
src/frontend/tests/extended/features/starter-projects.spec.ts

This pull request includes updates to the `.github/changes-filter.yaml` and `.github/workflows/ci.yml` files, as well as modifications to various test files and a backend component file. The changes aim to enhance the CI workflow, improve test coverage, and refine backend processing logic. The most important changes include adding new path filters, updating CI job conditions, modifying test tags, and refining backend component logic.
* [`.github/changes-filter.yaml`](diffhunk://#diff-1b2ef07bf2b24cfe900fb2d2b36e0ca604e96b38cd48e00c82d21d64a9c06697R31-R32): Added new path filters for backend directories to the `starter-projects` and `components` sections. [[1]](diffhunk://#diff-1b2ef07bf2b24cfe900fb2d2b36e0ca604e96b38cd48e00c82d21d64a9c06697R31-R32) …

fix: Update path filters, test tags and backend processing (nightly-fix)

---

src/frontend/src/utils/utils.ts

This pull request includes several changes to improve file management functionality and enhance the user interface. The most important changes include adding support for file management in multiple components, updating API constants, and introducing a new `MorphingMenu` component.
* [`src/frontend/src/components/core/folderSidebarComponent/components/sideBarFolderButtons/index.tsx`](diffhunk://#diff-c555da19c21570f424bb71bd92a075b37bbe7be3fbc75387b03b37728a8dc9cfR1-R6): Added support for file management, including a new `SidebarFooter` with buttons to manage files. [[1]](diffhunk://#diff-c555da19c21570f424bb71bd92a075b37bbe7be3fbc75387b03b37728a8dc9cfR1-R6) [[2]](diffhunk://#diff-c555da19c21570f424bb71bd92a075b37bbe7be3fbc75387b03b37728a8dc9cfR449-R466)
* …

fix: adds edge filtering only to parameters not hidden

---

src/frontend/tests/extended/features/filterEdge-shard-1.spec.ts

This pull request includes changes to the `src/frontend/tests/extended/features/filterEdge-shard-1.spec.ts` file to improve error handling and update the list of element test IDs.
Changes to element test IDs:
* Removed "inputsChat Input" and "helpersMessage History" from the `elementTestIds` array.
Improvements to error handling:
* Modified the `Promise.all` block to log an error message if an element is not visible instead of just expecting visibility.

tests: Improve Error Handling and Update Element Test IDs in filterEdge-shard-1.spec.ts

---

src/frontend/src/components/core/chatComponents/ContentDisplay.tsx

Refactor the output check in the ContentDisplay component

fix: improve output check

---

.github/workflows/codeflash.yml

Modify the Codeflash workflow to allow the optimizer step to continue even if an error occurs.

ci: Update Codeflash workflow to continue on error

---

src/backend/base/langflow/services/auth/utils.py

Enhance the decryption process for API keys by adding detailed error handling and logging. This change allows for a fallback mechanism if the initial decryption attempt fails, improving overall reliability.

refactor: Improve API key decryption error logging

---

docs/docs/Concepts/concepts-overview.md

This pull request includes updates to the documentation to provide detailed instructions on how to access and configure log files for Langflow.

docs: add log file location and configuration instructions

---

scripts/aws/lib/construct/ecr.ts
scripts/aws/package-lock.json
scripts/aws/package.json

This pull request includes several updates to the dependencies and paths used in the AWS CDK scripts. The most important changes include modifying the backend path in the `EcrRepository` construct and updating various dependencies in the `package-lock.json` and `package.json` files.
* [`scripts/aws/lib/construct/ecr.ts`](diffhunk://#diff-319c68a812af7c297aed8f24abed701fdd6480870dd87096935419dd2f92fafdL22-R22): Changed the `backendPath` from "langflow" to "docker".
* [`scripts/aws/package.json`](diffhunk://#diff-1687e4beabbade8e8c2c3dc464ba344574c335ded9af139c14f0e0e1c514bafaL16-R16): Updated the `aws-cdk` version from `^2.141.0` to `^2.1000.2`.
* [`scripts/aws/package-lock.json`](diffhunk://#diff-a15bb9c37af2f7f423fb83c73be01d589b547ae8baa20e4d11447cd7c5f9ae9bL25-R25): Updated multiple …

fix: aws docker file is now in different place

---

docs/docs/Components/components-models.md

This pull request introduces a new component for generating text using xAI models in the documentation.

docs: add-xai-component

---

src/frontend/src/pages/FlowPage/components/PageComponent/index.tsx
src/frontend/src/pages/FlowPage/components/UpdateAllComponents/index.tsx

This pull request includes several changes to the `FlowPage` components to improve error handling, update UI elements, and optimize the code structure. The most important changes are grouped by theme below:
* [`src/frontend/src/pages/FlowPage/components/UpdateAllComponents/index.tsx`](diffhunk://#diff-1fa6c72d078cb9d7b501ddccdfdf2babb7ed1c958eca52d03d718ac420deb751L15-R59): Added constants for error messages and updated the error handling logic to use these constants. This change improves the consistency and readability of error messages. [[1]](diffhunk://#diff-1fa6c72d078cb9d7b501ddccdfdf2babb7ed1c958eca52d03d718ac420deb751L15-R59) [[2]](diffhunk://#diff-1fa6c72d078cb9d7b501ddccdfdf2babb7ed1c958eca52d03d718ac420deb751L80-R116)
* …

feat: Enhance component update system with edge validation alerts

---

src/backend/base/langflow/initial_setup/starter_projects/Research Agent.json
src/backend/base/langflow/initial_setup/starter_projects/Sequential Tasks Agents.json

fix: templates with broken connection

---

.github/actions/setup-uv/action.yml
.github/workflows/codeflash.yml
.github/workflows/docker-build.yml
.github/workflows/integration_tests.yml
.github/workflows/lint-py.yml
.github/workflows/nightly_build.yml
.github/workflows/python_test.yml
.github/workflows/release.yml
.github/workflows/release_nightly.yml
.github/workflows/style-check-py.yml
.github/workflows/typescript_test.yml
Makefile
pyproject.toml
src/backend/base/langflow/initial_setup/setup.py
src/backend/base/langflow/services/storage/local.py
src/backend/base/langflow/utils/validate.py
src/backend/base/pyproject.toml
uv.lock

feat: Add support for Python 3.13

---

src/backend/base/langflow/components/nvidia/nvidia_ingest.py
src/backend/base/langflow/services/storage/local.py
src/backend/tests/conftest.py
src/backend/tests/unit/api/v1/test_files.py
src/backend/tests/unit/graph/graph/test_cycles.py

Improve test assertions and skip certain cycle tests that require specific output. Refactor file listing in LocalStorageService for better performance and update installation instructions for NVIDIA Ingest dependencies.

fix: Enhance tests and update NVIDIA Ingest installation instructions

---

src/backend/base/langflow/services/telemetry/service.py

Introduce a new attribute to the TelemetryService class to manage the logging of package version tasks.

fix: Add `log_package_version_task` attribute to TelemetryService

---

pyproject.toml
src/backend/base/pyproject.toml
uv.lock

Update the package versions for langflow and langflow-base to their latest releases.

chore: Update langflow and langflow-base package versions to 1.2.0 and 0.2.0

---

src/backend/base/langflow/initial_setup/setup.py
src/backend/base/langflow/initial_setup/starter_projects/Graph Vector Store RAG.json

This pull request includes significant updates to the `update_edges_with_latest_component_versions` function in the `src/backend/base/langflow/initial_setup/setup.py` file. The changes enhance the function's ability to update project edges with the latest component versions, reconcile missing nodes, and log changes for debugging purposes.
Key improvements include:
* Added detailed docstring explaining the function's purpose, operations, and arguments.
* Implemented deep copy creation to avoid modifying the original project data.
* Enhanced the extraction and parsing of source and target handles, including escaping and updating handles.
* Added logic to reconcile missing nodes by type, updating the edge source and target accordingly.
* Updated edge IDs to reflect changes in source and …

fix: Enhance edge update logic and refactor edge data handling

---

src/backend/base/langflow/services/database/models/flow/model.py
src/frontend/src/controllers/API/queries/flows/use-post-add-flow.ts
src/frontend/src/modals/exportModal/index.tsx
src/frontend/src/pages/MainPage/components/list/index.tsx
src/frontend/src/utils/reactflowUtils.ts

Improve the flow download process by adding recursive JSON sorting for consistent output and include flow tags in the export modal payload to preserve comprehensive metadata. Error handling has also been added to the download function.

refactor: sort json before exporting and add tags to flows

---

pyproject.toml
src/backend/base/langflow/components/data/__init__.py
src/backend/base/langflow/components/data/s3_bucket_uploader.py
src/backend/tests/unit/components/data/test_s3_uploader_component.py
uv.lock

This pull request introduces a new component called S3BucketUploader.
New Feature:
Allows users to take input from File and Directory components and saves the file in an s3 bucket. Requires a public s3 bucket with key/secret access.

 feat: implement S3 bucket uploader component and unit test

---

src/frontend/src/components/core/parameterRenderComponent/components/tableComponent/index.tsx

This pull request includes several changes to the `TableComponent` in the `src/frontend/src/components/core/parameterRenderComponent/components/tableComponent/index.tsx` file. The changes primarily focus on improving the handling of visible columns and enhancing the grid's performance and layout.
Improvements to column handling:
* Modified the `colDef` mapping to use the filtered array length instead of the original column definitions length to ensure correct column suppression (`[src/frontend/src/components/core/parameterRenderComponent/components/tableComponent/index.tsxL58-R63](diffhunk://#diff-f3fcb59cd5fd40bf313028ede0595abb9ebe326e02946ecaece08678d8ea212fL58-R63)`).
* Updated the `storeReference` to only include visible columns, improving the accuracy of the store reference …

fix: remove empty space for hidden column

---

docker/build_and_push_ep.Dockerfile

Adds system library libpq5 to the -ep docker image

build: add postgresql client library libpq5

---

src/backend/base/langflow/services/tracing/service.py

Removed logs_queue attribute and log_worker() method
Simplified start(), stop(), and flush() methods
Maintained Service compatibility
Fixes: #6842

refactor: remove async queue from tracing service

---

src/backend/tests/unit/components/models/test_deepseek.py

Enhance the DeepSeek model component test by parameterizing it with temperature and max tokens, allowing for more flexible testing scenarios.

test: Parameterize DeepSeek model component test correctly

---

src/backend/base/langflow/initial_setup/setup.py
src/backend/base/langflow/main.py

This PR adds a new asynchronous task to sync flows from the file system to the database, triggered when a flow has an associated fs_path.
* Introduces the async function sync_flows_from_fs to monitor and update flows based on file changes.
* Adds new dependency imports and integrates the sync task into the app lifecycle by creating and canceling the task in the lifespan function.

feat: Sync flows from FS to DB if flow has fs_path

---

src/backend/base/langflow/services/tracing/service.py

ref: Refactor tracing service

---

src/backend/base/langflow/components/agentql/agentql_api.py
src/backend/base/langflow/initial_setup/starter_projects/News Aggregator.json
src/backend/base/langflow/initial_setup/starter_projects/Price Deal Finder.json

- Updated raw params to be explicit UI controls
- Added new Stealth Mode parameter
- Updated templates

feat: Update AgentQL integration with new features

---

src/backend/base/langflow/initial_setup/starter_projects/Custom Component Maker.json
src/backend/base/langflow/initial_setup/starter_projects/Graph Vector Store RAG.json
src/backend/base/langflow/initial_setup/starter_projects/Meeting Summary.json
src/backend/base/langflow/initial_setup/starter_projects/News Aggregator.json
src/backend/base/langflow/initial_setup/starter_projects/Price Deal Finder.json
src/backend/base/langflow/initial_setup/starter_projects/Sequential Tasks Agents.json
src/frontend/tests/core/regression/generalBugs-prompt.spec.ts

This pull request includes updates to the `Custom Component Maker.json` file in the `src/backend/base/langflow/initial_setup/starter_projects` directory. The changes mainly involve updating the IDs and positions of various components within the JSON file.
Component ID updates:
* Changed the `id` of `Memory` component from `Memory-v5bRq` to `Memory-lzTrH`. [[1]](diffhunk://#diff-a517d7d5e1e4decfb12711c96ae08e2c6c174241f01e51da60e3dcdb63406822L10-R191) [[2]](diffhunk://#diff-a517d7d5e1e4decfb12711c96ae08e2c6c174241f01e51da60e3dcdb63406822L509-R516) [[3]](diffhunk://#diff-a517d7d5e1e4decfb12711c96ae08e2c6c174241f01e51da60e3dcdb63406822L738-R752)
* Changed the `id` of `Prompt` component from `Prompt-QIyYT` to `Prompt-mySXT`. [[1]](diffhunk://#diff-a517d7d5e1e4decfb12711c96ae08e2c6c174241f01e51 …

fix: refactor templates to remove small bugs

---

src/frontend/tests/extended/integrations/chatInputOutputUser-shard-1.spec.ts

This pull request includes updates to the `src/frontend/tests/extended/integrations/chatInputOutputUser-shard-1.spec.ts` file to improve the testing process by adding new assertions and updating existing ones.
Improvements to testing process:
* Added `expect` import from `@playwright/test` to enable assertions in the test file.
* Updated the test to check for specific text elements and added an assertion to verify the presence of multiple "Close" buttons.

test: enhance chat integration tests with additional assertions and validations

---

pyproject.toml
uv.lock

should fix https://github.com/langflow-ai/langflow/issues/7039

fix: bump assistants version to fix module not found error 

---

src/backend/base/langflow/template/utils.py
src/backend/tests/unit/template/utils/test_apply_json_filter.py

This pull request includes several changes to the `src/backend/base/langflow/template/utils.py` and `src/backend/tests/unit/template/utils/test_apply_json_filter.py` files to improve performance, error handling, and code readability. The most important changes include adding type ignores, using list comprehensions for better performance, and refining exception handling.
Performance improvements:
* Replaced for loops with list comprehensions in `apply_json_filter` to enhance performance. [[1]](diffhunk://#diff-e9e1cbc76c38e83cfde79b3e77521b65b07c24767788072aea55a6a063bcf900L158-R161) [[2]](diffhunk://#diff-e9e1cbc76c38e83cfde79b3e77521b65b07c24767788072aea55a6a063bcf900L219-R215)
Error handling improvements:
* Refined exception handling in `apply_json_filter` to catch specific exceptions …

fix: Performance and Error Handling Improvements in JSON Filtering

---

src/frontend/tests/core/integrations/Custom Component Generator.spec.ts
src/frontend/tests/core/unit/nestedComponent.spec.ts

This pull request includes updates to the test files to improve the accuracy and reliability of the tests. The most important changes include adding new steps to ensure proper component generation and modifying assertions to be more robust.
Improvements to `Custom Component Generator.spec.ts`:
* Added steps to fill in the input for creating a custom component and sending the request. (`src/frontend/tests/core/integrations/Custom Component Generator.spec.ts`)
* Modified the assertion to check for the presence of "langflow" in a case-insensitive manner. (`src/frontend/tests/core/integrations/Custom Component Generator.spec.ts`)
Enhancements to `nestedComponent.spec.ts`:
* Added steps to interact with the sidebar options and verify the legacy switch is checked. …

fix: Improve test accuracy with component generation steps and robust assertions (nightly fix)

---

src/backend/base/langflow/initial_setup/starter_projects/Search agent.json

fix search agent template and updates the agent component

feat: update search agent template agent component

---

src/frontend/src/pages/FlowPage/components/PageComponent/index.tsx
src/frontend/tests/core/features/filterEdge-shard-0.spec.ts
src/frontend/tests/core/features/globalVariables.spec.ts
src/frontend/tests/core/features/publish-flow.spec.ts

This pull request includes several changes to the frontend codebase, focusing on adjusting zoom levels, adding wait times in tests, and modifying interactions within test files. The most important changes are summarized below:
* [`src/frontend/src/pages/FlowPage/components/PageComponent/index.tsx`](diffhunk://#diff-58f6af33afc15c24e3df56ce2169081e35e5fe005f6281ebc5d7156b2eaa7d0eL581-R581): Reduced the `maxZoom` value from 8 to 3 to limit the maximum zoom level on the page.
* [`src/frontend/tests/core/features/filterEdge-shard-0.spec.ts`](diffhunk://#diff-63af3ac954e352067f20ebf13dc89a702b2d9e528749336b552ec836afb17d1dR67-R77): Added `page.waitForTimeout(1000)` calls to introduce delays and improve test stability.
* [`src/frontend/tests/core/features/globalVariables.spec.ts`](diffhunk://#di …

fix: Test Stability Enhancements (nightly fix)

---

src/frontend/tests/extended/features/tool-mode.spec.ts
src/frontend/tests/extended/integrations/chatInputOutputUser-shard-1.spec.ts

This pull request includes several changes to the frontend test files to improve the reliability and readability of the tests. The most important changes are as follows:
* Updated the test ID for the URL component to ensure the correct element is being interacted with (`src/frontend/tests/extended/features/tool-mode.spec.ts`).
* Added a timeout to ensure the page has enough time to load before proceeding with the next actions (`src/frontend/tests/extended/integrations/chatInputOutputUser-shard-1.spec.ts`).
* Removed an unnecessary timeout to streamline the test execution (`src/frontend/tests/extended/integrations/chatInputOutputUser-shard-1.spec.ts`).

tests: change handle testid on URL Component

---

src/backend/base/langflow/initial_setup/starter_projects/Pokédex Agent.json
src/backend/tests/unit/components/data/test_api_request_component.py

This pull request primarily involves updates to the `Pokédex Agent.json` file in the `src/backend/base/langflow/initial_setup/starter_projects` directory. The changes include updating various IDs and modifying some properties for better functionality and clarity. Additionally, there is a minor update to a test file. 
* Updated IDs for various components such as `APIRequest`, `ChatInput`, `ChatOutput`, `Agent`, and notes to new values for consistency and uniqueness. [[1]](diffhunk://#diff-2350a5b134d0b2279e637307e5732868388adda7acf8622f60c0d89cffb1b42fL10-R74) [[2]](diffhunk://#diff-2350a5b134d0b2279e637307e5732868388adda7acf8622f60c0d89cffb1b42fL83-R96) [[3]](diffhunk://#diff-2350a5b134d0b2279e637307e5732868388adda7acf8622f60c0d89cffb1b42fL595-R595) …

test: fix outdated components (nightly fix)

---

src/backend/base/langflow/initial_setup/starter_projects/Pokédex Agent.json
src/backend/tests/unit/components/data/test_api_request_component.py

This pull request includes changes to the `src/backend/tests/unit/components/data/test_api_request_component.py` file to update the test cases for output formats. The most important change is the modification of the test for data output to reflect the new behavior of the `to_data` method.
Updates to test cases:
* [`src/backend/tests/unit/components/data/test_api_request_component.py`](diffhunk://#diff-b6f4e58234a45a2fd482ab669d7bfdc1550c8bb1e40228195b25fbac917124e2L248-R252): Removed tests for `as_message` and `as_data` methods, and added a test for the `to_data` method which now returns a list of `Data` objects.

test: update api-request tests

---

src/frontend/package-lock.json
src/frontend/src/controllers/API/queries/auth/use-post-logout.ts
src/frontend/src/stores/flowStore.ts
src/frontend/src/stores/flowsManagerStore.ts
src/frontend/src/stores/foldersStore.tsx
src/frontend/src/types/zustand/flow/index.ts
src/frontend/src/types/zustand/flowsManager/index.ts
src/frontend/src/types/zustand/folders/index.ts
src/frontend/tests/core/features/user-flow-state-cleanup.spec.ts

Introduce reset methods for folders, flows, and flow states to improve state management. Enhance logout functionality to reset relevant states and invalidate queries for data consistency. Add tests to ensure proper cleanup of user flow states between sessions.
Fixes #6695 #6151

fix: Enhance state management with reset methods and logout functionality improvements

---

src/frontend/src/components/core/dropdownComponent/index.tsx
src/frontend/src/utils/reactflowUtils.ts

Include a tribute in the `reactflowUtils.ts` file honoring Otávio Anovazzi for his significant contributions to the Langflow project.

docs: Add tribute comment to Otávio Anovazzi in reactflowUtils.ts

---

src/backend/base/langflow/main.py

Improve logging practices by replacing rich print statements with logger.debug in main.py, enhancing clarity and integration during application startup and shutdown.

refactor: update logging to use logger.debug for consistency

---

.github/ISSUE_TEMPLATE/bug-report.yaml

Eliminate the reference to anovazzi1 in the bug report template.

chore: Remove mention of anovazzi1 from bug report template

---

src/frontend/src/constants/constants.ts

Updated the priorityFields set to include "mode" for enhanced functionality.

fix: add "mode" to priorityFields in constants (#7279)

---

src/backend/base/langflow/template/utils.py
src/backend/tests/unit/template/utils/test_apply_json_filter.py

Add additional test cases for dictionary access to improve coverage and robustness. Refactor the apply_json_filter function for better clarity and performance, simplifying data extraction and handling special cases more effectively.

fix: Enhance dictionary access tests and refactor apply_json_filter function

---

docs/sidebars.js

Bump MCP and rename some nav items to make it stand out more.

docs: move mcp up in integrations sidebar

---

pyproject.toml
src/backend/base/pyproject.toml
src/frontend/package-lock.json
src/frontend/package.json
uv.lock

Bump python and react projects.

chore: bump langflow for 1.3.1

---

src/backend/base/langflow/api/v1/mcp.py

-fix: holst name error,alter :holst->host

fix: Fixed typo in mcp host setup

---

docs/docs/Deployment/deployment-docker.md

Fixing docs related to [issue](https://discord.com/channels/1116803230643527710/1356821120757796964/1356821120757796964)

fix: add ENV to Dockerfile when packing flows to image

---

src/backend/base/langflow/components/models/nvidia.py

Enhance robustness by ignoring connection errors and adding logging for issues when accessing the NVIDIA API. Implement exception handling for various connection-related errors to provide better user feedback.
Fixes #7443

fix: Improve error handling for NVIDIA model component

---

src/frontend/src/pages/FlowPage/components/PageComponent/index.tsx
src/frontend/tests/core/features/group.spec.ts
src/frontend/tests/core/features/saveComponents.spec.ts
src/frontend/tests/core/features/toolModeGroup.spec.ts
src/frontend/tests/core/regression/generalBugs-shard-5.spec.ts

This pull request includes changes to the `src/frontend/src/pages/FlowPage/components/PageComponent/index.tsx` file to enhance the functionality and user experience of the FlowPage component. The most important changes involve adding a new import, updating the selection mode, and modifying zoom and pan behaviors.
Enhancements to FlowPage component:
* [`src/frontend/src/pages/FlowPage/components/PageComponent/index.tsx`](diffhunk://#diff-58f6af33afc15c24e3df56ce2169081e35e5fe005f6281ebc5d7156b2eaa7d0eR33): Added `SelectionMode` to the import statement from `@xyflow/react`.
* [`src/frontend/src/pages/FlowPage/components/PageComponent/index.tsx`](diffhunk://#diff-58f6af33afc15c24e3df56ce2169081e35e5fe005f6281ebc5d7156b2eaa7d0eR574): Set `selectionMode` to `SelectionMode.Partial` in the …

feat: adds pan and pinch nav mode like figma

---

docs/css/custom.css

* Decrease space between nav items
* Add cole's fix so menu doesn't clash with ad in light mode
* Change ad to fixed so it doesn't move up the nav

docs: decrease leftnav spacing

---

src/frontend/src/components/core/dropdownComponent/index.tsx
src/frontend/src/components/core/parameterRenderComponent/components/dropdownComponent/index.tsx
src/frontend/src/style/applies.css
src/frontend/tests/extended/regression/general-bugs-dropdown-select-not-in-list.spec.ts

This pull request includes several improvements to the `Dropdown` component in the `src/frontend/src/components/core/dropdownComponent` directory, as well as the addition of a new test for the dropdown functionality. The changes enhance the dropdown's handling of values not in the list and improve the component's overall functionality.
Improvements to the `Dropdown` component:
* [`src/frontend/src/components/core/dropdownComponent/index.tsx`](diffhunk://#diff-98068ce778ac9a53f4733f9c370c5e54bd27c30b6545fa4241f10cba35518700R55-R61): Added `handleOnNewValue` prop and updated the `useMemo` dependencies for `validOptions` and `value` to include `filteredOptions`. [[1]](diffhunk://#diff-98068ce778ac9a53f4733f9c370c5e54bd27c30b6545fa4241f10cba35518700R55-R61) …

fix: Improve Dropdown component handling of custom values and add regression test

---

src/backend/base/langflow/initial_setup/starter_projects/Basic Prompt Chaining.json
src/backend/base/langflow/initial_setup/starter_projects/Basic Prompting.json
src/backend/base/langflow/initial_setup/starter_projects/Blog Writer.json
src/backend/base/langflow/initial_setup/starter_projects/Custom Component Maker.json
src/backend/base/langflow/initial_setup/starter_projects/Diet Analysis.json
src/backend/base/langflow/initial_setup/starter_projects/Document Q&A.json
src/backend/base/langflow/initial_setup/starter_projects/Financial Agent.json
src/backend/base/langflow/initial_setup/starter_projects/Financial Report Parser.json
src/backend/base/langflow/initial_setup/starter_projects/Image Sentiment Analysis.json
src/backend/base/langflow/initial_setup/starter_projects/Instagram Copywriter.json
src/backend/base/langflow/initial_setup/starter_projects/LoopTemplate.json
src/backend/base/langflow/initial_setup/starter_projects/Market Research.json
src/backend/base/langflow/initial_setup/starter_projects/Meeting Summary.json
src/backend/base/langflow/initial_setup/starter_projects/Memory Chatbot.json
src/backend/base/langflow/initial_setup/starter_projects/News Aggregator.json
src/backend/base/langflow/initial_setup/starter_projects/Portfolio Website Code Generator.json
src/backend/base/langflow/initial_setup/starter_projects/Price Deal Finder.json
src/backend/base/langflow/initial_setup/starter_projects/Research Agent.json
src/backend/base/langflow/initial_setup/starter_projects/SEO Keyword Generator.json
src/backend/base/langflow/initial_setup/starter_projects/SaaS Pricing.json
src/backend/base/langflow/initial_setup/starter_projects/Sequential Tasks Agents.json
src/backend/base/langflow/initial_setup/starter_projects/Text Sentiment Analysis.json
src/backend/base/langflow/initial_setup/starter_projects/Twitter Thread Generator.json
src/backend/base/langflow/initial_setup/starter_projects/Vector Store RAG.json
src/backend/base/langflow/initial_setup/starter_projects/Youtube Analysis.json
src/backend/base/langflow/inputs/inputs.py

This pull request includes changes to the `Basic Prompt Chaining.json` file to improve the readability and consistency of the JSON format by converting single-line arrays to multi-line arrays. The most important changes include updating the format of `output_types`, `inputTypes`, and other array fields.
Formatting improvements:
* Converted `output_types` fields to multi-line arrays for better readability. [[1]](diffhunk://#diff-5526508850d110b0d021e8a2356c9290b1c07a02d44a56f18f368f54ad5f4abdL11-R20) [[2]](diffhunk://#diff-5526508850d110b0d021e8a2356c9290b1c07a02d44a56f18f368f54ad5f4abdL34-R47) [[3]](diffhunk://#diff-5526508850d110b0d021e8a2356c9290b1c07a02d44a56f18f368f54ad5f4abdL57-R74) [[4]](diffhunk://#diff-5526508850d110b0d021e8a2356c9290b1c07a02d44a56f18f368f54ad5f4abdL80-R101) …

fix: removed handle on secret input

---

.devcontainer/README.md
DEVELOPMENT.md
src/backend/base/langflow/__main__.py

Improves the CLI onboarding message by:
•	Updating layout for better readability
•	Applying brand-aligned color styling
•	Clarifying access link, GitHub, and Discord references

feat: Update CLI message and style

---

.devcontainer/README.md
DEVELOPMENT.md
src/backend/base/langflow/__main__.py

Safer rendering for different terminals.

Fix: CLI Social Links

---

src/frontend/src/pages/FlowPage/components/PageComponent/index.tsx
src/frontend/tests/core/features/group.spec.ts
src/frontend/tests/core/features/saveComponents.spec.ts
src/frontend/tests/core/features/toolModeGroup.spec.ts
src/frontend/tests/core/regression/generalBugs-shard-5.spec.ts

Reverts langflow-ai/langflow#7410

fix: revert "feat: adds pan and pinch nav mode like figma"

---

pyproject.toml
src/backend/base/pyproject.toml
src/frontend/package-lock.json
src/frontend/package.json
uv.lock

Bump the versions of langflow and langflow-base in their respective configuration files to ensure compatibility with the latest features and fixes.

chore: Update langflow and langflow-base package versions to 1.3.3 and 0.3.3

---

docs/docs/Get-Started/get-started-installation.md

Add `<Tabs groupId="package-manager">` to installation page so tabs are synced with one click.

docs: group install tabs by package manager

---

pyproject.toml
src/backend/base/pyproject.toml
src/frontend/package.json
uv.lock

Update version numbers in project files to reflect the new releases.

chore: Bump version numbers for langflow and langflow-base to 1.3.4 and 0.3.4 respectively

---

pyproject.toml
uv.lock

changed pydantic-settings==2.4.0 to pydantic-settings>=2.2.0,<3.0.0 as uv cli suggested without dmg the current project deps

fix: make pydantic-settings less strict to avoid deps conflicts

---

src/frontend/src/constants/constants.ts
src/frontend/src/hooks/flows/use-add-flow.ts

This pull request includes changes to improve error handling and introduce new constants for better code maintainability. The most important changes include adding new error constants, updating error handling in the `use-add-flow` hook, and importing the new constants where necessary.
Error handling improvements:
* [`src/frontend/src/constants/constants.ts`](diffhunk://#diff-3a3810648efc852f35a3780d6fe4ec65734c218f2281a175d9347a65db3fd360R1071-R1072): Added a new constant `UUID_PARSING_ERROR` for handling UUID parsing errors.
* [`src/frontend/src/hooks/flows/use-add-flow.ts`](diffhunk://#diff-51f99cda7111618620f1f262ad11b34013662e517e589110a62b936f8e8f59e0R1): Imported the new `UUID_PARSING_ERROR` constant and added new error constants `FLOW_CREATION_ERROR`, `FOLDER_NOT_FOUND_ERROR`, and …

fix: Enhance error handling with new constants in flow management components (devx)

---

src/backend/base/langflow/components/tools/mcp_component.py
src/frontend/src/components/core/dropdownComponent/index.tsx
src/frontend/tests/core/features/toolModeGroup.spec.ts
src/frontend/tests/extended/features/edit-flow-name.spec.ts
src/frontend/tests/extended/features/edit-tools.spec.ts
src/frontend/tests/extended/features/mcp-server.spec.ts
src/frontend/tests/extended/features/tool-mode.spec.ts

This pull request introduces changes to both the backend and frontend components of the project, focusing on enhancing functionality and improving user experience. Key updates include adding a utility method for validation in the backend, modifying build configuration handling, and refining dropdown behavior in the frontend.
* **Validation Utility Method**:
- Added `_is_valid_key_value_item` method to validate if an item is a dictionary with `key` and `value` fields. This improves input validation and ensures consistent data handling. (`src/backend/base/langflow/components/tools/mcp_component.py`, [src/backend/base/langflow/components/tools/mcp_component.pyR206-R209](diffhunk://#diff-8b368b159254d9a5a8ebef207dcb28d4790e3c6fcd01325b61d67bfd078b4177R206-R209))
* **Build Configuration …

fix: make dropdown not repeat values on update, update mcp component

---

src/backend/base/langflow/components/data/sql_executor.py

This PR addresses fixes and improvements in the SQL query component, primarily by updating inputs, outputs, and how the SQL query is executed.
- Updated input types for better data validation (e.g., BoolInput for include_columns and add_error).
- Replaced the use of an external SQL tool with direct database method calls and introduced dedicated methods to build data and dataframes.
- Modified logging to use self.log and updated the component icon.

fix: sql query component

---

src/backend/base/langflow/base/agents/events.py
src/backend/base/langflow/services/tracing/langfuse.py
src/backend/base/langflow/services/tracing/langsmith.py
src/backend/base/langflow/services/tracing/service.py

Improve data handling by integrating serialization in LangFuse and LangSmith tracers. Enhance event handling to process AI message chunks during stream processing.

fix: streaming now works on Agent and ChatOutput

---

src/backend/base/langflow/services/tracing/arize_phoenix.py

We recently updated the Arize receivers to correctly handle the `authorization` header with or without the `Bearer` prefix.
This PR reverts the temporary changes made earlier, restoring the original behavior:
- Switches back to using the `arize-phoenix-otel` package instead of raw OTEL packages.
- Restores the correct export headers setup for both Arize and Phoenix tracing.
Tracing for both Arize and Phoenix now works as expected with the appropriate headers.

revert: Traces Export Headers For Arize & Phoenix Integration

---

src/frontend/src/pages/MainPage/pages/empty-page.tsx

This pull request includes minor adjustments to the styling of the `EmptyPageCommunity` component in `empty-page.tsx`. These changes primarily focus on improving the consistency and readability of the button's appearance.
Styling updates:
* Updated the `className` property of the `Button` component to use `max-w-[10rem]` instead of `max-w-[155px]` for better readability and alignment with the design system.
* Removed the `relative left-1` class from the `ForwardedIconComponent` to simplify its positioning.

fix: Update EmptyPageCommunity button dimensions and simplify icon positioning

---

src/frontend/src/components/core/dropdownComponent/index.tsx

This pull request refactors the `Dropdown` component in `src/frontend/src/components/core/dropdownComponent/index.tsx` to improve metadata handling, enhance performance, and ensure better reliability when working with filtered options and metadata. The key changes focus on creating a more efficient metadata mapping strategy and ensuring consistent behavior across various scenarios.
* Replaced the previous approach of filtering and mapping metadata with a more efficient `metadataMap` for quick lookup, ensuring metadata directly corresponds to filtered options. This change simplifies logic and improves performance.
* Updated the `formatTooltipContent` function to use `filteredMetadata` instead of `optionsMetaData`, ensuring tooltips are correctly aligned with the filtered options.
* …

fix: Icons on dropdown are inconsistent when search/selecting

---

.github/workflows/codspeed.yml

Improve execution control in the codspeed workflow by adding a timeout parameter.

chore: Update codspeed workflow with timeout parameter

---

README.md

Added Discord and tweaked some of the other CTAs

docs: adds Discord server reference in README

---

src/backend/base/langflow/components/models/azure_openai.py

* Updates `AZURE_OPENAI_API_VERSIONS` list to include new preview versions:
* `2024-12-01-preview`
* `2025-01-01-preview`
* `2025-02-01-preview`
Reference: https://learn.microsoft.com/en-us/azure/ai-services/openai/api-version-deprecation

feat: Adds additional azure openai api versions

---

docs/openapi.json

* Bump openapi.json to 1.4.0
* Remove `{flow_id}` from descriptions that causes builds to fail
[Preview build](https://d5rxiv0do0q3v.cloudfront.net/langflow-drafts/docs-bump-api-manually/api)

docs: bump openapi.json to 1.4.0

---

src/frontend/tests/core/features/auto-login-off.spec.ts
src/frontend/tests/core/features/user-flow-state-cleanup.spec.ts
src/frontend/tests/extended/features/autoLogin.spec.ts

This pull request updates several test files in the frontend codebase to improve test reliability and consistency. The key changes include replacing hardcoded selectors with updated text, introducing a utility function for test setup, and refining test metadata tags.
* Updated the `waitForSelector` call in `src/frontend/tests/core/features/auto-login-off.spec.ts` and `src/frontend/tests/core/features/user-flow-state-cleanup.spec.ts` to use the text `"Welcome to LangFlow"` instead of `"Begin with a template, or start from scratch."` for better alignment with the current UI. [[1]](diffhunk://#diff-15cd338b54b49fc2bf923efdb0b1cfa4a7a2f982c6d6639dcf35adf6c2d07f1eL209-R211) [[2]](diffhunk://#diff-87a1826663c0a4c88bcd20a8e87b7b102e35fa9bbc70b3d32a28eef440f949d0L92-R94)
* Added the …

test: improve test reliability with updated selectors and utility functions

---

src/backend/base/langflow/components/tools/mcp_component.py

This pull request introduces a minor update to the `MCPToolsComponent` class in `src/backend/base/langflow/components/tools/mcp_component.py` to enhance configurability by marking certain inputs as advanced.

feat: Update mcp_component add advanced True for env and headers

---

docs/docs/Get-Started/get-started-installation.md

This pull request updates the installation documentation for Langflow by adding troubleshooting steps for resolving a common installation error on Linux systems.

docs: add troubleshooting steps for installation failures on Linux

---

pyproject.toml
src/backend/base/pyproject.toml
src/frontend/package-lock.json
src/frontend/package.json
uv.lock

Update version numbers for langflow and langflow-base to 1.4.1 and 0.4.1 respectively.

chore: Bump version to 1.4.1 for langflow and langflow-base

---

docs/docs/Concepts/concepts-playground.md

Add base64 image usage to Playground concepts page.

docs: base64 images in playground

---

src/frontend/src/components/common/genericIconComponent/index.tsx
src/frontend/src/utils/styleUtils.ts

Updates the icon caching logic and centralizes it to the util
* **Introduction of `getCachedIcon` utility**:
- Added a new function `getCachedIcon` in `styleUtils.ts` to encapsulate the logic for retrieving cached icons, replacing direct calls to `iconCache.get` across the codebase. (`[src/frontend/src/utils/styleUtils.tsL451-R495](diffhunk://#diff-ce70511ff4131ac5078d799cd2295f98874bad89bcde4732f33c967c1bbc71f2L451-R495)`)
- The `iconCache` map is now scoped to `styleUtils.ts` and no longer exported, improving encapsulation. (`[src/frontend/src/utils/styleUtils.tsL9-R9](diffhunk://#diff-ce70511ff4131ac5078d799cd2295f98874bad89bcde4732f33c967c1bbc71f2L9-R9)`)
* **Consolidation of caching logic in `getNodeIcon`**:
- Refactored `getNodeIcon` to centralize caching logic, ensuring all icon …

refactor: move caching logic to styleUtils

---

.github/workflows/ci.yml

Revise the CI workflow to monitor for updates to the PyPI package instead of checking the nightly build status. This change enhances the reliability of version tracking.

chore: update CI workflow to check PyPI package version updates

---

src/frontend/src/components/core/jsonOutputComponent/json-output-view.tsx
src/frontend/src/style/classes.css
src/frontend/src/style/index.css

This pull request includes updates to improve layout consistency, enhance styling for better user experience, and adjust selection background colors for improved visibility. Below are the key changes grouped by theme:
* Updated the `JsonOutputViewComponent` layout to ensure it occupies the full height of its container by adding `h-full` to the class list of the parent `div`. (`src/frontend/src/components/core/jsonOutputComponent/json-output-view.tsx`, [src/frontend/src/components/core/jsonOutputComponent/json-output-view.tsxL27-R27](diffhunk://#diff-96b8d5d19185b4ef7ae0ee006e3e5ecc5b272f66e905a400ff4d687fe6c8ce59L27-R27))
* Added a new `.cm-selectionLayer` class with `z-index: 1` and `pointer-events: none` to improve the layering and interaction behavior of selection elements. …

fix: json selection not visible

---

src/backend/base/langflow/api/v1/projects.py
src/backend/base/langflow/api/v2/files.py
src/frontend/tests/extended/features/files-page.spec.ts

This pull request introduces multiple updates across the backend and frontend, focusing on improving database query handling, updating test tags, and enhancing test assertions. Below is a summary of the most important changes grouped by theme:
* **Pagination Enhancement**: Replaced `paginate` with `apaginate` for asynchronous pagination in `src/backend/base/langflow/api/v1/projects.py`, improving performance for paginated queries. [[1]](diffhunk://#diff-84f451bd0a7fb4da80c9fc0c14bd4ac797ca1c1e97599289c6b2ea62d0f4fee3L13-R13) [[2]](diffhunk://#diff-84f451bd0a7fb4da80c9fc0c14bd4ac797ca1c1e97599289c6b2ea62d0f4fee3L155-R155)
* **SQL Query Updates**: Updated queries in `src/backend/base/langflow/api/v2/files.py` to use `col()` for better SQL expression handling and compatibility in batch file …

fix: Enhance DB queries with async pagination and improve test reliability

---

src/backend/base/langflow/components/models/ollama.py

fix: remove double await in ChatOllamaComponent

---

docs/docs/Components/components-logic.md

This pull request introduces a small update to the documentation for the **Loop** component by adding a helpful tip for users.

docs: add loop component template suggestion

---

src/frontend/src/components/core/folderSidebarComponent/components/sideBarFolderButtons/index.tsx
src/frontend/src/controllers/API/queries/folders/use-get-download-folders.ts
src/frontend/src/customization/utils/custom-get-download-folders.ts

This pull request refactors and modularizes the folder download functionality in the sidebar component by introducing reusable utilities. The most important changes include extracting the folder download logic into a utility function, updating the API request configuration for folder downloads, and modifying the component to use the new utilities.
* [`src/frontend/src/customization/utils/custom-get-download-folders.ts`](diffhunk://#diff-d0f0edef335d72213f78c9f6be9ad08e08dd50350b4ce7c9faf722fb8a093d8fR1-R41): Introduced two new utility functions, `customGetDownloadTypeFolders` for configuring API requests and `customGetDownloadFolderBlob` for handling the folder download logic, including creating and downloading the blob.
* [`src/frontend/src/components/core/folderSidebarComponent/component …

feat: modularize folder download functionality with reusable utilities

---

docs/docs/Components/components-processing.md

This pull request modifies the documentation for the "Combine Text" component in `docs/docs/Components/components-processing.md` by relocating its section to a Legacy position within the file without altering its content.

docs: combine text component is legacy

---

docs/sidebars.js

Sidebar titles under Develop are unnecessarily verbose.

docs: fix develop sidebar titles

---

src/backend/base/langflow/components/data/__init__.py
src/backend/base/langflow/components/data/news_search.py
src/backend/tests/unit/components/data/test_news_search.py

This pull request introduces a new `NewsSearchComponent` to the codebase, which enables searching Google News via RSS and returns clean article data. The changes include the implementation of the component, updates to the component registry, and unit tests to ensure functionality.
* Implemented a new `NewsSearchComponent` in `src/backend/base/langflow/components/data/news_search.py`. This component allows users to search for news articles using various parameters like query, language, country, topic, and location. It fetches data from Google News RSS feeds, processes the results, and returns a structured `DataFrame`.
* Added the `NewsSearchComponent` to the component registry in `src/backend/base/langflow/components/data/__init__.py` to make it available for use. …

feat: News Search Component

---

.github/workflows/docker-build.yml

Upgrade the Docker Buildx action in the workflow to use the latest version for improved functionality and performance.

ci: Update Docker Buildx to latest version

---

src/frontend/src/components/core/dropdownComponent/index.tsx
src/frontend/tests/extended/regression/general-bugs-dropdown-select-not-in-list.spec.ts

accidentally went to main first w/ this PR https://github.com/langflow-ai/langflow/pull/8356

fix: lfoss-1284

---

src/backend/base/langflow/initial_setup/starter_projects/Youtube Analysis.json

Fix Youtube Anslysis template.
Removed If Else which always failed.
User need to enter a valid youtube URL.

fix: updates Youtube Analysis template error message

---

.github/workflows/release.yml

* Added 'secrets: inherit' to the CI job in release.yml for better security management.
* Cleaned up job configuration for clarity and maintainability.

chore: update GitHub Actions workflow to inherit secrets

---

src/backend/base/langflow/initial_setup/starter_projects/Nvidia Remix.json

This commit didn't make it into the 1.5 branch https://github.com/langflow-ai/langflow/commit/e6c09f8085823cdd164f6336e7881b67a3a9ac7e

bug: re-add NVIDIA Remix starter template

---

src/backend/base/langflow/initial_setup/starter_projects/Vector Store RAG.json

This pull request updates the Vector Store RAG template to use the latest file component.

fix: Use the newest file component in Vector Store RAG Template

---

src/backend/tests/integration/components/mcp/test_mcp_superuser_flow.py
src/backend/tests/unit/api/v1/test_mcp_projects.py
src/backend/tests/unit/test_auth_settings.py
src/backend/tests/unit/test_setup_superuser_flow.py

- Updated test functions to remove monkeypatching for cleaner integration.
- Improved error handling in tests for long-term token creation without a superuser.
- Added new tests to verify superuser setup behavior with and without configured credentials.
- Cleaned up imports and ensured consistent use of async context managers in tests.

refactor: streamline superuser flow tests and enhance error handling

---

src/frontend/src/pages/FlowPage/components/nodeToolbarComponent/__tests__/minimal-condition.test.tsx
src/frontend/src/pages/FlowPage/components/nodeToolbarComponent/__tests__/nodeToolbar-focused.test.tsx
src/frontend/src/pages/FlowPage/components/nodeToolbarComponent/index.tsx

This pull request introduces comprehensive unit tests for the minimal node logic in the NodeToolbar component and refactors the minimal condition calculation to be more robust and accurate. The changes ensure that the logic for determining when a node is "minimal" (eligible for minimization/expansion) is well-tested and correctly implemented, especially regarding outputs with or without group outputs.
**Testing improvements:**
- Added a detailed test suite (`minimal-condition.test.tsx`) that covers all edge cases and behaviors of the minimal node logic, including output combinations, edge cases, and effect behaviors.
- Added a focused and readable test (`nodeToolbar-focused.test.tsx`) to validate the core minimal logic and its integration with the UI, ensuring real-world scenarios are …

fix: Add comprehensive tests and improve minimal condition logic

---

src/backend/base/langflow/initial_setup/starter_projects/Instagram Copywriter.json
src/backend/base/langflow/initial_setup/starter_projects/Invoice Summarizer.json
src/backend/base/langflow/initial_setup/starter_projects/Market Research.json
src/backend/base/langflow/initial_setup/starter_projects/News Aggregator.json
src/backend/base/langflow/initial_setup/starter_projects/Nvidia Remix.json
src/backend/base/langflow/initial_setup/starter_projects/Pokédex Agent.json
src/backend/base/langflow/initial_setup/starter_projects/Price Deal Finder.json
src/backend/base/langflow/initial_setup/starter_projects/Research Agent.json
src/backend/base/langflow/initial_setup/starter_projects/SaaS Pricing.json
src/backend/base/langflow/initial_setup/starter_projects/Search agent.json
src/backend/base/langflow/initial_setup/starter_projects/Sequential Tasks Agents.json
src/backend/base/langflow/initial_setup/starter_projects/Simple Agent.json
src/backend/base/langflow/initial_setup/starter_projects/Social Media Agent.json
src/backend/base/langflow/initial_setup/starter_projects/Travel Planning Agents.json
src/backend/base/langflow/initial_setup/starter_projects/Youtube Analysis.json

This pull request updates several starter project configuration files in the `src/backend/base/langflow/initial_setup/starter_projects` directory. The main changes are a simplification of model selection options and the addition of a new field to facilitate connecting other models. These updates streamline the user interface and improve extensibility for future integrations.
**Model selection options simplification:**
* Removed less-used model options such as `Groq`, `Custom`, and in some cases `SambaNova` from the `options` lists, leaving only the most relevant models (e.g., `OpenAI`, `Anthropic`, `Google Generative AI`, etc.). This reduces clutter and focuses the selection on supported and popular providers. [[1]](diffhunk://#diff-5d6ded6e79298fe0d8d3e046b0fa85a89fec1f78154eb80b39acc5bdd …

fix: Updated Agent Starter Projects with new Templates

---

src/frontend/src/components/core/flowToolbarComponent/index.tsx
src/frontend/src/customization/components/custom-chatView.tsx
src/frontend/src/customization/constants.ts
src/frontend/src/modals/apiModal/codeTabs/code-tabs.tsx

This pull request introduces several codebase improvements focused on modal management and UI consistency in the frontend. The main changes include refactoring the flow toolbar to use an export modal instead of a share modal, introducing a customizable chat input component, and centralizing code tab styling for easier maintenance and consistency.
**Modal Management Refactor:**
* Refactored the flow toolbar in `flowToolbarComponent/index.tsx` to replace the share modal logic with an export modal, updating state variables and shortcut handlers accordingly. [[1]](diffhunk://#diff-fa085ba4e24214d10978e8e8d929242633c9a698956b79309d546e27b0b72272L14-R15) [[2]](diffhunk://#diff-fa085ba4e24214d10978e8e8d929242633c9a698956b79309d546e27b0b72272L28-R30) …

refactor: Improve modal management and UI consistency

---

docs/docs/Components/bundles-aiml.mdx
docs/docs/Components/bundles-amazon.mdx
docs/docs/Components/bundles-anthropic.mdx
docs/docs/Components/bundles-azure.mdx
docs/docs/Components/bundles-baidu.mdx
docs/docs/Components/bundles-cohere.mdx
docs/docs/Components/bundles-deepseek.mdx
docs/docs/Components/bundles-groq.mdx
docs/docs/Components/bundles-huggingface.mdx
docs/docs/Components/bundles-ibm.mdx
docs/docs/Components/bundles-lmstudio.mdx
docs/docs/Components/bundles-maritalk.mdx
docs/docs/Components/bundles-mistralai.mdx
docs/docs/Components/bundles-novita.mdx
docs/docs/Components/bundles-ollama.mdx
docs/docs/Components/bundles-openai.mdx
docs/docs/Components/bundles-openrouter.mdx
docs/docs/Components/bundles-perplexity.mdx
docs/docs/Components/bundles-sambanova.mdx
docs/docs/Components/bundles-vertexai.mdx
docs/docs/Components/bundles-xai.mdx
docs/docs/Components/components-models.mdx
docs/docs/Components/components-processing.mdx
docs/docs/Develop/data-types.mdx

Revert name change that is not released yet

chore: revert smart function name change in docs
