src/backend/base/langflow/components/assemblyai/AssemblyAIPollTranscript.py
✨ (AssemblyAIPollTranscript.py): introduce RangeSpec field typing to define a range for polling interval in seconds
=> fix: add range_spec to AssemblyAITranscriptionJobPoller

.github/actions/setup-uv/action.yml, .github/workflows/docker-build.yml, .github/workflows/integration_tests.yml, .github/workflows/lint-py.yml, .github/workflows/nightly_build.yml, .github/workflows/python_test.yml, .github/workflows/release.yml, .github/workflows/release_nightly.yml, .github/workflows/style-check-py.yml, .github/workflows/typescript_test.yml, pyproject.toml, src/backend/base/pyproject.toml
Few more updates for the swap to `uv`
Test workflow (skipped publishing) that succeeded - https://github.com/langflow-ai/langflow/actions/runs/11221324879
=> ci: fix release workflows for uv

src/frontend/src/customization/feature-flags.ts, src/frontend/src/pages/FlowPage/components/extraSidebarComponent/index.tsx, src/frontend/tests/extended/regression/generalBugs-shard-12.spec.ts
This pull request hides the integrations feature by setting the `ENABLE_INTEGRATIONS` flag to false.
=> feature: Hide integrations

Makefile
This pull request adds a new target called 'unsafe_fix' to the Makefile. The 'unsafe_fix' target allows applying unsafe fixes with ruff. This will help in resolving certain issues in the codebase.
=> chore: Add 'unsafe_fix' target to Makefile

Makefile
This PR introduces a set of Makefile targets to streamline database migration management using Alembic within our project. The following commands have been added:
- **`alembic-revision`**: Generates a new migration script with an autogenerated schema change. Usage: `make alembic-revision message="Your message here"`.
- **`alembic-upgrade`**: Upgrades the database to the latest version. Usage: `make alembic-upgrade`.
- **`alembic-downgrade`**: Downgrades the database by one version. Usage: `make alembic-downgrade`.
- **`alembic-current`**: Displays the current migration version applied to the database. Usage: `make alembic-current`.
- **`alembic-history`**: Shows the history of all migrations. Usage: `make alembic-history`.
- **`alembic-check`**: Checks the migration status. Usage: `make …
=> chore:Add Alembic Commands to Makefile 

src/frontend/src/helpers/create-file-upload.ts
This pull request improves the createFileUpload function by adding better DOM checks and handling potential race conditions that could arise during file or folder uploads.
- Added a check to ensure the input element still exists in the DOM before attempting to remove it, preventing the "failed to execute 'RemoveChild' on 'Node': the node to be removed is not a child of this node" error.
#4070
=> fix: prevent possible race condition on upload flows/folders

src/backend/base/langflow/services/database/models/vertex_builds/model.py, src/backend/base/langflow/utils/util_strings.py, src/backend/tests/unit/utils/test_truncate_long_strings.py, src/backend/tests/unit/utils/test_truncate_long_strings_on_objects.py
This pull request addresses a performance issue in the database by truncating the params column in the vertex_build table. The params column currently stores large amounts of data, which can lead to memory heap exhaustion, causing performance degradation or potential crashes.
#4008
=> fix: truncate "params" column on vertex_build table to prevent memory heap on database

src/backend/base/langflow/schema/schema.py
Fixes #4110
This pull request enhances the `recursive_serialize_or_str` function in the `schema.py` file. It adds support for handling `BaseModelV1` in addition to `BaseModel`. It also improves the exception logging by logging the error message when an object cannot be serialized. This change ensures better error handling and more robust serialization of objects.
=> fix: enhance recursive_serialize_or_str to handle BaseModelV1 and improve exception logging

src/backend/base/langflow/components/prototypes/FlowTool.py
This pull request addresses a bug in the `Flow as Tool` feature where the `name` and `description` attributes were incorrectly associated with the class's `self.name` and `self.description`. This resulted in the tool returning the `Flow as Tool`'s own name and description instead of the values input by the user in the tool's input fields.
=> fix: name/description bug in "Flow as Tool"

pyproject.toml, uv.lock
This pull request adds the `opensearch-py` dependency to the `pyproject.toml` file. The `opensearch-py` version 2.7.1 is included as a wheel and as a source distribution. The dependency includes other required packages such as `certifi`, `events`, `python-dateutil`, `requests`, and `urllib3`.
=> chore: add opensearch-py dependency

src/backend/base/langflow/base/data/utils.py, src/backend/tests/unit/utils/test_format_directory_path.py, src/backend/tests/unit/utils/test_rewrite_file_path.py
#3997
📝 (utils.py): add format_directory_path function to properly escape and format directory paths for consistency and validity
=> fix: escape directory to prevent \n on Windows directory name to fail on Pathlib + Tests

src/frontend/src/modals/IOModal/components/chatView/chatInput/components/textAreaWrapper/index.tsx, src/frontend/src/modals/IOModal/components/chatView/chatInput/helpers/get-class-file-preview.ts, src/frontend/src/modals/codeAreaModal/index.tsx, src/frontend/src/style/applies.css
Fixed border on chat input on playground and fixed ace editor not taking up entire screen.
=> fix: border and editor display issues

src/backend/base/langflow/type_extraction/type_extraction.py, src/backend/tests/unit/test_schema.py
🐛 (type_extraction.py): fix condition to correctly handle UnionType objects in type extraction process
=> fix: Union type on components 

scripts/ci/update_lf_base_dependency.py, scripts/ci/update_pyproject_name.py, scripts/ci/update_pyproject_version.py, scripts/ci/update_uv_dependency.py, src/backend/tests/conftest.py, src/backend/tests/locust/locustfile.py, src/backend/tests/unit/test_custom_component.py, src/backend/tests/unit/test_custom_component_with_client.py, src/backend/tests/unit/test_data_components.py, src/backend/tests/unit/test_files.py, src/backend/tests/unit/test_helper_components.py
=> ref: Use pathlib in tests

src/frontend/package-lock.json, src/frontend/src/components/dateReaderComponent/index.tsx, src/frontend/src/modals/IOModal/components/chatView/chatMessage/index.tsx, src/frontend/src/modals/IOModal/index.tsx, src/frontend/src/stores/messagesStore.ts, src/frontend/src/utils/buildUtils.ts
This pull request includes several commits that address batch updates and scrolling issues in the codebase. The commits introduce changes such as using `Flush` instead of `setTimeout` to prevent batch updates, fixing scroll behavior while streaming, and using `setTimeout` with `flushSync` for batch updates in `buildUtils.ts`. These changes aim to improve the performance and functionality of the code.
=> fix: batch updates and scrolling issues

src/frontend/src/components/ui/switch.tsx, src/frontend/src/style/ag-theme-shadcn.css
This pull request fixes the toggle and row hover colors in the code. The toggle colors have been adjusted to match the desired style, and the row hover color has been changed to use the primary foreground color. These changes ensure a consistent and visually appealing user experience.
=> fix: toggle and row hover colors

src/backend/base/langflow/interface/initialize/loading.py, src/backend/base/langflow/services/variable/service.py, src/backend/tests/unit/services/variable/test_service.py
Ensure proper error handling when loading variables from the database
=> fix: environment variable loading and improve error handling in DB retrieval

pyproject.toml, src/backend/base/langflow/base/astra_assistants/util.py, uv.lock
Importing OpenAI from assistants was causing `dummy` to be set as the OPENAI_API_KEY when it is not provided resulting in a confusing error message.
=> fix: update assistants client import

.github/workflows/docker-build.yml, .github/workflows/release.yml, .github/workflows/release_nightly.yml, docker/build_and_push_ep.Dockerfile
Adds a dockerfile with entrypoint for use by datastax langflow, and adds to automation
=> build: dockerfile with entrypoint

pyproject.toml
We should consider doing this for other dependencies too.
=> chore: use ~= for assistants dependency

src/backend/base/langflow/custom/custom_component/component.py, uv.lock
This pull request fixes a bug in the custom component where the `deepcopy` function was not correctly passing the `memo` argument. This caused issues when creating a deep copy of the component. The bug has been fixed by updating the `deepcopy` calls in the `__deepcopy__` method of the component.
=> fix: add memo to deepcopy call to avoid recursion error

src/backend/base/langflow/components/tools/RetrieverTool.py
refactor build method signature to accept additional keyword arguments for future extensibility
=> fix: fix retrieverTool component

src/frontend/src/pages/FlowPage/components/nodeToolbarComponent/index.tsx
This pull request fixes an issue where the override modal was not exiting properly. The patch includes a change to the NodeToolbarComponent file that ensures the modal is closed when the component is successfully saved.
=> fix: override modal not exiting

src/backend/base/langflow/graph/vertex/base.py
🐛 (base.py): fix AttributeError by checking if custom_component has set_event_manager method before calling it
=> fix: object has no attribute 'set_event_manager'

src/backend/base/langflow/base/data/utils.py, src/backend/base/langflow/components/agents/JsonAgent.py, src/backend/base/langflow/components/agents/OpenAPIAgent.py, src/backend/base/langflow/components/documentloaders/GitLoader.py, src/backend/base/langflow/components/helpers/JSONtoData.py, src/backend/base/langflow/components/vectorstores/Redis.py, src/backend/base/langflow/custom/code_parser/code_parser.py, src/backend/base/langflow/initial_setup/setup.py, src/backend/base/langflow/interface/utils.py, src/backend/base/langflow/services/cache/utils.py, src/backend/base/langflow/services/database/service.py, src/backend/base/langflow/services/settings/base.py, src/backend/base/langflow/services/settings/manager.py, src/backend/base/langflow/services/settings/utils.py, src/backend/base/langflow/services/storage/local.py
Use pathlib read/write functions
=> ref: Use pathlib read/write functions

src/backend/base/langflow/services/settings/base.py
=> feat: concat default variables with env values

src/frontend/src/components/headerComponent/index.tsx
- Added logic to change the **My Collection** button variant to "primary" or "secondary" in the header based on the current pathname, including the "/flows" route.
**Before**:
**After**:
=> fix: Update header button variant based on the active route (#4207)

src/backend/base/langflow/api/health_check_router.py, src/backend/base/langflow/api/v1/api_key.py, src/backend/base/langflow/api/v1/chat.py, src/backend/base/langflow/api/v1/endpoints.py, src/backend/base/langflow/api/v1/files.py, src/backend/base/langflow/api/v1/flows.py, src/backend/base/langflow/api/v1/login.py, src/backend/base/langflow/api/v1/monitor.py, src/backend/base/langflow/api/v1/starter_projects.py, src/backend/base/langflow/api/v1/store.py, src/backend/base/langflow/api/v1/users.py, src/backend/base/langflow/api/v1/validate.py, src/backend/base/langflow/api/v1/variable.py, src/backend/tests/conftest.py, src/backend/tests/unit/test_files.py
It doesn't have added value to put `get_xxx_service` methods in `Depends` injections. It even makes the code harder to read.
So this PR moves them to the code.
This PR also removes some `response_model` when they can be set as the method return type.
=> ref: Move get services out of API methods

src/backend/base/langflow/api/utils.py, src/backend/base/langflow/api/v1/chat.py, src/backend/base/langflow/base/io/chat.py, src/backend/base/langflow/base/vectorstores/model.py, src/backend/base/langflow/graph/edge/base.py, src/backend/base/langflow/graph/graph/base.py, src/backend/base/langflow/graph/graph/state_model.py, src/backend/base/langflow/graph/vertex/base.py, src/backend/base/langflow/graph/vertex/types.py, src/backend/base/langflow/services/chat/service.py, src/backend/base/langflow/services/socket/utils.py, src/backend/base/langflow/services/store/service.py, src/backend/base/pyproject.toml, src/backend/tests/integration/utils.py, src/backend/tests/unit/graph/graph/test_cycles.py
Fixing but not enforcing at the moment since a lot of attributes can't be changed in Component
Renamed:
- Vertex._added_message
- Vertex._custom_component Vertex._built
- Vertex._built_object
- Vertex._built_result
- Vertex._data
- Vertex._raw_params
- Vertex._has_cycle_edges
- Vertex._build_params()
- Vertex._parse_data()
- Vertex._built_object_repr()
- Vertex._finalize_build()
- Graph._has_session_id_vertices
- StoreService._get()
- ChatService._async_cache_locks
- build_vector_store._is_cached_vector_store_checked
=> ref: Fix some ruff rules for private access (SLF)

src/backend/base/langflow/components/vectorstores/astradb_graph.py
Add AstraGraphVectorStoreComponent
See https://python.langchain.com/api_reference/astradb/graph_vectorstores/langchain_astradb.graph_vectorstores.AstraDBGraphVectorStore.html
=> feat: Add AstraGraphVectorStoreComponent

src/frontend/src/contexts/authContext.tsx, src/frontend/src/controllers/API/api.tsx, src/frontend/src/controllers/API/queries/folders/use-get-folders.ts, src/frontend/src/controllers/API/queries/variables/use-get-mutation-global-variables.ts, src/frontend/src/stores/authStore.ts
✨ (authContext.tsx): Add functionality to fetch global variables on authentication
🔧 (api.tsx): Replace universal-cookie import with react-cookie for consistency
🔧 (authStore.ts): Replace universal-cookie import with react-cookie for consistency
🔧 (use-get-global-variables.ts): Add check to only fetch global variables if user is authenticated
✨ (use-get-mutation-global-variables.ts): Add mutation function to fetch and update global variables
🔧 (authStore.ts): Replace universal-cookie import with react-cookie for consistency
=> fix: correctly call the /variable endpoint after the user is authenticated

src/backend/base/langflow/schema/artifact.py, src/backend/base/langflow/schema/data.py, src/backend/base/langflow/schema/schema.py, src/backend/base/langflow/schema/serialize.py
This pull request includes two commits. The first commit enhances the data serialization process by adding recursive handling in the `to_json` method. This allows for better handling of `datetime` objects by converting them to ISO format. The second commit refactors the `recursive_serialize_or_str` function into a separate module called `serialize.py`. This improves modularity and reusability of the code. The function is moved from `schema.py` to the new module, and the imports in `data.py`, `artifact.py`, and `schema.py` are updated accordingly.
=> fix: make sure data is json serializable

src/backend/base/langflow/initial_setup/setup.py, src/backend/base/langflow/main.py, src/backend/base/langflow/services/telemetry/service.py
Removes a lot of `Task was destroyed but it is pending!` warnings during tests
=> fix: Fix async usage in app startup

src/frontend/src/modals/apiModal/utils/get-curl-code.tsx, src/frontend/src/modals/apiModal/utils/get-js-api-code.tsx, src/frontend/src/modals/apiModal/utils/get-python-api-code.tsx, src/frontend/src/modals/apiModal/utils/get-python-code.tsx, src/frontend/src/stores/tweaksStore.ts, src/frontend/src/types/tweaks/index.ts
This pull request fixes an issue where an error would occur on an API call when tweaks are active. The fix removes the input value when tweaks are active to prevent the error.
#4148
=> fix: input value error when tweaks are active

src/backend/base/langflow/load/load.py, src/backend/base/langflow/logging/logger.py, src/backend/base/langflow/main.py
The Loguru FileSink is blocking so it is bad to use it in the event loop.
Use instead an AsyncSink wrapping the FileSink to delegate the log writing to the default thread pool.
NB: when the AsyncFileSink is used, logs produced outside of the event loop are not written to the file.
=> fix: Make logger file sink non-blocking when used with asyncio

src/backend/base/langflow/base/agents/agent.py, src/backend/base/langflow/components/agents/tool_calling.py
This pull request introduces several enhancements and refactorings to improve agent processing and streamline the codebase. The most significant changes include adding a new method for processing agent events, updating type imports, and modifying input handling in the `ToolCallingAgentComponent`.
* [`src/backend/base/langflow/base/agents/agent.py`](diffhunk://#diff-87ba96f91b4bbce3350ae83d5d4c7dfa3a7c800deeed21a60857dff1caaefe04L112-R168): Added `process_agent_events` method to handle different agent events asynchronously, improving the logging and processing of agent events.
* [`src/backend/base/langflow/base/agents/agent.py`](diffhunk://#diff-87ba96f91b4bbce3350ae83d5d4c7dfa3a7c800deeed21a60857dff1caaefe04L149-R214): Updated `run_agent` method to use `process_agent_events` for better …
=> refactor: update inputs in `ToolCallingAgentComponent` and add astream_events setup

.github/workflows/python_test.yml, Makefile, pyproject.toml, src/backend/base/pyproject.toml, uv.lock
Introduce the `--exclude-warning-annotations` option to pytest commands in the Makefile to enhance test output control. Update dependencies in `pyproject.toml` to include `pytest-github-actions-annotate-failures` for improved failure annotation in GitHub Actions.
* Added lgtm label to test ci
=> ci: add pytest failure annotations

src/backend/base/langflow/api/v1/chat.py, src/backend/base/langflow/custom/directory_reader/directory_reader.py, src/backend/base/langflow/services/database/models/vertex_builds/model.py
This pull request includes several changes aimed at improving asynchronous task handling, fixing encoding issues, and modifying serialization methods. The most important changes are grouped by their themes below:
* [`src/backend/base/langflow/api/v1/chat.py`](diffhunk://#diff-44baaabf1ab87d4713c828053d97a7f9f5dc8d1ab9c2f8d05c1a0bcdc43e999cL331-R331): Simplified the creation of asynchronous tasks by directly calling async functions instead of using `asyncio.to_thread`. [[1]](diffhunk://#diff-44baaabf1ab87d4713c828053d97a7f9f5dc8d1ab9c2f8d05c1a0bcdc43e999cL331-R331) [[2]](diffhunk://#diff-44baaabf1ab87d4713c828053d97a7f9f5dc8d1ab9c2f8d05c1a0bcdc43e999cL363-R364)
* [`src/backend/base/langflow/custom/directory_reader/directory_reader.py`](diffhunk://#diff-800eb80c3693169ed81e9b469c1f8d26285b79 …
=> fix: Refactor file reading and async task creation, fix return type in vertex_builds model

src/backend/base/langflow/api/v1/folders.py
This pull request fixes a cartesian product warning in `delete_folder` by replacing Folder.user_id with Flow.user_id for correct filtering.
The query previously used Folder.user_id, leading to the warning: `SAWarning: SELECT statement has a cartesian product between FROM element(s) "flow" and FROM element "folder".`
=> fix: cartesian product warning in delete_folder

.github/workflows/docker-build.yml, .github/workflows/nightly_build.yml, .github/workflows/release_nightly.yml, docker/build_and_push_base.Dockerfile, scripts/ci/update_pyproject_combined.py
This pull request includes several updates to the CI/CD workflows and Docker build configurations to improve reliability and maintainability. Key changes include adding environment setup steps, enhancing error handling, unifying version update scripts, and modifying Dockerfile mounts and paths.
* **Environment Setup:** Added a new step to set up the environment in the `docker-build.yml` workflow. (`.github/workflows/docker-build.yml`)
* **Error Handling:** Enhanced error handling for version extraction in the `docker-build.yml` workflow. (`.github/workflows/docker-build.yml`)
* **Mounting Project Files:** Updated the Dockerfile to mount additional project files required for building with `uv`. (`docker/build_and_push_base.Dockerfile`) …
=> chore: update dockerfiles and docker-build workflows to fix releases

pyproject.toml, src/backend/base/langflow/base/agents/crewai/crew.py, src/frontend/tests/core/integrations/Hierarchical Agent.spec.ts, src/frontend/tests/core/integrations/Sequential Task Agent.spec.ts, uv.lock
This pull request includes updates to dependencies and a modification to the `step_callback` method in the `crew.py` file to handle the `result` object more precisely.
* [`pyproject.toml`](diffhunk://#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711L57-R57): Updated the `langfuse` dependency to version `2.53.1` because we were hitting https://github.com/langfuse/langfuse/issues/3757#issuecomment-2437997123
Codebase improvements:
* [`src/backend/base/langflow/base/agents/crewai/crew.py`](diffhunk://#diff-aac665729add88217de9d16ee357a07a7220dc39b132f6683e286f3ea8b624fdL81-R81): Modified the `step_callback` method to use `result.raw` instead of `result` directly, ensuring the correct attribute is accessed for the message text. …
=> fix: langfuse upgrade and crew result usage

src/backend/base/langflow/initial_setup/setup.py
This pull request includes changes to the `src/backend/base/langflow/initial_setup/setup.py` file to remove the `Graph` import and its usage in the `create_or_update_starter_projects` function. These changes simplify the initial setup process by eliminating unnecessary error handling related to `Graph` that caused all projects to be built and slowed startup.
Codebase simplification:
* Removed the import of `Graph` from `langflow.graph.graph.base` as it is no longer used.
* Removed the try-except block that attempted to create a `Graph` from the project data and logged an exception if it failed, simplifying the `create_or_update_starter_projects` function.
=> refactor: remove error handling for Graph loading in starter project setup

src/backend/base/langflow/logging/logger.py
This pull request refactors the logger to dynamically retrieve the maximum buffer size from the environment variable `LANGFLOW_LOG_RETRIEVER_BUFFER_SIZE`. This change allows for more flexibility as the buffer size can now be adjusted without needing to restart the application, improving the overall logging functionality.
=> refactor: dynamically retrieve maximum buffer size from environment in SizedLogBuffer

src/backend/base/langflow/base/models/model.py, src/backend/base/langflow/base/models/model_constants.py, src/backend/base/langflow/base/models/model_utils.py, src/backend/base/langflow/worker.py, src/backend/tests/unit/base/models/test_model_constants.py
This pull request introduces several significant changes to improve the handling of language models within the `langflow` project. The main updates include the addition of methods for building and retrieving language models, the introduction of a new class for model constants, and utility functions for model information retrieval. Additionally, a unit test has been added to verify the initialization of model constants.
Introduced `ModelConstants` class in `model_constants.py` to hold model-related constants and solve circular import issues. This includes methods for initializing provider names and model information.
1. **`PROVIDER_NAMES`**:
- This is a list that holds the names of model providers. It is populated with the `display_name` of each model from the `MODEL_INFO` dictionary.
- …
=> feat: Add model_utils and model_constants intorducing  `PROVIDER_NAMES` and `MODEL_INFO` variables for dynamic updation of model data

src/backend/base/langflow/components/vectorstores/astradb.py
This pull request fixes a bug in the Astra DB component which passes empty lists for the metadata include and exclude parameters, where the underlying `langchain-astradb` code explicitly expects them to be None (and providing empty lists for both results in an error).
```python
"""
Validate the constructor indexing parameters and normalize them
into a ready-to-use dict for the 'options' when creating a collection.
"""
params = [
metadata_indexing_include,
metadata_indexing_exclude,
collection_indexing_policy,
]
if params.count(None) < len(params) - 1:
msg = (
"At most one of the parameters `metadata_indexing_include`,"
" `metadata_indexing_exclude` and `collection_indexing_policy`"
" can be specified as non null."
)
raise ValueError(msg)
```
=> Bugfix langchain astradb metadata

.github/workflows/codspeed.yml, pyproject.toml, src/backend/base/pyproject.toml, uv.lock
This pull request introduces a new CodSpeed workflow to automate benchmarking on pull requests, enhancing performance tracking and ensuring consistent test execution. Additionally, it incorporates the `pytest-codspeed` package to improve performance testing capabilities, allowing for better measurement of the test suite's speed. These changes aim to maintain high code quality and performance standards in the project.
No benchmarks were added yet
=> ci: add CodSpeed workflow and pytest-codspeed for performance testing

src/backend/base/langflow/api/utils.py, src/backend/base/langflow/api/v1/flows.py, src/backend/base/langflow/api/v1/folders.py, src/backend/base/langflow/api/v1/store.py, src/backend/base/langflow/graph/graph/base.py, src/backend/base/langflow/graph/vertex/base.py, src/backend/base/langflow/interface/initialize/loading.py, src/backend/base/langflow/services/auth/utils.py, src/backend/tests/blockbuster.py, src/backend/tests/unit/api/v1/test_variable.py, src/backend/tests/unit/test_messages_endpoints.py, src/backend/tests/unit/test_user.py
Make some functions that don't await non-async (RUF029)
=> ref: Make some functions that don't await non-async (RUF029)

src/backend/base/langflow/components/langchain_utilities/sql_database.py
When running the SQLDatabase component, it gives an error that it does not have the set_event_manager. To fix this, I changed the inherited class to Component, which has the newly implemented event control.
=> fix: SQLDatabase has no attribute set_event_manager

src/backend/base/langflow/api/v1/login.py, src/backend/base/langflow/services/auth/utils.py, src/backend/base/langflow/services/database/service.py, src/backend/base/langflow/services/utils.py
Fix db session used in different threads
=> fix: Fix db session used in different threads

.github/workflows/codspeed.yml, src/backend/tests/performance/test_server_init.py, src/backend/tests/unit/test_chat_endpoint.py, src/backend/tests/unit/test_endpoints.py
This pull request introduces benchmark tests to evaluate the performance of database initialization and application startup processes. Additionally, benchmark markers have been added to various test cases to help identify potential bottlenecks and ensure overall efficiency in the application setup. These enhancements aim to improve performance monitoring and facilitate future optimizations.
=> tests: Add performance benchmarks for database initialization and app startup

src/backend/base/langflow/components/agents/__init__.py, src/backend/base/langflow/components/models/openai.py, src/backend/base/langflow/custom/custom_component/component.py, src/backend/tests/unit/custom/custom_component/test_component.py
Reverts langflow-ai/langflow#4389 because it caused the starter projects update logic to change wrong parameters.
=> Revert "fix: Optimize Setting of Output Required Inputs"

src/backend/base/langflow/components/vectorstores/astradb.py
This PR fixes #4387 by passing in the optional embedding provider key properly
=> fix: Handle BYO Embeddings (#4387)

src/frontend/src/CustomNodes/GenericNode/components/NodeName/index.tsx, src/frontend/src/CustomNodes/GenericNode/components/NodeStatus/index.tsx, src/frontend/src/CustomNodes/GenericNode/index.tsx, src/frontend/src/controllers/API/api.tsx, src/frontend/src/pages/FlowPage/components/nodeToolbarComponent/index.tsx, src/frontend/src/style/index.css
This pull request introduces several updates to the `NodeName`, `NodeStatus`, and `GenericNode` components, along with some style adjustments. The main changes include adding support for beta nodes, updating UI elements, and refining CSS variables for better theming.
* Added a `beta` property to the `NodeName` component and adjusted the class names to reflect the beta status. [[1]](diffhunk://#diff-cd0ae5bd5cad085fffab84b76a875266eba559321189b95ea5efc61e24efce6dR16-R24) [[2]](diffhunk://#diff-cd0ae5bd5cad085fffab84b76a875266eba559321189b95ea5efc61e24efce6dR93)
* Updated the `NodeStatus` component to display a "BETA" badge when the node is in beta status.
* Modified the `GenericNode` component to pass the `beta` property and display a shadow effect on hover. …
=> feat: Change Beta Tag and UI Enhancements for Node Components

src/backend/base/langflow/components/vectorstores/pinecone.py
Error building Component Pinecone: Invalid type for variable '0'. Required value type is float and passed type was float64 at ['values'][0]
Fixed the issue by forcing float32
=> fix: correct issue with handling float32

src/backend/base/langflow/components/vectorstores/astradb.py, src/frontend/src/components/canvasControlsComponent/index.tsx, src/frontend/src/components/flowToolbarComponent/index.tsx, src/frontend/src/modals/templatesModal/components/GetStartedComponent/index.tsx, src/frontend/src/modals/templatesModal/components/navComponent/index.tsx, src/frontend/src/modals/templatesModal/index.tsx, src/frontend/tests/extended/features/starter-projects.spec.ts, src/frontend/tests/extended/features/twoEdges.spec.ts
=> refactor: Design tweaks canvas actions and templates based on uplift feedback

src/frontend/src/modals/apiModal/utils/get-js-api-code.tsx
This pull request refactors the API key header in the `get-js-api-code.tsx` file to use the `x-api-key` header instead of the `Authorization` header. It also removes the streaming functionality from the `initiateSession` and `runFlow` functions. This change improves the code by simplifying the API key handling and removing unnecessary streaming code.
=> fix: Refactor API key header and remove streaming

src/backend/base/langflow/schema/message.py, src/frontend/package-lock.json, src/frontend/src/modals/IOModal/components/chatView/chatMessage/newChatMessage.tsx
This pull request updates the error message structure in the ChatMessage component to fix a merge error.
=> fix: update error message structure in ChatMessage component

README.ES.md, README.KR.md, README.PT.md, README.ja.md, README.zh_CN.md
This PR updates the documentation to reflect the parameter change from `--timeout` to `--worker-timeout` in the Langflow CLI commands. The change clarifies usage for setting API timeouts.
This can be verified with the CLI command:
```
langflow run --help
```
I noticed this issue while responding to Issue #4442
=> docs: replace --timeout with --worker-timeout

src/frontend/src/CustomNodes/GenericNode/components/NodeInputField/index.tsx, src/frontend/src/CustomNodes/GenericNode/components/NodeStatus/index.tsx, src/frontend/src/components/pageLayout/index.tsx, src/frontend/src/customization/components/custom-parameter.tsx, src/frontend/src/pages/FlowPage/components/ParentDisclosureComponent/index.tsx, src/frontend/src/pages/FlowPage/components/flowSidebarComponent/components/emptySearchComponent/index.tsx, src/frontend/src/pages/FlowPage/components/flowSidebarComponent/components/featureTogglesComponent/index.tsx, src/frontend/src/pages/FlowPage/components/flowSidebarComponent/components/sidebarDraggableComponent/index.tsx, src/frontend/src/pages/FlowPage/components/flowSidebarComponent/components/sidebarFooterButtons/index.tsx, src/frontend/src/pages/FlowPage/components/flowSidebarComponent/components/sidebarItemsList/index.tsx, src/frontend/src/pages/FlowPage/components/flowSidebarComponent/helpers/apply-beta-filter.ts, src/frontend/src/pages/FlowPage/components/flowSidebarComponent/helpers/apply-edge-filter.ts, src/frontend/src/pages/FlowPage/components/flowSidebarComponent/helpers/apply-legacy-filter.ts, src/frontend/src/pages/FlowPage/components/flowSidebarComponent/helpers/combined-results.ts, src/frontend/src/pages/FlowPage/components/flowSidebarComponent/helpers/filtered-data.ts, src/frontend/src/pages/FlowPage/components/flowSidebarComponent/helpers/normalize-string.ts, src/frontend/src/pages/FlowPage/components/flowSidebarComponent/helpers/search-on-metadata.ts, src/frontend/src/pages/FlowPage/components/flowSidebarComponent/helpers/traditional-search-metadata.ts, src/frontend/src/pages/FlowPage/components/flowSidebarComponent/index.tsx
This pull request introduces several changes to the frontend components and utilities, primarily focusing on enhancing the user interface and improving the filtering and search functionalities. Key changes include updates to component styles, the addition of new components, and the implementation of various filtering helpers.
* [`src/frontend/src/CustomNodes/GenericNode/components/NodeInputField/index.tsx`](diffhunk://#diff-b68d4cff4ce636f41882b2e6c2fb46ce2e134bdf292e38bcf6df9c6c5807d518L128-R131): Modified the `getCustomParameterTitle` function to include `isFlexView` parameter for better flexibility in view rendering. [[1]](diffhunk://#diff-b68d4cff4ce636f41882b2e6c2fb46ce2e134bdf292e38bcf6df9c6c5807d518L128-R131) [[2]](diffhunk://#diff-b68d4cff4ce636f41882b2e6c2fb46ce2e134bdf292e38bcf6d …
=> feat: Enhance sidebar components

pyproject.toml, uv.lock
This pull request includes a small change to the `pyproject.toml` file. The change adds a new dependency to the project.
* Added `atlassian-python-api>=3.41.16` to the dependencies list in `pyproject.toml`.
closes #4309 4309
=> fix: adding atlassian-python-api to support confluence components

src/backend/base/langflow/custom/custom_component/component.py, src/backend/tests/unit/components/agents/test_agent_component.py
I added a StructuredTool to define the set function in the component. This change resolved an error that occurred when the list of tools was set by the component. In the future, we may need to add tests to manage unexpected situations in the component's set function.
I also updated the pytest related to Agent which had the wrong function of getting the response.
---------
This pull request includes changes to the `src/backend/base/langflow/custom/custom_component/component.py` and `src/backend/tests/unit/components/agents/test_agent_component.py` files to enhance functionality and improve the testing process.
* [`src/backend/base/langflow/custom/custom_component/component.py`](diffhunk://#diff-22fd745de33f20981c7cbcbf3c91d4a6f8719de20761eb22cf42f8ed6ec50169R13): Imported `StructuredTool` …
=> fix: component-set-handle-list-tools

.github/workflows/python_test.yml
This change modifies the CI configuration to stop backend unit tests on the first failure. By doing this, we can save time and resources in the CI pipeline, as tests won’t continue to run after a failure is detected. This should speed up feedback loops and reduce unnecessary processing.
reference: https://docs.pytest.org/en/stable/how-to/failures.html
=> ci: stop backend unit tests on first failure

.github/workflows/codspeed.yml, src/backend/tests/performance/test_server_init.py, src/backend/tests/unit/custom/custom_component/test_component_events.py
This pull request introduces a temporary database setup for performance tests by creating a fixture that sets a test database URL. The fixture ensures that the original database URL is restored after the tests are completed. Additionally, assertions have been added to various performance tests to verify that the temporary database URL is being used during the tests. This change enhances the reliability of performance testing by isolating the test environment.
=> ci: Add temporary database setup for performance tests

src/frontend/src/pages/FlowPage/index.tsx, src/frontend/src/pages/MainPage/pages/index.tsx
This pull request includes updates to improve the layout and overflow handling of the `FlowPage` and `CollectionPage` components in the frontend codebase.
Layout and overflow improvements:
* [`src/frontend/src/pages/FlowPage/index.tsx`](diffhunk://#diff-37a243d7fe9faf77fead8ea245d2884933fc5373bb9b4200371887aa989e21feL172-R172): Updated the `main` element to use `w-full` and `overflow-hidden` classes to better handle overflow and ensure the main content occupies the full width.
* [`src/frontend/src/pages/MainPage/pages/index.tsx`](diffhunk://#diff-1298711fb00b5357b2e39b6bab21791701b73458092407d6732e0dd28ae49475L75-R75): Similarly updated the `main` element to use `w-full` and `overflow-hidden` classes to improve layout consistency and overflow handling.
=> fix: refactor sidebar disposition for sidebar to not push main out of screen

src/backend/base/langflow/schema/serialize.py
This pull request addresses the serialization of BaseModel subclasses by ensuring that type objects are handled separately. The changes prevent type objects from being incorrectly serialized as instances, improving the overall serialization logic. This update enhances the robustness of the serialization process for models derived from BaseModel.
=> fix: serialize BaseModel subclasses and avoid calling methods on types

src/backend/base/langflow/components/textsplitters/__init__.py, src/backend/base/langflow/components/textsplitters/language_semantic.py
**Feat: Semantic Text Splitter with Advanced Threshold Controls**
**Overview**
Introduces a new Semantic Text Splitter component that provides flexible text chunking with statistical threshold controls and regex support.
**Features:**
- Multiple threshold control methods:
- Percentile-based splitting
- Standard deviation thresholds
- Interquartile range
- Configurable chunk size and count
- Optional regex-based splitting
=> feat: Adding Semantic Text Splitter Component (Text Splitters)

src/backend/base/langflow/utils/validate.py
This pull request includes improvements to the `extract_class_name` function in the `src/backend/base/langflow/utils/validate.py` file. The changes enhance the function's robustness and readability by adding type annotations, a detailed docstring, and additional error handling.
Improvements to `extract_class_name` function:
* Added type annotations to specify that the `code` parameter is a string and the function returns a string.
* Included a detailed docstring that describes the function's purpose, arguments, return value, and potential exceptions.
* Enhanced error handling by adding a `try-except` block to catch `SyntaxError` exceptions and raise a `ValueError` with a descriptive message.
* Improved the logic for checking class inheritance by iterating through the `bases` of class …
=> fix: Enhance extract_class_name function to identify Component subclasses

src/backend/base/langflow/base/agents/agent.py, src/backend/base/langflow/base/agents/events.py, src/backend/base/langflow/schema/message.py
This pull request simplifies the exception handling in the `LCAgentComponent` by removing redundant exception parameters and ensuring that nested exceptions are properly handled during message schema initialization. The `ExceptionWithMessageError` class has been refactored to streamline its usage, enhancing clarity and maintainability of the error handling logic.
=> fix: Simplify exception handling and refactor error messaging

Makefile
This pull request includes updates to the `Makefile` to enhance the flexibility and functionality of running unit tests. The most important changes include the addition of new flags for controlling test execution and the simplification of conditional logic for running tests.
Enhancements to test execution:
* [`Makefile`](diffhunk://#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52R22-R23): Added new flags `lf` and `ff` to control the behavior of the `pytest` command, allowing tests to run with the `--lf` (last-failed) and `--ff` (failed-first) options.
Simplification of conditional logic:
* [`Makefile`](diffhunk://#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52L133-R148): Simplified the conditional logic for running unit tests by consolidating …
=> chore: Add 'lf' and 'ff' options to Makefile for pytest configuration

pyproject.toml, src/frontend/tests/extended/integrations/duckduckgo.spec.ts, uv.lock
This pull request includes updates to dependencies and improvements to the DuckDuckGo search component test. The most important changes include updating the `duckduckgo-search` dependency version and modifying the test for the DuckDuckGo search component to remove the skip flag and improve the test logic.
* [`pyproject.toml`](diffhunk://#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711L94-R94): Updated `duckduckgo-search` dependency version from `6.3.0` to `6.3.4`.
Test improvements:
* [`src/frontend/tests/extended/integrations/duckduckgo.spec.ts`](diffhunk://#diff-4adeafe8432cd447af72a709cfd02bf951cabc4df1e40abb0ca6b725b98e9ae8L3-R3): Removed the `.skip` flag from the test for the DuckDuckGo search component, enabling the test to run.
* …
=> fix: Update duckduckgo-search to 6.3.4 and improve tests

src/frontend/src/CustomNodes/GenericNode/components/NodeDescription/index.tsx
This pull request includes a small change to the `src/frontend/src/CustomNodes/GenericNode/components/NodeDescription/index.tsx` file. The change adds the `nowheel` class to the `Markdown` component's className property to modify its styling.
=> fix: prevent nested scrolling in markdown code blocks

src/backend/base/langflow/components/vectorstores/astradb.py
This pull request cleans up some of the authentication parameters, properly passing a None value with the authentication is empty to allow for connecting to a vector store generated with NVIDIA vectorize
=> FIX: Properly pass missing vectorize params in Astra DB

src/backend/base/langflow/components/processing/parse_json_data.py, src/backend/tests/integration/components/helpers/test_parse_json_data.py
Summary: Prevent wrapping non-array inputs in arrays to ensure correct JSON parsing and filtering.
This PR addresses an issue where the ParseJSONDataComponent was always wrapping the input in an array, even if the input was not an array. This caused incorrect JSON parsing and filtering.
Changes
Modified the filter_data method to check if the input is a list before wrapping it.
If the input is not a list, it is processed as a single value.
If the input is a list, each item is processed separately.
Testing:
Run jq query - `.`
- input non array
output
- input array
output
=> fix: ParseJSONDataComponent prevent unnecessary array wrapping

src/frontend/src/pages/SignUpPage/index.tsx
Update the styling of the SignUpPage component to use the full screen height instead of a fixed height. This ensures that the page takes up the entire screen on all devices.
=> fix: update SignUpPage component styling to use full screen height

.github/workflows/codspeed.yml
This PR introduces concurrency control to the Run benchmarks workflow by adding a configuration that cancels in-progress runs. This enhancement ensures that only the latest workflow run is executed, improving resource management and efficiency during concurrent executions.
=> ci: Add concurrency control to Run benchmarks workflow

src/frontend/src/components/chatComponents/ContentBlockDisplay.tsx
This PR fixes the issue with the ContentBlockDisplay component not displaying block titles correctly. The commit removes the reverse bug logic in the playground and updates the conditional rendering logic for the block title in ContentBlockDisplay. It also adjusts the styling to ensure proper alignment and spacing. Ref: #4533.
=> fix: ContentBlockDisplay styling for block titles

src/backend/base/langflow/components/crewai/hierarchical_crew.py
This pull requests sets the OpenAI API Key as an environment variable and adds a new input to provide it in the hierarchical crew component
=> fix: Pass the OpenAI API Key to Crew()

src/backend/base/langflow/base/models/model_utils.py, src/backend/base/langflow/components/agents/agent.py
This pull request introduces a new utility function to extract the model name from a language model object and integrates this function into the agent component to enhance model handling.
* [`src/backend/base/langflow/base/models/model_utils.py`](diffhunk://#diff-3993cb22ffb3b497c82a36c953b945c89c6fffb36f90c33e635bbe18b9afdba8R1-R8): Added a `get_model_name` function to extract the model name from a language model object by checking for various attributes or falling back to the class name.
* [`src/backend/base/langflow/components/agents/agent.py`](diffhunk://#diff-b6bc6deb80f602f04a7fac26a6a51437042fbf4f791a9e35ac38bb204f846496R5): Imported the `get_model_name` function.
* [`src/backend/base/langflow/components/agents/agent.py`](diffhunk://#diff-b6bc6deb80f602f04a7fac2 …
=> fix: added model utils to get the model name

src/backend/base/langflow/components/processing/filter_data_values.py
This pull request refactors the inputs of the DataFilterComponent to use the StrInput class instead of the MessageInput class. The StrInput class is more appropriate for handling string inputs, and this change improves the clarity and consistency of the code.
=> fix: Refactor DataFilterComponent inputs

src/backend/base/langflow/services/settings/base.py, src/backend/base/langflow/services/tracing/service.py, src/backend/tests/conftest.py
This pull request introduces a new setting to deactivate tracing within the service settings, allowing for more flexible testing and configuration. Additionally, a fixture has been added to automatically deactivate tracing in tests using monkeypatch, ensuring that tracing does not interfere with test outcomes.
=> feat: Add option to deactivate tracing in service settings

src/frontend/src/pages/FlowPage/components/nodeToolbarComponent/index.tsx
This pull request includes a small change to the `NodeToolbarComponent` in `src/frontend/src/pages/FlowPage/components/nodeToolbarComponent/index.tsx`. The change removes the `open` prop from the `Select` component to potentially manage the component's open state differently.
* [`src/frontend/src/pages/FlowPage/components/nodeToolbarComponent/index.tsx`](diffhunk://#diff-d393b1ee50eb66298a5ab133ad2f25d072667612a1c6457f24aa6733c98131aaL557): Removed the `open` prop from the `Select` component.
=> refactor(NodeToolbar): Remove open prop from Select component

src/backend/base/langflow/base/models/aws_constants.py, src/backend/base/langflow/components/embeddings/amazon_bedrock.py
This pull request includes updates to the AWS model IDs and the `AmazonBedrockEmbeddingsComponent` class to enhance the organization and functionality of the codebase. The most important changes include the addition of new model IDs, the removal of certain models, and the introduction of a new constant for embedding model IDs.
Updates to AWS model IDs:
* [`src/backend/base/langflow/base/models/aws_constants.py`](diffhunk://#diff-6904bd334c473029f81cec383046983131b3124b1652a6ef4a78a89a57dfca1cR2-R53): Added new model IDs for Amazon Titan, Anthropic, AI21 Labs, Cohere, Meta, and Mistral AI models. Removed certain model IDs and created a new constant `AWS_EMBEDDING_MODEL_IDS` for embedding models.
Enhancements to AmazonBedrockEmbeddingsComponent:
* …
=> fix: aws components and model lists

.github/workflows/py_autofix.yml, .github/workflows/style-check-py.yml
This pull request refines the CI workflows by limiting the style check and autofix processes to Python files only. Additionally, it optimizes the environment setup for the autofix workflow, improving efficiency and reducing unnecessary checks on non-Python files.
=> ci: Limit workflows to Python files and optimize environment setup

pyproject.toml, src/backend/base/pyproject.toml, uv.lock
This pull request updates the version numbers for the `langflow` package to 1.1.0 and for the `langflow-base` package to 0.1.0 in their respective `pyproject.toml` files and the lock file. These changes reflect the latest updates and improvements made to the packages.
=> chore: Bump version to 1.1.0 and 0.1.0 for langflow and langflow-base

src/backend/base/langflow/processing/process.py, src/backend/base/langflow/processing/utils.py
This pull request refactors the `process.py` file to use the `validate_and_repair_json` function from the `utils.py` file for nested dictionary tweaks. The `apply_tweaks` function now checks if the tweak value is a nested dictionary and calls `validate_and_repair_json` to validate and repair the JSON string if necessary. This ensures that the JSON string is valid and can be parsed correctly.
=> fix: process.py to use validate_and_repair_json from utils.py

src/frontend/src/CustomNodes/GenericNode/components/NodeDescription/index.tsx, src/frontend/src/components/shadTooltipComponent/index.tsx, src/frontend/src/components/ui/sidebar.tsx, src/frontend/src/components/ui/tooltip.tsx, src/frontend/src/modals/apiModal/utils/get-js-api-code.tsx, src/frontend/src/modals/templatesModal/components/navComponent/index.tsx, src/frontend/src/stores/tweaksStore.ts
This pull request includes several changes to the tooltip components and the `getJsApiCode` function. The main updates involve refactoring tooltip usage, adjusting z-index values for tooltips, and simplifying the JavaScript API code generation.
* Updated the z-index values for `TooltipContent` and `TooltipContentWithoutPortal` to ensure tooltips are displayed correctly above other elements. (`src/frontend/src/components/shadTooltipComponent/index.tsx`, `src/frontend/src/components/ui/tooltip.tsx`) [[1]](diffhunk://#diff-d4bcf1bdb0e5e45e6424621aa9934f69faafb7698e3500304358e8dd0bea6921L31-R31) [[2]](diffhunk://#diff-8cce19b187a7886c71050ff6f6e140f945a1bb4860460e4c94124f9624aa8525L22-R22) [[3]](diffhunk://#diff-8cce19b187a7886c71050ff6f6e140f945a1bb4860460e4c94124f9624aa8525L39-R39)
* …
=> fix: improve js api code and fix tooltip z-index

.github/workflows/python_test.yml, .github/workflows/release.yml, .github/workflows/release_nightly.yml, pyproject.toml
This pull request updates the `langflow-base` dependency in the `pyproject.toml` file from version 0.0.99 to 0.1.0, ensuring that the project uses the latest features and fixes available in the new version.
=> chore: Update langflow-base dependency to version 0.1.0

.github/workflows/release.yml
This PR introduces a condition to the PyPI publish step in the release workflow, ensuring that the publish action only occurs if the version check step does not indicate a skip. This change enhances the workflow's efficiency by preventing unnecessary publish attempts.
=> ci: Add condition to PyPI publish step in release workflow

.github/workflows/create-release.yml
This PR introduces a new GitHub Actions workflow that facilitates the creation of releases. It allows users to specify the version, commit reference, and whether the release is a pre-release. Additionally, the POETRY_VERSION environment variable has been removed from the create-release workflow to streamline the process.
=> ci: Add GitHub Actions workflow for creating releases

src/backend/base/langflow/custom/custom_component/custom_component.py
This pull request addresses an issue with the `user_id` access logic within the `CustomComponent` class. Previously, there were inconsistencies in how the `user_id` attribute was accessed, leading to potential errors when the attribute was not set or incorrectly retrieved. 
In the BaseComponent, the default setting of `self._user_id` to None led to inaccurate user_id retrieval: 
https://github.com/langflow-ai/langflow/blob/2f96dbbdd4d26f5c837f4d651ec9bc42a03a97b5/src/backend/base/langflow/custom/custom_component/base_component.py#L31
The use of `hasattr(self, '_user_id')` always returned True, causing `_user_id` to be returned even when it was None.
https://github.com/langflow-ai/langflow/blob/2f96dbbdd4d26f5c837f4d651ec9bc42a03a97b5/src/backend/base/langflow/custom/custom_component/custom …
=> fix: correct user_id access logic

.github/workflows/codspeed.yml
This pull request modifies the Codspeed workflow configuration to exclude certain components from being processed. Specifically, the path for `src/backend/base/langflow/components/**` has been added to the exclusion list, ensuring that these components do not trigger the workflow.
=> ci: Exclude components changes from Codspeed workflow paths

src/backend/base/langflow/services/database/service.py
Fixes missing sqlite dialect in SQLAlchemy connection
Fixes: #4572
=> fix: missing sqlite dialect

src/frontend/tests/core/features/auto-login-off.spec.ts
This pull request includes three commits that improve the test time and replace timeouts with wait for selectors in the autoLogin test.
=> refactor: Improve time and use waitForSelector in auto-login tests

CONTRIBUTING.md, Makefile
This PR updates the local run instructions in the CONTRIBUTING.md file to reflect the use of 'uv' instead of 'Poetry'. This change aims to provide clearer guidance for setting up the development environment. Check env script was importing distutils which raised a `ModuleNotFoundError` if it was the first time the contributor was running it.
=> docs: Update local run instructions in CONTRIBUTING.md

src/backend/base/langflow/components/vectorstores/astradb.py
This pull request introduces several enhancements and refactorings to the `AstraDB` vector store component. The most significant changes include the introduction of a new `NestedDictInput` for advanced search filters, improvements to how search arguments are built, and better error handling during the search process.
* Introduced `NestedDictInput` for `advanced_search_filter` and deprecated the existing `search_filter` (`src/backend/base/langflow/components/vectorstores/astradb.py`).
* Enhanced `_build_search_args` method to clean and validate search filters, and to log deprecated usage of `search_filter` (`src/backend/base/langflow/components/vectorstores/astradb.py`).
* Improved error handling in `search_documents` method by adding specific error messages and logging steps …
=> feat: add NestedDictInput filter and non-vector search for AstraVectorStoreComponent

src/backend/base/langflow/services/database/service.py
Alembic not being initialized is an expected scenario when running langflow for the first time. Sets the log to debug and removes the exception.
=> chore: move alembic exception logging to debug

src/backend/base/langflow/__main__.py, src/backend/base/langflow/api/v1/api_key.py, src/backend/base/langflow/api/v1/login.py, src/backend/base/langflow/api/v1/users.py, src/backend/base/langflow/api/v1/variable.py, src/backend/base/langflow/base/agents/events.py, src/backend/base/langflow/custom/custom_component/custom_component.py, src/backend/base/langflow/initial_setup/setup.py, src/backend/base/langflow/main.py, src/backend/base/langflow/services/auth/utils.py, src/backend/base/langflow/services/database/models/api_key/crud.py, src/backend/base/langflow/services/database/models/folder/utils.py, src/backend/base/langflow/services/database/models/user/crud.py, src/backend/base/langflow/services/database/service.py, src/backend/base/langflow/services/database/utils.py, src/backend/base/langflow/services/utils.py, src/backend/base/langflow/services/variable/base.py, src/backend/base/langflow/services/variable/kubernetes.py, src/backend/base/langflow/services/variable/service.py, src/backend/tests/blockbuster.py, src/backend/tests/performance/test_server_init.py, src/backend/tests/unit/services/variable/test_service.py, src/backend/tests/unit/test_setup_superuser.py, src/backend/tests/unit/test_user.py
Use AsyncSession for user management
=> fix: Use AsyncSession for user management

src/backend/base/langflow/components/vectorstores/astradb.py, src/backend/base/langflow/components/vectorstores/astradb_graph.py
This pull request changes the terminology of "namespace" to "keyspace" to match changes in Astra DB.
=> fix: Rename `namespace` to `keyspace` in astra db

src/backend/base/langflow/api/utils.py, src/backend/base/langflow/api/v1/chat.py
Use `AsyncSession` in `build_graph_from_db`
=> fix: Use AsyncSession in build_graph_from_db

src/backend/base/langflow/api/v1/monitor.py, src/backend/base/langflow/services/database/models/vertex_builds/crud.py, src/backend/tests/conftest.py
Use AsyncSession in delete_vertex_builds
=> fix: Use AsyncSession in delete_vertex_builds

src/backend/base/langflow/graph/vertex/base.py
Add attribute check before calling set_event_manager to avoid AttributeError in components inheriting from CustomComponent.
=> fix: Add check for 'set_event_manager' method in custom_component before calling it

src/backend/base/langflow/services/telemetry/service.py
This update introduces a `worker_task` attribute to the `TelemetryService` class, which helps avoid potential `AttributeError` issues. This change enhances the robustness of the telemetry service by ensuring that the attribute is properly initialized.
=> fix: Add worker_task attribute to TelemetryService to prevent AttributeError

src/backend/base/langflow/graph/graph/base.py
This pull request modifies the sorting logic for chat inputs in the graph. It ensures that chat inputs with dependencies are not moved to the first layer, maintaining their original order when dependencies exist. This change improves the handling of chat inputs in the graph structure.
Fixes #4660
=> fix: Ensure chat inputs with dependencies are not prioritized in graph sorting

src/frontend/src/components/parameterRenderComponent/components/textAreaComponent/index.tsx
This pull request includes a few small changes to the `TextAreaComponent` in the `index.tsx` file. The changes focus on updating the class names for better handling of focus states and icon rendering.
* Added a `pr-10` class when the `TextAreaComponent` is focused to provide padding. (`src/frontend/src/components/parameterRenderComponent/components/textAreaComponent/index.tsx` [src/frontend/src/components/parameterRenderComponent/components/textAreaComponent/index.tsxR76](diffhunk://#diff-697f5e35a4c3db88eeb823f8987b6f32c24d482cca67e4750538cac35b061984R76))
* Removed the conditional `opacity-0` class from the icon container to ensure the icon is always visible. (`src/frontend/src/components/parameterRenderComponent/components/textAreaComponent/index.tsx` …
=> fix(TextAreaComponent): Update focus state padding and icon visibility

src/frontend/src/controllers/API/queries/files/use-download-files.ts
This pull request fixes an error that occurs when fetching data without any headers on the request. The issue was resolved by adding the 'Accept' header to the fetch request in order to handle the response correctly.
=> fix: error on fetch for no headers on request

src/frontend/src/CustomNodes/GenericNode/components/HandleTooltipComponent/index.tsx
This pull request includes a small, yet important change to the `HandleTooltipComponent` in the `index.tsx` file. The change ensures that each `Badge` component within the tooltip list has a unique key, which can help React efficiently update and render the list.
* [`src/frontend/src/CustomNodes/GenericNode/components/HandleTooltipComponent/index.tsx`](diffhunk://#diff-f286fd032653a39d18eb067d1981f06a2f81c02532353dce582ee272305cd271R51): Added a unique key to each `Badge` component in the `tooltips` map by combining the index and the lowercase version of the word.
=> fix: Add unique keys to Badge components in HandleTooltipComponent

Makefile, pyproject.toml, src/backend/base/langflow/api/v1/api_key.py
This PR updates the Makefile to include a configuration flag for ruff commands, allowing them to utilize the `pyproject.toml` file for settings. This change enhances the flexibility and maintainability of the code formatting and linting processes.
I did not add to check because there are a lot of errors so we should do it in a separate PR.
=> chore: Add pyproject.toml configuration to ruff format command in Makefile

src/backend/base/langflow/api/v1/endpoints.py
Adds deprecated flag to an old route that I _believe_ is superseded by more specific upload routes like https://github.com/langflow-ai/langflow/blob/deprecate-upload-route/src/backend/base/langflow/api/v1/files.py#L40
=> chore: add deprecation flag on base upload flow route

src/backend/base/langflow/components/vectorstores/milvus.py
Hi, I have renamed the displayed name of field from Connection Password to Token, which is what it is usally refered to as. Nothing else has been changed, please check!
=> fix: correct issue with Milvus field name, renamed connection password to Token

src/frontend/src/components/chatComponents/ContentDisplay.tsx, src/frontend/src/modals/IOModal/components/chatView/chatMessage/newChatMessage.tsx
This pull request adds support for ordered and unordered lists in the ContentDisplay and ChatMessage components. Previously, lists were not properly displayed and could cause overflow. With this change, lists are now rendered correctly and have a maximum width to prevent overflow.
=> fix: fix overflow for lists in markdown render

.github/workflows/docker_test.yml
This pull request includes updates to the `docker_test.yml` workflow file to improve the version checking mechanism for Docker images.
Improvements to version checking:
* [`.github/workflows/docker_test.yml`](diffhunk://#diff-91d171c86d0de252b57b744dff05648acb174351e56da20f59e5e242fb70984cL38-R38): Updated the `Test image` job to use the `get_version_info` method from `langflow.utils.version` instead of `get_version` from `langflow.version.version`.
* [`.github/workflows/docker_test.yml`](diffhunk://#diff-91d171c86d0de252b57b744dff05648acb174351e56da20f59e5e242fb70984cL54-R54): Updated the `Test backend image` job to use the `get_version_info` method from `langflow.utils.version` instead of `get_version` from `langflow.version.version`.
=> fix: update Test Docker Images workflow to use get_version_info 

src/backend/base/langflow/services/settings/base.py, src/backend/base/langflow/services/utils.py
This pull request introduces functions to clean up old transactions and vertex builds in the database, ensuring that only a configured maximum number of each is retained. The `clean_transactions` function deletes transactions exceeding the specified limit, while `clean_vertex_builds` performs a similar cleanup for vertex builds. Additionally, these cleanup functions are integrated into the service initialization process, and new configuration options for maximum retention limits have been added.
=> feat: Add database cleanup functions for transactions and vertex builds

src/backend/base/langflow/base/models/model_input_constants.py, src/backend/base/langflow/components/models/groq.py, uv.lock
This fixes an issue when trying to import anything from langflow-base. Since we were importing packages that are not installed in langflow-base it would raise an exception.
This pull request refactors the model input constants to manage missing imports more gracefully. It introduces error handling for ImportError exceptions in the initialization of various model components, including OpenAI, Azure OpenAI, Groq, Anthropic, NVIDIA, and Amazon Bedrock. This ensures that informative error messages are provided when required packages are not installed, improving the user experience and debugging process.
=> fix: Gracefully handle missing imports for model components

src/frontend/src/utils/reactflowUtils.ts
This was causing all starter projects to be reformatted in the backend because they were exported from the UI.
This pull request modifies the JSON output formatting for exported flow data in the `reactflowUtils.ts` file. The changes ensure that the JSON is indented for better readability by adding a spacing parameter to the `JSON.stringify` method.
=> fix: Indent JSON output for exported flow data

src/frontend/src/pages/MainPage/pages/index.tsx
This pull request includes a minor change to the `CollectionPage` component in `src/pages/MainPage/pages/index.tsx`. The change involves setting a specific width for the `SidebarProvider` component.
* [`src/frontend/src/pages/MainPage/pages/index.tsx`](diffhunk://#diff-1298711fb00b5357b2e39b6bab21791701b73458092407d6732e0dd28ae49475L60-R60): Added a `width` property with a value of "280px" to the `SidebarProvider` component.
=> fix: changed width of sidebar to be consistent across application

src/backend/base/langflow/inputs/inputs.py
This PR introduces validation for the `MessageBase` type within the message input conversion process. It ensures that if an instance of `MessageBase` is provided, it is correctly transformed into a `Message` object using the model's data. This enhancement improves the robustness of input handling in the application.
This helps when you create a component, call `send_message` passing a Message and then return the result of the call (which now is a `MessageRead`, not a `Message` anymore).
=> fix: Add validation for MessageBase type in message input conversion

src/frontend/src/components/ui/sidebar.tsx, src/frontend/src/pages/FlowPage/components/PageComponent/index.tsx, src/frontend/src/pages/MainPage/components/header/index.tsx
This pull request includes several changes to improve the handling of the sidebar state in the frontend codebase. The main changes involve removing the `useSidebar` hook and replacing it with data attributes to manage the sidebar's open state.
* [`src/frontend/src/components/ui/sidebar.tsx`](diffhunk://#diff-c3366f1c53140092f8bbc100e39829e6f4ed5040ad86d7941b54c52e2a07997dR134): Added a `data-open` attribute to manage the sidebar's open state.
* [`src/frontend/src/pages/FlowPage/components/PageComponent/index.tsx`](diffhunk://#diff-58f6af33afc15c24e3df56ce2169081e35e5fe005f6281ebc5d7156b2eaa7d0eL9-R9): Removed the `useSidebar` hook and replaced it with data attributes in various components to handle the sidebar's open state. [[1]](diffhunk://#diff-58f6af33afc15c24e3df56ce2169081e35e5fe005f6 …
=> fix: remove useSidebar to fix errors of SidebarWrapper when opening playground page

src/frontend/src/pages/FlowPage/components/PageComponent/index.tsx, src/frontend/src/stores/flowStore.ts
This pull request includes changes to the `PageComponent` and `flowStore` to remove outdated checks and alerts for old components in Langflow. The most important changes are:
Code cleanup:
* [`src/frontend/src/pages/FlowPage/components/PageComponent/index.tsx`](diffhunk://#diff-58f6af33afc15c24e3df56ce2169081e35e5fe005f6281ebc5d7156b2eaa7d0eL184-L192): Removed the `useEffect` hook that checked for old components and set a notice about their stability.
* [`src/frontend/src/stores/flowStore.ts`](diffhunk://#diff-c0be28c27c2bdb8f48b4b4efacde87f9bdceccd4b979600e9f7b38dcd7ffc357L350-R350): Removed the conditional check and alert for old components within the `useFlowStore` store.
=> chore: remove legacy component checks and alerts

src/backend/base/langflow/api/utils.py, src/backend/base/langflow/api/v1/chat.py, src/backend/base/langflow/custom/custom_component/component.py, src/backend/base/langflow/services/tracing/langwatch.py, src/backend/base/langflow/services/tracing/service.py, src/backend/tests/unit/events/test_event_manager.py
Hey there, we found 3 issues that broke tracing a little bit since a few months after a langflow refactoring, this PR fixes two of them:
The issue with input values is that the ones from `_inputs` seems to be the ones actually holding the value in runtime and those were not being passed, also it's a bit weird and heavy for monitoring tools that it sends the component code every time, the `Dynamic inputs` didn't seem to be working well, so I've replaced with `_inputs` which does what we expected
Now the issue with output is that an async trace ending was introduced, but the reset_io was kept sync, as a result the outputs were being set back to {} before the trace actually could capture the output value
For the `flow_name` being none, we couldn't find an easy way to fix it, so we put just a …
=> fix:  traces inputs and outputs not being sent to tracing services

src/frontend/tests/core/features/tweaksTest.spec.ts
Improve the waiting logic in the tweksTest.spec.ts file to ensure that the necessary elements are loaded before interacting with them. This includes using the waitForSelector function with appropriate timeouts for the modal and popover elements.
=> fix: Improve waiting logic in tweksTest.spec.ts

src/backend/base/langflow/components/tools/__init__.py, src/backend/base/langflow/components/tools/exa_search.py, src/backend/base/langflow/components/tools/wolfram_alpha_api.py, src/backend/base/langflow/components/vectorstores/pgvector.py, src/backend/base/langflow/components/vectorstores/redis.py, src/frontend/src/utils/styleUtils.ts
This pull request includes several changes to the `langflow` components and icons. The most important changes involve renaming a toolkit, updating icons, and adding new icons.
* Renamed `MetaphorToolkit` to `ExaSearchToolkit` in `src/backend/base/langflow/components/tools/__init__.py` and updated the corresponding import and class name. [[1]](diffhunk://#diff-978762db35f605246f0bf595f91cfb0ff502fa74a15603d70ea3f6902f009175L11-R11) [[2]](diffhunk://#diff-978762db35f605246f0bf595f91cfb0ff502fa74a15603d70ea3f6902f009175L39-R39) [[3]](diffhunk://#diff-4412c0a8c32e1b4158a949ea5fd1da723420406911eda7891c6ed2d4458f8c03L9-R15)
* Added an icon for `WolframAlphaAPIComponent` in `src/backend/base/langflow/components/tools/wolfram_alpha_api.py`.
* Changed the icon for `PGVectorStoreComponent` from …
=> feat: rename MetaphorToolkit file to ExaSearchToolkit and update component icons

src/frontend/src/components/flowToolbarComponent/components/playground-button.tsx, src/frontend/src/components/flowToolbarComponent/index.tsx, src/frontend/src/style/applies.css
This pull request introduces a new `PlaygroundButton` component to the flow toolbar in the frontend. The `PlaygroundButton` component replaces the existing logic for displaying the playground button, providing a cleaner and more modular implementation.
**_This PR also fixes a bug in which the icon on Playground was the old one when we didn't have ChatInput or ChatOutput on Canvas._**
* Added `PlaygroundButton` component in `src/frontend/src/components/flowToolbarComponent/components/playground-button.tsx`. This component handles the display logic for the playground button, including active and disabled states.
* Updated `FlowToolbar` component in `src/frontend/src/components/flowToolbarComponent/index.tsx` to use the new `PlaygroundButton` component instead of …
=> feat: Add PlaygroundButton component to flow toolbar

src/backend/base/langflow/components/embeddings/ollama.py
Removed unwanted parameter temperature for embedding
closes https://github.com/langflow-ai/langflow/issues/4728
This pull request includes several changes to the `OllamaEmbeddingsComponent` class in the `src/backend/base/langflow/components/embeddings/ollama.py` file. The changes focus on simplifying the component by removing an unused import and the `temperature` parameter.
Codebase simplification:
* Removed the unused `FloatInput` import from `langflow.io`. (`[src/backend/base/langflow/components/embeddings/ollama.pyL5-R5](diffhunk://#diff-9a66812daa372619c9b34060e9fd280defa5a1717e3e947098676466ae9ccc6dL5-R5)`)
* Changed the default value of the `model` parameter from `"llama3.1"` to `"nomic-embed-text"`. (`[src/backend/base/langflow/components/embeddings/ollama.pyL19-L31](diffhunk://#di …
=> fix: fixes Ollama Embeddings component

src/backend/base/langflow/components/langchain_utilities/csv.py
This pull request introduces a helper method to handle the `path` attribute in the `CSVAgentComponent` class in the `src/backend/base/langflow/components/langchain_utilities/csv.py` file. The main changes include the addition of the `_path` method and its integration into the existing methods for building agents.
Key changes:
* Added `_path` method to handle `path` attribute conversion from `Message` to `str`. (`src/backend/base/langflow/components/langchain_utilities/csv.py`)
* Updated `build_agent_response` method to use the new `_path` method for `path` attribute. (`src/backend/base/langflow/components/langchain_utilities/csv.py`)
* Updated `build_agent` method to use the new `_path` method for `path` attribute. (`src/backend/base/langflow/components/langchain_utilities/csv.py`)
=> fix: handle Message in path input in CSVAgentComponent

src/backend/base/langflow/base/agents/agent.py, src/backend/base/langflow/components/langchain_utilities/tool_calling.py
Tool name validation based on open ai Schema for tool names
Note: In case of Agent as Tool. This doesnt work if it tool is a Tool for Agent as tool. Only check when the agent as tool is invoked.
This pull request introduces changes to the agent validation and creation process in the `src/backend/base/langflow/base/agents/agent.py` file. The most important changes include the addition of a tool name validation method and its integration into the agent-building process.
* [`src/backend/base/langflow/base/agents/agent.py`](diffhunk://#diff-87ba96f91b4bbce3350ae83d5d4c7dfa3a7c800deeed21a60857dff1caaefe04R182-R193): Added a new method `validate_tool_names` to ensure tool names match a specific pattern using regular expressions. This method checks that tool names contain only letters, numbers, …
=> fix: validation for tool name

src/backend/base/langflow/services/database/service.py, src/backend/base/langflow/services/utils.py
We have encountered an issue with this one more time. Since it is not a breaking issue I decided we could use a warning instead. 
I also added a `session.add` call for so we can update the flow.
=> fix: Fix flow addition to session and handle IntegrityError for orphaned flows

src/frontend/src/modals/IOModal/components/chatView/chatMessage/newChatMessage.tsx
This pull request includes a small change to the `src/frontend/src/modals/IOModal/components/chatView/chatMessage/newChatMessage.tsx` file. The change modifies the styling of a `span` element to always underline when `closeChat` is true, removing the hover effect.
Styling change:
* [`src/frontend/src/modals/IOModal/components/chatView/chatMessage/newChatMessage.tsx`](diffhunk://#diff-a5c2764955c9d507dd134f3add3fec7958daa183ee41cfabe54f5c5702a483e7L267-R267): Changed the `className` condition to always apply "underline" instead of "hover:underline" when `closeChat` is true.
=> fix: add underline to name of component to make it look clickable on error

src/frontend/tests/core/integrations/Document QA.spec.ts
This pull request refactors the Document QA test to improve timeout handling. It updates the code to use `waitForSelector` instead of `waitForTimeout` for better synchronization.
=> refactor: improve timeout handling in Document QA test

src/frontend/tests/core/integrations/Basic Prompting.spec.ts
This pull request refactors the waiting logic in the Basic Prompting test. The changes include using `waitForSelector` instead of `waitForTimeout` to improve the waiting behavior.
=> refactor: improve waiting logic in Basic Prompting test

src/backend/base/langflow/base/embeddings/aiml_embeddings.py
This PR updates the import statements in `aiml_embeddings.py` to correctly reference Pydantic, ensuring compatibility and proper functionality of the code. The previous imports from `langchain_core.pydantic_v1` have been replaced with direct imports from `pydantic`.
=> refactor: updates import statements to use Pydantic in aiml_embeddings.py

src/frontend/tests/core/integrations/Blog Writer.spec.ts
This pull request refactors the timeout handling in the Blog Writer integration test. The timeout for waiting for the selector '[data-testid="fit_view"]' has been increased from 1000ms to 5000ms to ensure that the element is properly loaded before proceeding with the test.
=> fix: Improve timeout handling in Blog Writer integration test

src/backend/base/langflow/custom/custom_component/base_component.py, src/backend/base/langflow/schema/__init__.py
This PR raises ImportError to prevent silencing of AttributeError during custom component evaluation and adds the Message class to __init__ for easier, standardized imports
=> fix: raise ImportError instead of silencing AttributeError

src/backend/base/langflow/initial_setup/starter_projects/Vector Store RAG.json
This pull request includes changes to the descriptions of nodes in the `Vector Store RAG.json` file to correct the order of steps in the flow. The most important changes include swapping the descriptions of the "Load Data Flow" and "Retriever Flow" nodes to ensure the correct sequence of operations.
Changes to node descriptions:
* [`src/backend/base/langflow/initial_setup/starter_projects/Vector Store RAG.json`](diffhunk://#diff-10837b87e2da91a231aa3ec84c3b6317cd239066c0c8979d2ce127f6408cf67dL999-R999): Updated the description of the node with `id: note-UrQ0p` to "## 🐕 2. Retriever Flow"
* [`src/backend/base/langflow/initial_setup/starter_projects/Vector Store RAG.json`](diffhunk://#diff-10837b87e2da91a231aa3ec84c3b6317cd239066c0c8979d2ce127f6408cf67dL3245-R3245): Updated the description …
=> fix: swap descriptions for Load Data Flow and Retriever Flow in template

pyproject.toml, src/backend/base/pyproject.toml, uv.lock
This pull request updates the version numbers for the `langflow` package to 1.1.1 and for the `langflow-base` package to 0.1.1. Additionally, it adjusts the dependency version for `langsmith` to 0.1.137 to avoid 0.1.136 which has been yanked. These updates help maintain the integrity and functionality of the packages.
=> chore: Bump package versions for langflow and langflow-base

src/frontend/src/pages/MainPage/components/header/index.tsx
This pull request makes changes to the `HeaderComponent` in the `src/frontend/src/pages/MainPage/components/header/index.tsx` file to improve the UI layout and button styling.
UI Layout Improvements:
* Removed an unnecessary `div` wrapper around the `ShadTooltip` component to simplify the DOM structure.
Button Styling:
* Updated the `className` property of the `Button` component to adjust padding for different screen sizes.
=> fix: changed add flow button to be square on collapsed screen

.github/workflows/typescript_test.yml, src/frontend/src/CustomNodes/hooks/use-handle-new-value.tsx
This pull request includes a change to the `src/frontend/src/CustomNodes/hooks/use-handle-new-value.tsx` file to improve the handling of new node values. The most important change is the modification of the `setNodeClass` function to ensure node internals are updated correctly.
Enhancements to node value handling:
* [`src/frontend/src/CustomNodes/hooks/use-handle-new-value.tsx`](diffhunk://#diff-ad64cf66a29bad7dff76cae269058857414b87c120f9711f1e3cf4a124ee9fd8L75-R89): Modified the `setNodeClass` function to include additional parameters for `setNode`, ensuring that node internals are updated after setting the new node class.
=> fix: improve node internal updates in setNodeClass function

.github/workflows/typescript_test.yml
This pull request introduces a dynamic calculation for the shard count in the Playwright test workflow within the CI pipeline. The shard count is determined based on the total number of tests, optimizing the distribution of tests across shards. The calculation ensures a minimum of 1 shard and a maximum of 10, with the logic implemented to count tests based on specified patterns or all tests if no pattern is provided. This enhancement aims to improve test execution efficiency in the CI process.
=> ci: Add dynamic shard count calculation for Playwright tests in CI workflow

.github/workflows/nightly_build.yml
This PR updates the nightly build workflow to enable the release flag for TypeScript tests, ensuring that the tests run in a release mode during the nightly builds. This change aims to improve the testing process and ensure better coverage of release scenarios.
=> ci: Enable release flag for TypeScript tests in nightly build workflow

src/frontend/src/App.css
This pull request includes a small change to the `src/frontend/src/App.css` file. The change adds a new CSS rule for `.ag-cell` to set the `--ag-internal-calculated-line-height` property to `none` with `!important` priority.
* [`src/frontend/src/App.css`](diffhunk://#diff-3e7904848c381eb53375a14db869438235df15b6e439845f23d09b12382c0d47R186-R189): Added a new CSS rule for `.ag-cell` to set `--ag-internal-calculated-line-height` to `none` with `!important` priority.
BEFORE:
AFTER:
=> css: Fix AG Grid cell line height by setting internal property to none

src/frontend/src/App.css, src/frontend/src/style/ag-theme-shadcn.css
This pull request includes changes to the CSS files to improve the styling and ensure consistency across the grid. The most important changes include adding new CSS rules for the `.ag-cell` class and updating existing CSS rules in the `ag-theme-shadcn` class to use `!important`.
Styling improvements:
* [`src/frontend/src/App.css`](diffhunk://#diff-3e7904848c381eb53375a14db869438235df15b6e439845f23d09b12382c0d47R186-R193): Added new CSS rules for the `.ag-cell` class and its child elements to set the `--ag-internal-calculated-line-height` to `none` with `!important`.
* [`src/frontend/src/style/ag-theme-shadcn.css`](diffhunk://#diff-6cc8681a29a2d481a5c25262d479622a2af6884f86499e6da1e0b2e1723179b2L3-R20): Updated existing CSS rules in the `ag-theme-shadcn` class to use `!important` for …
=> fix: add !important to shadcn aggrid styling

.github/workflows/docker-build.yml
Adds arm64 builds to docker images.
This may increase docker build times significantly.
=> build: adds arm64 build to docker build workflow

src/backend/base/langflow/base/agents/events.py
This pull request addresses the issue of processing agent messages by adding support for various output formats. It ensures that the output can be a string or a list of dictionaries containing a 'text' key, improving the robustness of the message handling. If the output does not conform to these formats, a descriptive error is raised.
This fixes the experience with Anthropic models.
=> fix: handle different output formats in agent message processing

src/backend/base/langflow/template/utils.py
This PR fixes the issue where only node descriptions were updated and displayed correctly, ensuring display_name are also updated and reflected to users
=> fix: node display_name updates and display for users

src/backend/base/langflow/schema/__init__.py, src/backend/base/langflow/schema/data_set.py, src/backend/tests/unit/schema/test_schema_data_set.py
This pull request introduces significant enhancements to the `DataSet` class in the `langflow` schema, including new methods for initialization and row addition, as well as comprehensive testing for these features. Below are the most important changes:
* **Initialization Enhancements:**
- Added support for various data formats during initialization, including lists of `Data` objects, dictionaries, dictionary of lists, and pandas DataFrames.
- Introduced the `__init__` method to handle these different formats and ensure proper data conversion.
* **Row Addition Methods:**
- Added `add_row` method to allow adding a single row to the dataset, supporting both `Data` objects and dictionaries.
- Added `add_rows` method to allow adding multiple rows to the dataset, supporting lists of `Data` …
=> feat: make DataSet initialization similar to pandas'

src/frontend/tests/core/unit/fileUploadComponent.spec.ts
This pull request includes a refactoring of the `fileUploadComponent.spec.ts` file to improve the reliability and readability of the tests. The changes include updating the wait conditions in the tests to use `waitForSelector` instead of `waitForTimeout` for better synchronization. Additionally, the expectation for the visibility of a test file has been updated to use `toBeVisible` instead of `isVisible` for more accurate results. These changes aim to enhance the overall quality and maintainability of the test suite.
=> Refactor: update fileUploadComponent.spec.ts to improve test reliability, performance and readability

src/backend/base/langflow/field_typing/constants.py, src/backend/base/langflow/inputs/inputs.py, src/backend/base/langflow/schema/__init__.py, src/backend/base/langflow/schema/dataframe.py, src/backend/tests/unit/schema/test_schema_data_set.py
This pull request introduces a new `DataFrame` type to the supported component types and adds a `DataFrameInput` class to the input types definition. Additionally, it refactors the existing `DataSet` references to `DataFrame`, ensuring consistency across the codebase. The new `DataFrame` class extends the functionality of pandas' DataFrame to handle collections of `Data` objects seamlessly. This enhancement improves data handling capabilities within the application.
=> feat: Add DataFrameInput and refactor DataSet references

src/backend/base/langflow/components/tools/astradb.py
This pull request renames the Astra DB component in tools to "Astra DB Tool" (for distinguishability) and sets the API endpoint to be a SecretStrInput with parameters matching other Astra components, to use the global variable set.
=> fix: Use global var if available for api endpoint in Astra DB Tool

src/frontend/src/components/core/parameterRenderComponent/components/inputComponent/components/popover/index.tsx, src/frontend/src/components/ui/badge.tsx
This pull request includes several changes to the `CustomInputPopover` component and the `badgeVariants` styles in the frontend codebase. The main goal is to adjust the styling and improve the user interface consistency.
Styling adjustments in `CustomInputPopover`:
* Modified padding and margin values to improve the layout and appearance of the input component. (`src/frontend/src/components/core/parameterRenderComponent/components/inputComponent/components/popover/index.tsx`, [src/frontend/src/components/core/parameterRenderComponent/components/inputComponent/components/popover/index.tsxL71-R73](diffhunk://#diff-6dd2f8aa520258e6efb0482b5419536b2eb345b1cccdcf29c1b4562971c4f0e4L71-R73))
* Added a conditional class to adjust the text size when `editNode` is true. …
=> fix: add padding to global variables input

pyproject.toml, src/backend/base/langflow/api/v1/files.py, src/backend/base/langflow/components/embeddings/cloudflare.py, src/backend/base/langflow/main.py, src/backend/base/langflow/middleware.py, src/backend/base/pyproject.toml, src/backend/tests/unit/api/v1/test_files.py, uv.lock
This pull request introduces a new middleware for the FastAPI application to enforce content size limits on file uploads. It removes the previous file size limit check from the upload endpoint and adds tests to ensure the upload functionality adheres to the specified size constraints. Additionally, the `types-aiofiles` dependency has been added to the project configuration.
=> fix: updates file size limit to use middleware and add tests for uploads

src/frontend/src/pages/FlowPage/components/nodeToolbarComponent/index.tsx
This pull request refactors the NodeToolbarComponent by replacing the usage of the setNoticeData function with the setErrorData function. This change ensures that error data is properly handled.
=> fix: Update NodeToolbarComponent to use setErrorData instead of setNoticeData

src/frontend/tests/core/unit/nestedComponent.spec.ts
The nestedComponent test was updated to use explicit timeouts when waiting for certain elements to appear. This ensures that the test waits for the elements to be present before proceeding, preventing any potential race conditions or flakiness in the test results.
=> Refactor: update nestedComponent test to improve performance

src/frontend/src/pages/FlowPage/components/flowSidebarComponent/components/sidebarDraggableComponent/index.tsx, src/frontend/src/pages/FlowPage/components/nodeToolbarComponent/hooks/use-shortcuts.tsx, src/frontend/src/pages/FlowPage/components/nodeToolbarComponent/index.tsx, src/frontend/tests/core/integrations/Vector Store.spec.ts, src/frontend/tests/extended/regression/general-bugs-component-as-tool-shortcut.spec.ts, src/frontend/tests/utils/extract-and-clean-code.ts
This pull request includes several changes to the frontend codebase, focusing on the addition of new utilities, enhancements to existing components, and improvements to test cases. The most important changes include adding a new utility function for extracting and cleaning code, updating the `useShortcuts` hook to support a new tool mode, and enhancing the `SidebarDraggableComponent` with a data-testid attribute.
* Added `extractAndCleanCode` utility function in `src/frontend/tests/utils/extract-and-clean-code.ts` to centralize code extraction and cleaning logic.
* Updated `SidebarDraggableComponent` to include a `data-testid` attribute for the add component button, utilizing the `convertTestName` function for dynamic test IDs. [[1]](diffhunk://#diff-c94382f8e218f4b5d129a9052c8e0754e1b9cb7 …
=> Fix: Disable the ComponentAsTool shortcut when the component code does not have tool_mode=True + regression tests

src/backend/base/langflow/components/embeddings/cloudflare.py, src/backend/base/langflow/components/helpers/current_date.py, src/frontend/tests/core/features/filterSidebar.spec.ts
This pull request includes changes to the `CurrentDateComponent` class in the `src/backend/base/langflow/components/helpers/current_date.py` file. The main modifications involve removing the beta flag and reformatting the `outputs` list for better readability.
Changes to `CurrentDateComponent` class:
* Removed the `beta` attribute from the `CurrentDateComponent` class.
* Reformatted the `outputs` list to improve readability by breaking the `Output` instantiation into multiple lines.
=> fix: removed beta from current date

src/frontend/tests/core/unit/toggleComponent.spec.ts
This pull request includes a refactor that improves the reliability and performance of the tests in toggleComponent.spec.ts. The changes include using `waitForSelector` instead of `waitForTimeout` to ensure that the modals and elements are properly loaded before interacting with them. This helps to avoid potential timing issues and makes the tests more robust.
=> Improve test reliability and performance in toggleComponent.spec.ts

src/frontend/tests/core/unit/promptModalComponent.spec.ts
- Replaced the usage of waitForTimeout with waitForSelector in promptModalComponent.spec.ts to improve reliability and stability of the tests.
=> fix: Update promptModalComponent.spec.ts to use waitForSelector instead of waitForTimeout

src/backend/base/langflow/components/models/openai.py
This PR updates the 'temperature' input type for the OpenAI model and sets its minimum and maximum values.
Fixes: #4915
=> fix: update temperature input type and set min/max values

src/backend/base/langflow/components/langchain_utilities/spider.py, src/backend/base/langflow/components/langchain_utilities/sql_database.py
this pr update the icons in langchain bundle to ensure the pattern
=> fix: Add icon SQLDatabaseComponent 

.github/workflows/store_pytest_durations.yml
This pull request introduces a new GitHub Actions workflow that runs pytest and stores test durations. The workflow is scheduled to execute daily at 6:30 UTC, and it includes steps for setting up the environment, restoring cache, running tests, and automatically creating a pull request to update the test durations file. This enhancement aims to streamline the testing process and maintain accurate duration records for the tests.
=> ci: Add GitHub Actions workflow to store pytest durations once a day

src/backend/base/langflow/api/v1/endpoints.py, src/backend/base/langflow/api/v1/schemas.py, src/backend/base/langflow/custom/custom_component/component.py, src/frontend/src/CustomNodes/GenericNode/components/NodeInputField/index.tsx, src/frontend/src/CustomNodes/GenericNode/index.tsx, src/frontend/src/CustomNodes/helpers/mutate-template.ts, src/frontend/src/CustomNodes/hooks/use-handle-new-value.tsx, src/frontend/src/components/core/parameterRenderComponent/components/inputComponent/components/popover/index.tsx, src/frontend/src/components/core/parameterRenderComponent/components/inputGlobalComponent/index.tsx, src/frontend/src/components/core/parameterRenderComponent/components/refreshParameterComponent/index.tsx, src/frontend/src/controllers/API/queries/nodes/use-post-template-value.ts, src/frontend/src/pages/FlowPage/components/nodeToolbarComponent/index.tsx, src/frontend/src/utils/reactflowUtils.ts
This pull request includes several changes to implement and handle a new `tool_mode` attribute across various components and files in the codebase. The most important changes include adding the `tool_mode` attribute to schemas, updating logic to handle `tool_mode` in backend and frontend components, and ensuring that the state and UI reflect the new attribute correctly.
* Added `tool_mode` attribute to `UpdateCustomComponentRequest` schema in `src/backend/base/langflow/api/v1/schemas.py` to allow the attribute to be passed in API requests.
* Updated the `custom_component_update` function in `src/backend/base/langflow/api/v1/endpoints.py` to include the `tool_mode` attribute in the component node.
* Added `tool_mode` attribute handling in various frontend components, such as …
=> feat: Add toolset component utilities and refactor tool mode handling

src/backend/base/langflow/io/__init__.py, src/backend/base/langflow/schema/schema.py
This pull request introduces support for handling DataFrame types in log message serialization, ensuring that DataFrames are correctly converted to dictionaries for logging purposes. Additionally, it adds the `DataFrameInput` to the exports of `langflow.io`, enhancing the input options available for users.
If the Output of the component is a DataFrame you should be able to inspect it in the UI now without setting self.status
=> fix: Handle DataFrame serialization and export in langflow.io

src/backend/base/langflow/components/langchain_utilities/tool_calling.py
This PR fixes an issue where LangChain would complain if you passed a curly brace in the message.
=> fix: allow passing curly braces in messages to the Agent component

src/frontend/src/CustomNodes/GenericNode/components/NodeStatus/index.tsx
This pull request includes changes to the `NodeStatus` component in the `src/frontend/src/CustomNodes/GenericNode/components/NodeStatus/index.tsx` file to improve the handling of build and validation statuses.
Improvements to build and validation status handling:
* Simplified the condition that determines `conditionSuccess` by removing redundant checks and using optional chaining for `validationStatus`.
* Removed the line that sets `validationStatus` to `null` when the build status is `BUILDING` or `isBuilding` to prevent unnecessary state changes.
=> fix: prevent a glitch displaying run duration

src/frontend/src/alerts/notice/index.tsx, src/frontend/src/types/alerts/index.ts
This pull request refactors the `NoticeAlert` component to improve handling of timeout and cleanup logic, enhance performance, and simplify the rendering logic for the link.
1. **Refactor Timeout Logic**: 
- Previously, the timeout for auto-dismissing the alert and removing it was set directly within the `useEffect` hook. This change adds a `clearTimeout` call within the cleanup function to ensure that timeouts are cleared correctly when the component unmounts or re-renders.
2. **Optimized Click Handling**: 
- The alert dismissal logic on click has been encapsulated within a `handleClick` function, ensuring the alert's `removeAlert` function is called after the leave transition, maintaining synchronization with the animation.
3. **Simplified Link Rendering**:
- The condition for rendering …
=> refactor: Improve Timeout Handling, Simplify Link Logic, and Enhance Cleanup

src/backend/base/langflow/components/vectorstores/astradb.py
This pull request hides an input that is only required if running langflow OSS, so it doesnt appear in a hosted Astra environment.
=> fix: support Astra Enhanced flag in new component

src/backend/base/langflow/graph/graph/base.py
This PR introduces a validation method to ensure the graph structure adheres to specific rules regarding 'streaming' vertices. The goal is to prevent potential errors caused by invalid vertex connections.
=> fix: validate 'streaming' vertex connections in graph

src/frontend/src/CustomNodes/GenericNode/components/NodeDescription/index.tsx
This pull request includes changes to the `NodeDescription` component in the `src/frontend/src/CustomNodes/GenericNode/components/NodeDescription/index.tsx` file. The main goal of these changes is to improve the handling of whitespace in the node descriptions.
Improvements to whitespace handling:
* Modified the `className` property to include `whitespace-break-spaces` to ensure that whitespace is properly handled in the node description text.
* Updated the `Markdown` component's `className` property to include `whitespace-break-spaces` for better whitespace handling in code descriptions.
=> feat: improve whitespace handling in NodeDescription component

src/frontend/tests/extended/features/store-shard-0.spec.ts
This pull request removes unnecessary wait times in the `store-shard-0.spec.ts` file. The `waitForTimeout` calls with a timeout of 1000ms have been removed from the tests. This improves the efficiency of the tests by reducing unnecessary waiting.
=> Refactor: Remove unnecessary wait times in store-shard-0.spec.ts

pyproject.toml, src/backend/base/langflow/base/io/chat.py, src/backend/base/langflow/custom/directory_reader/directory_reader.py, src/backend/base/langflow/services/tracing/service.py, src/backend/tests/conftest.py, src/backend/tests/unit/api/v1/test_endpoints.py, src/backend/tests/unit/components/inputs/test_input_components.py, src/backend/tests/unit/graph/graph/test_base.py, src/backend/tests/unit/test_process.py, uv.lock
Remove some useless asyncio.to_thread
=> ref: Remove some useless asyncio.to_thread

src/backend/base/langflow/template/frontend_node/base.py
`to_frontend_node` calls `set_field_value_in_template` and `set_field_load_from_db_in_template` which modify the input components.
This PR makes a copy of the components before applying the modifications.
=> fix: Fix to_frontend_node modifying input components

src/frontend/tests/extended/regression/generalBugs-shard-11.spec.ts
This pull request increases the timeout for waiting for modals and elements in regression tests to 3000ms. It also replaces the usage of `waitForTimeout` with `waitForSelector` for better reliability.
=> refactor: Improve wait time for modals and elements in regression tests

src/backend/base/langflow/base/agents/agent.py, src/backend/base/langflow/base/tools/component_tool.py, src/backend/base/langflow/custom/custom_component/component.py, src/backend/tests/unit/custom/custom_component/test_component_events.py
The user-defined event manager callbacks may be blocking so they should be run in a thread-pool when executed from a coroutine.
=> fix: Execute event manager callbacks in asyncio thread

src/frontend/src/CustomNodes/GenericNode/components/NodeStatus/components/build-status-display.tsx, src/frontend/src/CustomNodes/GenericNode/components/NodeStatus/index.tsx
This pull request includes a small change to the `NodeStatus` component in the `src/frontend/src/CustomNodes/GenericNode/components/NodeStatus/index.tsx` file. The change updates the styling of the `STATUS_BUILD` element to include the `text-foreground` class.
* [`src/frontend/src/CustomNodes/GenericNode/components/NodeStatus/index.tsx`](diffhunk://#diff-a82985ebdf968b3b9ff88582d46208ef24ade91024f7e4bcdddc9451bfede45eL207-R207): Added the `text-foreground` class to the `STATUS_BUILD` span element to improve its styling.
Before:
Now:
=> chore(ui): add text-foreground class to NodeStatus build element

src/backend/base/langflow/components/models/openai.py
- Removed deprecated `output_schema` parameter
- Removed redundant `output_parser` parameter
- Simplified JSON output handling to use only `json_mode`
This PR cleans up the OpenAI component by:
1. Removing deprecated functionality that was marked for removal
2. Simplifying the way we handle structured outputs by relying solely on `json_mode`
3. Making the component more maintainable by reducing redundant parameters
The changes maintain all essential functionality while removing deprecated features. JSON output can still be achieved using the `json_mode` parameter.
=> refactor(openai): Remove deprecated parameters from OpenAI component

src/frontend/src/pages/MainPage/components/header/index.tsx, src/frontend/tests/extended/features/dragAndDrop.spec.ts, src/frontend/tests/extended/features/lock-flow.spec.ts
This pull request includes several updates to the frontend test suite and a minor change to a component in the main page. The most important changes involve adding test IDs for better element targeting, ensuring UI updates are properly handled, and improving test reliability by adding necessary waits and actions.
* [`src/frontend/src/pages/MainPage/components/header/index.tsx`](diffhunk://#diff-199241b1c40a4c34b8a20490e35826d94dbbc77765882d3324748bad1c01397aR144): Added `data-testid` attribute to the "new project" button for better test targeting.
* [`src/frontend/tests/extended/features/dragAndDrop.spec.ts`](diffhunk://#diff-b9839b9273615451795233816b37fb37abbb06550b928812d3137b6294d14139L11-R31): Added steps to ensure the workspace is available by interacting with the UI elements and …
=> test: Add test IDs and improve UI wait handling in frontend tests

src/backend/base/langflow/initial_setup/setup.py
Updating the starter projects requires writing to the `.venv` directory, which is not allowed in certain security-conscious deployments. This PR introduces an optional environment variable that allows such deployments to skip this update. 
The next PR for this effort will be adding a script to update the starter projects on merge instead, such that we should never expect this update on startup to be required in the first place.
=> feat: add optional env var to skip starter project updates

docs/docs/Components/components-custom-components.md, docs/docs/Configuration/configuration-api-keys.md, docs/docs/Guides/guides-chat-memory.md
This pull request includes the following typo fixes in the documentation:
1. Corrected "resusable" to "reusable" in `components-custom-components.md`.
2. Removed the extra "the" in `configuration-api-keys.md` for the sentence: "To revoke an API key, delete it from the the list of keys..." which is now corrected to: "To revoke an API key, delete it from the list of keys..."
3. Fixed the extra "a" in `guides-chat-memory.md` for the sentence: "A a single flow can host multiple session IDs..." which is now corrected to: "A single flow can host multiple session IDs..."
=> docs: fix typos in documentation files

src/frontend/tests/core/integrations/Market Research.spec.ts
This pull request includes changes to the `src/frontend/tests/core/integrations/Market Research.spec.ts` file to streamline the test imports and adjust the timeout for a specific test.
Test import streamlining:
* Removed unnecessary imports such as `addNewApiKeys`, `adjustScreenView`, `removeOldApiKeys`, `selectGptModel`, and `updateOldComponents` from the test file.
Test timeout adjustment:
* Increased the timeout for the `page.waitForSelector` method from 30 seconds to 3 minutes to accommodate longer build times.
=> test: increase timeout in Market Research tests

src/backend/base/langflow/components/models/lmstudiomodel.py
This pull request includes a change to the `build_model` method in the `lmstudiomodel.py` file to improve the handling of the `api_key`.
* [`src/backend/base/langflow/components/models/lmstudiomodel.py`](diffhunk://#diff-ed909b08aedd90a891a1da6a22826a994b10ce95ab806371662eb6dfbf8e9da4L105-R105): Modified the `api_key` assignment to use the `get_secret_value` method of `SecretStr` to ensure the actual secret value is retrieved.
=> fix: use SecretStr get_secret_value for LMStudio API key handling

docs/docs/Integrations/integrations-assemblyai.md
I've corrected several typographical errors in the AssemblyAI integration documentation to improve clarity and accuracy.
The following changes were made:
- "AssebmlyAI Poll Transcript" was corrected to "AssemblyAI Poll Transcript."
- "AssebmlyAI Get Subtitles" was corrected to "AssemblyAI Get Subtitles."
- "AssebmlyAI LeMUR" was corrected to "AssemblyAI LeMUR."
These fixes should help avoid confusion for developers using the AssemblyAI components in Langflow.
=> docs: fix typos Update integrations-assemblyai.md

src/backend/base/langflow/custom/custom_component/custom_component.py
This pull request includes a few changes to the `custom_component.py` file to enhance the handling of user IDs in the `variables` method and to import the `uuid` module.
**Codebase improvements:**
* [`src/backend/base/langflow/custom/custom_component/custom_component.py`](diffhunk://#diff-010449088e429212d46c7455250d37f399c727ed8e5ab77b99cb155242e879f3R7): Imported the `uuid` module to handle UUID conversions.
* [`src/backend/base/langflow/custom/custom_component/custom_component.py`](diffhunk://#diff-010449088e429212d46c7455250d37f399c727ed8e5ab77b99cb155242e879f3L442-R443): Modified the `variables` method to convert `self.user_id` to a `UUID` object before using it.
=> fix: improve UUID handling in custom component variables

src/backend/base/langflow/api/v1/monitor.py, src/backend/base/langflow/custom/custom_component/component.py, src/backend/base/langflow/custom/custom_component/custom_component.py, src/backend/base/langflow/memory.py
This pull request includes several changes to improve type consistency and error handling in the backend of the Langflow application. The most important changes involve updating type annotations for UUIDs, adding type checks, and improving error messages.
* [`src/backend/base/langflow/api/v1/monitor.py`](diffhunk://#diff-3ec73bcad57a386eda3d6a958899bc825249632a5cd6093376b153d10bf18d8aL43-R44): Updated type annotations for `flow_id` and `session_id` in the `get_messages` function to use `UUID` instead of `str`.
* [`src/backend/base/langflow/custom/custom_component/component.py`](diffhunk://#diff-22fd745de33f20981c7cbcbf3c91d4a6f8719de20761eb22cf42f8ed6ec50169R1014-R1015): Added a check to convert `flow_id` to `UUID` if it is a string in the `send_message` method.
* …
=> fix: make user_id variable valid and fix type signature in messages endpoints

src/backend/base/langflow/api/v1/chat.py, src/backend/base/langflow/graph/utils.py, src/backend/base/langflow/services/tracing/schema.py
This pull request refactors the JSON serialization in the `build_flow` and `log_vertex_build` functions. The `build_flow` function now uses the `model_dump` method instead of `model_dump_json` to serialize the vertex build response. Similarly, the `log_vertex_build` function now uses `model_dump` instead of `model_dump_json` to serialize the data and artifacts. This improves the JSON serialization process in these functions.
=> fix: Refactor JSON serialization in build_flow and log_vertex_build

src/backend/base/langflow/base/agents/events.py
This PR adds a safety check to ensure that the assignment to `tool_blocks_map` is only performed when `agent_message.content_blocks` and its contents are available. This prevents potential errors when accessing these properties.
=> fix: Ensure safe assignment to tool_blocks_map in agent_message handling

src/backend/base/langflow/base/models/google_generative_ai_constants.py
This PR adds support for two new Google Gemini models:
- **gemini-2.0-flash-exp**
- **gemini-exp-1206**
=> feat: add gemini-2.0-flash-exp and gemini-exp-1206 models

.github/workflows/ci.yml, .github/workflows/conventional-labels.yml
This pull request introduces a nightly build status check to the CI workflow, ensuring that the CI process only proceeds if the latest nightly build was successful. Additionally, it updates the PR label workflow to trigger on the 'synchronize' event, allowing for better handling of PR updates.
=> ci: Add nightly build status check and synchronize event to CI workflows

src/backend/base/langflow/base/models/model_input_constants.py, src/backend/base/langflow/services/database/service.py
This pull request addresses two main improvements. First, it prevents duplicate logging of SQLite pragmas in the `DatabaseService` by introducing a flag that ensures the debug message for setting pragmas is logged only once per session, enhancing logging efficiency. Second, it introduces `ModelProvidersDict` as a `TypedDict` to define the structure for model provider configurations, updating the `MODEL_PROVIDERS_DICT` type annotation for improved type safety and clarity, which enhances code readability and maintainability.
=> refactor: reduce logging of SQLite pragmas and enhance model provider type safety

.github/workflows/lint-py.yml, .github/workflows/nightly_build.yml, .github/workflows/python_test.yml
This pull request updates the GitHub Actions workflow to include Python 3.13 in the testing matrix. The changes ensure that the new version is tested alongside existing versions, enhancing compatibility and support for the latest Python features.
=> ci: Update GitHub Actions workflow to include Python 3.13

src/frontend/src/hooks/flows/use-add-flow.ts, src/frontend/src/stores/flowStore.ts, src/frontend/src/utils/reactflowUtils.ts
This pull request introduces several changes to the `use-add-flow` functionality and the handling of global variables within the flow management system. The most important changes include importing and utilizing the `useGlobalVariablesStore` in various parts of the code, and modifying the `updateGroupRecursion` function to accommodate global variables.
Enhancements to `use-add-flow` functionality:
* [`src/frontend/src/hooks/flows/use-add-flow.ts`](diffhunk://#diff-51f99cda7111618620f1f262ad11b34013662e517e589110a62b936f8e8f59e0L1-R5): Imported `useGlobalVariablesStore` and used it to access `unavailableFields` and `globalVariablesEntries` within the `useAddFlow` hook. These variables are then passed to the `updateGroupRecursion` function. …
=> fix: update hidden secret_str load_from_db when adding flow

src/backend/base/langflow/api/v1/flows.py, src/backend/base/langflow/api/v1/monitor.py, src/backend/base/langflow/main.py, src/backend/base/langflow/services/database/models/transactions/crud.py, src/backend/base/langflow/services/database/models/transactions/model.py, src/backend/tests/unit/test_database.py, src/frontend/src/controllers/API/queries/transactions/use-get-transactions.ts, src/frontend/src/modals/flowLogsModal/index.tsx
This PR introduces pagination to the transactions log using `fastapi-pagination` on the backend and `PaginatorComponent` on the frontend.
These changes aim to enhance retrieval speed, reduce memory consumption, and prevent potential lags during frequent debugging sessions.
=> feat: implement pagination for transaction log queries

.github/actions/setup-uv/action.yml, .github/workflows/python_test.yml, .github/workflows/store_pytest_durations.yml
This pull request introduces a new input parameter 'python-version' for the setup-uv action, allowing users to specify the Python version with a default of 3.12. The GitHub Actions workflow has been updated to utilize this new input, enhancing flexibility by using a matrix input instead of a version file. Additionally, the Python version is now directly specified in the workflow for consistency and clarity.
=> ci: Add Python version input to setup-uv action and update workflow configuration

src/frontend/src/components/ui/select-custom.tsx, src/frontend/src/components/ui/select.tsx, src/frontend/src/modals/IOModal/components/chatView/chatMessage/components/editMessageButton/newMessageOptions.tsx
This pull request includes changes to the SelectItem component. The component has been refactored to add a div wrapper around the children in the SelectItem component. Additionally, unused imports have been removed from the newMessageOptions.tsx file.
fix #4073
=> Refactor: update selectItem component and remove unused imports

.github/workflows/nightly_build.yml, .github/workflows/python_test.yml
This pull request modifies the Python version matrix in the GitHub Actions workflows to remove Python 3.13. This change enhances compatibility and streamlines the testing process by clarifying the supported Python versions in the CI configuration.
=> ci: Update Python version matrix in CI workflows to exclude 3.13

.github/changes-filter.yaml
This PR updates the changes-filter.yaml to include the new 'uv.lock' and 'src/backend/base/uv.lock' files, as well as 'src/backend/base/pyproject.toml' for better tracking of changes in the backend project structure. The paths have been adjusted to ensure proper monitoring of relevant files.
=> ci: update changes filter to include lock files and base pyproject.toml

pyproject.toml, src/backend/base/pyproject.toml, uv.lock
This pull request updates several package versions, including `pydantic` to 2.10.0 and `weaviate-client` to 4.10.2, while also adding new dependencies such as `eval-type-backport` and `griffe`. Additionally, the `pydantic-ai` dependency has been introduced with a minimum version of 0.0.12. These updates aim to enhance functionality and maintain compatibility with the latest versions of the libraries.
=> feat: add pydantic-ai and update dependencies to support it

src/backend/base/langflow/schema/message.py, src/backend/base/langflow/schema/validators.py, src/backend/base/langflow/services/database/models/message/model.py, src/backend/tests/unit/schema/test_schema_message.py, src/backend/tests/unit/test_messages_endpoints.py
This pull request improves the timestamp handling in the Message model by introducing new validators and serializers, ensuring accurate conversion and timezone management. It includes the addition of timestamp serialization tests to validate the handling of various formats, as well as enhancements to error messaging for invalid formats. The changes also integrate Pydantic's `Annotated` for better validation and introduce new functions for consistent UTC output. Overall, these updates enhance the robustness and reliability of timestamp data representation in the application.
=> fix: make messages appear in the correct order again

.github/workflows/ci.yml, .github/workflows/conventional-labels.yml
This pull request introduces changes to the GitHub Actions workflows to support the `merge_group` event, ensuring that CI runs appropriately for merge groups.
Changes to GitHub Actions workflows:
* [`.github/workflows/ci.yml`](diffhunk://#diff-b803fcb7f17ed9235f1e5cb1fcd2f5d3b2838429d4368ae4c57ce4436577f03fL42-R42): Added support for the `merge_group` event to the `on` section, enabling CI to trigger for merge groups.
* [`.github/workflows/ci.yml`](diffhunk://#diff-b803fcb7f17ed9235f1e5cb1fcd2f5d3b2838429d4368ae4c57ce4436577f03fL83-R83): Updated the `should-run-ci` output condition to include the `merge_group` event, ensuring CI runs when this event occurs.
* [`.github/workflows/conventional-labels.yml`](diffhunk://#diff-ff26597550dc7e886d568568618290e90ad2f9018fa0d65667783b1d6dcc00c2R7): …
=> chore: Update CI workflow to include 'merge_group' event

src/backend/base/langflow/api/v1/chat.py, src/backend/base/langflow/schema/message.py
This pull request improves error handling in the `build_flow` function by introducing the `ErrorMessage` schema, which standardizes error reporting. The changes include the removal of `session_id` from the error messages in the chat endpoint and enhancements to error handling logic, providing better context by including `flow_id`, `session_id`, and `trace_name`. This results in clearer and more maintainable error handling across various exception cases.
=> fix: make errors in build_flow function use the standardized ErrorMessage schema

src/backend/base/langflow/services/database/models/vertex_builds/crud.py
This PR optimizes the SQL query to retrieve only the most recent record for each vertex in the `VertexBuildTable`. Previously, all data was fetched and transmitted to the frontend, which only needed the latest entry per vertex, leading to excessive and unnecessary browser memory usage.
=> perf: optimize vertex build query for recent records

src/backend/base/langflow/schema/image.py, src/backend/tests/unit/schema/test_image.py
Replaces incorrect use of split with a cross-platform method for separating file paths.
=> fix: file path handling for cross-os compatibility

src/backend/base/langflow/inputs/inputs.py, src/backend/tests/unit/base/tools/test_toolmodemixin.py
feat: add ToolModeMixin to existting Input Types except SecretsInputs
This pull request includes updates to various input classes in the `src/backend/base/langflow/inputs/inputs.py` file, adding the `ToolModeMixin` to several classes to enhance their functionality. The most important changes are as follows:
Enhancements to input classes:
* [`TableInput`](diffhunk://#diff-f12c9ca218a67d203869442cb70537349ad1f026a3c20c88c8f1e15ae71bdbc8L33-R33): Added `ToolModeMixin` to the class definition.
* [`StrInput`](diffhunk://#diff-f12c9ca218a67d203869442cb70537349ad1f026a3c20c88c8f1e15ae71bdbc8L94-R94): Added `ToolModeMixin` to the class definition.
* [`IntInput`](diffhunk://#diff-f12c9ca218a67d203869442cb70537349ad1f026a3c20c88c8f1e15ae71bdbc8L302-R302): Added `ToolModeMixin` to the class …
=> feat: add ToolModeMixin to existting Input Types except SecretsInputs

src/backend/base/langflow/base/agents/agent.py, src/backend/base/langflow/components/langchain_utilities/sql.py, src/backend/base/langflow/initial_setup/starter_projects/Instagram Copywriter.json, src/backend/base/langflow/initial_setup/starter_projects/Market Research.json, src/backend/base/langflow/initial_setup/starter_projects/Research Agent.json, src/backend/base/langflow/initial_setup/starter_projects/SaaS Pricing.json, src/backend/base/langflow/initial_setup/starter_projects/Sequential Tasks Agents .json, src/backend/base/langflow/initial_setup/starter_projects/Simple Agent.json, src/backend/base/langflow/initial_setup/starter_projects/Travel Planning Agents.json
This pull request includes a small change to the `src/backend/base/langflow/base/agents/agent.py` file. The change simplifies the `input_types` for the `HandleInput` instance within the `LCToolsAgentComponent` class by removing `BaseTool` and `StructuredTool`, leaving only `Tool`.
* [`src/backend/base/langflow/base/agents/agent.py`](diffhunk://#diff-87ba96f91b4bbce3350ae83d5d4c7dfa3a7c800deeed21a60857dff1caaefe04L200-R200): Simplified `input_types` for `HandleInput` instance in `LCToolsAgentComponent` class.
=> refactor: simplify input_types in LCToolsAgentComponent  (remove BaseTool and StructuredTool)

src/backend/base/langflow/components/tools/calculator.py
- **Speed Increase:** 📈 **`103%`** (**`1.03x` faster**)
- **Runtime Reduction:** ⏱️ From **`1.93 millisecond`** down to **`949 microseconds`** (best of `1` runs)
---
Certainly! Here is an optimized version of the provided program.
1. **Caching Operators Dictionary**: 
- Moved the operators dictionary to the `__init__` method of the class. This avoids redefining the dictionary every time `_eval_expr` is called.
These changes improve speed and efficiency without significantly altering the logic or structure of the method. The returned value remains unaffected, meeting the requirement for an identical output to the original program.
---
The new optimized code was tested for correctness. The results are listed below:
| Test                        | Status            | Details                | …
=> refactor:  (codeflash) ⚡️ Speed up method `CalculatorToolComponent._eval_expr` by 103%

Makefile
This PR eliminates the redundant clearing of the `src/backend/base/langflow/frontend` directory in the `build_langflow_base` target of the Makefile. This change fixes the build step to make sure the frontend is bundled with the wheel.
=> fix: Remove unnecessary directory clearing in build_langflow_base target

.github/workflows/ci.yml
This pull request modifies the CI workflow configuration to ensure that the `workflow_dispatch` event can trigger the CI process. This change enhances the flexibility of the CI system by allowing manual triggers in addition to the existing conditions.
=> ci: Update CI condition to allow workflow_dispatch trigger to bypass nightly check

src/frontend/tests/extended/features/tool-mode.spec.ts
This pull request includes changes to the `src/frontend/tests/extended/features/tool-mode.spec.ts` file to enhance the tool mode test functionality. The most important changes include adding a new utility import, incorporating zoom functionality, and modifying the agent interaction steps.
Enhancements to tool mode test functionality:
* [`src/frontend/tests/extended/features/tool-mode.spec.ts`](diffhunk://#diff-c1473350bc51716fab29cedef6c555fd3bc79ac0202b7df11897f8ae0cd0e3d4R3): Added import for the `zoomOut` utility function.
* [`src/frontend/tests/extended/features/tool-mode.spec.ts`](diffhunk://#diff-c1473350bc51716fab29cedef6c555fd3bc79ac0202b7df11897f8ae0cd0e3d4R117-R132): Added steps to click the "fit view" button and perform a zoom out action.
* …
=> test: Enhance tool mode spec with zoom controls and drag-drop functionality

.pre-commit-config.yaml
This pull request updates the pre-commit configuration to integrate ruff for linting and formatting Python files. The configuration now uses the ruff pre-commit hook for both checking and formatting, streamlining the development process and ensuring consistent code quality.
=> ci: Update pre-commit configuration to use ruff for linting and formatting

.pre-commit-config.yaml, src/backend/base/langflow/api/v1/variable.py, src/backend/base/langflow/services/variable/base.py, src/backend/base/langflow/services/variable/kubernetes.py, src/backend/base/langflow/services/variable/service.py, src/backend/tests/unit/api/v1/test_variable.py, src/backend/tests/unit/services/variable/test_service.py
This pull request refactors the variable tests to improve clarity and reusability by utilizing fixtures for generic and credential types. It implements a `get_all` method in the `KubernetesSecretService` to retrieve and decrypt user variables, and adds an abstract method in `VariableService` for retrieving all variables for a user. Additionally, the variable service is enhanced to handle decryption for generic types, and the default variable type is updated to `CREDENTIAL_TYPE`. Minor fixes include updating the variable type constant and adjusting the pre-commit configuration for formatting.
=> feat: return variable value if it is a generic variable

src/backend/base/langflow/api/v1/endpoints.py, src/backend/base/langflow/interface/initialize/loading.py
This pull request improves the robustness of the `custom_component_update` and `update_params_with_load_from_db_fields` functions by ensuring that only fields with defined values are included in the loading process. It updates the conditions to skip parameters that are either absent or have falsy values, enhancing the overall reliability of parameter handling.
=> fix: avoid checking variables with empty value

src/frontend/src/modals/IOModal/newModal.tsx, src/frontend/src/modals/apiModal/index.tsx, src/frontend/src/modals/shareModal/index.tsx
This pull request includes several changes to improve the readability and functionality of modals in the frontend. The changes primarily focus on ensuring that certain elements are only rendered when the modal is open, and improving the formatting of JSX elements.
Key changes:
* [`src/frontend/src/modals/IOModal/newModal.tsx`](diffhunk://#diff-ae615faa0832e4b0502ba9612038896904f6871eb5adfa571b8fbb212272eb08R262): Wrapped certain elements in conditional rendering blocks to ensure they are only displayed when the modal is open. [[1]](diffhunk://#diff-ae615faa0832e4b0502ba9612038896904f6871eb5adfa571b8fbb212272eb08R262) [[2]](diffhunk://#diff-ae615faa0832e4b0502ba9612038896904f6871eb5adfa571b8fbb212272eb08R508)
* [`src/frontend/src/modals/apiModal/index.tsx`](diffhunk://#diff-61e47d90dd636537 …
=> refactor: improve conditional rendering on panel buttons 

src/backend/base/langflow/components/langchain_utilities/csv.py
#5185
This pull request includes enhancements to the `CSVAgentComponent` class in the `src/backend/base/langflow/components/langchain_utilities/csv.py` file, focusing on adding support for Pandas keyword arguments.
* Added `DictInput` for `pandas_kwargs` to the `inputs` list to allow passing Pandas keyword arguments to the agent.
* Updated the `build_agent_response` method to include `pandas_kwargs` in the agent's configuration.
* Updated the `build_agent` method to include `pandas_kwargs` in the agent's configuration.
* Added `DictInput` import from `langflow.inputs.inputs`.
=> feat: Add Pandas kwargs support for CSV Agent

src/backend/base/langflow/alembic/versions/b2fa308044b5_add_unique_constraints.py, src/backend/base/langflow/initial_setup/setup.py
This PR adds the following checks on initial setup:
* Validate the `flow_id` is a uuid before insertion to database. This addresses https://github.com/langflow-ai/langflow/issues/5370
* Unknown why this was an issue only for this particular user in this scenario. 
* Updates a migration script to check for existence of fk relation - https://github.com/langflow-ai/langflow/issues/5371
* @ogabrielluiz I believe this change to the migration script is backwards-compatible, since it's just an additional validation rather than an addition/removal of a relation, but please double check.
=> fix: add initial setup validations 

src/backend/base/langflow/services/database/models/flow/model.py
This pull request includes several changes to improve the code readability and functionality in the `langflow` backend. The most important changes include reformatting imports, updating the `read_flows` function to use `FlowHeader.model_validate`, adding `model_validator` to `FlowHeader`, and reformatting the `FlowBase` and `Flow` classes for better readability.
* [`src/backend/base/langflow/api/v1/flows.py`](diffhunk://#diff-37c1756ce77874f858b4862cefff35a28b8d1d3ec6534381934b3db73782eb26L20-R20): Reformatted imports to a single line for better readability.
* [`src/backend/base/langflow/services/database/models/flow/model.py`](diffhunk://#diff-adeae5acd8e79a62451c8957c0b5c5f102c5ba8c34e41d440514da6169e37db9L30-R43): Reformatted the `FlowBase` and `Flow` classes to improve readability by …
=> fix: add data field to returned object on flowheader if flow is a component

src/backend/base/langflow/alembic/env.py, src/backend/base/pyproject.toml
Fix parallel execution of alembic with PostgreSQL
=> fix: Fix parallel execution of alembic with PostgreSQL

src/frontend/package-lock.json, src/frontend/src/pages/FlowPage/components/flowSidebarComponent/index.tsx
This pull request includes significant changes to the `FlowSidebarComponent` in `src/frontend/src/pages/FlowPage/components/flowSidebarComponent/index.tsx`. The modifications focus on improving the component's structure, optimizing the search functionality, and adding new state management and hooks.
* Reorganized and updated imports to include necessary hooks and libraries such as `Fuse`, `memo`, and `useHotkeys`.
* Introduced new state variables and hooks for managing search functionality, component visibility, and user interactions.
* Added a new interface `FlowSidebarComponentProps` to define props for the component.
* Enhanced the search logic with optimized filtering, memoization, and handling of search results. This includes the use of `Fuse` for fuzzy searching …
=> refactor(sidebar): Optimize FlowSidebarComponent with improved search and performance

src/frontend/src/CustomNodes/GenericNode/components/HandleTooltipComponent/index.tsx, src/frontend/src/CustomNodes/GenericNode/components/handleRenderComponent/index.tsx, src/frontend/src/pages/FlowPage/components/PageComponent/index.tsx, src/frontend/src/pages/FlowPage/components/extraSidebarComponent/sidebarFilterComponent/index.tsx, src/frontend/tests/core/regression/generalBugs-shard-5.spec.ts
This pull request includes several changes aimed at improving the handling of node colors and tooltips in the frontend components. The most important changes include the removal of redundant color properties, the addition of utility imports, and the enhancement of tooltip rendering.
* [`src/frontend/src/CustomNodes/GenericNode/components/HandleTooltipComponent/index.tsx`](diffhunk://#diff-f286fd032653a39d18eb067d1981f06a2f81c02532353dce582ee272305cd271R3-L20): Removed `accentColorName` and `accentForegroundColorName` properties and replaced them with `nodeColorsName` utility for dynamic color handling. [[1]](diffhunk://#diff-f286fd032653a39d18eb067d1981f06a2f81c02532353dce582ee272305cd271R3-L20) [[2]](diffhunk://#diff-f286fd032653a39d18eb067d1981f06a2f81c02532353dce582ee272305cd271L54-R55) …
=> feat: add generic handle that inherits colors for multiple types

src/frontend/tests/extended/features/notifications.spec.ts, src/frontend/tests/extended/regression/generalBugs-shard-3.spec.ts
This pull request addresses visibility issues with the Chat Input in the test suite. The `fit view` action has been commented out to prevent it from hiding the Chat Input during tests. Additionally, the tests have been updated to use Text Input instead of Chat Input, as the latter starts minimized, ensuring that the tests run smoothly without UI interruptions.
=> tests: fix tests that use Chat Input

src/frontend/tests/extended/regression/generalBugs-shard-3.spec.ts
This pull request includes a small change to the `src/frontend/tests/extended/regression/generalBugs-shard-3.spec.ts` file. The change reorders the mouse actions in a test to ensure the `mouse.up()` action occurs after `mouse.down()`.
* [`src/frontend/tests/extended/regression/generalBugs-shard-3.spec.ts`](diffhunk://#diff-c61d7345b8378427eeb622d524db04463e36b6e63e156b6f2e6d30b0b76ab473L67-R68): Reordered the mouse actions in a test to ensure `mouse.up()` occurs after `mouse.down()`
=> fix: adjust mouse actions in regression test for proper drag-and-drop

Makefile
This PR modifies the build command in the Makefile for the frontend to display output during the build process, enhancing visibility into the build status. Previously, the output was suppressed, making it difficult to diagnose issues during the build.
=> ci: Update Makefile to show output during frontend build

src/backend/base/langflow/schema/message.py
https://github.com/langflow-ai/langflow/blob/0118e98b5c432ba0690c8feffedeb6808e91d4c9/src/backend/base/langflow/schema/message.py#L384
```
/Users/feng/Work/my/forks/langflow-main/src/backend/base/langflow/schema/message.            
py", line 384, in __init__                                                                    
if hasattr(exception, "body") and "message" in exception.body:                            
|                                   |         -> None                          
|                                   ->                                         
APIConnectionError('Connection error.')                                                       
-> APIConnectionError('Connection error.')                                     
TypeError: argument of type 'NoneType' is not …
```
=> fix: error message issue when "exception.body" is None

src/backend/base/langflow/components/helpers/structured_output.py
This PR fixes Structured Output component in case when user did not provide Schema Name and set Generate Multiple flag
Current behavior results in somewhat cryptic error message from OpenAI:
`BadRequestError: Error code: 400 - {'error': {'message': "Invalid 'tools[0].function.name': empty string. Expected a string with minimum length 1, but got an empty string instead.", 'type': 'invalid_request_error', 'param': 'tools[0].function.name', 'code': 'empty_string'}}`
Introduce a sane default, consistent with `langflow.helpers.base_model.build_model_from_schema` that handles situation when user did not provide schema name
=> fix: StructuredOutputComponent tool name generation for multiple=True mode

src/backend/base/langflow/alembic/env.py
Fix parallel execution of alembic with SQlite
=> fix: Fix parallel execution of alembic with SQlite

src/frontend/src/components/core/dropdownComponent/index.tsx
This pull request includes changes to the `Dropdown` component in the `src/frontend/src/components/core/dropdownComponent/index.tsx` file to improve the user experience and simplify the code.
Improvements to user experience:
* Added a `hover:cursor-pointer` class to the `CommandItem` element to indicate that the item is clickable.
Code simplification:
* Removed the `ShadTooltip` wrapper around the `CommandItem` element to simplify the component structure.
=> feat: enhance UX with clickable items and simplified structure

src/frontend/src/icons/Langwatch/langwatch.jsx
this pr fixes the langwatch icon with the proper viewbox
=> fix: Update dimensions of SvgLangwatch component

src/backend/base/langflow/helpers/data.py, src/backend/tests/unit/helpers/test_data.py
Formatting templates caused a `TypeError` when the `data` dictionary contained a `data` key, due to keyword argument conflicts.
Adjusted the logic to avoid conflicts by checking for the `data` key before passing it explicitly. Added a comment for clarity.
=> fix: resolve data keyword conflict in template formatting

src/frontend/src/controllers/API/index.ts, src/frontend/src/types/api/index.ts
This pull request removes unused API functions that are no longer needed. The changes include removing the `sendAllProps` type and updating the `errorsTypeAPI` type. These changes improve the codebase by removing unnecessary code and reducing complexity.
=> Refactor: Remove unused API functions

src/backend/base/langflow/components/git/git.py, src/backend/tests/unit/components/git/__init__.py, src/backend/tests/unit/components/git/test_git_component.py
This pull request includes significant updates to the `GitLoaderComponent` class in the `src/backend/base/langflow/components/git/git.py` file, enhancing its functionality and improving the user interface for selecting repository sources and filtering files.
Enhancements to `GitLoaderComponent`:
* Added support for selecting between local and remote Git repositories by introducing a new `DropdownInput` for `repo_source`, and updated the `repo_path` and `clone_url` inputs to reflect this selection.
* Improved the `file_filter` input's `info` attribute to provide clearer examples of how to include and exclude files using patterns.
* Introduced a temporary directory mechanism for cloning remote repositories, which is cleaned up after loading documents. …
=> feat: improve gitloader component

docs/sidebars.js, src/backend/base/langflow/components/langchain_utilities/recursive_character.py
This pull request includes updates to the documentation and a minor change to a component's documentation link.
=> docs: add components-processing link to sidebar and update documentation link in component

src/backend/base/langflow/api/v1/endpoints.py, src/backend/base/langflow/events/event_manager.py, src/backend/base/langflow/graph/graph/base.py, src/backend/base/langflow/processing/process.py
This pull request introduces several enhancements to the `langflow` API, focusing on adding support for event streaming and improving flow execution telemetry. The key changes include the integration of an `EventManager` for handling streaming events, updates to flow execution functions to support streaming, and the addition of new utility functions for event management.
Enhancements to event streaming and telemetry:
* [`src/backend/base/langflow/api/v1/endpoints.py`](diffhunk://#diff-2cc70b3b7a7be90cba6b85c839b082b0cc844c917644fdc2c9fafba56ba8b607R5-R13): Added the `EventManager` parameter to flow execution functions (`simple_run_flow`, `simple_run_flow_task`, `simplified_run_flow`) and implemented new asynchronous functions (`consume_and_yield`, `run_flow_generator`) to handle event …
=> feat: Implement streaming support and EventManager integration in flow execution

src/backend/base/langflow/custom/custom_component/component.py, src/backend/base/langflow/graph/schema.py, src/backend/base/langflow/graph/utils.py
This pull request improve the logic for skipping messages in the codebase. The `TextInput` and `TextOutput` components have been commented out, and a new function has been added to check if a graph has an output vertex connected to it. Additionally, a function has been added to skip messages based on the vertex configuration and message type. These changes aim to enhance the overall efficiency and functionality of the code.
=> feat: make Agents not send message if not connected to an output component

src/backend/tests/base.py
This PR updates the `ComponentTestBase` class to skip tests when the `file_names_mapping` is empty, instead of raising an `AssertionError`. This change improves user feedback by providing a clear message indicating the reason for skipping the test, enhancing the overall testing experience.
=> tests: allow tests to skip version tests if `file_names_mapping` is empty

src/backend/tests/conftest.py, src/backend/tests/unit/api/v1/test_files.py
This pull request includes several changes to the test files in the backend, primarily focusing on clearing the services cache, adding new fixtures, and refactoring test functions to use these new fixtures. The most important changes include the addition of new fixtures for API keys, users, and flows, and the refactoring of existing test functions to utilize these fixtures.
* [`src/backend/tests/conftest.py`](diffhunk://#diff-2f574640999ddf5d1e3c1d4217f1d8d3018710f2801838edea87078a919ca77eR357-R361): Added code to clear the services cache by importing and clearing `service_manager.factories` and `service_manager.services` in the `init_app` function.
* [`src/backend/tests/unit/api/v1/test_files.py`](diffhunk://#diff-e2da636c00eddb3006c69cd63771801802cf918a292bef72ce967b318b94cff8R2-R99): …
=> tests: fix tests by clearing service_manager services

src/backend/base/langflow/initial_setup/setup.py, src/backend/base/langflow/main.py, src/backend/base/langflow/services/settings/base.py, src/backend/tests/unit/test_initial_setup.py
Loads flows and components from zip file URLs.
The URLs are configured by the setting `bundle_urls` (env var `LANGFLOW_BUNDLE_URLS`).
The zip file must have the following structure:
```
|- a_bundle
|- flows
|- c54f9130-f2fa-4a3e-b22a-3856d946351b.json
|- 85447b5e-d7f8-4505-a6eb-15510cbcdb3f.json
|-components
|- some_component.py
|- another_component.py
|- another_bundle
|- flows
|- 57e4dfea-593a-49ae-a1bc-28f71b1ef843.json
```
Example zip: https://github.com/cbornet/test-flow/archive/refs/heads/main.zip
As for loading flows from a dir, a superuser and `AUTO_LOGIN=true` are needed to load the flows.
When using a GitHub repo, the zip files can be generated using the GitHub API: https://docs.github.com/en/repositories/working-with-files/using-files/downloading-source-code-archives#source-code …
=> feat: Add support for loading flows and components from URLs

docker_example/docker-compose.yml
This makes the postgres instance only reachable from the langflow container and allows it to spin up even if another process (e.g. another postgres instance) is running on the host and binds to the same port.
=> chore: Use expose instead of ports in docker compose example

src/backend/base/langflow/base/tools/component_tool.py, src/backend/base/langflow/base/tools/constants.py, src/backend/base/langflow/custom/custom_component/component.py, src/backend/base/langflow/inputs/input_mixin.py, src/backend/base/langflow/schema/table.py, src/frontend/src/App.css, src/frontend/src/components/core/parameterRenderComponent/components/TableNodeComponent/index.tsx, src/frontend/src/components/core/parameterRenderComponent/index.tsx, src/frontend/src/components/core/parameterRenderComponent/types.ts, src/frontend/src/modals/tableModal/index.tsx, src/frontend/src/types/api/index.ts, src/frontend/src/types/utils/functions.ts, src/frontend/src/utils/stringManipulation.ts, src/frontend/src/utils/utils.ts
this pr update some default values for the tool table on tool-mode
=> feature: add command feature column to toolset table and other minor table improvements

src/frontend/src/style/index.css, src/frontend/src/utils/styleUtils.ts
This pull request includes changes to the color scheme used in the frontend. The changes focus on updating color values in the CSS file and modifying the color assignments in the `styleUtils.ts` file.
Color scheme updates:
* [`src/frontend/src/style/index.css`](diffhunk://#diff-90e2b07b21bd53ac0fe04b56353e8b37e8ba1f3034f51e66306a1ff010ab4437L114-R115): Updated the `--datatype-pink` and `--datatype-pink-foreground` color values.
Color assignments in `styleUtils.ts`:
* [`src/frontend/src/utils/styleUtils.ts`](diffhunk://#diff-ce70511ff4131ac5078d799cd2295f98874bad89bcde4732f33c967c1bbc71f2L455-R461): Changed the color assignment for `wrappers` and `prototypes` from "pink" to "rose".
* [`src/frontend/src/utils/styleUtils.ts`](diffhunk://#diff-ce70511ff4131ac5078d799cd2295f98874bad89bcde4732f3 …
=> refactor: update DataFrame color to pink

src/backend/base/langflow/components/data/api_request.py, src/backend/tests/unit/components/data/test_api_request_component.py
Addresses nightly build failures seen on 3.11 and 3.12 versions.
=> fix: address api_request issues on Python 3.11+

src/frontend/tests/extended/regression/generalBugs-shard-7.spec.ts
This pull request includes changes to the `src/frontend/tests/extended/regression/generalBugs-shard-7.spec.ts` file to enhance the stability and reliability of the tests by modifying the way elements are interacted with.
Improvements to test stability:
* Replaced `dragTo` with `hover` and `click` for the "embeddingsOllama Embeddings" element to ensure the component is added correctly.
Enhancements to element selection:
* Changed the selection method from `.nth(2)` to `.first()` for elements with the placeholder "Type something..." to ensure the correct input field is targeted. [[1]](diffhunk://#diff-25a4b87a3b8c7c12b1fafa208c4efe861f17ece8643943057c7eda0348b70984L55-R64) [[2]](diffhunk://#diff-25a4b87a3b8c7c12b1fafa208c4efe861f17ece8643943057c7eda0348b70984L79-R92)
=> test: improve element interactions in generalBugs shard 7 tests (nightly fix)

src/frontend/src/routes.tsx
The deprecated playground page has been commented out in the code to prevent it from being used. This change ensures that the page is no longer accessible and avoids any potential issues related to its usage.
=> refactor: Comment out deprecated playground page

.github/workflows/release_nightly.yml
This pull request replaces the use of `uv` for installing dependencies and running the application in the CI workflow with standard Python commands. This change aims to improve reliability and reduce potential issues related to dependency timeouts.
=> ci: Stop using uv to catch dependency timeouts in nightly workflow

src/backend/base/langflow/services/database/models/flow/utils.py
This pull request includes a small change to the `src/backend/base/langflow/services/database/models/flow/utils.py` file. The change improves the method for checking the presence of "nodes" in the `flow_data` dictionary by using key access instead of the `hasattr` function.
* [`src/backend/base/langflow/services/database/models/flow/utils.py`](diffhunk://#diff-67749e1b270b011305729740ad79f6db329bc584ccacec838597956e75d42b1bL8-R8): Changed the method for checking the presence of "nodes" in `flow_data` from `hasattr` to key access.
=> fix: replace hasattr with dictionary key check for flow_data nodes (nightly fix)

src/frontend/src/controllers/API/queries/flows/use-patch-update-flow.ts, uv.lock
This pull request includes a small change to the `src/frontend/src/controllers/API/queries/flows/use-patch-update-flow.ts` file. The change modifies the `locked` property to default to `false` instead of `null`.
* [`src/frontend/src/controllers/API/queries/flows/use-patch-update-flow.ts`](diffhunk://#diff-4db6da1e4a55fca23f49479288ddea59624745ffd2bdbc7b50d8dbe040281de4L31-R31): Changed the default value of `locked` from `null` to `false`.
=> fix: default flow locked property to false instead of null (nightly fix)

src/backend/base/pyproject.toml, uv.lock
This pull request introduces the `aiofile` package as a dependency in both `uv.lock` and `pyproject.toml`, ensuring it adheres to specified version constraints. Additionally, it refines the dependency management structure by renaming `[package.dependency-groups]` to `[package.dev-dependencies]` and updating `[package.metadata.dependency-groups]` to `[package.metadata.requires-dev]` in `uv.lock`, promoting consistency across configuration files.
=> chore: Add aiofile dependency to langflow-base

.github/workflows/nightly_build.yml
This PR modifies the nightly build workflow to ensure that any existing main tags are deleted before new ones are generated. An existing tag causes the build to be stuck in time.
=> ci: Update nightly build workflow to delete existing main tags before generating new ones

src/backend/base/langflow/components/needle/needle.py
- Replaced the generic 'search' icon with a dedicated 'Needle' icon to properly represent the Needle component in the UI, addressing the missing icon issue.
=> fix: add missing Needle component icon

src/backend/base/langflow/api/v1/endpoints.py, src/backend/tests/unit/test_endpoints.py
this pr prevent's a behavior were the tweaks were not applied before even if they were provided and no input value was given
Fixes #5438
=> Fix: update tweaks processing to allow input_type without input_value

.github/workflows/add-labels.yml
This pull request introduces a GitHub Actions workflow that automates the management of the 'lgtm' label on pull requests. The workflow adds the label when a pull request is approved and removes it when changes are requested, streamlining the review process and ensuring accurate labeling based on reviewer feedback. The implementation leverages the GitHub Script action to handle label operations effectively.
=> ci: Add GitHub Actions workflow for LGTM label management

src/backend/base/langflow/components/models/nvidia.py
This pull request includes updates to the NVIDIA model component in the `langflow` project to add support for tool models. The changes introduce a new input type and refactor the method for retrieving available models.
Enhancements to NVIDIA model component:
* [`src/backend/base/langflow/components/models/nvidia.py`](diffhunk://#diff-9497a9d3010368c344c0dad0b1b04a8b84f2be1617da122437b70fc227d821a0R36-R45): Added `BoolInput` to allow users to enable or disable tool models.
* [`src/backend/base/langflow/components/models/nvidia.py`](diffhunk://#diff-9497a9d3010368c344c0dad0b1b04a8b84f2be1617da122437b70fc227d821a0R63-R73): Refactored the `update_build_config` method to use the new `get_models` method, which filters models based on the `tool_model_enabled` flag.
Refactoring and code …
=> feat: Add Support for validating  Tool Mode Models in NVIDIA LLM Component

src/backend/base/langflow/graph/graph/base.py, src/backend/base/langflow/graph/graph/state_manager.py, src/backend/base/langflow/services/state/service.py
This PR removes erroneous subscribe call in `Graph.set_run_id`.
Fixes #5275
=> fix: remove subscribe call and add unsubscribe method in StateService

src/backend/base/langflow/components/models/amazon_bedrock.py
- Make aws_access_key_id field required
- Make aws_secret_access_key field required
=> feat: make AWS credentials required in bedrock component

src/backend/base/langflow/components/tools/youtube_transcripts.py
This change ensures that users provide a video URL before using the YouTube Transcripts component, preventing potential runtime errors due to missing video source.
=> feat: make YouTube Transcripts URL field required

src/frontend/tests/core/integrations/Custom Component Generator.spec.ts, src/frontend/tests/core/unit/sliderComponent.spec.ts
This pull request includes several changes to the integration and unit tests in the frontend codebase. The changes focus on updating the API key requirements, modifying the test setup, and ensuring the tests run correctly with the new configurations.
* [`src/frontend/tests/core/integrations/Custom Component Generator.spec.ts`](diffhunk://#diff-d914f41b7bd3fca12fd73e47e07d28542a0c70076f89767d5fbb600eed61e726L4-L11): Removed unused utility imports to clean up the code.
* [`src/frontend/tests/core/integrations/Custom Component Generator.spec.ts`](diffhunk://#diff-d914f41b7bd3fca12fd73e47e07d28542a0c70076f89767d5fbb600eed61e726L20-R14): Updated the API key requirement message to reflect the use of `ANTHROPIC_API_KEY` instead of `OPENAI_API_KEY`.
* [`src/frontend/tests/core/integrations/Custom …
=> test: Update API key requirements and test configurations for frontend tests (fix nightly)

src/backend/base/langflow/components/git/__init__.py, src/backend/base/langflow/components/git/gitextractor.py
This pull request introduces a new component called `GitExtractorComponent` to the `langflow` project, for analyzing Git repositories.
Features:
- Repository Info: Extracts branch, remotes, and commit details
- Statistics: Calculates file counts, sizes, and line numbers
- Directory Structure: Generates complete folder tree
- File Content: Extracts text files with binary handling
- Memory Safe: Implements content truncation for large repos
- Error Handling: Graceful error recovery and resource cleanup
The `GitExtractorComponent` is designed to analyze a Git repository and provide various information and file contents. Additionally, the `__init__.py` file has been updated to include this new component.
New component addition:
* [`src/backend/base/langflow/components/git/gitextractor.py`](dif …
=> feat: add GitExtractor component

src/frontend/src/App.css, src/frontend/src/CustomNodes/GenericNode/index.tsx
This pull request includes a small change to the `src/frontend/src/App.css` file. The change modifies the width property of `.react-flow__node` to use `fit-content` with an `!important` flag, ensuring that the width fits the content within the node.
* [`src/frontend/src/App.css`](diffhunk://#diff-3e7904848c381eb53375a14db869438235df15b6e439845f23d09b12382c0d47L22-R22): Changed the `.react-flow__node` width property from `auto` to `fit-content !important`.
=> fix: adjust GenericNode width to fit component wrapper

src/backend/base/langflow/components/processing/__init__.py, src/backend/base/langflow/components/processing/llm_router.py
This PR adds a new LLM Router component that intelligently routes queries to the most appropriate language model based on OpenRouter specifications and task requirements.
- Automatic model specification fetching from OpenRouter API
- Dynamic model selection based on task complexity and requirements
- Multiple optimization modes (quality, speed, cost, balanced)
- Robust error handling with fallback mechanisms
1. Connect multiple LLM models to the router
2. Add a judge LLM for selection
3. Provide input message
4. Select optimization preference
5. Router will automatically select and use the most appropriate model
=> feat: add LLM Router component using OpenRouter specs

src/backend/base/langflow/components/nvidia/nvidia_rerank.py
This pull request refactors the NvidiaRerankComponent by removing an unused legacy flag, renaming the output from 'search_results' to 'reranked_documents', and eliminating the base_retriever output. Additionally, it updates the document handling to utilize the new Data model, ensuring type safety and consistency. These changes enhance the clarity, maintainability, and functionality of the component.
Fixes #5734 
Thanks @brian-ogrady!
Co-authored-by: @brian-ogrady
=> feat: make NvidiaRerankComponent work with search_results

src/backend/base/langflow/initial_setup/starter_projects/Instagram Copywriter.json, src/backend/base/langflow/initial_setup/starter_projects/Market Research.json, src/backend/base/langflow/initial_setup/starter_projects/SaaS Pricing.json, src/backend/base/langflow/initial_setup/starter_projects/Simple Agent.json, src/backend/base/langflow/initial_setup/starter_projects/Vector Store RAG.json
This pull request includes updates to several starter project JSON files in the `src/backend/base/langflow/initial_setup/starter_projects` directory. The changes primarily involve updating metadata and adding new fields to improve the configuration of these projects.
Metadata updates:
* [`src/backend/base/langflow/initial_setup/starter_projects/Instagram Copywriter.json`](diffhunk://#diff-5d6ded6e79298fe0d8d3e046b0fa85a89fec1f78154eb80b39acc5bdd1bb42baL3164-R3174): Updated the `id`, `last_tested_version`, `name`, and added `gradient`, `icon`, and `tags` fields.
* [`src/backend/base/langflow/initial_setup/starter_projects/Market Research.json`](diffhunk://#diff-633ea36314515f61aad893da1d70ebba0cecf77783d084343b43ca94c0e1849aL2556-R2565): Updated the `id`, `last_tested_version`, `name`, and …
=> fix: restore template tags and correct names (nightly fix)

.github/workflows/python_test.yml
This PR increases the verbosity of the backend unit tests output by adding the -vv parameter. This change provides more detailed information during test execution, making it easier to debug and analyze test results.
=> ci: adds verbosity to the backend unit tests output

src/backend/base/langflow/components/helpers/current_date.py
This component is used as a default tool in the agent component. Since the agent was able to select the time zone it desired, if you asked about a location that wasn't in this list the agent would error out.
Python includes access to the tzdb database through zoneinfo and that has a full list of available zones.
=> feat: use all available time zone names in CurrentDateComponent

src/backend/base/langflow/schema/data.py
This pull request enhances the datetime serialization process by ensuring that timezone information is included. The custom serializer now converts datetime objects to UTC before formatting them, providing a more accurate representation of date and time.
=> fix: update datetime serialization to include timezone information

src/backend/base/langflow/services/telemetry/service.py
Logging this as exception causes a huge error message when running Langflow offline.
=> fix: change telemetry logging level from exception to error

src/backend/base/langflow/base/tools/component_tool.py
This pull request includes a change to the `get_tools` method in the `src/backend/base/langflow/base/tools/component_tool.py` file. The change ensures that a component's name is properly formatted by using either `component.name` or `component.display_name` if available, and then stripping any trailing period.
* [`src/backend/base/langflow/base/tools/component_tool.py`](diffhunk://#diff-e6b607a8c5e404d2d308314cf694b33701ebcd21f8d564b6932c522d3a5e02cbL213-R214): Updated the `name` variable assignment to use `component.name` or `component.display_name` and strip any trailing period.
This was noted as bug. Leading to cause None in Tool name
=> fix: tool name in component toolkit if the name of the component is None

src/frontend/src/components/core/parameterRenderComponent/components/tableComponent/index.tsx
This pull request includes a small change to the `TableComponent` in the `src/frontend/src/components/core/parameterRenderComponent/components/tableComponent/index.tsx` file. The change ensures that the `getSelectedRows` method is safely accessed using optional chaining.
* [`src/frontend/src/components/core/parameterRenderComponent/components/tableComponent/index.tsx`](diffhunk://#diff-f3fcb59cd5fd40bf313028ede0595abb9ebe326e02946ecaece08678d8ea212fL226-R226): Modified the `hasSelection` prop to use optional chaining for the `getSelectedRows` method.
#5447
=> fix: Add optional chaining for getSelectedRows in TableComponent

src/backend/tests/performance/test_server_init.py
This pull request removes redundant `@pytest.mark.benchmark` decorators from several performance test functions in `test_server_init.py`. This streamlines the test suite while ensuring that the integrity of the tests is maintained. The changes enhance readability and maintainability of the test code.
=> tests: Remove unnecessary benchmark markers from server init tests

src/backend/base/langflow/base/tools/constants.py
This pull request removes the "commands" field from the TOOL_TABLE_SCHEMA. The "commands" field was previously used to add commands to the tool, but it is no longer needed. This change simplifies the TOOL_TABLE_SCHEMA and improves the overall code structure.
=> refactor: Remove "commands" field from TOOL_TABLE_SCHEMA

uv.lock
Codeflash had a breaking change recently with some upgrades.
This PR cleanly upgrades codeflash version in the lock file to get the CI time code optimization working again.
=> chore(deps): Upgrade codeflash - fix CI time crash

src/backend/base/langflow/main.py
The RFC 7578 spec for multipart/form-data requests [does not require the body of a request to end with a CRLF](https://www.rfc-editor.org/rfc/rfc7578#page-4), only that each section begins with a CRLF. While many clients implement multipart requests with the trailing CRLF, the implementation for fetch in Node.js version 22 and below does not.
This caused my a good number of hours debugging!
It does turn out that in September 2024 the Node.js fetch implementation [added the CRLF](https://github.com/nodejs/undici/pull/3625), though this hasn't made it to a Node.js release yet.
This change allows the boundary to end with a CRLF or not, as long as the boundary is followed by the end of the request body.
=> fix: allow multipart/form-data boundary to end with a newline

src/backend/tests/base.py, src/backend/tests/unit/api/v1/test_endpoints.py, src/backend/tests/unit/test_messages.py
This pull request updates the test suite to utilize asynchronous methods, enhancing reliability and performance. Key changes include modifying the `ComponentTestBase` to manage output processing during tests, updating various test methods to await asynchronous calls, and streamlining the structure for better clarity. These improvements ensure that tests handle message storage and retrieval correctly while maintaining a clean and efficient codebase.
=> fix: make sure tests run async 

src/backend/base/langflow/services/tracing/service.py, src/backend/tests/unit/components/agents/test_agent_component.py
This pull request enhances the initialization logic of the TracingService by modifying the `start` method to allow the service to start even when deactivated. Additionally, it introduces an early return in the `initialize_tracers` method if the service is deactivated, which prevents unnecessary initialization calls. These changes streamline the service's startup process and ensure that the deactivated state is respected during tracer initialization.
=> fix: Improve TracingService initialization logic around `deactivated`

.env.example, src/backend/base/langflow/services/database/service.py, src/backend/base/langflow/services/database/utils.py, src/backend/base/langflow/services/settings/base.py
DSLFv2 spins up a knative service running a langflow pod that immediately attempts to start in tandem while the database manager creates the appropriate tenant in the postgresql schema. Pods must give the database services time to create the tenant; this PR adds a short (and optional) retry on startup.
=> feat: add retry on database connection

src/frontend/src/components/ui/refreshButton.tsx, src/frontend/tests/core/features/freeze-path.spec.ts, src/frontend/tests/core/integrations/Vector Store.spec.ts, src/frontend/tests/core/regression/generalBugs-shard-9.spec.ts, src/frontend/tests/extended/regression/generalBugs-shard-3.spec.ts
This pull request includes updates to test files to correct the `data-testid` attributes used for element selection. These changes ensure that the tests correctly identify and interact with the elements.
Changes to test files:
* [`src/frontend/tests/core/regression/generalBugs-shard-9.spec.ts`](diffhunk://#diff-f52c0e7362d42e8988c86f3f0b14db1e98d9d096e879e7677b5d134c0fd22b8dL98-R98): Updated the `data-testid` attribute from `handle-memory-shownode-text-right` to `handle-memory-shownode-message-right` for selecting the chat memory output element.
* [`src/frontend/tests/extended/regression/generalBugs-shard-3.spec.ts`](diffhunk://#diff-c61d7345b8378427eeb622d524db04463e36b6e63e156b6f2e6d30b0b76ab473L112-R112): Updated the `data-testid` attribute from `handle-openaimodel-shownode-text-right` …
=> test: update data-testid attributes for chat memory and OpenAI model elements

.github/workflows/store_pytest_durations.yml
This pull request introduces a new step in the GitHub Actions workflow that automatically closes any open pull requests titled "chore: update test durations" before creating a new one. This enhancement ensures that only one pull request for updating test durations is active at a time, streamlining the workflow and minimizing potential merge conflicts.
=> ci: Automatically close existing PRs for test duration updates

docker/build_and_push.Dockerfile, docker/build_and_push_base.Dockerfile, docker/build_and_push_ep.Dockerfile, docker/dev.Dockerfile
We were having issues with the `GitLoader` component, throwing following error:
```
Could not import git python package. Please install it with `pip install GitPython`.
```
Looking into this, it was due to the missing Git binary.
I noticed that the git binary was added in https://github.com/langflow-ai/langflow/pull/5040, but only in the builder step, not in the runtime step.
This PR adds the binary in the runtime step so it can be used by e.g. the `GitLoader` component
=> fix: add the git binary to the final step of the container images

README.FR.md
I noticed that the word "Tout" was used incorrectly in the text. It should be "Tous" since "liens" is plural, and the article needs to match the plural form.
=> docs: Fix incorrect article form in French text Update README.FR.md

src/backend/base/langflow/components/tools/__init__.py, src/backend/base/langflow/components/tools/wikipedia.py, src/backend/base/langflow/components/tools/wikipedia_api.py, src/backend/tests/unit/components/tools/test_wikipedia_api.py
fixes depreciation in: https://github.com/langflow-ai/langflow/pull/5432
This pull request introduces a new `WikipediaComponent` and deprecates the existing `WikipediaAPIComponent`. The changes include adding the new component, updating the initialization and usage of the components, and modifying the test cases to reflect these updates.
New Component Addition:
* Added `WikipediaComponent` to `src/backend/base/langflow/components/tools/__init__.py` and included it in the list of components. [[1]](diffhunk://#diff-978762db35f605246f0bf595f91cfb0ff502fa74a15603d70ea3f6902f009175R28) [[2]](diffhunk://#diff-978762db35f605246f0bf595f91cfb0ff502fa74a15603d70ea3f6902f009175R66)
* Implemented `WikipediaComponent` in `src/backend/base/langflow/components/tools/wikipedia.py`, including methods for …
=> feat: adds Wikipedia Component and deprecates the wikipedia API tool component

src/backend/base/langflow/services/database/service.py
This pull request includes changes to the `src/backend/base/langflow/services/database/service.py` file to avoid accidental rollbacks.
Improvements to error handling:
* [`src/backend/base/langflow/services/database/service.py`](diffhunk://#diff-5080dfd112519bcd08d066dc693e4fd6bda43febd06ca96998952413871e1677R151-R155): Modified the `with_session` method to handle `SQLAlchemyError` specifically and log the error message. This change ensures that database-related errors are caught and logged appropriately.
Codebase enhancement:
* [`src/backend/base/langflow/services/database/service.py`](diffhunk://#diff-5080dfd112519bcd08d066dc693e4fd6bda43febd06ca96998952413871e1677L17-R17): Added the `exc` import from `sqlalchemy` to support the improved error handling in the `with_session` method.
=> fix: make `with_session` rollback only on SQLAlchemy errors

src/backend/base/langflow/graph/graph/utils.py, src/backend/tests/unit/graph/graph/test_utils.py
this pr adds a test for sorting the graph correctly when there are multiple subgraphs on the flow and fix the sorting algorythm
=> Fix: update initial graph sort for disconnected graph

src/backend/base/langflow/field_typing/constants.py, src/backend/base/langflow/utils/validate.py
This pull request introduces the `DEFAULT_IMPORT_STRING` into the dynamic class creation process, enhancing import management. Additionally, the unused `get_default_imports` function has been removed to streamline the codebase. The `prepare_global_scope` function has also been updated to improve import handling, ensuring a more efficient and cleaner implementation.
This fixes `NameError` being raised due to custom Components not having the imports injected into them anymore since #5733.
=> fix: Incorporate DEFAULT_IMPORT_STRING for dynamic class creation and clean up unused function

src/backend/base/langflow/api/v1/endpoints.py, src/backend/base/langflow/template/utils.py
This pull request addresses issues with the tool mode handling in the frontend node updates. It corrects the parameter name in the `update_frontend_node_with_template_values` function and enhances the logic to ensure that the tool mode is accurately retrieved and validated. Additionally, the conditions for setting the tool mode have been refined to improve its accuracy based on the template values provided. These changes collectively enhance the functionality and reliability of the custom component endpoint.
=> fix: make sure tool mode is not lost on component validation

src/backend/base/langflow/services/database/models/message/model.py
This pull request modifies the MessageTable model to ensure that string timestamps are correctly converted to UTC. A new check has been added to handle string inputs, ensuring they are parsed and adjusted to UTC before formatting. This change enhances the consistency and reliability of timestamp handling in the application.
=> fix: ensure string timestamps are converted to UTC in MessageTable model

src/backend/base/langflow/template/utils.py
This PR corrects the retrieval of tool modes in the `update_frontend_node_with_template_values` function by ensuring that the tool modes are computed from the `frontend_node` instead of the `raw_frontend_node`. This change improves the accuracy of the template updates in the frontend.
=> fix: Fix tool mode retrieval in frontend node template update

src/backend/base/langflow/api/v1/chat.py, src/backend/base/langflow/graph/vertex/base.py, src/backend/base/langflow/graph/vertex/vertex_types.py
When running a Loop flow, more than one task to log_transaction would be added, causing `database is locked` error. This makes sure and outstanding tasks in the vertex are awaited before adding new ones.
=> fix: improve task management in _log_transaction_async to avoid database locks

docs/package-lock.json, docs/package.json, docs/yarn.lock
This pull request includes updates to the dependencies and resolutions in the `docs/package.json` file. The most important changes are the updates to various `@docusaurus` packages and the addition of resolutions for the `lodash` package.
* Updated `@docusaurus/core`, `@docusaurus/plugin-client-redirects`, `@docusaurus/plugin-google-tag-manager`, and `@docusaurus/preset-classic` from version `3.5.2` to `^3.7.0`.
* Updated `docusaurus-plugin-openapi`, `docusaurus-plugin-openapi-docs`, `docusaurus-preset-openapi`, and `docusaurus-theme-openapi-docs` to newer versions.
* Updated `@docusaurus/module-type-aliases` from version `3.5.2` to `^3.7.0`.
Resolutions:
* Added resolutions for `lodash` to ensure consistent versions across dependencies.
=> chore: Update Docusaurus and OpenAPI dependencies to latest versions

.github/workflows/integration_tests.yml, .github/workflows/python_test.yml, .github/workflows/release.yml
This pull request updates the default Python versions in the CI workflows by removing Python 3.13 from the integration_tests.yml, python_test.yml, and release.yml files. This change ensures compatibility and reduces testing overhead, streamlining the CI process.
=> ci: Update Python version defaults in CI workflows

.github/workflows/integration_tests.yml, .github/workflows/lint-py.yml, .github/workflows/python_test.yml, .github/workflows/release.yml, pyproject.toml, src/backend/base/pyproject.toml, uv.lock
This pull request updates the CI workflows and project metadata to remove Python 3.13 from the testing matrix, ensuring compatibility with Python versions 3.10 and 3.12. The version numbers in the project metadata have been incremented, and unnecessary whitespace has been cleaned up for better readability. Additionally, dependencies have been organized and updated to streamline the project. This change aims to enhance the overall compatibility and efficiency of the CI process.
=> chore: bump langflow and langflow-base

src/backend/base/langflow/api/router.py, src/backend/base/langflow/api/v1/mcp.py, src/backend/base/langflow/components/logic/run_flow.py, src/backend/base/langflow/main.py
This PR removes the inclusion of mcp_router from the global context in router.py. The previous implementation caused issues by executing code before the settings service was fully initialized.
=> fix: env-file loading

src/frontend/src/style/index.css, src/frontend/src/utils/styleUtils.ts
This pull request includes updates to the `src/frontend/src/utils/styleUtils.ts` file to add color mappings for the `AgentExecutor` node.
Changes to color mappings:
* [`src/frontend/src/utils/styleUtils.ts`](diffhunk://#diff-ce70511ff4131ac5078d799cd2295f98874bad89bcde4732f33c967c1bbc71f2R435): Added `AgentExecutor` to the `nodeColors` object with the color `#903BBE`.
* [`src/frontend/src/utils/styleUtils.ts`](diffhunk://#diff-ce70511ff4131ac5078d799cd2295f98874bad89bcde4732f33c967c1bbc71f2R484): Added `AgentExecutor` to the `nodeColorsName` object with the color name `purple`.
=> fix: fixes AgentExecutor handle greyed out 

src/backend/base/langflow/components/nvidia/nvidia_rerank.py
=> fix: remove reference to a non-existent method in NvidiaRerankComponent

src/backend/base/langflow/utils/validate.py, src/backend/tests/unit/test_validate_code.py
Enhance the import mechanism to allow modules that are not explicitly included in __init__.py files to be importable by attempting to access them as attributes first, and falling back to importing the full module path if necessary.
=> fix: Ensure importability of modules not included in __init__.py files

src/frontend/src/utils/utils.ts
This pull request includes changes to improve the robustness and reliability of utility functions in `src/frontend/src/utils/utils.ts`. The modifications focus on enhancing the handling of edge cases and ensuring that the functions return consistent boolean values.
Improvements to utility functions:
* [`logHasMessage`](diffhunk://#diff-b6539a7271a3a6e713a0745ccd15aea9fde0cc556a866fe09cfd7e552dc2bf81L463-R498): Enhanced the function to handle cases where `outputName` is not provided or `data.outputs` is undefined, ensuring it returns `false` in these scenarios. Improved the logic to check for the presence of messages more reliably.
* [`logTypeIsUnknown`](diffhunk://#diff-b6539a7271a3a6e713a0745ccd15aea9fde0cc556a866fe09cfd7e552dc2bf81L463-R498): Updated the function to return `false` if …
=> fix: handle undefined data.outputs and outputName params in log utility functions

src/backend/base/langflow/components/vectorstores/astradb.py, src/backend/base/langflow/initial_setup/starter_projects/Vector Store RAG.json
This pull request enables a combobox in the collection dropdown, which will allow a user to create a non-vectorize collection directly through langflow if desired.
=> fix: Allow basic Astra DB Collection creation in combobox

src/backend/base/langflow/load/load.py
In https://github.com/langflow-ai/langflow/pull/5057 `load_flow_from_json` was made async, and the needed logic changes were added.
One of the changes is that the file is now loaded as string, instead of being a file object.
Therefore the way of loading also needs to change, from [`json.load`](https://docs.python.org/3/library/json.html#json.load) to [`json.loads`](https://docs.python.org/3/library/json.html#json.loads)
This is not the case, and an error is thrown.
```
File "/app/.venv/lib/python3.12/site-packages/langflow/load/load.py", line 61, in aload_flow_from_json
flow_graph = json.load(content)
^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/json/__init__.py", line 293, in load
return loads(fp.read(),
^^^^^^^
AttributeError: 'str' object has no attribute 'read'
```
This PR …
=> fix: use correct json load method when loading flow from file

src/backend/base/langflow/services/database/service.py
Convert the table check method to async to improve performance and responsiveness in the database service.
=> fix: add missing await to table check 

docs/docs/Components/components-models.md
This pull request includes an update to the documentation for the `Components` section, specifically adding a new component for DeepSeek's language models.
New component addition:
* [`docs/docs/Components/components-models.md`](diffhunk://#diff-502420bd2808776928ead369ad2bc99416da0a5a5d58520b8ba58819e66aebc8R134-R158): Added a new section for the DeepSeek component, detailing its inputs and outputs, including parameters such as `max_tokens`, `model_name`, and `api_key`.
=> docs: add DeepSeek component documentation with inputs and outputs

src/backend/base/langflow/components/tools/astradb.py, src/backend/base/langflow/components/tools/astradb_cql.py
This pull request updates the return format of the Astra DB Tool and CQL Tool components to return a Tool object, making them compatible with other Langflow components.
=> fix: return a standard tool for each Astra DB Tool component

src/backend/base/langflow/base/agents/agent.py, src/backend/base/langflow/components/langchain_utilities/csv_agent.py
This pull request includes changes to the `Output` configuration in the `LCAgentComponent` and `CSVAgentComponent` classes to improve the visibility settings of the `Agent` output.
Visibility settings update:
* [`src/backend/base/langflow/base/agents/agent.py`](diffhunk://#diff-87ba96f91b4bbce3350ae83d5d4c7dfa3a7c800deeed21a60857dff1caaefe04L72-R72): Modified the `Output` for `Agent` in `LCAgentComponent` to include `hidden=True`.
* [`src/backend/base/langflow/components/langchain_utilities/csv_agent.py`](diffhunk://#diff-c168846face60946ac035d0572d1f85c58c8e1e7fdd66ab6629df235adc22304L59-R59): Modified the `Output` for `Agent` in `CSVAgentComponent` to include `hidden=True`.
=> fix: Hides agent executor output in components

src/backend/base/langflow/components/processing/update_data.py, src/frontend/src/CustomNodes/GenericNode/components/NodeStatus/index.tsx
This pull request includes a change to the `UpdateDataComponent` class in `src/backend/base/langflow/components/processing/update_data.py`. The change ensures that the `Data` field is marked as required.
* [`src/backend/base/langflow/components/processing/update_data.py`](diffhunk://#diff-050cb4102347879d1fece343bacd8b4dd1e3afcb0038fc38deb6588f7e34055dR30): Added the `required=True` attribute to the `Data` field in the `UpdateDataComponent` class to ensure that data is mandatory.
This component needs a data component connected to him to run.
=> feat: Data field required in UpdateDataComponent

src/backend/base/langflow/services/auth/utils.py
This pull request enhances the error logging for JWT validation failures by providing more specific debug messages. Instead of a generic error message, it now logs a detailed message indicating whether the failure was due to an invalid token format or signature, which will aid in debugging authentication issues more effectively.
=> refactor: Improve JWT error logging for better debugging of authentication issues

.github/workflows/store_pytest_durations.yml
Change the schedule for the pytest durations workflow to execute every Monday at 6:30 UTC.
=> ci: Update pytest durations workflow schedule to run weekly on Monday

src/backend/base/langflow/__main__.py, src/backend/base/langflow/services/telemetry/service.py, src/backend/base/langflow/utils/version.py
Enhance the robustness of API requests by adding comprehensive error handling and logging mechanisms. This change aims to provide clearer feedback during failures and improve overall user experience.
=> fix: Improve error handling at startup

src/frontend/package-lock.json, src/frontend/src/icons/Novita/index.tsx, src/frontend/src/icons/Novita/novita.jsx, src/frontend/src/icons/Novita/novita.svg
This pull request includes updates to the `Novita` icon component and its associated SVG file, as well as a minor change to the `package-lock.json` file. The most important changes involve adding dark mode support to the `NovitaIcon` component and modifying the SVG properties for better scalability and styling.
Changes to `Novita` icon component:
* [`src/frontend/src/icons/Novita/index.tsx`](diffhunk://#diff-4da4fd3af5c922d4126bf08d3a3957f27b1b16422d84b3241666a4ad7338ae98R1-R11): Added import of `useDarkStore` and updated the `NovitaIcon` component to pass the `isdark` prop to `SvgNovita`.
Changes to `Novita` SVG file:
* [`src/frontend/src/icons/Novita/novita.jsx`](diffhunk://#diff-92312211df0f2ae70ecdf1cae8751d8c8c1d06139f2efb936dfe23997552f00cL3-R14): Updated the SVG properties …
=> fix: add correct size properties to novitaAI icon

docs/docs/Deployment/deployment-gcp.md
This pull request includes a change to the `docs/docs/Deployment/deployment-gcp.md` file, which simplifies the pricing section by removing the detailed cost table and associated notes.
Also, the deployment script still works.
=> docs: Update GCP deployment documentation to clarify pricing details

src/backend/base/langflow/custom/custom_component/component.py, src/backend/base/langflow/schema/artifact.py
This pull request includes several changes to improve the handling and processing of artifacts in the backend. The most important changes involve modifying the logic for determining the artifact type, updating the raw result processing, and refactoring the post-processing of raw data.
Improvements to artifact type determination and raw result processing:
* [`src/backend/base/langflow/custom/custom_component/component.py`](diffhunk://#diff-22fd745de33f20981c7cbcbf3c91d4a6f8719de20761eb22cf42f8ed6ec50169L960-R972): Modified the `_build_artifact` method to correctly prioritize `raw` over `status` when determining the artifact type. Updated the `_process_raw_result` method to check for `status` after other conditions, ensuring proper handling of raw results.
Refactoring of post-processing …
=> refactor: improve artifact type handling and result processing

src/backend/base/langflow/api/v1/chat.py
This pull request marks several vertex-related endpoints in the API as deprecated. This change is intended to signal to users that these endpoints will be phased out in future releases, allowing for a smoother transition to alternative solutions. The affected endpoints include those for retrieving vertices order, building a vertex, and streaming vertex data.
=> chore: Mark internal vertex-related endpoints as deprecated

.github/changes-filter.yaml, src/backend/base/langflow/custom/custom_component/component.py
This pull request includes changes to the `components` section in the `.github/changes-filter.yaml` file and modifications to the `_build_artifact` method in the `component.py` file. The changes focus on adding a new directory to the components list and improving the logic for processing raw results and determining artifact types in the backend.
* [`.github/changes-filter.yaml`](diffhunk://#diff-1b2ef07bf2b24cfe900fb2d2b36e0ca604e96b38cd48e00c82d21d64a9c06697R48): Added the `src/backend/base/langflow/custom/**` directory to the `components` section to ensure changes in this directory are tracked appropriately.
* [`src/backend/base/langflow/custom/custom_component/component.py`](diffhunk://#diff-22fd745de33f20981c7cbcbf3c91d4a6f8719de20761eb22cf42f8ed6ec50169L960-L972): Modified the …
=> revert: update components filter and build artifact logic

src/backend/tests/unit/api/v1/test_endpoints.py, src/backend/tests/unit/test_custom_component.py
With this, the concerned tests can be launched from PyCharm's editor.
=> fix: Use relative paths for data files in unit tests

src/frontend/src/modals/apiModal/utils/get-widget-code.tsx
src attribute has extra double quotes
=> fix: Correct widget code URL

src/backend/base/langflow/components/vectorstores/clickhouse.py
A problem was reported regarding an unsuccessful connection attempt to clickhouse. After some analysis I found out that the problem was the lack of port information in the connection test, so the default port was used.
I also changed the advanced configuration of clickhouse as it was incorrect.
Issue: https://github.com/langflow-ai/langflow/issues/5954
=> fix: Problem checking Clickhouse connection when port is different from default

src/backend/base/langflow/base/tools/component_tool.py, src/backend/base/langflow/custom/custom_component/component.py, src/backend/base/langflow/initial_setup/starter_projects/Basic Prompt Chaining.json, src/backend/base/langflow/initial_setup/starter_projects/Basic Prompting.json, src/backend/base/langflow/initial_setup/starter_projects/Blog Writer.json, src/backend/base/langflow/initial_setup/starter_projects/Custom Component Maker.json, src/backend/base/langflow/initial_setup/starter_projects/Document Q&A.json, src/backend/base/langflow/initial_setup/starter_projects/Graph Vector Store RAG.json, src/backend/base/langflow/initial_setup/starter_projects/Image Sentiment Analysis.json, src/backend/base/langflow/initial_setup/starter_projects/Instagram Copywriter.json, src/backend/base/langflow/initial_setup/starter_projects/Market Research.json, src/backend/base/langflow/initial_setup/starter_projects/Memory Chatbot.json, src/backend/base/langflow/initial_setup/starter_projects/Research Agent.json, src/backend/base/langflow/initial_setup/starter_projects/SEO Keyword Generator.json, src/backend/base/langflow/initial_setup/starter_projects/SaaS Pricing.json, src/backend/base/langflow/initial_setup/starter_projects/Sequential Tasks Agents .json, src/backend/base/langflow/initial_setup/starter_projects/Simple Agent.json, src/backend/base/langflow/initial_setup/starter_projects/Travel Planning Agents.json, src/backend/base/langflow/initial_setup/starter_projects/Twitter Thread Generator.json, src/backend/base/langflow/initial_setup/starter_projects/Vector Store RAG.json, src/backend/base/langflow/template/field/base.py, src/backend/tests/unit/test_schema.py
Introduce a `tool_mode` field in the Output model to specify tool usage. Implement a method in `ComponentToolkit` to determine if an output should be skipped based on its properties.
=> feat: Add tool_mode to Output model and add it to the skip output check

docs/css/custom.css
This pull request includes changes to the `docs/css/custom.css` file to enhance the handling and display of images within markdown content.
=> fix: size-down-docs-images

src/backend/base/langflow/components/tools/duck_duck_go_search_run.py
This pull request makes significant changes to the `src/backend/base/langflow/components/tools/duck_duck_go_search_run.py` file. The changes include a major refactor of the `DuckDuckGoSearchComponent` class, transitioning from the `LCToolComponent` base class to the `Component` base class, and updating the methods and properties to align with the new structure.
Refactor and updates to `DuckDuckGoSearchComponent`:
* Changed base class from `LCToolComponent` to `Component`, and updated imports accordingly.
* Updated properties such as `display_name`, `description`, `documentation`, and `icon` to match the new class structure.
* Modified input definitions to include additional metadata like `required`, `info`, and `tool_mode`.
* Added `outputs` property to define the output methods …
=> fix: refactor DuckDuckGo search component to use new Component base class (nightly fix)

src/frontend/package-lock.json, src/frontend/tests/extended/integrations/duckduckgo.spec.ts
This pull request includes several changes to the `src/frontend` directory, focusing on updating dependencies and improving the test suite for DuckDuckGo integration. Below are the most important changes:
* [`src/frontend/package-lock.json`](diffhunk://#diff-9eaa8c31e85b60ae25c139f2d6363cc9dcb6926125b5bf1d0cac092547e8cfcbL839): Removed the "extraneous" flag from the `@clack/prompts` package to ensure proper dependency management.
Improvements to DuckDuckGo integration tests:
* [`src/frontend/tests/extended/integrations/duckduckgo.spec.ts`](diffhunk://#diff-4adeafe8432cd447af72a709cfd02bf951cabc4df1e40abb0ca6b725b98e9ae8L14-R26): Updated the selector for waiting for the DuckDuckGo search tool to use `data-testid` instead of an XPath expression, improving test …
=> tests: update DuckDuckGo test selectors

src/frontend/package-lock.json, src/frontend/src/pages/FlowPage/components/PageComponent/index.tsx
This pull request includes a few changes to the `src/frontend` package. The changes involve a minor update to the `package-lock.json` file and an enhancement to the `PageComponent` in the `FlowPage` component.
Enhancements to `FlowPage` component:
* [`src/frontend/src/pages/FlowPage/components/PageComponent/index.tsx`](diffhunk://#diff-58f6af33afc15c24e3df56ce2169081e35e5fe005f6281ebc5d7156b2eaa7d0eR554): Added the `elevateEdgesOnSelect` property set to `true` to enhance the user interaction experience with the flow page.
Minor update to package configuration:
* [`src/frontend/package-lock.json`](diffhunk://#diff-9eaa8c31e85b60ae25c139f2d6363cc9dcb6926125b5bf1d0cac092547e8cfcbL839): Removed the `extraneous` property from the `@clack/prompts/node_modules/is-unicode-supported` dependency.
=> fix: elevate edges on select

src/backend/base/langflow/initial_setup/setup.py
Improve the profile picture copying process by optimizing I/O operations and implementing better error handling. The changes include asynchronous bulk copying and checks to avoid redundant file operations.
=> refactor: Enhance profile picture copying with optimized I/O and error handling

pyproject.toml, src/backend/base/pyproject.toml
Update the version numbers for both langflow and langflow-base to reflect the latest release.
=> chore: Bump version to 1.1.4 for langflow and 0.1.4 for langflow-base

src/backend/base/langflow/components/models/openai.py, src/backend/base/langflow/initial_setup/starter_projects/Basic Prompt Chaining.json, src/backend/base/langflow/initial_setup/starter_projects/Basic Prompting.json, src/backend/base/langflow/initial_setup/starter_projects/Blog Writer.json, src/backend/base/langflow/initial_setup/starter_projects/Document Q&A.json, src/backend/base/langflow/initial_setup/starter_projects/Graph Vector Store RAG.json, src/backend/base/langflow/initial_setup/starter_projects/Image Sentiment Analysis.json, src/backend/base/langflow/initial_setup/starter_projects/Instagram Copywriter.json, src/backend/base/langflow/initial_setup/starter_projects/Market Research.json, src/backend/base/langflow/initial_setup/starter_projects/Memory Chatbot.json, src/backend/base/langflow/initial_setup/starter_projects/Research Agent.json, src/backend/base/langflow/initial_setup/starter_projects/SEO Keyword Generator.json, src/backend/base/langflow/initial_setup/starter_projects/SaaS Pricing.json, src/backend/base/langflow/initial_setup/starter_projects/Sequential Tasks Agents .json, src/backend/base/langflow/initial_setup/starter_projects/Simple Agent.json, src/backend/base/langflow/initial_setup/starter_projects/Travel Planning Agents.json, src/backend/base/langflow/initial_setup/starter_projects/Twitter Thread Generator.json, src/backend/base/langflow/initial_setup/starter_projects/Vector Store RAG.json
This pull request introduces new configuration options for the OpenAI model component and updates the initial setup for the Basic Prompt Chaining project. The most important changes include adding new input fields for `max_retries` and `timeout`, and integrating these fields into the model building process.
max retries set to 700, since default open ai value is 600 (set above the default to prevent further errors of remote protocol error.)
Enhancements to OpenAI model configuration:
* [`src/backend/base/langflow/components/models/openai.py`](diffhunk://#diff-315722d3776898e43e8f0e24de9a20f816f2b2fd5ada9fe5e4180ce3eb262206R71-R84): Added `max_retries` and `timeout` as new `IntInput` fields to the `OpenAIModelComponent` class. These fields are used to set the maximum number of retries and …
=> feat: add max retry and request timeout to open ai component, fixes remote protocol error caused by OpenAI LLM in Agents

src/backend/base/langflow/graph/schema.py, src/backend/base/langflow/graph/vertex/vertex_types.py
This pull request includes a small change to the `src/backend/base/langflow/graph/schema.py` file. The change removes the `InterfaceComponentTypes.TextInput` from the `INPUT_COMPONENTS` list.
* [`src/backend/base/langflow/graph/schema.py`](diffhunk://#diff-18ff9d04e38afcbd589463290cf6aa93e8faed272efcc544c59b71f9f8e86edaL64): Removed `InterfaceComponentTypes.TextInput` from the `INPUT_COMPONENTS` list.
=> Refactor: Simplify Vertex Queue Initialization by Removing is_input_vertex Dependency

src/backend/base/langflow/graph/vertex/base.py
Ensure that file path input is correctly processed as a list when dealing with list-type fields in the Vertex class.
=> fix: ensure file path is list before iterating over it

pyproject.toml, src/backend/base/langflow/services/variable/service.py, src/backend/base/pyproject.toml, uv.lock
Enhance error handling for variable decryption in `DatabaseVariableService`, ensuring failures are logged and original values are retained. Update package versions for `langflow` and `langflow-base`.
=> fix: Improve variable decryption error handling

pyproject.toml, src/backend/base/pyproject.toml, uv.lock
Update version numbers for langflow and langflow-base in their respective configuration files.
This is so the Nightly Build finds a valid version. This also improves the nightly versions because now a nightly will reference a version that is not released yet.
=> chore: Bump version to 1.1.5 for langflow and 0.1.5 for langflow-base

src/backend/base/langflow/base/data/base_file.py
Modify file extension validation to ensure consistent handling of extensions by using lowercase comparison.
=> fix: make extension check case-insensitive in BaseFileComponent

src/backend/base/langflow/base/tools/constants.py, src/backend/base/langflow/schema/table.py, src/frontend/src/components/core/parameterRenderComponent/components/tableComponent/index.tsx, src/frontend/src/types/utils/functions.ts, src/frontend/src/utils/utils.ts
This pull request introduces a new feature to handle hidden columns in the table components. The changes span across backend and frontend files to ensure proper handling and rendering of hidden columns.
* [`src/backend/base/langflow/base/tools/constants.py`](diffhunk://#diff-c60ffce8614e539a6fa7c3e47ac11aa7b89f15b9e09d9549c907ef15a7d33894R15): Added the `hidden` attribute to the column definitions with appropriate boolean values. [[1]](diffhunk://#diff-c60ffce8614e539a6fa7c3e47ac11aa7b89f15b9e09d9549c907ef15a7d33894R15) [[2]](diffhunk://#diff-c60ffce8614e539a6fa7c3e47ac11aa7b89f15b9e09d9549c907ef15a7d33894R25) [[3]](diffhunk://#diff-c60ffce8614e539a6fa7c3e47ac11aa7b89f15b9e09d9549c907ef15a7d33894R36)
* [`src/backend/base/langflow/schema/table.py`](diffhunk://#diff-66bd9e20d21689c7321905c0c …
=> feat: option to hide a column in frontend when defining a Table Input, hides Tool identifier from table display

src/backend/base/langflow/components/embeddings/huggingface_inference_api.py
This pull request includes several updates to the `src/backend/base/langflow/components/embeddings/huggingface_inference_api.py` file, focusing on improving the handling of API keys and local URLs for HuggingFace embeddings. The most important changes include updating the advanced setting for the API key input, expanding the list of local URLs, and modifying the default API key for local deployment.
Improvements to API key handling:
* [`class HuggingFaceInferenceAPIEmbeddingsComponent(LCEmbeddingsModel)`](diffhunk://#diff-541c702f2347658d1a1cb6bca6a4321a8c385512105750aec884c84a10b19113L24-R26): Changed the `advanced` setting for the `api_key` input from `True` to `False` to make it more accessible.
Enhancements to local URL handling:
* [`def …
=> fix: improved the huggingface emdeddings component, to handle local inference and serverless inference  

pyproject.toml, src/backend/base/langflow/components/scrapegraph/__init__.py, src/backend/base/langflow/components/scrapegraph/scrapegraph_markdownify_api.py, src/backend/base/langflow/components/scrapegraph/scrapegraph_search_api.py, src/backend/base/langflow/components/scrapegraph/scrapegraph_smart_scraper_api.py, uv.lock
Add search endpoint according to [https://docs.scrapegraphai.com/services/searchscraper](https://docs.scrapegraphai.com/services/searchscraper)
This pull request includes several updates to the `ScrapeGraph` components, including dependency updates, new API integration, and enhancements to existing APIs.
* Updated `scrapegraph-py` dependency from version `1.10.2` to `1.12.0` in `pyproject.toml`.
* Added `ScrapeGraphSearchApi` component with methods for initializing and using the ScrapeGraph search functionality.
* Modified `ScrapeGraphMarkdownifyApi` to use `MessageTextInput` for the `url` input and set `tool_mode` to `True`. [[1]](diffhunk://#diff-3abf36ce577a1ca7e4ff8ce7eeea7425cda77186afccc7a0852869744bd65565R3-L5) [[2]](diffhunk://#diff-3abf36ce577a1ca7e4ff8ce7eeea7425cda77186afccc7a08 …
=> feat: ScrapeGraph AI component updates and add new component ScrapgraphSearch API

src/frontend/src/CustomNodes/helpers/count-handles.ts
This pull request includes changes to the `countHandlesFn` function in `count-handles.ts` to improve the logic for determining handle counts based on node data. The most important changes include adding a condition to check for `tool_mode`, reordering the checks for `input_types`, and adding a new case for the `table` type.
Improvements to handle count logic:
* Added a condition to check for `tool_mode` to determine if the handle should be counted as false.
* Reordered the check for `input_types` to occur after the `show` check.
* Added a new case for the `table` type to return false in the switch statement.
=> fix: made tool_mode components minimizable

src/frontend/src/components/core/folderSidebarComponent/components/sideBarFolderButtons/components/select-options.tsx
This pull request includes a small change to the `src/frontend/src/components/core/folderSidebarComponent/components/sideBarFolderButtons/components/select-options.tsx` file. The change updates the `FolderSelectItem` component's `name` property from "Download Content" to "Download".
* [`src/frontend/src/components/core/folderSidebarComponent/components/sideBarFolderButtons/components/select-options.tsx`](diffhunk://#diff-d5ce5da31ecc0209d1b295e4cf9f4a3eadd9af8c2511a85567c9fb706e6cc033L69-R69): Updated `FolderSelectItem` component's `name` property from "Download Content" to "Download".
=> fix: changed naming for download button on sidebar nav context menu

src/frontend/src/modals/IOModal/components/chatView/chatMessage/chat-message.tsx
Eliminate the redundant lockChat condition when determining the loading state of ChatMessage.
=> fix: remove unnecessary lockChat condition in ChatMessage loading state

src/backend/base/langflow/base/compressors/model.py, src/backend/base/langflow/components/cohere/cohere_rerank.py, src/backend/base/langflow/components/nvidia/nvidia_rerank.py
Move the API key input from the base compressor model to the specific Cohere and NVIDIA Rerank components, enhancing clarity and specificity in the input handling.
=> refactor: move API key input into Cohere and NVIDIA rerank components

src/backend/base/langflow/graph/graph/base.py, src/backend/base/langflow/graph/graph/constants.py, src/backend/base/langflow/graph/graph/runnable_vertices_manager.py, src/backend/base/langflow/graph/graph/utils.py, src/backend/base/langflow/graph/vertex/base.py, src/backend/base/langflow/graph/vertex/vertex_types.py, src/backend/tests/unit/graph/graph/test_runnable_vertices_manager.py
Introduce an `is_loop` property to the Vertex class for identifying looping outputs. Improve the runnability logic in the graph traversal by updating methods to handle loop vertices more effectively and optimizing adjacency maps for better performance.
=> fix: Enhance vertex runnability logic with loop detection

src/frontend/src/components/core/parameterRenderComponent/components/tableComponent/components/TableOptions/index.tsx
This pull request includes several changes to the `TableOptions` component in the `index.tsx` file to improve the user interface by updating the styles and behavior of buttons based on their state.
Changes to button styles and behavior:
* Updated the button styles to show a "not allowed" cursor and a placeholder foreground color when there is no selection (`hasSelection`) in the table. (`src/frontend/src/components/core/parameterRenderComponent/components/tableComponent/components/TableOptions/index.tsx`)
* Modified the button styles to display a "not allowed" cursor and a placeholder foreground color when there is no selection (`hasSelection`) in the table, and to show a primary color with a hover effect when there is a selection. …
=> fix: updates color of inactive buttons on table component

src/backend/base/pyproject.toml
Modify the codeflash configuration to exclude the components directory from processing.
This is causing way too much spam PRs.
=> chore: Update codeflash config to ignore components

src/backend/tests/unit/components/data/test_url_component.py
Change the default URL in the URL component test from `https://example.com` to `https://google.com`.
=> fix: Update default URL in URL component test

src/frontend/tests/extended/features/validate-raise-errors-components.spec.ts, src/frontend/tests/utils/add-custom-component.ts
This pull request introduces a new test to validate error handling in custom components and adds a utility function to facilitate the addition of these components in tests.
New test for error handling in custom components:
* [`src/frontend/tests/extended/features/validate-raise-errors-components.spec.ts`](diffhunk://#diff-65053f5ed5f85f95eaa9a1d8f28844bc6308d187f0c8b5aceeb11054489236fcR1-R90): Added a test to ensure that users can see error messages on popups when an error is raised in a custom component. The test includes the creation of a custom component that raises a `ValueError` with a specific message.
Utility function for adding custom components:
* [`src/frontend/tests/utils/add-custom-component.ts`](diffhunk://#diff-584a6ca4ec1728b3443ebf08abdaf7e99362b7c6d776114ae590ab14dd9d27feR …
=> test: Add validation for error handling in custom components and utility function

src/backend/base/langflow/components/processing/save_to_file.py, src/backend/tests/unit/components/processing/test_save_to_file_component.py
This pull request introduces a new component for saving various types of data to files in different formats. The `SaveToFileComponent` class has been added to handle DataFrames, Data, and Messages, providing options for saving them in formats such as CSV, Excel, JSON, and Markdown.
* [`src/backend/base/langflow/components/processing/save_to_file.py`](diffhunk://#diff-9d7ce72a176300ab240d49aacccf3915cf78f288dcbb472bb60e6514e078229eR1-R163): Added the `SaveToFileComponent` class, which allows saving DataFrames, Data, or Messages to various file formats. This includes defining inputs for selecting the data type and format, and outputs for confirmation messages.
* Implemented methods `_save_dataframe`, `_save_data`, and `_save_message` to handle the saving process for …
=> feat: add SaveToFile component for DataFrame, Data and Message exports

Makefile, pyproject.toml, src/backend/base/langflow/graph/utils.py, src/backend/base/langflow/services/settings/base.py, src/backend/tests/locust/locustfile.py, uv.lock
Improve Locust load testing capabilities with dynamic configurations, error handling, and realistic simulations. Optimize database connection settings for better performance and scalability. Enhance transaction logging and add comprehensive load testing support in the Makefile.
=> chore: Enhance Locust load testing and optimize database settings

src/frontend/src/CustomEdges/index.tsx, src/frontend/src/CustomNodes/GenericNode/components/handleRenderComponent/index.tsx
This pull request includes changes to the `src/frontend/src/CustomEdges/index.tsx` and `src/frontend/src/CustomNodes/GenericNode/components/handleRenderComponent/index.tsx` files to adjust the positioning and visual effects of custom edges and nodes. The most important changes include modifying the edge positioning calculations and updating the box-shadow properties for the node handles.
* [`src/frontend/src/CustomEdges/index.tsx`](diffhunk://#diff-d3f638b710d8dafb455ca26a7829b94b29a938ee7c5ef856e52b212b46eda05fL24-R25): Adjusted the `sourceXNew` and `targetXNew` calculations by adding/subtracting 7 pixels to improve the edge alignment.
* [`src/frontend/src/CustomEdges/index.tsx`](diffhunk://#diff-d3f638b710d8dafb455ca26a7829b94b29a938ee7c5ef856e52b212b46eda05fL45-R56): Updated the …
=> fix: adjust edge position to not overlay handles on select

src/backend/base/langflow/serialization/serialization.py
This pull request includes several changes to the `src/backend/base/langflow/serialization/serialization.py` file to improve code readability by reformatting function definitions and long lines. The most important changes include reformatting function signatures and improving the readability of conditional statements.
Improvements to code readability:
* Reformatted function definitions to place parameters on separate lines for better readability. (`_serialize_document`, `_serialize_pydantic`, `_serialize_pydantic_v1`, `_serialize_list_tuple`, `_serialize_dataframe`, `_serialize_series`, `_serialize_numpy_type`, `_serialize_dispatcher`, `serialize`, `serialize_or_str`) [[1]](diffhunk://#diff-1c177d78ca092f535662dbe9830b7d50ecc3673ac797c76a041bf04a13f8970cL61-R63) …
=> fix: removed default max length for serialize function

src/backend/base/langflow/api/utils.py, src/frontend/src/pages/MainPage/components/grid/index.tsx, src/frontend/src/pages/MainPage/components/list/index.tsx
This pull request includes changes to both the backend and frontend of the application to improve the handling and display of flow data. The most important changes include updating the cascade delete functionality, modifying modal behavior based on flow types, and ensuring proper deletion warnings are displayed.
* [`src/backend/base/langflow/api/utils.py`](diffhunk://#diff-a5536abdc36b706233e33dcb6ae402b9f9721ac540978b2e8da67f79ad09aabdR21): Added import for `MessageTable` and updated the `cascade_delete_flow` function to ensure messages are deleted when a flow is deleted. [[1]](diffhunk://#diff-a5536abdc36b706233e33dcb6ae402b9f9721ac540978b2e8da67f79ad09aabdR21) [[2]](diffhunk://#diff-a5536abdc36b706233e33dcb6ae402b9f9721ac540978b2e8da67f79ad09aabdL284-R294)
* …
=> fix: Adjust flow cascade deletion and improve flow delete message UI

src/frontend/src/App.css, src/frontend/src/style/classes.css
This pull request includes changes to the CSS files to improve the styling of certain elements. The most important changes include the removal of the `overflow-y` and `max-height` properties from the `.jv-indent` class and the addition of the `overflow-y` property to the `.json-view` class.
Styling changes:
* [`src/frontend/src/App.css`](diffhunk://#diff-3e7904848c381eb53375a14db869438235df15b6e439845f23d09b12382c0d47L69-L70): Removed the `overflow-y` and `max-height` properties from the `.jv-indent` class to potentially address layout or scrolling issues.
* [`src/frontend/src/style/classes.css`](diffhunk://#diff-20389fa3f9c927b863b7941b7a81e87d4d6d8f53f049354aaf1863fa1a3ac5ebR177): Added the `overflow-y` property to the `.json-view` class to enable vertical scrolling within the element.
=> fix: fixed scroll to outer layer on json viewer

src/frontend/src/constants/constants.ts
This pull request includes a small change to the `src/frontend/src/constants/constants.ts` file. The change corrects the capitalization of the "Open Playground" display name and name in the `defaultShortcuts` array.
* [`src/frontend/src/constants/constants.ts`](diffhunk://#diff-3a3810648efc852f35a3780d6fe4ec65734c218f2281a175d9347a65db3fd360L822-R823): Corrected the capitalization of "Open Playground" in the `defaultShortcuts` array.
=> chore: fix capitalization of "Open Playground" in default shortcuts

.github/workflows/deploy_gh-pages.yml, docs/package.json, docs/yarn.lock
This pull request updates the deployment workflow for GitHub Pages in the `.github/workflows/deploy_gh-pages.yml` file. The primary change is switching the package manager from npm to yarn. This workflow currently fails because it's looking for `package-lock.json`.
Also sync dependencies.
[Build test succeeds](https://github.com/langflow-ai/langflow/actions/runs/13400849982)
=> ci: change docs build to use yarn

src/backend/base/langflow/initial_setup/starter_projects/Vector Store RAG.json
This pull request restores the default API key variable names for the Vector Store RAG template
=> fix: restore default Vector Store RAG key variables

src/backend/base/langflow/services/storage/local.py
Update the file listing method to enhance performance by utilizing asynchronous threading for directory iteration.
=> fix: use async thread in list files

.github/workflows/docker-build.yml
This pull request includes updates to the `.github/workflows/docker-build.yml` file to improve the reliability of Docker build and push actions by incorporating a retry mechanism.
Changes to Docker build and push actions:
* Replaced `docker/build-push-action@v6` with `Wandalen/wretry.action@master` to add retry capability for Docker Hub builds.
* Replaced `docker/build-push-action@v6` with `Wandalen/wretry.action@master` to add retry capability for GitHub Container Registry builds.
* Replaced `docker/build-push-action@v6` with `Wandalen/wretry.action@master` to add retry capability for matrix component builds.
=> chore: Update Docker build workflow for reliability improvements

src/frontend/src/components/ui/skeletonGroup.tsx, src/frontend/src/pages/FlowPage/components/PageComponent/index.tsx, src/frontend/src/pages/FlowPage/components/flowSidebarComponent/components/sidebarFooterButtons/index.tsx, src/frontend/src/pages/FlowPage/components/flowSidebarComponent/index.tsx, src/frontend/src/pages/FlowPage/index.tsx
This pull request introduces several enhancements to the `FlowPage` component and its subcomponents to improve the loading state handling and user interface. The most important changes include adding a loading skeleton, refactoring components to accept a loading state, and updating the `FlowPage` to manage and pass down this state.
* [`src/frontend/src/components/ui/skeletonGroup.tsx`](diffhunk://#diff-2d79515cb4e2673652693ba1866fe3d47d52b041d318ea8ad02f9b27f67048efR1-R21): Added a new `SkeletonGroup` component to display loading skeletons.
* [`src/frontend/src/pages/FlowPage/components/PageComponent/index.tsx`](diffhunk://#diff-58f6af33afc15c24e3df56ce2169081e35e5fe005f6281ebc5d7156b2eaa7d0eL82-R88): Updated the `Page` component to accept a `setIsLoading` function prop and use it to …
=> feat: Add loading state and skeleton UI for FlowPage sidebar

src/backend/base/langflow/services/tracing/langfuse.py, src/backend/base/langflow/services/tracing/langwatch.py
two tiny commit :
1. don't init langwatch if not configure
2. return langfuse callback for detail tracing
=> fix: don't init langwatch if not configure

src/frontend/src/modals/textModal/components/textEditorArea/index.tsx, src/frontend/src/modals/textModal/index.tsx
This pull request introduces changes to the `TextEditorArea` component to add a new `resizable` property, allowing more control over the textarea's resizing behavior. Additionally, it updates the `TextModal` component to utilize this new property.
Enhancements to `TextEditorArea` component:
* Added an optional `resizable` property to the `TextEditorArea` component to enable or disable the textarea's resize functionality. (`src/frontend/src/modals/textModal/components/textEditorArea/index.tsx`)
* Updated the `Textarea` element within `TextEditorArea` to conditionally apply CSS classes based on the `resizable` property. (`src/frontend/src/modals/textModal/components/textEditorArea/index.tsx`)
Updates to `TextModal` component:
* Set the `resizable` property to `false` in the `TextModal` …
=> fix: disable resizing in TextModal

src/backend/base/langflow/schema/table.py, src/frontend/src/components/core/parameterRenderComponent/components/TableNodeComponent/index.tsx, src/frontend/src/components/core/parameterRenderComponent/components/tableComponent/components/tableAutoCellRender/index.tsx, src/frontend/src/components/core/parameterRenderComponent/components/tableComponent/components/tableToggleCellEditor/index.tsx, src/frontend/src/types/utils/functions.ts, src/frontend/src/utils/utils.ts, src/frontend/tests/core/unit/tableInputComponent.spec.ts
This pull request includes significant changes to the backend and frontend code to improve the handling of table schemas and rendering components. The most important changes include updates to the `Column` class to support new data types, enhancements to the table rendering logic, and the addition of a new toggle cell editor component.
* [`src/backend/base/langflow/schema/table.py`](diffhunk://#diff-66bd9e20d21689c7321905c0c2e5b0e4e5cedb2e92c2f6c00c092a4714f597baL28-R44): Updated the `Column` class to support new data types (`bool`, `int`, `float`) for the `default` field and added a new `type` field. Implemented a `set_formatter_from_type` method to set the formatter based on the type and convert default values accordingly. [[1]](diffhunk://#diff-66bd9e20d21689c7321905c0c2e5b0e4e5cedb2e92 …
=> fix: handle null and boolean correctly on table parameter

.gitattributes, src/frontend/src/pages/FlowPage/components/UpdateAllComponents/index.tsx
This pull request includes a change to the `UpdateAllComponents` function in the `FlowPage` component. The change introduces a reset of the `edgesUpdateRef` object within the `getSuccessTitle` function to ensure the tracking of the number of edges and update status is reset before the success message is generated.
* [`src/frontend/src/pages/FlowPage/components/UpdateAllComponents/index.tsx`](diffhunk://#diff-1fa6c72d078cb9d7b501ddccdfdf2babb7ed1c958eca52d03d718ac420deb751R62-R66): Added code to reset `edgesUpdateRef` within the `getSuccessTitle` function.
=> Fix: Reset Edge Update Tracking Before Success Message in UpdateAllComponents

src/backend/base/langflow/helpers/data.py
This pull request includes a small but important change to the `data_to_text_list` function in the `src/backend/base/langflow/helpers/data.py` file. The change ensures that the `error` key in the `format_dict` is checked for a truthy value before assigning it to the `text` key.
* [`src/backend/base/langflow/helpers/data.py`](diffhunk://#diff-4e2e18fb4871befde95e9c1207b7554a7c4437fc3f06c0075dffd3cdb842896fL86-R86): Modified the `data_to_text_list` function to check if the `error` key in `format_dict` is truthy before assigning it to the `text` key.
=> Fix: error handling in data_to_text_list function

src/backend/base/langflow/alembic.ini
Since https://github.com/langflow-ai/langflow/pull/6258 the command `make alembic-revision` doesn't work anymore with the default `alembic.ini`
=> fix: Fix URL for alembic migrations

src/backend/base/langflow/services/settings/base.py
Update the default method for event delivery from streaming to polling in the settings configuration.
=> feat: Change default event delivery method to polling

src/backend/base/langflow/api/build.py, src/backend/base/langflow/api/v1/chat.py, src/backend/base/langflow/api/v1/schemas.py, uv.lock
Introduce a new endpoint to cancel ongoing flow build jobs, along with the necessary backend support for handling cancellations. Implement robust error handling and logging to ensure reliability during the cancellation process.
=> feat: Add flow build cancellation endpoint and functionality

src/frontend/src/components/core/dropdownComponent/index.tsx, src/frontend/src/utils/utils.ts
This pull request focuses on improving the `Dropdown` component by filtering out null or undefined options to ensure the component works with valid data. The changes include the introduction of a new utility function and updates to the component to use this function.
Key changes:
* Added `filterNullOptions` utility function to filter out null or undefined options in `src/frontend/src/utils/utils.ts`.
* Updated import statements in `src/frontend/src/components/core/dropdownComponent/index.tsx` to include `useMemo` and `filterNullOptions`.
* Introduced `validOptions` using `useMemo` to filter out null or undefined options and replaced occurrences of `options` with `validOptions` in the `Dropdown` component. [[1]](diffhunk://#diff-98068ce778ac9a53f4733f9c370c5e54bd27c30b6545fa4241f10cba355187 …
=> fix: Improve dropdown component with null option filtering

.github/workflows/ci.yml
Enhance the CI workflow to check for successful nightly builds within the current day, increase the number of workflow runs retrieved, and provide more detailed logging of build run status.
=> ci: Improve nightly build status check in CI workflow

src/backend/base/langflow/components/helpers/store_message.py
This PR fixes an UnboundLocalError in MessageStoreComponent when using external memory.
When external memory is enabled, `stored_messages` was not properly initialized, leading to an error.
- Ensure `stored_messages` is always initialized as an empty list.
- Use `stored_messages = await self.memory.aget_messages() or []` to prevent `None` assignment.
- Ensure transformation happens only if `stored_messages` is not empty.
- Manually tested with and without external memory.
=> fix: prevent UnboundLocalError in MessageStoreComponent

src/frontend/src/CustomNodes/GenericNode/index.tsx
This pull request includes changes to the `GenericNode` component to improve the layout and styling. The most important changes include adjustments to the class names for better handling of the node's display and the addition of truncation to the node name tooltip.
Styling improvements:
* [`src/frontend/src/CustomNodes/GenericNode/index.tsx`](diffhunk://#diff-b6793e0279f94c374aae18db97958c0af6befc2b49b7ce30e0294f9c80ba0d0eL493-R494): Modified the class names in the main node container to conditionally apply "border-b" or "relative" based on the `showNode` state.
* [`src/frontend/src/CustomNodes/GenericNode/index.tsx`](diffhunk://#diff-b6793e0279f94c374aae18db97958c0af6befc2b49b7ce30e0294f9c80ba0d0eL510-R512): Added the "truncate" class to the node name tooltip to ensure the node name is …
=> fix: changed edge position on minimized and not updated node

src/backend/base/pyproject.toml, uv.lock
Introduce optional dependencies for PostgreSQL in the `pyproject.toml` and update the lock file to include SQLAlchemy with aiosqlite support.
=> fix: Add optional PostgreSQL dependencies for SQLAlchemy in langflow-base

src/frontend/tests/core/integrations/Portfolio Website Code Generator.spec.ts
This pull request includes changes to the `Portfolio Website Code Generator` test in `src/frontend/tests/core/integrations/Portfolio Website Code Generator.spec.ts` to improve the reliability of the test by adjusting the timeout settings for selectors.
Test reliability improvements:
* Increased the timeout for the `.language-html` selector from 30 seconds to 90 seconds to ensure the test waits long enough for the element to appear.
* Increased the timeout for the `.markdown` selector from 3 seconds to 30 seconds to provide a more realistic waiting period for the element to load.
=> fix: Increase timeouts in Portfolio Website Code Generator test for improved reliability (nightly fix)

src/backend/base/pyproject.toml
currently codeflash does not work correctly in the GHA since it is using absolute paths for the ignore-paths field, codeflash relies on this being relative to the pyproject.toml, this fixes that.
=> chore: make codeflash config ignore-paths relative in langflow-base

src/frontend/src/components/core/parameterRenderComponent/components/TableNodeComponent/index.tsx, src/frontend/src/components/core/parameterRenderComponent/components/tableComponent/components/tableAutoCellRender/index.tsx, src/frontend/src/utils/utils.ts
This pull request includes changes to improve the handling of boolean formatters and the rendering of table cells in the frontend components. The most important changes include adding support for boolean formatters in the `TableNodeComponent`, integrating a new toggle component for cell rendering, and updating the utility functions accordingly.
Improvements to boolean formatter handling:
* [`src/frontend/src/components/core/parameterRenderComponent/components/TableNodeComponent/index.tsx`](diffhunk://#diff-0c62a57e27e05515113667234bff939fa464b255c228c92bc12c6ab9d61576a4L144-R145): Added support for `boolean` formatter in the `isCustomEdit` check.
Integration of new toggle component:
* [`src/frontend/src/components/core/parameterRenderComponent/components/tableComponent/components/tableAuto …
=> fix: changed badge to toggle on editable boolean fields on table component

src/frontend/src/alerts/alertDropDown/index.tsx, src/frontend/src/components/ui/loading.tsx, src/frontend/tests/extended/regression/general-bugs-icons-fallback.spec.ts
This pull request includes several important changes to the `AlertDropdown` component in the `src/frontend/src/alerts/alertDropDown/index.tsx` file. The changes focus on removing unnecessary dependencies and improving the code's readability and maintainability.
Improvements to the `AlertDropdown` component:
* Removed the import and usage of `ShortUniqueId` to simplify the code and reduce dependencies. [[1]](diffhunk://#diff-0543dd590276f022c89bfbef77b609cbf97fedc6d953222d2f9939a0b56367b4L3) [[2]](diffhunk://#diff-0543dd590276f022c89bfbef77b609cbf97fedc6d953222d2f9939a0b56367b4L34-R33) [[3]](diffhunk://#diff-0543dd590276f022c89bfbef77b609cbf97fedc6d953222d2f9939a0b56367b4L84-R78)
* Replaced the `ref` prop of the `PopoverContent` component with `notificationRef` to improve clarity and …
=> fix: improve ref naming causing fallback error on icons + regression test

src/backend/base/langflow/api/build.py
Ensures that end_all_traces is called at the end of all flow build events, ensuring proper trace finalization.
Fixes #6880
=> fix: ensure end_all_traces is called at the end of all flow build events

src/frontend/src/components/authorization/authGuard/index.tsx, src/frontend/src/constants/constants.ts, src/frontend/src/controllers/API/api.tsx, src/frontend/src/controllers/API/queries/auth/use-get-autologin.ts, src/frontend/src/controllers/API/queries/auth/use-post-refresh-access.ts, src/frontend/src/controllers/API/services/request-processor.ts, src/frontend/tests/core/features/auto-login-off.spec.ts, src/frontend/vite.config.mts
When starting Langflow using `make backend` and `make frontend` commands, users experienced an error where the frontend became available before the backend was fully initialized. This caused:
- Redirection to the login page even with Auto-Login enabled
- Requirement to manually refresh the page to complete login
- Poor user experience that appeared like a bug
This PR addresses the timing issue between frontend and backend initialization, ensuring proper authentication flow when Auto-Login is enabled.
1. Toggle Auto-Login setting in your `.env` file
2. Start the application with `make backend` and `make frontend` 
3. Open localhost:3000 before backend initialization completes
4. Verify smooth login experience without manual refresh
This change improves the user experience by properly …
=> fix: Add robust auto-login system with exponential backoff to fix authentication redirects in make command environments

src/frontend/src/components/core/appHeaderComponent/components/FlowMenu/index.tsx, src/frontend/src/components/core/appHeaderComponent/index.tsx
This pull request includes several changes to the `AppHeader` and `FlowMenu` components in the `src/frontend/src/components/core/appHeaderComponent` directory. The main focus is on improving the layout and responsiveness of these components. Below are the most important changes:
* Adjusted the `MenuBar` class names to improve layout and responsiveness by adding `w-full` and `shrink-0` classes. [[1]](diffhunk://#diff-22996ac0e1d31e677dd1f1b8a19404c313ac28d4f617d936618398b260072f07L233-R233) [[2]](diffhunk://#diff-22996ac0e1d31e677dd1f1b8a19404c313ac28d4f617d936618398b260072f07L266-R274) [[3]](diffhunk://#diff-22996ac0e1d31e677dd1f1b8a19404c313ac28d4f617d936618398b260072f07L283-R283)
* Removed unnecessary `truncate` classes to ensure elements do not get cut off unexpectedly.
* Added `z-30` …
=> fix: make header flow title occupy remaining space

src/frontend/src/CustomNodes/GenericNode/index.tsx
This pull request includes a change to the `GenericNode` component in the `src/frontend/src/CustomNodes/GenericNode/index.tsx` file. The change simplifies the CSS class list by removing the `truncate` class from the main node's `div` element.
Changes in `GenericNode` component:
* [`src/frontend/src/CustomNodes/GenericNode/index.tsx`](diffhunk://#diff-b6793e0279f94c374aae18db97958c0af6befc2b49b7ce30e0294f9c80ba0d0eL496-R496): Removed the `truncate` class from the `div` element's class list to potentially improve the display of text within the node.
=> fix: make chat input handle overflow

src/frontend/src/CustomNodes/GenericNode/components/handleRenderComponent/index.tsx
This pull request includes a change to the `HandleRenderComponent` in the `index.tsx` file to improve the handling of color names by removing duplicates and simplifying the logic.
Improvements to color name handling:
* [`src/frontend/src/CustomNodes/GenericNode/components/handleRenderComponent/index.tsx`](diffhunk://#diff-6b00d330838431fd5fd114f3ed4159196f47f74d00a65bd4d5fa2ed70cf726fbR281-R307): Created a `Set` from `colorName` to remove duplicates, calculated the unique color count, and used the first unique color in the logic for determining `handleColorName`, `handleColor`, and `accentForegroundColorName`.
=> feat: display the color itself instead of gray if there's only one color in the handle

src/frontend/src/CustomNodes/GenericNode/components/NodeDescription/index.tsx, src/frontend/src/CustomNodes/NoteNode/index.tsx
This pull request includes updates to the styling of components in the `src/frontend/src/CustomNodes` directory. The changes focus on improving the layout and appearance of the `NodeDescription` and `NoteNode` components.
Styling updates:
* [`src/frontend/src/CustomNodes/GenericNode/components/NodeDescription/index.tsx`](diffhunk://#diff-29f29ad00a7a070d08356cd7caef9f3c7746207bd09b69e65551917943849002L156-R156): Added padding and adjusted text size for the `Textarea` component to enhance its appearance.
* [`src/frontend/src/CustomNodes/NoteNode/index.tsx`](diffhunk://#diff-f8b8ed9929042c70be90d199a6389270c4dde1e7ad261d8a5e5c560983220cdaL154-R154): Modified the className to include `flex-1` for better layout control and consistency during transitions.
=> fix: make edit sticky notes mode occupy whole note

src/frontend/package-lock.json, src/frontend/package.json
This pull request includes changes to update the versioning of the `langflow` project across various components. The most important changes are:
Version updates:
* [`Makefile`](diffhunk://#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52R42): Added a command to bump the version in the `src/frontend` directory using npm.
* [`src/frontend/package-lock.json`](diffhunk://#diff-9eaa8c31e85b60ae25c139f2d6363cc9dcb6926125b5bf1d0cac092547e8cfcbL3-R3): Updated the version from `0.1.2` to `1.2.0`.
* [`src/frontend/package.json`](diffhunk://#diff-12ee508ecc1901fe1a1d71ed459dba8454f3160983ee18b2c51b76ade45235d3L3-R3): Updated the version from `0.1.2` to `1.2.0`.
=> fix: bump frontend version to current version and add command to bump frontend version in Makefile

src/frontend/package-lock.json, src/frontend/tests/extended/regression/generalBugs-shard-6.spec.ts
Update the frontend package version to 1.2.0 and improve the error message wait condition in the test to dynamically check for a minimum length, enhancing test robustness.
=> chore: Bump frontend package version and enhance test reliability

src/frontend/src/controllers/API/queries/nodes/use-post-validate-component-code.ts
This pull request includes a change to the `usePostValidateComponentCode` mutation function in the `src/frontend/src/controllers/API/queries/nodes/use-post-validate-component-code.ts` file. The change modifies the mutation options to disable retries and retry delays.
* [`src/frontend/src/controllers/API/queries/nodes/use-post-validate-component-code.ts`](diffhunk://#diff-9f8270699c193619ca23967a57577064faca1578b651d94c821f9285a72af9d3L43-R47): Updated the mutation options to include `retry: 0` and `retryDelay: 0`, ensuring that the mutation does not retry in case of failure.
=> fix: Disable retries in usePostValidateComponentCode mutation

docs/docs/API-Reference/api-reference-api-examples.md, docs/docs/Deployment/deployment-docker.md, docs/docs/Deployment/deployment-kubernetes.md, docs/package.json, docs/tailwind.config.js
Remove docs-related build errors:
* Replace unsupported code block syntaxes
* Add a tailwind-config.js file 
* Add MIT to the license field of package.json 
* Fix linking errors
Result:
```
yarn build
yarn run v1.22.18
$ docusaurus build
[INFO] [en] Creating an optimized production build...
✔ Client
Compiled successfully in 4.08s
✔ Server
● Client █████████████████████████ cache (99%) shutdown IdleFileCachePlugin
stored
✔ Server
[SUCCESS] Generated static files in "build".
[INFO] Use `npm run serve` command to test your build locally.
✨  Done in 9.96s.
➜  docs git:(docs-fix-syntax-errors) ✗ yarn serve
yarn run v1.22.18
$ docusaurus serve
[SUCCESS] Serving "build" directory at: http://localhost:3000/
^C
➜  docs git:(docs-fix-syntax-errors) ✗ yarn start
yarn run v1.22.18
$ docusaurus start …
```
=> docs: fix syntax errors at build

src/frontend/src/icons/Anthropic/Anthropic.jsx
Anthropic icon was inconsistent, made it consistent by passing the necessary props.
previously:
after fix:
=> fix: pass props to SvgAnthropicBox component

src/frontend/src/utils/reactflowUtils.ts
Improve the checkHasToolMode function to accurately detect tool mode status by adding a condition for templates with exactly three fields: _type, code, and tools_metadata. This enhancement increases the function's reliability in determining tool mode.
=> fix: check if component is in tool mode as well to display Tool Mode switch

src/frontend/tests/core/integrations/Pokedex Agent.spec.ts, src/frontend/tests/core/integrations/Social Media Agent.spec.ts
This pull request introduces new integration tests for the Pokedex Agent and Social Media Agent. These tests ensure that the respective agents function correctly by simulating user interactions and verifying the outputs.
New integration tests:
* [`src/frontend/tests/core/integrations/Pokedex Agent.spec.ts`](diffhunk://#diff-91c904e5906cc34cdd85c6ad5ef96b80428732380e3adf5fd05c73cb3cb9067eR1-R52): Added a test to verify the functionality of the Pokedex Agent, including setting up the environment, simulating user interactions, and checking the output for specific content.
* [`src/frontend/tests/core/integrations/Social Media Agent.spec.ts`](diffhunk://#diff-df04d8e025e2cadfbc68695ca3c1cd59bdc3c6c2e4876aff080b150ada752abfR1-R69): Added a test to verify the functionality of the Social Media …
=> test: add pokedex agent and social media agent integration tests

src/backend/base/langflow/initial_setup/starter_projects/Pokédex Agent.json, src/frontend/tests/core/integrations/starter-projects.spec.ts, src/frontend/tests/extended/regression/generalBugs-shard-3.spec.ts
This pull request includes several changes to the `Pokédex Agent.json` file aimed at updating node and edge identifiers, adding new properties, and removing unused fields. The most important changes include updating edge and node IDs, adding properties to edges, and removing deprecated fields.
Updates to edge and node identifiers:
* Updated edge IDs and related properties to new values for better consistency (`id`, `source`, `sourceHandle`, `target`, `targetHandle`). [[1]](diffhunk://#diff-2350a5b134d0b2279e637307e5732868388adda7acf8622f60c0d89cffb1b42fR5-R74) [[2]](diffhunk://#diff-2350a5b134d0b2279e637307e5732868388adda7acf8622f60c0d89cffb1b42fL75-R96)
* Updated node IDs to new values for improved clarity (`id` in `nodes` section).
Enhancements to edge properties:
* Added `animated` and …
=> tests: update node/edge IDs and properties in starter project (nightly fix)

src/frontend/tests/extended/integrations/chatInputOutputUser-shard-1.spec.ts
This pull request includes a small change to the `src/frontend/tests/extended/integrations/chatInputOutputUser-shard-1.spec.ts` file. The change involves updating the test selector to match the new data-testid format.
* [`src/frontend/tests/extended/integrations/chatInputOutputUser-shard-1.spec.ts`](diffhunk://#diff-cb9b53bf3d01d702cb8d3bb07babf818a6a2aff482fdaf8fc7ad2bafeada850bL175-R175): Changed the test selector from `[data-testid="${urlNodeId}-data-output-modal"]` to `[data-testid="${urlNodeId}-dataframe-output-modal"]`.
=> tests: update selector to match new data-testid format in chat integration test (nightly fix)

.github/workflows/typescript_test.yml, src/backend/base/langflow/initial_setup/starter_projects/Financial Agent.json, src/backend/tests/unit/template/utils/test_apply_json_filter.py, src/frontend/tests/core/features/publish-flow.spec.ts, src/frontend/tests/core/integrations/Simple Agent.spec.ts, src/frontend/tests/core/regression/generalBugs-shard-9.spec.ts
This pull request includes several changes to the `.github/workflows/typescript_test.yml` file and the `Financial Agent.json` file in the `src/backend/base/langflow/initial_setup/starter_projects` directory. The most important changes involve updating default values, optimizing shard counts, and modifying node IDs and properties in the JSON configuration.
Changes to `.github/workflows/typescript_test.yml`:
* Updated the `default` value for `description` fields from single quotes to double quotes. [[1]](diffhunk://#diff-5d797ebb3ae4ad03df6436d2142e2362e045f06db4f745ec0a5a414a91504d03L19-R19) [[2]](diffhunk://#diff-5d797ebb3ae4ad03df6436d2142e2362e045f06db4f745ec0a5a414a91504d03L40-R40)
* Adjusted the shard count calculation to allow a maximum of 15 shards instead of 10.
Changes to …
=> test: update workflow configuration and Financial Agent JSON structure (nightly fix)

src/frontend/package-lock.json, src/frontend/src/components/core/dropdownComponent/index.tsx, src/frontend/src/components/core/flowToolbarComponent/components/deploy-dropdown.tsx
This pull request includes several changes to the `src/frontend` directory, focusing on improving the `deploy-dropdown.tsx` component and updating the `package-lock.json` file. The most important changes include the addition of a utility function for class names, refactoring the class name assignment, and updating the `package-lock.json` file.
Improvements to `deploy-dropdown.tsx` component:
* Added the `cn` utility function from `@/utils/utils` to manage class names more efficiently.
* Refactored the class name assignment for the dropdown item to use the `cn` function, improving readability and maintainability.
* Disabled the publish switch when `hasIO` is false, ensuring better control over the component's behavior.
Updates to `package-lock.json` file:
* Removed the `extraneous` field …
=> fix: reposition and disable shareable playground toggle on empty flow

src/backend/base/langflow/components/memories/zep.py
For the reasons mentioned in issues #4266 and #5993, this PR deprecates the component
=> chore: mark zep componente as deprecated

src/backend/base/langflow/base/vectorstores/model.py
This pull request updates the new `_prepare_ingest_data` function to return an empty list, rather than a list of a null like attribute, when no ingestion connection is made to vector store components.
=> fix: Return empty list when not ingesting data

src/frontend/src/components/core/flowToolbarComponent/components/deploy-dropdown.tsx, src/frontend/src/controllers/API/queries/flows/use-patch-update-flow.ts, src/frontend/src/pages/Playground/index.tsx, src/frontend/src/types/flow/index.ts, src/frontend/tests/core/features/publish-flow.spec.ts, src/frontend/tests/core/unit/floatComponent.spec.ts
This pull request includes several changes to standardize the `access_type` field values and remove commented-out code. The changes ensure consistency in the `access_type` field values across the codebase by using uppercase strings. Additionally, an unnecessary commented-out section in the `deploy-dropdown.tsx` file has been removed.
Standardization of `access_type` field values:
* [`src/frontend/src/components/core/flowToolbarComponent/components/deploy-dropdown.tsx`](diffhunk://#diff-ed7af519b4da90e7f9693659b6f59be8a2f47bc173e59fde2ea6c3e49b522489L33-R33): Updated `access_type` field values to use uppercase strings. [[1]](diffhunk://#diff-ed7af519b4da90e7f9693659b6f59be8a2f47bc173e59fde2ea6c3e49b522489L33-R33) [[2]](diffhunk://#diff-ed7af519b4da90e7f9693659b6f59be8a2f47bc173e59fde2ea6c3e …
=> fix: change access_type to fit new ENUM

src/backend/base/langflow/components/processing/alter_metadata.py, src/backend/base/langflow/components/processing/json_cleaner.py
This pull request includes updates to mark certain components as legacy in the `src/backend/base/langflow/components/processing` directory. 
The most important changes include:
* [`src/backend/base/langflow/components/processing/alter_metadata.py`](diffhunk://#diff-c4adf408d41d297e10550a57aa383137d04671df61d3364ce969b1db1370d885R12): Added the `legacy` attribute set to `True` in the `AlterMetadataComponent` class.
* [`src/backend/base/langflow/components/processing/json_cleaner.py`](diffhunk://#diff-fb7a201f70c86b2045ceccae73171258e8ddc4850e327166246ffd4f15ebdb9cL17-R17): Added the `legacy` attribute set to `True` in the `JSONCleaner` class.
=> feat: add legacy tag deprecated components

src/frontend/src/controllers/API/api.tsx, src/frontend/src/controllers/API/queries/auth/use-get-autologin.ts, src/frontend/src/controllers/API/queries/auth/use-post-refresh-access.ts
This pull request includes changes to the API interceptor and the use of the refresh access token mutation in the frontend codebase. The most important changes include modifying the logic for retrying refresh tokens and updating the retry configuration for access token refresh.
Changes to API interceptor logic:
* [`src/frontend/src/controllers/API/api.tsx`](diffhunk://#diff-40877b80b2243cdac1ce21fa28ef5d9e9ab22eaf0051893e4c3236c3ec273150L68-R72): Modified the logic to determine when to retry refreshing tokens by introducing a new variable `shouldRetryRefresh`. This change simplifies the conditions under which a refresh is attempted.
* [`src/frontend/src/controllers/API/api.tsx`](diffhunk://#diff-40877b80b2243cdac1ce21fa28ef5d9e9ab22eaf0051893e4c3236c3ec273150L88): Removed an unnecessary …
=> fix: Improve token refresh logic and API interceptor handling

src/backend/base/langflow/components/tools/glean_search_api.py, src/backend/base/langflow/initial_setup/starter_projects/Diet Analysis.json, src/backend/base/langflow/initial_setup/starter_projects/Financial Agent.json, src/backend/base/langflow/initial_setup/starter_projects/Financial Report Parser.json, src/backend/base/langflow/initial_setup/starter_projects/Gmail Agent.json, src/backend/base/langflow/initial_setup/starter_projects/Instagram Copywriter.json, src/backend/base/langflow/initial_setup/starter_projects/Invoice Summarizer.json, src/backend/base/langflow/initial_setup/starter_projects/LoopTemplate.json, src/backend/base/langflow/initial_setup/starter_projects/Market Research.json, src/backend/base/langflow/initial_setup/starter_projects/Meeting Summary.json, src/backend/base/langflow/initial_setup/starter_projects/News Aggregator.json, src/backend/base/langflow/initial_setup/starter_projects/Portfolio Website Code Generator.json, src/backend/base/langflow/initial_setup/starter_projects/Price Deal Finder.json, src/backend/base/langflow/initial_setup/starter_projects/Research Agent.json, src/backend/base/langflow/initial_setup/starter_projects/SEO Keyword Generator.json, src/backend/base/langflow/initial_setup/starter_projects/Search agent.json, src/backend/base/langflow/initial_setup/starter_projects/Sequential Tasks Agents.json, src/backend/base/langflow/initial_setup/starter_projects/Social Media Agent.json, src/backend/base/langflow/initial_setup/starter_projects/Travel Planning Agents.json, src/backend/base/langflow/initial_setup/starter_projects/Vector Store RAG.json, src/backend/base/langflow/initial_setup/starter_projects/Youtube Analysis.json
This pull request includes a minor change to the `src/backend/base/langflow/components/tools/glean_search_api.py` file. The change updates the `icon` attribute of the `GleanSearchAPIComponent` class to use a different icon name.
* [`src/backend/base/langflow/components/tools/glean_search_api.py`](diffhunk://#diff-7482c741b055e68a32e49981de3cd0da48aa1cb3d674d8aab69bdc1c291ab6d5L104-R104): Updated the `icon` attribute from "GleanSearch" to "Glean".
=> fix: Glean icon missing

docs/docs/Integrations/Nvidia/integrations-nvidia-ingest.md
I'm not sure why this was now required, but if not added on my version of uv, uv will automatically downgrade langflow and other packages. 
```
uv --version             
uv 0.4.16 (e81ed8ec5 2024-09-24)
```
=> docs: add prerelease flag to nvidia ingest instructions

src/frontend/src/modals/promptModal/index.tsx
This pull request includes changes to the `PromptModal` component in the `src/frontend/src/modals/promptModal/index.tsx` file. The changes involve the removal of an unused constant and adjustments to the modal header layout.
* Removed the `PROMPT_DIALOG_SUBTITLE` constant from the import statement as it is no longer used in the component.
* Modified the `BaseModal.Header` to remove the `description` prop and adjusted the placement of the `Edit Prompt` text and `IconComponent` for better alignment.
=> fix: remove redundant description from Prompt modal

src/frontend/src/components/core/parameterRenderComponent/components/inputFileComponent/index.tsx
This pull request includes an update to the `InputFileComponent` in the `src/frontend/src/components/core/parameterRenderComponent/components/inputFileComponent/index.tsx` file. The most important change involves conditionally enabling the `useGetFilesV2` hook based on the `ENABLE_FILE_MANAGEMENT` flag.
Enhancements to file management:
* [`src/frontend/src/components/core/parameterRenderComponent/components/inputFileComponent/index.tsx`](diffhunk://#diff-68cd26e922bccf5191323c0f9ed58160ce8528c3479e556151c1ce4d4258a6caL146-R148): Updated the `useGetFilesV2` hook to include an `enabled` option that is set based on the `ENABLE_FILE_MANAGEMENT` flag.
=> fix: check if file management is on before getting files

src/frontend/src/components/authorization/authGuard/index.tsx
This pull request includes a small change to the `ProtectedRoute` component in the `authGuard` module. The change simplifies the condition for the `shouldRedirect` variable by combining the `autoLogin` and `isAutoLoginEnv` checks into a single logical OR operation.
* [`src/frontend/src/components/authorization/authGuard/index.tsx`](diffhunk://#diff-18da52e5b642d1dcf06ad684c83caacf6a85ba9d10f63b5b299fb857b1d120e0L21-R21): Simplified the condition for `shouldRedirect` by combining the `autoLogin` and `isAutoLoginEnv` checks into a single logical OR operation.
=> fix: logout redirection on auto-login off

src/frontend/tests/extended/features/files-page.spec.ts
This pull request includes changes to the `src/frontend/tests/extended/features/files-page.spec.ts` file, specifically focusing on temporarily skipping certain tests. The changes introduce a `test.skip()` statement to several test cases with a `@TODO` comment indicating the need to understand the behavior of these tests.
Key changes:
* `src/frontend/tests/extended/features/files-page.spec.ts`: Added `test.skip()` to the following test cases to temporarily skip them while investigating their behavior:
* "should navigate to files page and show empty state"
* "should upload file using upload button"
* "should upload file using drag and drop"
* "should search uploaded files"
=> tests: Skip tests that are failing during nightly build

src/backend/base/pyproject.toml, uv.lock
This pull request includes a small change to the `src/backend/base/pyproject.toml` file. The change adds the `webrtcvad` dependency to the list of dependencies.
* [`src/backend/base/pyproject.toml`](diffhunk://#diff-791e429538b782db78051d7dc01bf66022b585810db3f20b644e26ce5d1cce48R87): Added `webrtcvad>=2.0.10` to the dependencies list.
=> fix: Add webrtcvad dependency to backend base requirements

src/frontend/package-lock.json
This pull request includes several updates to the `src/frontend/package-lock.json` file to change dependencies from Linux x64 to Darwin arm64 and to add new dependencies for fsevents.
Changes from Linux x64 to Darwin arm64:
* Updated `@esbuild/darwin-arm64` version 0.21.5 to use the correct Darwin arm64 package.
* Updated `@million/lint/node_modules/@esbuild/darwin-arm64` version 0.20.2 to use the correct Darwin arm64 package.
* Updated `@napi-rs/nice-darwin-arm64` version 1.0.1 to use the correct Darwin arm64 package.
* Updated `@rollup/rollup-darwin-arm64` to use the correct Darwin arm64 package.
* Updated `@swc/core-darwin-arm64` to use the correct Darwin arm64 package.
Addition of new dependencies:
* Added `fsevents` version 2.3.2 to support file system events on Darwin.
* Added …
=> fix: rollback package-lock.json file

pyproject.toml, uv.lock
Updated the langchain-astradb package to version 0.5.3, modifying pyproject.toml and uv.lock to ensure compatibility with Graph RAG and other enhancements. This update improves support for advanced retrieval methods and ensures stability with the latest dependencies.
Files Changed:
•	pyproject.toml (Updated langchain-astradb to 0.5.3)
•	uv.lock (Regenerated to reflect dependency changes)
=> fix: updated version of lanchain-astradb to 0.5.3

src/frontend/src/constants/constants.ts
This pull request includes a small change to the `src/frontend/src/constants/constants.ts` file. The change adds a new supported type, "tab", to the `LANGFLOW_SUPPORTED_TYPES` set.
* [`src/frontend/src/constants/constants.ts`](diffhunk://#diff-3a3810648efc852f35a3780d6fe4ec65734c218f2281a175d9347a65db3fd360R657): Added "tab" to the `LANGFLOW_SUPPORTED_TYPES` set.
=> fix: add tab to supported types to not show input handles

src/backend/base/langflow/components/models/nvidia.py
real time refresh on a text field is not possible due to the number of update requests it sends as you type
=> fix: nvidia model component refresh behavior

src/frontend/src/pages/AppInitPage/index.tsx
This pull request includes changes to the `AppInitPage` component to improve the loading and refetching logic. The most important changes include adding refetch functionality and updating the useEffect dependencies.
Enhancements to loading and refetching logic:
* [`src/frontend/src/pages/AppInitPage/index.tsx`](diffhunk://#diff-3f47a6563af8bf59cd241de64d00738828c81574a70e287ac6b4cdbdefc99ef2L22-R40): Added `refetch` and `refetchExamples` functions to `useGetAutoLogin` and `useGetBasicExamplesQuery` hooks, respectively.
* [`src/frontend/src/pages/AppInitPage/index.tsx`](diffhunk://#diff-3f47a6563af8bf59cd241de64d00738828c81574a70e287ac6b4cdbdefc99ef2L22-R40): Updated the `useEffect` hook to include `isConfigFetched` in its dependency array and to call `refetch` and `refetchExamples` when …
=> fix: refetch endpoints on backend startup (improvement for devs) 

src/frontend/src/controllers/API/queries/auth/use-post-logout.ts
This pull request includes changes to the `use-post-logout.ts` file to enhance the logout functionality by incorporating cookie handling. The most important changes include importing the `Cookies` library and modifying the `logoutUser` function to check for an `auto_login_lf` cookie.
Enhancements to logout functionality:
* [`src/frontend/src/controllers/API/queries/auth/use-post-logout.ts`](diffhunk://#diff-b82440cdb42aa9d4e70abe54789c41e27dc4f2962bf729061686728c095895b8R4): Imported the `Cookies` library to manage cookies.
* [`src/frontend/src/controllers/API/queries/auth/use-post-logout.ts`](diffhunk://#diff-b82440cdb42aa9d4e70abe54789c41e27dc4f2962bf729061686728c095895b8R13-R20): Modified the `logoutUser` function to check for the `auto_login_lf` cookie in addition to the `autoLogin` …
=> fix: prevent logout when auto-login is true

src/frontend/src/controllers/API/queries/_builds/use-get-builds-polling-mutation.ts, src/frontend/src/controllers/API/queries/auth/use-post-logout.ts
This pull request includes updates to the `use-get-builds-polling-mutation.ts` and `use-post-logout.ts` files to handle edge cases and improve functionality. The most important changes include modifying the return type of `getBuildsFn`, adding a condition to set `flowPool`, and enhancing the logout functionality with additional checks.
Improvements to `use-get-builds-polling-mutation.ts`:
* Modified the return type of `getBuildsFn` to include `undefined` to handle cases where the request is already in progress.
* Added a condition to check if `flowPool` has keys before setting it, ensuring only valid data is processed.
Enhancements to `use-post-logout.ts`:
* Imported necessary constants and `Cookies` to manage auto-login state.
* Updated the `logoutUser` function to include checks for …
=> fix: add validation on build request to prevent output glitch

src/frontend/src/components/core/parameterRenderComponent/components/inputComponent/components/popover/index.tsx, src/frontend/src/components/core/parameterRenderComponent/components/inputGlobalComponent/index.tsx
This pull request includes changes to improve the handling of the `disabled` state in the `CustomInputPopover` and `InputGlobalComponent` components. The main changes ensure that the components behave correctly when they are disabled.
Improvements to handling the `disabled` state:
* [`src/frontend/src/components/core/parameterRenderComponent/components/inputComponent/components/popover/index.tsx`](diffhunk://#diff-6dd2f8aa520258e6efb0482b5419536b2eb345b1cccdcf29c1b4562971c4f0e4L232-R232): Modified the `CustomInputPopover` component to account for the `disabled` state in various conditions, including when displaying selected options, input value, and placeholder text. [[1]](diffhunk://#diff-6dd2f8aa520258e6efb0482b5419536b2eb345b1cccdcf29c1b4562971c4f0e4L232-R232) …
=> fix: Improve disabled state handling in CustomInputPopover and InputGlobalComponent

src/frontend/src/shared/components/textOutputView/index.tsx
This pull request includes an enhancement to the `TextOutputView` component in the `src/frontend/src/shared/components/textOutputView/index.tsx` file. The most important change is the addition of a feature to handle and notify users when the text output is truncated.
Enhancement to `TextOutputView` component:
* Added a check to determine if the `value` length exceeds 20,000 characters and display a notification if the output has been truncated.
=> feat: Add truncation notification for large outputs

src/frontend/src/components/core/parameterRenderComponent/components/inputFileComponent/index.tsx
This pull request includes changes to the `InputFileComponent` in the `src/frontend/src/components/core/parameterRenderComponent/components/inputFileComponent/index.tsx` file to improve the layout and styling of the component.
Styling improvements:
* Added a `w-full` class to the `div` with `data-testid="input-file-component"` to ensure it takes the full width of its container.
* Modified the `Button` component's class list to include `w-full font-semibold` for better styling consistency and full-width display.
=> fix: add full width on Select files button

src/frontend/tailwind.config.mjs
This pull request includes changes to the `src/frontend/tailwind.config.mjs` file to adjust the gradient background in the configuration. The changes ensure a smoother transition in gradient backgrounds by modifying the transparency percentage.
Gradient background adjustments:
* Changed the transparency percentage in the gradient background from 75% to 80% for a more gradual transition.
* Updated the transparency percentage in the gradient background from the default value to 80% for consistency.
=> fix: made truncate gradient appear just in the end of the truncated component

src/backend/tests/unit/components/data/test_api_request_component.py
This pull request includes a small change to the `test_make_request_binary_response` method in the `src/backend/tests/unit/components/data/test_api_request_component.py` file. The change adds print statements to help identify where the content is stored in the response.
* [`src/backend/tests/unit/components/data/test_api_request_component.py`](diffhunk://#diff-b6f4e58234a45a2fd482ab669d7bfdc1550c8bb1e40228195b25fbac917124e2L147-R150): Added print statements to output the keys and data in the response for debugging purposes.
=> test: fix api_request test (nightly fix)

src/backend/base/langflow/api/v1/mcp.py, src/backend/base/langflow/base/mcp/util.py, src/backend/tests/unit/components/data/test_api_request_component.py
This pull request introduces changes to the `src/backend/base/langflow/api/v1/mcp.py` file to ensure flow names are consistently handled in snake_case format. The changes include updating function calls and modifying the flow name processing logic.
* Updated import statement to use `get_flow_snake_case` instead of `get_flow` in `src/backend/base/langflow/api/v1/mcp.py`.
* Modified `handle_list_tools` function to convert flow names to snake_case before using them.
* Updated `handle_call_tool` function to use `get_flow_snake_case` for retrieving flows.
* Renamed `get_flow` to `get_flow_snake_case` and adjusted the flow name comparison logic in `src/backend/base/langflow/base/mcp/util.py`.
=> fix: Standardize flow name handling with snake_case conversion in MCP API

src/frontend/src/CustomNodes/GenericNode/components/NodeInputField/index.tsx, src/frontend/src/components/core/parameterRenderComponent/components/inputComponent/components/popover/index.tsx, src/frontend/src/components/core/parameterRenderComponent/components/inputComponent/index.tsx, src/frontend/src/components/core/parameterRenderComponent/components/inputGlobalComponent/index.tsx, src/frontend/src/components/core/parameterRenderComponent/components/strRenderComponent/index.tsx, src/frontend/src/components/core/parameterRenderComponent/index.tsx, src/frontend/src/components/core/parameterRenderComponent/types.ts, src/frontend/src/types/components/index.ts
This pull request includes changes to the `NodeInputField` and `CustomInputPopover` components to enhance functionality and improve the user interface. The most important changes are as follows:
Enhancements to `NodeInputField` component:
* Added a `hasRefreshButton` memoized value to determine if a refresh button should be displayed based on the node's template. (`src/frontend/src/CustomNodes/GenericNode/components/NodeInputField/index.tsx`, [src/frontend/src/CustomNodes/GenericNode/components/NodeInputField/index.tsxR71-R74](diffhunk://#diff-b68d4cff4ce636f41882b2e6c2fb46ce2e134bdf292e38bcf6df9c6c5807d518R71-R74))
* Updated the `displayHandle` logic to hide the handle if a refresh button is present. (`src/frontend/src/CustomNodes/GenericNode/components/NodeInputField/index.tsx`, …
=> fix: update handle display logic and improve popover layout in node components

src/backend/base/langflow/components/tools/glean_search_api.py
This pull request includes a small change to the `src/backend/base/langflow/components/tools/glean_search_api.py` file. The change adds the `tool_mode` attribute to the `MultilineInput` for the `query` field in the `GleanSearchAPIComponent` class to enhance its functionality.
* [`src/backend/base/langflow/components/tools/glean_search_api.py`](diffhunk://#diff-7482c741b055e68a32e49981de3cd0da48aa1cb3d674d8aab69bdc1c291ab6d5L115-R118): Added `tool_mode=True` to the `MultilineInput` for the `query` field in the `GleanSearchAPIComponent` class.
=> fix: add tool_mode to query input on gleanSearchComponent

src/frontend/src/components/core/parameterRenderComponent/components/floatComponent/index.tsx
This pull request includes updates to the `FloatComponent` in the `src/frontend/src/components/core/parameterRenderComponent/components/floatComponent/index.tsx` file to enhance the handling of input values and improve the user experience. The most important changes include adding local state management for the input value, updating the local value when the prop changes, and modifying event handlers to use the new local state.
Enhancements to input value handling:
* Added local state `localValue` to manage the input value independently of the prop value.
* Implemented an `useEffect` hook to update `localValue` whenever the prop `value` changes.
Event handler modifications:
* Updated the `handleChangeInput` function to set the `localValue` instead of calling `handleOnNewValue` directly.
* …
=> fix: allow float to be typed in float input

src/backend/base/langflow/api/build.py, src/backend/base/langflow/services/job_queue/service.py
Introduce a grace period for tasks marked for cleanup, allowing them to persist for a specified duration before removal. Update the job queue service to track cleanup timestamps and manage cleanup timing effectively. Enhance documentation to clarify the new cleanup mechanism.
This fixes a problem that caused long running agents to be cleaned up and the frontend to not receive the correct events.
=> fix: Implement cleanup grace period for job queue tasks

src/frontend/src/CustomNodes/GenericNode/index.tsx
This pull request includes changes to the `GenericNode` component in the `src/frontend/src/CustomNodes/GenericNode/index.tsx` file. The changes primarily focus on enhancing the selection logic for nodes.
The most important changes include:
Enhancements to node selection logic:
* Added a new `selectedNodes` constant that filters the nodes to include only those that are selected. (`src/frontend/src/CustomNodes/GenericNode/index.tsx`)
* Updated the `memoizedNodeToolbarComponent` to display the toolbar only when a single node is selected. (`src/frontend/src/CustomNodes/GenericNode/index.tsx`)
* Included `selectedNodes` in the dependency array for the `useEffect` hook to ensure it reacts to changes in the selected nodes. (`src/frontend/src/CustomNodes/GenericNode/index.tsx`)
=> fix: made node toolbar not appear when selecting multiple nodes

src/frontend/src/components/core/parameterRenderComponent/components/inputFileComponent/index.tsx
This pull request includes a small change to the `InputFileComponent` in the `src/frontend/src/components/core/parameterRenderComponent/components/inputFileComponent/index.tsx` file. The change simplifies the conditional class assignment for the `className` property of a button element. 
* [`src/frontend/src/components/core/parameterRenderComponent/components/inputFileComponent/index.tsx`](diffhunk://#diff-68cd26e922bccf5191323c0f9ed58160ce8528c3479e556151c1ce4d4258a6caL257-R260): Simplified the conditional class assignment for the `className` property by using a ternary operator.
=> fix: made plus button on file component not occupy full width

src/frontend/src/CustomNodes/hooks/use-handle-new-value.ts, src/frontend/src/constants/constants.ts, src/frontend/src/controllers/API/queries/nodes/use-post-template-value.ts
This pull request includes several changes to improve the handling of new values and the mutation process in the frontend codebase. The most important changes involve adding debouncing to the `handleOnNewValue` function and modifying the retry behavior of the `usePostTemplateValue` mutation.
Enhancements to `handleOnNewValue` function:
* [`src/frontend/src/CustomNodes/hooks/use-handle-new-value.ts`](diffhunk://#diff-0e6f6b3f7ee5b77c22d6f3a6375292722443eb6d8bf0b90c92a03daf2d8f8693L9-R10): Added `debounce` from `lodash` and `useRef` from `react` to debounce the `mutateTemplate` function calls, reducing the frequency of updates and improving performance. [[1]](diffhunk://#diff-0e6f6b3f7ee5b77c22d6f3a6375292722443eb6d8bf0b90c92a03daf2d8f8693L9-R10) …
=> fix: Add debouncing to handleOnNewValue and disable retries for usePostTemplateValue mutation

src/backend/tests/unit/template/utils/test_apply_json_filter.py, src/frontend/src/CustomNodes/GenericNode/index.tsx
This pull request includes changes to the `test_complex_nested_access` function in the `src/backend/tests/unit/template/utils/test_apply_json_filter.py` file to handle specific edge cases more gracefully.
Improvements to edge case handling:
* Added a condition to skip the specific failing case where the data is `{'': {'': []}}`.
* Introduced assumptions to skip tests with empty keys, which have special handling, for both the outer and inner keys.
=> test: fix apply json filter validation test

src/backend/tests/unit/services/tasks/test_temp_flow_cleanup.py, src/backend/tests/unit/template/utils/test_apply_json_filter.py
This pull request includes updates to the unit tests for the `apply_json_filter` function in `src/backend/tests/unit/template/utils/test_apply_json_filter.py`. The changes address the handling of empty string filters and special cases for nested key access.
Updates to unit tests:
* [`test_nested_object_access`](diffhunk://#diff-c1c9d62f75bfe35d8e9d541e24e8af28ac72917bb64dcc6d55f4bcfdb8c71d1aR56-R75): Added a check to skip dictionaries with empty string keys and updated assertions to reflect that the function returns `None` for empty string filters.
* [`test_edge_cases`](diffhunk://#diff-c1c9d62f75bfe35d8e9d541e24e8af28ac72917bb64dcc6d55f4bcfdb8c71d1aR56-R75): Modified parameterized test cases to expect `None` for empty dictionary and whitespace filters.
* …
=> test: Fix apply_json_filter to handle empty string filters and nested key access edge cases

src/frontend/src/components/core/dataOutputComponent/index.tsx, src/frontend/src/components/core/parameterRenderComponent/components/tableComponent/components/TableOptions/index.tsx, src/frontend/src/components/core/parameterRenderComponent/components/tableComponent/index.tsx
This pull request includes several changes to the `DataOutputComponent` and `TableComponent` to improve pagination handling and update state management. The most important changes are as follows:
* [`src/frontend/src/components/core/dataOutputComponent/index.tsx`](diffhunk://#diff-36efa9122816dc4e90f3d6d240c57b2e7899edb9d02ab98882dcfcff16d448bcL16-R28): Updated `DataOutputComponent` to use `useState` and `useEffect` for managing the internal state of rows, limiting the number of rows to 1000, and ensuring proper conversion of rows to objects if necessary.
* [`src/frontend/src/components/core/dataOutputComponent/index.tsx`](diffhunk://#diff-36efa9122816dc4e90f3d6d240c57b2e7899edb9d02ab98882dcfcff16d448bcR40-R44): Added `paginationInfo` prop to handle pagination information and updated the …
=> fix: make dataframe output format identify and show truncation

src/frontend/src/pages/FlowPage/components/nodeToolbarComponent/index.tsx, src/frontend/tests/core/features/freeze.spec.ts, src/frontend/tests/extended/regression/generalBugs-shard-10.spec.ts
This pull request includes a minor change to the `src/frontend/src/pages/FlowPage/components/nodeToolbarComponent/index.tsx` file. The change updates the label of a toolbar button from "Freeze Path" to "Freeze".
* [`src/frontend/src/pages/FlowPage/components/nodeToolbarComponent/index.tsx`](diffhunk://#diff-d393b1ee50eb66298a5ab133ad2f25d072667612a1c6457f24aa6733c98131aaL463-R463): Updated the label of the "Freeze Path" button to "Freeze".
=> fix: changed naming from freeze path to freeze

.github/workflows/docker-build.yml, .github/workflows/nightly_build.yml, .github/workflows/python_test.yml, .github/workflows/release.yml, .github/workflows/release_nightly.yml
Update version extraction commands across multiple workflow files to consistently use 'head -n 1', improving reliability in version detection.
=> chore: Ensure consistent version extraction for langflow-base in workflows

src/frontend/src/modals/IOModal/new-modal.tsx, src/frontend/src/pages/Playground/index.tsx
This pull request includes a small yet significant change to the `IOModal` component in the `new-modal.tsx` file. The change involves updating the state management hook used to retrieve the `currentFlow` state.
* [`src/frontend/src/modals/IOModal/new-modal.tsx`](diffhunk://#diff-35a8d953d616582d1e2933848c04ac2cbda55ee7939d22620d60374f0df61815L70-R70): Replaced the `useFlowsManagerStore` hook with the `useFlowStore` hook for fetching the `currentFlow` state.
=> fix: update currentflow to be fetched from Flow Store for icon to be rendered correctly

src/backend/base/langflow/custom/custom_component/component.py, src/backend/base/langflow/utils/validate.py
Uses [Artemis by TurinTech](https://artemis.turintech.ai) to find optimizations and quality improvements. These changes were selected as part of a [Sourcekon](https://docs.artemis.turintech.ai/code-audit/profiling-with-sourcekon) profiling, after which Artemis Intelligence was used to suggest multiple versions of improvements based on iterative scoring feedback.
Specifically, these changes
* Utilize loop fission to improve readability, minimize operations in instruction cache to potentially improve cache locality, and pre-group `definitions` for a single compilation and execution. 
* Improve error handling
=> ref: split ast parsing / class exec loops

src/backend/base/langflow/components/tools/mcp_component.py
This pull request includes a few changes to the `MCPToolsComponent` class in the `src/backend/base/langflow/components/tools/mcp_component.py` file. The most significant change is the removal of the `sse_url` attribute.
Codebase simplification:
* [`src/backend/base/langflow/components/tools/mcp_component.py`](diffhunk://#diff-8b368b159254d9a5a8ebef207dcb28d4790e3c6fcd01325b61d67bfd078b4177L33-L34): Removed the `sse_url` attribute from the `MCPToolsComponent` class.
=> fix: MCP SSE Model tool mode issue

src/frontend/src/controllers/API/helpers/constants.ts
This pull request includes a minor change to the `src/frontend/src/controllers/API/helpers/constants.ts` file. The change corrects the `PUBLIC_FLOW` URL by removing the leading slash.
* [`src/frontend/src/controllers/API/helpers/constants.ts`](diffhunk://#diff-de99daefacebca7e0f392df2dad151bd9c9d51078b51c7c5112c6ccda15f6b20L28-R28): Corrected the `PUBLIC_FLOW` URL by removing the leading slash.
=> fix: make sure public flow endpoint is correctly identified

src/frontend/src/components/core/parameterRenderComponent/components/inputGlobalComponent/index.tsx
This pull request includes a small change to the `src/frontend/src/components/core/parameterRenderComponent/components/inputGlobalComponent/index.tsx` file. The change adds an additional condition to the `if` statement to check if the `value` is an empty string before returning `unavailableFields[display_name]`.
Change details:
* [`src/frontend/src/components/core/parameterRenderComponent/components/inputGlobalComponent/index.tsx`](diffhunk://#diff-caa2538c44f1fa4f2e83da3cb4ac7b060852e688dec0a7b6bc89cc18e2b5a58dL44-R45): Added a condition to check if `value` is an empty string in the `if` statement that verifies if `display_name` is included in `unavailableFields`.
=> fix: made global variables apply to fields not overwrite fields on refresh

src/backend/base/langflow/services/database/models/api_key/crud.py, src/backend/tests/conftest.py, src/backend/tests/unit/test_endpoints.py
Add tests for concurrent requests with chat input type with `stream=True`.
=> tests: add tests for streaming calls on api/v1/run

docs/docs/Integrations/Nvidia/integrations-nvidia-nim-wsl2.md
https://superuser.com/questions/949428/whats-the-difference-between-127-0-0-1-and-0-0-0-0
It works locally in the WSL2 environment due to implicit redirection, but from windows host -> WSL2 it needs `localhost` or the `WSL2` address.
=> docs: fix localhost address for NIM docs

src/backend/base/langflow/alembic/versions/f3b2d1f1002d_add_column_access_type_to_flow.py
This PR fixes a small typo in the Alembic migration script where sa.EnuM was mistakenly used instead of sa.Enum for the access_type_enum.
The issue did not cause a runtime error immediately, which made it harder to spot during review
=> fix: typo in Alembic enum type declaration

src/frontend/src/components/ui/button.tsx, src/frontend/src/modals/IOModal/components/chatView/chatInput/components/voice-assistant/voice-assistant.tsx, src/frontend/src/style/index.css
This pull request includes changes to the styling and behavior of the `outlineAmber` button variant and updates to the `accent-amber` color values in the CSS. The most important changes include modifying the `outlineAmber` button variant, updating the hover behavior of the voice assistant settings icon, and adjusting the `accent-amber` color values in the CSS.
Styling changes:
* [`src/frontend/src/components/ui/button.tsx`](diffhunk://#diff-563c249a9783eb98b2bf8f32f082aee8a2746e243b2bb7d59974f4455c0a2121L17-R17): Modified the `outlineAmber` button variant to remove the hover border effect.
Behavioral changes:
* [`src/frontend/src/modals/IOModal/components/chatView/chatInput/components/voice-assistant/voice-assistant.tsx`](diffhunk://#diff-fa0c14eb69379a58b00c257854ca8efb8b00fd1355beda2e3c7 …
=> fix: add correct amber colors and button design

src/frontend/src/modals/IOModal/components/chatView/components/chat-view.tsx
This pull request includes several changes to the `chat-view.tsx` file to clean up unused imports and add debugging information. The most important changes are as follows:
Code cleanup:
* Removed unused imports from `chat-view.tsx`, including `ForwardedIconComponent`, `ProfileIcon`, `CustomProfileIcon`, and `ENABLE_DATASTAX_LANGFLOW`.
Debugging improvements:
* Added a `console.log` statement to log the state of `messages`, `isBuilding`, `chatInputNode`, and `isTabHidden` in the `useEffect` hook.
Code simplification:
* Simplified the `useEffect` hook by removing the unnecessary `else` branch that checked `isTabHidden` to conditionally set `chatValueStore`.
=> fix: removed dependency from useEffect that causes chat input to be cleared

src/frontend/src/constants/constants.ts
This pull request includes an update to the `LANGFLOW_SUPPORTED_TYPES` constant in the `src/frontend/src/constants/constants.ts` file. The change adds new supported types to the set.
* [`src/frontend/src/constants/constants.ts`](diffhunk://#diff-3a3810648efc852f35a3780d6fe4ec65734c218f2281a175d9347a65db3fd360R658-R659): Added "sortableList" and "connect" to the `LANGFLOW_SUPPORTED_TYPES` set.
=> fix: removed handle from sortableinput and connectinput

src/frontend/src/utils/styleUtils.ts
Moves the home assistants components to a bundle
=> fix: move home assistants to bundle

pyproject.toml, src/backend/base/pyproject.toml, src/frontend/package-lock.json, src/frontend/package.json, uv.lock
This pull request includes version updates for the `langflow` project and its dependencies. The most important changes involve updating the version numbers in several configuration files to ensure consistency across the project.
Version updates:
* [`pyproject.toml`](diffhunk://#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711L4-R4): Updated the project version from `1.3.1` to `1.3.2` and the `langflow-base` dependency from `0.3.1` to `0.3.2`. [[1]](diffhunk://#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711L4-R4) [[2]](diffhunk://#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711L22-R22)
* [`src/backend/base/pyproject.toml`](diffhunk://#diff-791e429538b782db78051d7dc01bf66022b585810db3f20b644e26ce5d1cce48L3-R3): Updated the …
=> chore: bump langflow and langflow-base for 1.3.2 release

src/frontend/src/components/core/flowToolbarComponent/components/deploy-dropdown.tsx
This pull request includes several changes to the `deploy-dropdown.tsx` file to enhance the functionality and maintainability of the PublishDropdown component. The most important changes include the addition of a `CustomLink` component and the use of `useHref` from `react-router-dom` to construct URLs dynamically.
Enhancements to the PublishDropdown component:
* [`src/frontend/src/components/core/flowToolbarComponent/components/deploy-dropdown.tsx`](diffhunk://#diff-ed7af519b4da90e7f9693659b6f59be8a2f47bc173e59fde2ea6c3e49b522489R150-R164): Added the `CustomLink` component to replace the previous `window.open` method for opening the playground link in a new tab. This improves the readability and maintainability of the code. [[1]](diffhunk://#diff-ed7af519b4da90e7f9693659b6f59be8a2f47bc173e …
=> fix: publish button not redirecting to right path

src/backend/base/langflow/alembic/env.py, src/backend/base/langflow/initial_setup/setup.py, src/backend/base/langflow/services/settings/base.py, src/backend/tests/unit/api/v1/test_flows.py, src/backend/tests/unit/test_initial_setup.py
This PR introduces a configurable polling interval for syncing flows from the file system by leveraging an environment variable and corresponding settings.
* Added a new environment variable fixture and test in test_initial_setup.py to verify polling updates.
* Modified the sync_flows_from_fs function in setup.py to use a configurable interval derived from settings.
* Updated settings and minor formatting improvements in test_flows.py and alembic/env.py.
=> feat: Add configurable polling interval for syncing flows from FS

src/frontend/package-lock.json, src/frontend/package.json, src/frontend/src/modals/flowLogsModal/index.tsx, src/frontend/src/utils/utils.ts
This pull request includes several changes to the frontend package and utility functions. The most notable changes involve adding a new dependency for time zone handling and updating the flow logs modal to display timestamps in the local time zone.
* Added `moment-timezone` version `0.5.48` to `package.json` and `package-lock.json` to handle time zone conversions. [[1]](diffhunk://#diff-9eaa8c31e85b60ae25c139f2d6363cc9dcb6926125b5bf1d0cac092547e8cfcbR62) [[2]](diffhunk://#diff-9eaa8c31e85b60ae25c139f2d6363cc9dcb6926125b5bf1d0cac092547e8cfcbR11765-R11775) [[3]](diffhunk://#diff-12ee508ecc1901fe1a1d71ed459dba8454f3160983ee18b2c51b76ade45235d3R57)
* Introduced a new utility function `convertUTCToLocalTimezone` in `utils.ts` to convert UTC timestamps to the local time zone. …
=> feat: Display flow logs timestamps in local time zone

src/frontend/src/components/core/flowToolbarComponent/components/deploy-dropdown.tsx, src/frontend/src/components/core/flowToolbarComponent/components/playground-button.tsx, src/frontend/src/components/core/flowToolbarComponent/index.tsx, src/frontend/src/modals/IOModal/components/chatView/chatMessage/chat-message.tsx, src/frontend/src/modals/IOModal/new-modal.tsx
This pull request includes changes to the `flowToolbarComponent` and related components to conditionally enable the "Publish" feature based on the `ENABLE_PUBLISH` feature flag. The most important changes involve adding the `ENABLE_PUBLISH` import, updating the `PublishDropdown` component, and modifying the `FlowToolbar` component to handle the new feature flag.
Feature flag integration:
* [`src/frontend/src/components/core/flowToolbarComponent/components/deploy-dropdown.tsx`](diffhunk://#diff-ed7af519b4da90e7f9693659b6f59be8a2f47bc173e59fde2ea6c3e49b522489L13-R13): Added `ENABLE_PUBLISH` import and modified the `PublishDropdown` component to conditionally render based on the `ENABLE_PUBLISH` flag. [[1]](diffhunk://#diff-ed7af519b4da90e7f9693659b6f59be8a2f47bc173e59fde2ea6c3e49b522489L13-R …
=> feat: put Shareable Playground under ENABLE_PUBLISH feature flag and removed old publish

src/backend/base/langflow/components/nvidia/nvidia_ingest.py, src/frontend/src/constants/constants.ts, src/frontend/src/helpers/create-file-upload.ts, src/frontend/src/modals/fileManagerModal/components/dragFilesComponent/index.tsx
This pull request includes changes to both the backend and frontend components to improve functionality and user experience. The most important changes include modifying file handling and upload mechanisms, as well as updating constants for better configuration.
Backend changes:
* [`src/backend/base/langflow/components/nvidia/nvidia_ingest.py`](diffhunk://#diff-e2345c6cd9d86c7275148ba76f6c8c94e8955f48453af3aaa3409a51347571adL27-R27): Removed the assignment of `msg` to `file_types`, leaving `file_types` as an empty list.
Frontend changes:
* [`src/frontend/src/constants/constants.ts`](diffhunk://#diff-3a3810648efc852f35a3780d6fe4ec65734c218f2281a175d9347a65db3fd360R1069): Added a new constant `DEFAULT_FILE_PICKER_TIMEOUT` set to 60000.
* …
=> fix: removed file uploaded successfully message when no file is picked, fixed nvidia ingest message

src/backend/base/langflow/api/build.py, src/backend/base/langflow/api/utils.py, src/backend/base/langflow/api/v1/chat.py, src/backend/tests/unit/build_utils.py, src/frontend/src/CustomNodes/GenericNode/components/NodeStatus/index.tsx, src/frontend/src/controllers/API/api.tsx, src/frontend/src/controllers/API/queries/config/use-get-config.ts, src/frontend/src/modals/IOModal/new-modal.tsx, src/frontend/src/stores/flowStore.ts, src/frontend/src/stores/utilityStore.ts, src/frontend/src/types/zustand/flow/index.ts, src/frontend/src/types/zustand/utility/index.ts, src/frontend/src/utils/buildUtils.ts
This pull request introduces several changes to handle event delivery configurations more effectively in both the backend and frontend. The key updates include adding a new request parameter for event delivery, updating utility store configurations, and modifying various components to use the new event delivery configuration.
* Added `request` parameter to the `build_flow` function in `chat.py` to access request headers.
* Modified the `build_flow` function to check the "X-Event-Delivery" header and adjust the event delivery method accordingly.
* Replaced `config.data?.event_delivery` with `eventDeliveryConfig` in `NodeStatus` and `IOModal` components to use the new utility store state. [[1]](diffhunk://#diff-a82985ebdf968b3b9ff88582d46208ef24ade91024f7e4bcdddc9451bfede45eL90-R90) …
=> fix: Resolve event delivery configuration header passing between frontend and backend

src/backend/base/langflow/api/v1/chat.py, src/backend/tests/unit/test_chat_endpoint.py
Update the event delivery condition in the build_flow function to ensure proper handling of non-DIRECT types, enhancing the robustness of event delivery. Additionally, improve test assertions for job_id presence in responses.
=> fix: job id should be returned only if event_delivery is not direct

src/frontend/src/controllers/API/queries/flows/use-get-refresh-flows-query.ts, src/frontend/src/controllers/API/queries/flows/use-get-refresh-flows.ts
This pull request includes updates to error handling in two query functions within the `src/frontend/src/controllers/API/queries/flows` directory. The primary changes involve importing `AxiosError` and adding conditional checks for this error type in the catch blocks.
Error handling improvements:
* [`src/frontend/src/controllers/API/queries/flows/use-get-refresh-flows-query.ts`](diffhunk://#diff-c70b5e2e0695512c8ec4c67ea960b49e6a4be89aa8af4f2ac81563b6990fa750R12): Imported `AxiosError` from `axios` and added a conditional check for `AxiosError` with a status other than 403 in the `useGetRefreshFlowsQuery` function. [[1]](diffhunk://#diff-c70b5e2e0695512c8ec4c67ea960b49e6a4be89aa8af4f2ac81563b6990fa750R12) [[2]](diffhunk://#diff-c70b5e2e0695512c8ec4c67ea960b49e6a4be89aa8af4f2ac81563b6990fa7 …
=> Fix: Prevent Error Popups When Session Expires During Logout

src/frontend/src/CustomNodes/GenericNode/components/NodeOutputfield/index.tsx
This pull request includes changes to the `NodeOutputField` component in `src/frontend/src/CustomNodes/GenericNode/components/NodeOutputfield/index.tsx` to improve the handling of empty outputs. The most important changes include the addition of a new `emptyOutput` state, the creation of a `disabledInspectButton` state, and updates to the `ShadTooltip` and `OutputModal` components to use these new states.
Improvements to handling empty outputs:
* Added a new `emptyOutput` state to check if all output messages are empty.
* Created a new `disabledInspectButton` state to disable the inspect button when outputs are empty or other conditions are met.
Updates to component behavior:
* Updated the `ShadTooltip` component to display a message when outputs are empty.
* Updated the `OutputModal` and …
=> feat: Disable inspect button for empty node outputs

docs/docs/Components/components-helpers.md, docs/docusaurus.config.js
This pull request includes a small change to the `docs/docusaurus.config.js` file. The change updates the `trackingID` in the `gtag` configuration.
* [`docs/docusaurus.config.js`](diffhunk://#diff-28742c737e523f302e6de471b7fc27284dc8cf720be639e6afe4c17a550cd654L69-R69): Updated the `trackingID` from "G-L8Y98PSEMQ" to "G-SLQFLQ3KPT".
*
=> fix: update Google Analytics tracking ID in docusaurus configuration

src/backend/base/langflow/api/v1/chat.py
This pull request includes changes to the `async def build_flow` function in the `src/backend/base/langflow/api/v1/chat.py` file. The most important change is the removal of the `settings_service` parameter from the function signature.
* [`src/backend/base/langflow/api/v1/chat.py`](diffhunk://#diff-44baaabf1ab87d4713c828053d97a7f9f5dc8d1ab9c2f8d05c1a0bcdc43e999cL175): Removed the `settings_service` parameter from the `async def build_flow` function signature.
=> fix: remove unecessary comment from build_flow

Makefile
Modify the backend installation command in the Makefile to include PostgreSQL as an extra dependency.
=> chore: Update Makefile to include PostgreSQL in backend installation

src/backend/base/langflow/api/v2/files.py
Update the file API routes to include trailing slashes for consistency across upload, list, and delete endpoints.
=> fix: Standardize endpoint paths in files v2 API

src/backend/base/langflow/base/vectorstores/model.py, src/backend/base/langflow/initial_setup/starter_projects/Hybrid Search RAG.json, src/backend/base/langflow/initial_setup/starter_projects/Vector Store RAG.json
This pull request includes changes to the `src/backend/base/langflow/base/vectorstores/model.py` file to update the `QueryInput` parameters. The most important change is the modification of the `info` attribute to provide a more accurate description of the search functionality.
* [`src/backend/base/langflow/base/vectorstores/model.py`](diffhunk://#diff-2393357b05f6ba626e42103c089e1769b136251439604f0e5f2147677769998dL68-R68): Updated the `info` attribute of `QueryInput` to describe the search as a "similarity search" instead of a "combined similarity and lexical terms search."
=> fix: remove lexical search from astra db hybrid search

src/frontend/src/components/core/appHeaderComponent/components/FlowMenu/index.tsx, src/frontend/src/hooks/useUnsavedChanges.ts, src/frontend/src/modals/flowSettingsModal/index.tsx
When doing something as simple as moving a node around the header (menubar, and flowsettingsmodal) rerender on each move. This is unnecessary and this PR addresses by removing the dependency on `useFlowStore` and `useFlowsManagerStore` currentFlow state
Before:
After: (note found in the list)
=> refactor: reduce menu bar rerenders

src/backend/base/langflow/alembic/versions/1b8b740a6fa3_remove_fk_constraint_in_message_.py
Introduce a helper function to rename primary key constraints according to naming conventions. Update the migration upgrade function to utilize this helper for the relevant tables, ensuring database integrity is maintained.
=> fix: Implement primary key renaming in Alembic migration for message, transaction, and vertex_build tables

src/backend/base/langflow/services/auth/utils.py
This pull request introduces a deprecation warning and updates the authentication logic in the `api_key_security` function to prepare for upcoming changes in version 1.5. The most important change is the addition of a warning to inform users about the future requirement of an API key or JWT for authentication.
* `src/backend/base/langflow/services/auth/utils.py`:
- Added a `DeprecationWarning` to notify users that starting from v1.5, the default behavior of AUTO_LOGIN authentication will require an API key or JWT. This ensures users are aware of the upcoming change and can update their integrations accordingly.
- Updated the logic to check for `query_param` or `header_param` and validate them using the `check_key` function if present. This prepares the codebase for the new authentication …
=> feat: add deprecation warning for AUTO_LOGIN

docs/docs/Deployment/deployment-docker.md
This pull request updates the deployment documentation with a comprehensive guide on customizing the Langflow Docker image, including an example `Dockerfile`, step-by-step instructions, and an explanation of how to replace or modify components like `astradb_graph.py`.
Also updated code block syntax from `shell` to `bash` for consistency
=> docs: modify the langflow docker image

src/frontend/tests/extended/features/mcp-server.spec.ts
This pull request updates the `mcp-server.spec.ts` test file to improve the robustness and functionality of the MCP server test suite. Key changes include adding retry logic for dropdown interactions, replacing a hover action with a drag-and-drop operation, and introducing additional wait times to enhance test reliability.
* Added retry logic with a maximum of three attempts to ensure the dropdown becomes enabled after clicking the refresh button. This includes logging retry attempts and throwing an error if the dropdown remains disabled. [[1]](diffhunk://#diff-37d0e42832061615b47a8d9aac2a99d55e565969f0e0e9311e1e536152013f9aR34-R61) [[2]](diffhunk://#diff-37d0e42832061615b47a8d9aac2a99d55e565969f0e0e9311e1e536152013f9aR109-R150)
* Introduced additional `waitForTimeout` calls to stabilize …
=> test: Enhance MCP server test reliability with retry logic and improved interactions (nightly fix)

src/frontend/src/CustomNodes/NoteNode/components/select-items.tsx
This pull request includes a small change to the `src/frontend/src/CustomNodes/NoteNode/components/select-items.tsx` file. The change consolidates imports by grouping `SelectContentWithoutPortal` and `SelectItem` under the same module, `@/components/ui/select-custom`, improving code organization.
=> fix: change note toolbar wrong import that causes wrong padding

src/backend/base/langflow/components/tools/mcp_component.py, src/frontend/src/components/common/genericIconComponent/index.tsx, src/frontend/src/pages/MainPage/pages/homePage/components/McpServerTab.tsx, src/frontend/src/shared/components/delete-confirmation-modal.tsx, src/frontend/tests/extended/features/mcp-server-tab.spec.ts, src/frontend/tests/extended/features/mcp-server.spec.ts
This pull request includes updates to improve the clarity and consistency of the MCP-related UI text and component descriptions in both the backend and frontend. The most important changes include renaming and rephrasing the MCP component's display name and description, as well as refining the wording in the MCP Server tab UI for better user guidance.
* [`src/backend/base/langflow/components/tools/mcp_component.py`](diffhunk://#diff-8b368b159254d9a5a8ebef207dcb28d4790e3c6fcd01325b61d67bfd078b4177L80-R81): Updated the `display_name` from "MCP Server" to "MCP Connection" and rephrased the `description` to "Connect to an MCP server to use its tools" for improved clarity.
* [`src/frontend/src/pages/MainPage/pages/homePage/components/McpServerTab.tsx`](diffhunk://#diff-da4edd139a58d412a5bba68a4 …
=> fix: update texts on mcp component and tab, fix icons not updating

src/backend/base/langflow/components/composio/gmail_composio.py, src/frontend/src/pages/MainPage/pages/empty-page.tsx
This pull request enhances the `ComposioGmailAPIComponent` to support extracting specific fields from API responses for various Gmail actions. The changes include adding metadata to define result fields for actions and updating the execution logic to utilize this metadata.
* Added `get_result_field` and `result_field` attributes to the following Gmail actions to specify which field in the API response should be extracted:
- [`GMAIL_LIST_THREADS`](diffhunk://#diff-4f363eaaeb0d748c11cfb4d083b044d4de6d1da648f3e7c09ebc4d14d4688a9aR83-R84): Extracts the `threads` field.
- [`GMAIL_LIST_LABELS`](diffhunk://#diff-4f363eaaeb0d748c11cfb4d083b044d4de6d1da648f3e7c09ebc4d14d4688a9aR93-R94): Extracts the `labels` field.
- [`GMAIL_GET_PEOPLE`](diffhunk://#diff-4f363eaaeb0d748c11cfb4d083b044d4de6d1da648f3 …
=> fix: composio gmail output maps

src/frontend/tests/core/features/actionsMainPage-shard-1.spec.ts
This pull request updates the `src/frontend/tests/core/features/actionsMainPage-shard-1.spec.ts` file to enhance test stability by adding conditional checks for element visibility before interacting with them.
* Added a conditional check using `isVisible()` for the "components-btn" element before performing actions in the "search components" test. This ensures that the test interacts with the element only if it is visible, reducing the likelihood of test flakiness. [[1]](diffhunk://#diff-36a468fe1b606480803881b9531659b213fc01c3f267d43faaaa2590f92a3e47R80) [[2]](diffhunk://#diff-36a468fe1b606480803881b9531659b213fc01c3f267d43faaaa2590f92a3e47L134-R139)
=> fix: make component test pass if component tab is not present

src/backend/tests/unit/components/bundles/composio/test_gmail.py
This pull request updates a unit test in `test_gmail.py` to reflect a change in the behavior of the `execute_action` method. Specifically, the test now asserts that the method returns the `result_field` directly instead of the entire data dictionary.
* **Unit test update:**
* [`src/backend/tests/unit/components/bundles/composio/test_gmail.py`](diffhunk://#diff-a5119444f0339aa3609d5219850cf6aa2603f5d8f6dd2af71f4083fa32df0b56L116-R117): Modified the `test_execute_action_fetch_emails` test to assert that `execute_action` returns the `result_field` directly, aligning with the updated behavior of the method.
=> ffix: Update Gmail test to assert direct result_field return instead of full data dictionary (nightly fix)

src/backend/base/langflow/api/v1/endpoints.py, src/backend/base/langflow/graph/utils.py, src/backend/base/langflow/serialization/serialization.py
Seeing transaction failure logs (with some additional print statements):
```
ERROR    2025-04-19 13:33:11 - ERROR    - utils - Exception details: PydanticSerializationError                                            utils.py:144
ERROR    2025-04-19 13:33:11 - ERROR    - utils - Error logging transaction: Unable to serialize unknown type: <class                      utils.py:143
'pandas.core.frame.DataFrame'>   
```
Not sure if a recent change to process dataframes occurred, but this fixes it by checking if the value is a dataframe and converting it to json first
I ran some benchmarks to verify this doesn't _add_ serialization time. We have performance issues serializing dataframes now, but this change is unrelated.
=> fix: transaction logging of pandas dataframes

src/backend/base/langflow/base/agents/events.py
This pull request refactors the `_extract_output_text` function in `src/backend/base/langflow/base/agents/events.py` to improve its robustness and updates its usage in the `handle_on_chain_stream` function. The most important changes include restructuring the `_extract_output_text` function to handle additional edge cases and ensuring the `handle_on_chain_stream` function uses the updated logic.
* Enhanced `_extract_output_text` to handle edge cases where the input is an empty list, a list with non-dictionary items, or dictionaries without a "text" key. It now raises a `ValueError` with a descriptive message for unsupported formats.
* Modified `handle_on_chain_stream` to use the updated `_extract_output_text` function for processing `data_chunk.content`, ensuring consistent and robust …
=> fix: Streaming for anthropic models in Agents

src/backend/base/langflow/base/tools/run_flow.py
Hotfix to enable only single execution for the runflow in tool mode.
All three outputs give similar responses in various formats, whereas in tool mode, the result must only be in message format.
________________
This pull request updates the `_base_outputs` list in the `src/backend/base/langflow/base/tools/run_flow.py` file to enhance the configuration of `Output` objects. The most notable change is the addition of the `tool_mode` attribute to two `Output` definitions, improving their configurability.
* Added the `tool_mode` attribute (set to `False`) to the `flow_outputs_data` and `flow_outputs_dataframe` `Output` objects for enhanced configurability.
=> fix: run flow multiple execution in tool mode

src/frontend/src/modals/IOModal/components/chatView/chatInput/chat-input.tsx, src/frontend/src/modals/IOModal/components/chatView/chatInput/components/input-wrapper.tsx, src/frontend/src/modals/IOModal/components/chatView/chatInput/hooks/use-drag-and-drop.ts, src/frontend/src/modals/IOModal/components/chatView/components/chat-view.tsx
This pull request introduces changes to enhance feature flag handling for enabling or disabling image uploads in the Playground page. The updates ensure that the behavior of file uploads, drag-and-drop functionality, and UI components is consistent with the `ENABLE_IMAGE_ON_PLAYGROUND` flag.
* **Conditional file upload handling**: Updated the `handleFileChange` function in `chat-input.tsx` to block file uploads on the Playground page when the `ENABLE_IMAGE_ON_PLAYGROUND` flag is disabled.
* **Input wrapper logic adjustment**: Modified the conditional rendering logic in `input-wrapper.tsx` to ensure that the `UploadFileButton` is displayed only when the Playground page is enabled for image uploads.
* **Drag-and-drop enhancements**: Updated the `useDragAndDrop` hook in …
=> fix: playground page allowing image upload even if feature flag is disabled

src/frontend/src/pages/MainPage/pages/homePage/components/McpServerTab.tsx
This pull request introduces a change to the `McpServerTab` component in `McpServerTab.tsx` to improve how the API base URL is determined. The most important updates include importing the `api` module and using its `baseURL` property as a fallback for constructing the `apiUrl`.
* [`src/frontend/src/pages/MainPage/pages/homePage/components/McpServerTab.tsx`](diffhunk://#diff-da4edd139a58d412a5bba68a4e4e84c77cf40f53711bceee9c9a12da4ea2eda8R6): Added an import for the `api` module from `@/controllers/API/api` to access the default `baseURL`.
* [`src/frontend/src/pages/MainPage/pages/homePage/components/McpServerTab.tsx`](diffhunk://#diff-da4edd139a58d412a5bba68a4e4e84c77cf40f53711bceee9c9a12da4ea2eda8L64-R67): Modified the `apiUrl` to dynamically use `api.defaults.baseURL` or fall back to …
=> fix: get backend url dynamically for mcp

src/frontend/src/customization/feature-flags.ts, src/frontend/src/modals/IOModal/components/chatView/components/chat-view.tsx
This fix disables images on playground since there is no way of handling public images by now.
* [`src/frontend/src/customization/feature-flags.ts`](diffhunk://#diff-5475ebe578c52e406769df95401c19b8e8316917f09835449aff30824262b6baL15-R15): Disabled the `ENABLE_IMAGE_ON_PLAYGROUND` feature flag by setting it to `false`. This change likely reflects a decision to temporarily or permanently turn off this feature.
=> fix: disable images on playground

src/backend/base/langflow/services/settings/base.py
Update the default method for event delivery from polling to streaming to enhance performance.
=> feat: Change default event delivery method to streaming

src/backend/base/langflow/logging/logger.py
Typo property fix
LAGFLOW_PRETTY_LOGS -> LANGFLOW_PRETTY_LOGS
=> fix: correct typo in pretty-logs property

.github/workflows/ci.yml
This pull request updates the CI workflow configuration in `.github/workflows/ci.yml` to introduce a new condition for running tests and to refine the logic for job execution. The changes primarily focus on controlling when tests are executed based on labels and event types, and ensuring proper dependencies between jobs.
* **Added `should-run-tests` output condition**: Introduced a new output, `should-run-tests`, to determine if tests should run based on the presence of the `fast-track` label or specific event types (`workflow_call`, `workflow_dispatch`, or `merge_group`). This condition is also logged for debugging purposes. (`[.github/workflows/ci.ymlR90-R98](diffhunk://#diff-b803fcb7f17ed9235f1e5cb1fcd2f5d3b2838429d4368ae4c57ce4436577f03fR90-R98)`)
* **Updated `test-backend` and …
=> chore: Update CI workflow to conditionally run tests based on the presence of a label

src/backend/base/langflow/main.py
Adds a wait to allow loguru to flush async logs. Avoids these logs on local build shutdown:
```
--- Logging error in Loguru Handler #-1 ---
Record was: {'elapsed': datetime.timedelta(seconds=95, microseconds=904420), 'exception': None, 'extra': {}, 'file': (name='manager.py', path='/Users/jordan.frazier/Documents/Langflow/langflow/src/backend/base/langflow/services/manager.py'), 'function': 'teardown', 'level': (name='DEBUG', no=10, icon='🐞'), 'line': 95, 'message': 'Teardown service storage_service', 'module': 'manager', 'name': 'langflow.services.manager', 'process': (id=12370, name='SpawnProcess-1'), 'thread': (id=8647473856, name='MainThread'), 'time': datetime(2025, 5, 5, 16, 50, 50, 397965, tzinfo=datetime.timezone(datetime.timedelta(days=-1, seconds=61200), 'PDT'))}
Traceback (most …
```
=> fix: wait on loguru to flush async logs from services

docker/build_and_push_ep.Dockerfile
Now that the default is swapped to `streaming`, we must set this env back to `polling` for DSLFv1 to operate.
=> build: add event-delivery polling for cloud image

docs/docs/Components/components-vector-stores.md
This pull request improves the existing documentation for the hybrid search functionality in the Astra DB component.
Main change:
- Added an important notice (`:::important`) clarifying that a collection must be created with vector, lexical, and rerank capabilities enabled to use hybrid search. This information was previously missing from the main flow.
- Provided a link to the official DataStax documentation for creating hybrid search collections.
- Updated step 5 to avoid redundancy with the newly added important notice.
=> docs: improve hybrid search documentation for Astra DB component

src/backend/base/langflow/services/database/models/flow/model.py
suppress warnings from migrations on the `flow` table, such as in the following:
Closes https://github.com/langflow-ai/langflow/issues/6016
Closes https://github.com/langflow-ai/langflow/issues/6944
Note that this will suppress all instances of this warning, which can be beneficial if we have a bug in the flow deletion logic where we attempt to delete a flow that doesn't exist, but as this is not business-critical logic for langflow, I believe it to be fine.
=> fix: suppress migration warnings on flow table

src/frontend/src/CustomNodes/GenericNode/components/nodeIcon/index.tsx, src/frontend/src/CustomNodes/GenericNode/index.tsx
This pull request simplifies the `NodeIcon` component in the `GenericNode` feature by removing the `hasToolMode` property and its associated logic. The changes improve maintainability by eliminating unused code and unnecessary complexity.
* Removed the `hasToolMode` property from the `NodeIcon` component's props and its usage throughout the component. This includes removing the conditional logic for `hasToolMode` in class names and styles. (`src/frontend/src/CustomNodes/GenericNode/components/nodeIcon/index.tsx`) [[1]](diffhunk://#diff-108b8898385719cca096f06d0b63e5ff9ab30ab55a020f819400c01fe2123abfL21-L27) [[2]](diffhunk://#diff-108b8898385719cca096f06d0b63e5ff9ab30ab55a020f819400c01fe2123abfL60-L66)
* Removed unused imports `BG_NOISE` and `toolModeGradient` from `styleUtils`, as they …
=> fix: removed gradient from icon when component is tool mode

src/backend/base/langflow/base/mcp/util.py
This pull request refines the `parse_type` function in `src/backend/base/langflow/base/mcp/util.py` to improve its handling of `anyOf` schemas.
Improvements to `anyOf` handling:
* Modified the `parse_type` function to simplify `anyOf` schemas by selecting the first non-null type from the subtypes. If no non-null type is found, it defaults to `str` instead of returning a tuple of types.
bug repros with this mcp server:
```
import asyncio
from fastapi import FastAPI
from fastmcp import FastMCP
from fastmcp.server.openapi import RouteMap, RouteType
api: FastAPI = FastAPI()
async def main():
mcp = FastMCP.from_fastapi(
api,
route_maps=[
RouteMap(
methods=["GET", "POST", "PUT", "PATCH", "DELETE", "OPTIONS", "HEAD"],
pattern=r".*",
route_type=RouteType.TOOL,
),
],
)
await …
```
=> fix: mcp anyOf support

src/backend/base/langflow/components/tools/mcp_component.py, src/backend/base/langflow/custom/custom_component/component.py
Ensure the proper initialisation of Tool mode variables.
______________________
This pull request introduces changes to improve tool metadata handling, refactor tool-related methods, and enhance code clarity in `mcp_component.py` and `custom_component.py`. The key updates include adding metadata initialization, simplifying metadata filtering, and refactoring the tool data construction logic.
* [`src/backend/base/langflow/components/tools/mcp_component.py`](diffhunk://#diff-8b368b159254d9a5a8ebef207dcb28d4790e3c6fcd01325b61d67bfd078b4177R502): Added an empty `metadata` dictionary to tool objects during their creation in the `update_tools` method to ensure consistent metadata initialization.
* [`src/backend/base/langflow/custom/custom_component/component.py`](diffhunk://#diff-22fd745de33f209 …
=> fix: MCP Tool mode issue

src/frontend/src/CustomNodes/GenericNode/components/NodeOutputfield/index.tsx, src/frontend/src/CustomNodes/GenericNode/components/RenderInputParameters/index.tsx, src/frontend/src/CustomNodes/GenericNode/index.tsx
This pull request focuses on improving the behavior and rendering logic of input and output fields in the `GenericNode` component. The key changes include refining the tooltip messages for output visibility, introducing a filtered list of template fields for rendering, and improving the logic for determining the visibility of outputs.
* Updated the tooltip logic in `NodeOutputfield` to display more accurate messages based on the `disabled` and `hidden` states. The tooltip now shows "Cannot hide output" when disabled, enhancing clarity for users. (`src/frontend/src/CustomNodes/GenericNode/components/NodeOutputfield/index.tsx`, [src/frontend/src/CustomNodes/GenericNode/components/NodeOutputfield/index.tsxL76-L89](diffhunk://#diff-4742b353430022eb88d35ab987d50925c592f35702319e1d476e2d53818cd7 …
=> fix: update hide outputs behavior to show current state, update disabled button UI

docs/docs/Get-Started/get-started-installation.md
This pull request updates the installation prerequisites in the `Get Started` documentation for Langflow OSS by adding hardware requirements:
`- A dual-core CPU and at least 2 GB of RAM. More intensive use requires a multi-core CPU and at least 4 GB of RAM.`
=> docs: add hardware requirements to installation prerequisites

.github/workflows/release.yml
Trim whitespace from the version check command in the release workflow to ensure accurate version comparison.
=> fix: remove whitespace in version check of release workflow

pyproject.toml, uv.lock
This pull request updates the `pyproject.toml` file to adjust dependencies and remove the project metadata section. The most significant changes involve version-specific dependency adjustments for `fastavro`.
* Updated the `fastavro` dependency to specify different versions based on the Python version: `fastavro==1.9.7` for Python versions below 3.13, and `fastavro>=1.9.8` for Python 3.13 and above.
* Removed the `[project]` metadata section, including the `name` and `version` fields, from the `pyproject.toml` file.
=> chore: Implement Python version-specific fastavro dependencies and remove project metadata

src/frontend/src/modals/fileManagerModal/components/recentFilesComponent/index.tsx
The Issue
`RectentFilesComponent` infinitely rerenders
`filesWithType` is created on each render and is a dependency for the `useEffect`
That useEffect call calls `setFuse` which triggers a rerender and we have an infinite loop
=> fix: File manager rerenders

src/backend/base/langflow/base/mcp/util.py
Switch to asynchronous file operations for improved performance in error log management, ensuring non-blocking behavior during size checks and cleanup processes.
=> fix: Use async file operations for error log management in MCPStdioClient

src/backend/base/langflow/api/v1/flows.py, src/frontend/src/components/core/appHeaderComponent/components/FlowMenu/index.tsx, src/frontend/src/components/core/editFlowSettingsComponent/index.tsx, src/frontend/src/modals/flowSettingsModal/index.tsx, src/frontend/src/pages/FlowPage/index.tsx, src/frontend/src/types/components/index.ts, src/frontend/tests/extended/features/edit-flow-name.spec.ts
This pull request introduces updates to both the backend and frontend to improve flow handling, validation, and user experience. Key changes include better handling of null or empty values for flow names and endpoint names, the addition of minimum length validation for inputs, and placeholder and default values for improved usability.
* **Flow Update Handling**:
- Updated `update_flow` in `flows.py` to explicitly handle cases where `endpoint_name` is null or an empty string, ensuring it is set to `None` in the update data.
* **Default and Placeholder Values**:
- Updated `FlowMenu` to set default flow names to "Untitled Flow" when `currentFlowName` is null or empty. This includes changes to `setFlowName` logic and the addition of a placeholder for flow name input. …
=> fix: edit flow name settings not to be empty

src/frontend/src/hooks/files/use-upload-file.ts
This pull request refines the file upload validation logic in the `useUploadFile` hook by simplifying the handling of file extensions and improving error messaging.
Validation improvements:
* [`src/frontend/src/hooks/files/use-upload-file.ts`](diffhunk://#diff-5a343839628bab9956b47ee640a69fe9b2cd564728b38a1339d025ab653b3fe1L41-R44): Removed the redundant conditional check for `file.type` when extracting the file extension, ensuring the logic is simpler and more consistent. Enhanced the error message to include the disallowed file type for better clarity.
=> fix: added check to upload .md files correctly

src/backend/base/langflow/api/v1/flows.py, src/backend/base/langflow/api/v1/voice_mode.py, src/frontend/src/controllers/API/queries/messages/use-get-messages-polling.ts, src/frontend/src/controllers/API/queries/transactions/use-get-transactions.ts, src/frontend/src/controllers/API/queries/variables/use-get-global-variables.ts, src/frontend/src/controllers/API/queries/voice/use-get-voice-list.ts, src/frontend/src/modals/IOModal/components/chatView/chatInput/components/voice-assistant/components/audio-settings/audio-settings-dialog.tsx, src/frontend/src/modals/flowLogsModal/index.tsx, src/frontend/src/stores/globalVariablesStore/globalVariables.ts, src/frontend/src/types/zustand/globalVariables/index.ts
This pull request includes several changes to improve type safety, simplify code, and enhance functionality across both the backend and frontend. Key updates include modifying queue types to use dictionaries instead of strings, simplifying the polling manager logic, and improving API query functions with better parameter handling and type safety.
* **Bug fix: Improved Type Safety in QueueCz/fix audio triggers**:
- Updated `openai_send_q` and `client_send_q` in `flow_tts_websocket` to use `asyncio.Queue[dict]` instead of `asyncio.Queue[str]`. This ensures the queues handle structured data rather than raw JSON strings. This was breaking voice mode in the playground [[1]](diffhunk://#diff-41b04dcf95abc28892d4a8e3b2e674a8c014706c6f49c95cadb76b6efaef59b4L1146-R1147) …
=> fix: voice_mode break fix

src/frontend/package-lock.json, src/frontend/src/components/core/folderSidebarComponent/components/sideBarFolderButtons/components/get-started-progress.tsx, src/frontend/src/components/core/folderSidebarComponent/components/sideBarFolderButtons/components/header-buttons.tsx, src/frontend/src/components/core/parameterRenderComponent/components/inputFileComponent/index.tsx
This pull request includes updates to the frontend codebase, focusing on dependency version upgrades, UI styling adjustments, and improved file management functionality. Below are the most important changes grouped by theme:
* Updated the `langflow` package version from `1.3.4` to `1.4.1` in `package-lock.json` to reflect the latest release.
* Changed the font weight from `font-semibold` to `font-medium` for the "Get Started Progress" title in `get-started-progress.tsx` for consistency with other UI elements.
* Updated the "Projects" text in `header-buttons.tsx` to use `font-medium` instead of `font-semibold` for uniform styling across components.
* Enhanced the file list container in `inputFileComponent/index.tsx` by adding `nopan nowheel` classes and enabling scrollable behavior with …
=> fix: add scroll and max height on chosen files on File Component, fixed font weight on start page

src/frontend/src/utils/reactflowUtils.ts
This pull request updates the `cleanEdges` function in `src/frontend/src/utils/reactflowUtils.ts` to introduce a new `tool_mode` property and adjust edge-cleaning logic to account for this property.
* Added a new `isToolMode` variable to capture the `tool_mode` property from the `template` field of the `targetNode`. (`[src/frontend/src/utils/reactflowUtils.tsR98](diffhunk://#diff-a380d7691b7dad914af3baf94d210fa2df4f56c0f8533eb0e17c29bb8dc0e91cR98)`)
* Modified the condition for filtering edges to include a check for `tool_mode` compatibility between the `targetNode` and the edge's `id`. This ensures edges are removed if the `tool_mode` property is mismatched. (`[src/frontend/src/utils/reactflowUtils.tsL127-R131](diffhunk://#diff-a380d7691b7dad914af3baf94d210fa2df4f56c0f8533eb0e17c29bb8dc0e …
=> fix: remove connected edges when enabling tool mode for them to not reconnect later

src/frontend/src/modals/fileManagerModal/components/recentFilesComponent/index.tsx, src/frontend/src/pages/MainPage/pages/homePage/index.tsx
This pull request enhances keyboard state management by adding logic to reset key states (`Shift` and `Ctrl`) under specific conditions, ensuring a consistent user experience. The changes primarily focus on handling window focus loss, component unmounting, and navigation events.
* **Reset key states on window focus loss**:
- Added a `handleBlur` function to reset `Shift` and `Ctrl` key states when the window loses focus. This is implemented in both `RecentFilesComponent` and `HomePage` components. [[1]](diffhunk://#diff-c6f351d6c91a6cc5a12366ddfba8a9201635642f6d029947c0fcc58baaef28aeR82-R98) [[2]](diffhunk://#diff-ff0f0473b212e9e2e6493c82b06f52752dd6602693587a4ead6cc8ae40bc5816R122-R140)
* **Clean up on component unmount**:
- Ensured that event listeners for `blur`, `keydown`, and `keyup` …
=> fix: made ctrl and shift state reset when switching windows to solve bulk editing issues

src/backend/base/langflow/api/v1/mcp_projects.py
This pull request modifies the query used to list project tools in the `list_project_tools` function to exclude flows that are components. 
Key change:
* [`src/backend/base/langflow/api/v1/mcp_projects.py`](diffhunk://#diff-59e508b675da2296985654fefffa69b74a00d283904743fb65f27dad798c6bd0L79-R79): Updated the `flows_query` to include a condition that filters out flows where `Flow.is_component` is `True`. This ensures that only non-component flows are included in the results.
=> fix: filter flow JSON from component JSON in MCP Servers

src/frontend/src/CustomNodes/GenericNode/components/NodeStatus/index.tsx, src/frontend/src/CustomNodes/NoteNode/NoteToolbarComponent/index.tsx, src/frontend/src/components/core/parameterRenderComponent/components/connectionComponent/index.tsx, src/frontend/src/components/core/parameterRenderComponent/components/linkComponent/index.tsx, src/frontend/src/customization/utils/custom-open-new-tab.ts, src/frontend/src/modals/IOModal/new-modal.tsx, src/frontend/src/pages/FlowPage/components/nodeToolbarComponent/index.tsx
This pull request refactors how new browser tabs are opened across the frontend codebase by introducing a centralized utility function, `customOpenNewTab`. The changes improve maintainability and consistency by replacing direct calls to `window.open` with this utility function.
* Created a new utility function `customOpenNewTab` in `src/frontend/src/customization/utils/custom-open-new-tab.ts` that wraps the existing `openInNewTab` function for standardized usage.
* Replaced calls to `window.open` with `customOpenNewTab` in the following components:
- `NodeStatus` component in `src/CustomNodes/GenericNode/components/NodeStatus/index.tsx`
- `ConnectionComponent` in `src/components/core/parameterRenderComponent/components/connectionComponent/index.tsx`
- `LinkComponent` in …
=> feat: centralize browser tab opening with customOpenNewTab utility

docs/docs/API-Reference/api-reference-api-examples.md
This PR removes duplicate entries in the API examples page introduced in [this commit](https://github.com/langflow-ai/langflow/blob/main/docs/docs/API-Reference/api-reference-api-examples.md#diff-6b419cbbea6e751a89a918b56052505eaf4239faa2770b84b06f97e6175c8a1b).
[Preview build](https://d5rxiv0do0q3v.cloudfront.net/langflow-drafts/docs-remove-duplicate-entries-in-api-examples/api-reference-api-examples#projects)
=> docs: remove duplicate entries from api examples page

.github/workflows/docker-build.yml
This pull request updates the `.github/workflows/docker-build.yml` file to include support for a new release type in the workflow logic.
Workflow updates:
* [`.github/workflows/docker-build.yml`](diffhunk://#diff-3414847e2ad632333f775cabb810f0dc0df61a570365df34750a08b00912fe82L111-R111): Added support for the `nightly-main-all` release type in the conditional logic for determining the version.
=> fix: update docker build workflow to include 'nightly-main-all' release type for versioning

src/backend/base/langflow/components/nvidia/system_assist.py
* Removed the suppressed import of `register_rise_client` and `send_rise_command` at the top of the file.
* Moved the import of `send_rise_command` into the `sys_assist_prompt` method with `contextlib.suppress(ImportError)`
Apparently this is required given the way we build components.
=> fix: g-assist import bug

src/frontend/src/icons/mistral/mistralIcon.jsx
This pull request updates the `MistralIcon` component in `src/frontend/src/icons/mistral/mistralIcon.jsx` to simplify and modernize its SVG structure. The changes include resizing the SVG canvas, updating styles for better readability, and replacing the previous complex grid of rectangles with a streamlined, color-coded design.
* **Canvas adjustments**: Updated the `viewBox` from `0 0 256 233` to `0 0 129 91` for a more compact and precise canvas size.
* **Style enhancements**: Added inline styles for `fillRule`, `clipRule`, `strokeLinejoin`, and `strokeMiterlimit` to improve SVG rendering consistency.
* **Color-coded rectangles**: Replaced the previous grid of rectangles with a simplified layout of color-coded rectangles, reducing the number of elements and improving maintainability.
* …
=> fix: changed mistral icon to new

src/frontend/src/CustomNodes/helpers/mutate-template.ts
This pull request updates the `mutate-template.ts` file to improve how node outputs are handled during template mutations. The key changes involve introducing a utility function to manage hidden outputs.
* [`src/frontend/src/CustomNodes/helpers/mutate-template.ts`](diffhunk://#diff-a65752801640d4acb83ee2c8787c474b31940dec9357cec061f4db81634b65cdR9): Added an import for the new `updateHiddenOutputs` utility function to handle hidden outputs during template mutations.
* [`src/frontend/src/CustomNodes/helpers/mutate-template.ts`](diffhunk://#diff-a65752801640d4acb83ee2c8787c474b31940dec9357cec061f4db81634b65cdL56-R60): Updated the `mutateTemplate` function to use `updateHiddenOutputs` for merging existing outputs with new template outputs, ensuring hidden outputs are preserved.
=> fix: update mutate template to preserve minimized outputs

src/frontend/src/CustomNodes/GenericNode/components/NodeOutputfield/index.tsx
This pull request updates the `InspectButton` component in `NodeOutputfield` to include a check for a `disabled` state. This ensures that the button's styles and behavior are appropriately adjusted when it is disabled.
* [`src/frontend/src/CustomNodes/GenericNode/components/NodeOutputfield/index.tsx`](diffhunk://#diff-4742b353430022eb88d35ab987d50925c592f35702319e1d476e2d53818cd795L141-R144): Added a condition to check for the `disabled` state when determining the button's classes. This prevents hover effects and adjusts the appearance when the button is disabled.
=> fix: made disabled output button not appear as clickable

src/backend/base/langflow/components/data/url.py
This pull request refactors the `fetch_content` method in `src/backend/base/langflow/components/data/url.py` to enhance error handling and replace the `requests` library with `httpx`. Key changes include improved error propagation for single URLs, expanded exception handling, and updates to the `RecursiveUrlLoader` configuration.
* Replaced the `requests` library with `httpx` for HTTP requests, updating exception handling to use `httpx`-specific error classes. (`[[1]](diffhunk://#diff-be3b89252611954c8d88cb52a4f9a322d881951fe48d1bcd31d9b6af8838d794L3-R3)`, `[[2]](diffhunk://#diff-be3b89252611954c8d88cb52a4f9a322d881951fe48d1bcd31d9b6af8838d794R179-R206)`)
* Added logic to propagate errors (e.g., HTTP errors, decoding errors, unexpected exceptions) when processing a single URL, ensuring …
=> fix: add error handling in url component

src/backend/base/langflow/services/tracing/langfuse.py
Eliminate an unnecessary client flush in the LangFuseTracer to enhance performance.
=> fix: Improve performance by removing unnecessary client flush in LangFuseTracer

src/backend/base/langflow/services/tracing/langsmith.py
Replace direct access to the run_link with a property to enhance encapsulation and maintainability.
=> fix: Refactor run_link access to avoid unnecessary external call

src/backend/base/langflow/components/data/__init__.py, src/backend/base/langflow/components/data/rss.py, src/backend/tests/unit/components/data/test_rss.py
This pull request introduces a new `RSSReaderComponent` to the codebase, enabling the parsing of RSS feeds and returning their contents in a structured format. It also includes corresponding unit tests to ensure the component's functionality and error handling. The key changes are summarized below:
* **Component Implementation**: Added the `RSSReaderComponent` class in `src/backend/base/langflow/components/data/rss.py`. This component fetches and parses RSS feeds, returning the articles as a `DataFrame`. It includes error handling for network issues and malformed feeds.
* **Component Registration**: Registered `RSSReaderComponent` in `src/backend/base/langflow/components/data/__init__.py` by importing it and adding it to the `__all__` list. …
=> feat: add rss component

src/frontend/src/pages/FlowPage/index.tsx
This pull request makes a minor update to the `FlowPage` component in `src/frontend/src/pages/FlowPage/index.tsx`. The changes improve the logic for setting the flow tab ID and ensure the `useEffect` dependency array is complete.
This fixes the problem where flows, if accessed through the main page, wouldn't get the nodes that needed update.
Key changes:
* **Logic improvement**: Updated the conditional check in the `awaitgetTypes` function to include a validation for `types` having keys, ensuring the function only runs when `types` is populated.
* **Dependency array update**: Added `types` to the dependency array of the `useEffect` hook to ensure it re-runs when `types` changes.
=> fix: updated flow pages to just set the flow if types are fetched

docs/docusaurus.config.js
This pull request updates the "Manage Privacy Choices" link in the footer to point to `https://langflow.org/preferences` instead of `/cookies`.
=> docs: cookie-banner-link

src/frontend/tests/extended/integrations/duckduckgo.spec.ts
This pull request removes an unnecessary click action in a test file to streamline the test flow.
* [`src/frontend/tests/extended/integrations/duckduckgo.spec.ts`](diffhunk://#diff-4adeafe8432cd447af72a709cfd02bf951cabc4df1e40abb0ca6b725b98e9ae8L35-L36): Removed the `fit_view` button click action, as it was redundant and did not contribute to the test outcome.
=> fix: removed fit view that caused duck duck go test to fail

src/frontend/src/components/core/folderSidebarComponent/components/sideBarFolderButtons/components/get-started-progress.tsx
This pull request refactors the logic for calculating the "Get Started" progress percentage in the `GetStartedProgress` component. The changes simplify the calculation by introducing a `stepValue` constant and restructuring the logic to increment `totalPercentage` directly for each completed step.
* [`src/frontend/src/components/core/folderSidebarComponent/components/sideBarFolderButtons/components/get-started-progress.tsx`](diffhunk://#diff-8d321fde6165c43e414eab942a430830c848898375d8ab3c1edc2e6acdcfe423L38-R58): Simplified the progress calculation by replacing the `totalSteps` and `completedSteps` logic with a `stepValue` constant and directly incrementing `totalPercentage` for each completed step. Adjusted the maximum percentage to be capped at 100 using `Math.min`.
=> fix: simplify GetStartedProgress percentage calculation logic

src/frontend/tests/extended/features/mcp-server-tab.spec.ts, src/frontend/tests/extended/features/notifications.spec.ts, src/frontend/tests/extended/regression/general-bugs-shard-3909.spec.ts
This pull request updates test cases in the frontend test suite to improve reliability and accuracy. The most significant changes include replacing the use of `.nth()` with `.last()` for better targeting of elements, refining selector conditions for improved stability, and updating text expectations to match recent UI changes.
* Updated `mcp-server-tab.spec.ts` to replace `.nth(rowsCount + 1)` with `.last()` for selecting the last input element, ensuring more robust element targeting. Additionally, added `scrollIntoViewIfNeeded()` before clicking the element for better test stability. [[1]](diffhunk://#diff-7be38a6d14c366a786e62666ed82fb46f758a4d65b76f8c486a56eb90b700e39L98-R100) [[2]](diffhunk://#diff-7be38a6d14c366a786e62666ed82fb46f758a4d65b76f8c486a56eb90b700e39L110-R111)
* Modified …
=> fix: fixes nightly tests

src/frontend/tests/extended/features/mcp-server-tab.spec.ts
This pull request updates a test script in `src/frontend/tests/extended/features/mcp-server-tab.spec.ts` to improve the reliability of element selection and interaction, and adjusts timeout durations for better synchronization.
* Added a loop to ensure the correct element is selected by repeatedly checking its `id` attribute and scrolling it into view if needed. This change enhances the reliability of selecting the last `input[data-ref="eInput"]` element.
* Increased the timeout duration from 500ms to 2000ms after filling the "input_update_name" field and after closing the modal. This change aims to improve test stability by allowing more time for UI updates.
=> fix: mcp test when there are a lot of flows

src/backend/tests/unit/build_utils.py
Increases benchmark timeouts just to get tests passing for now
=> tests: increase benchmark timeouts from 10 to 30s

src/backend/base/langflow/components/processing/regex.py, src/backend/base/langflow/components/processing/update_data.py
This pull request marks two components as legacy by adding a `legacy = True` attribute to their definitions. These changes help identify outdated components in the codebase.
* **Marking components as legacy:**
* [`src/backend/base/langflow/components/processing/regex.py`](diffhunk://#diff-2a632913895f9dc0b7c2965c3f2f57b1a28f84c35a2bfea6f6016f49b36370e0R13): Added `legacy = True` to the `RegexExtractorComponent` class.
* [`src/backend/base/langflow/components/processing/update_data.py`](diffhunk://#diff-050cb4102347879d1fece343bacd8b4dd1e3afcb0038fc38deb6588f7e34055dR23): Added `legacy = True` to the `UpdateDataComponent` class.
=> ref: Deprecate regex and update data components

src/backend/base/langflow/components/nvidia/system_assist.py
This pull request introduces a change to the `NvidiaSystemAssistComponent` class in `src/backend/base/langflow/components/nvidia/system_assist.py`. The key update ensures that the `register_rise_client` import is safely handled using `contextlib.suppress` to avoid errors if the `gassist.rise` module is unavailable.
* Wrapped the import of `register_rise_client` from `gassist.rise` in a `contextlib.suppress(ImportError)` block to prevent potential `ImportError` exceptions from disrupting the execution of the `maybe_register_rise_client` method.
=> fix: import bug

src/backend/base/langflow/initial_setup/setup.py
This pull request includes a small change to the `scape_json_parse` function in `src/backend/base/langflow/initial_setup/setup.py`. The change ensures that if the input `json_string` is `None`, the function will return an empty dictionary.
=> fix: handle empty JSON String in Template loading

src/frontend/src/components/core/flowToolbarComponent/components/deploy-dropdown.tsx
Introduce an export flow in the deploy dropdown, allowing users to access the export functionality directly from the interface.
=> feat: add export option to deploy dropdown

src/frontend/tests/core/regression/generalBugs-shard-9.spec.ts
This pull request updates the `generalBugs-shard-9.spec.ts` test file to enhance the regression tests for the frontend. The changes focus on improving test coverage for the drag-and-drop functionality, adding interactions with new UI elements, and refining test steps for better accuracy.
* Replaced the click action on `fit_view` with interactions involving the `sidebar-search-input`, including clicking, filling with "Parser", and dragging the `processingParser` element to a specific position on the flowchart canvas.
* Updated the test to include clicking on the `tab_0_retrieve` element, ensuring coverage for tab navigation functionality.
* Modified node connection steps by replacing hover and mouse down/up actions with direct click interactions on specific test IDs, such as …
=> test: enhance node connection tests in chatMemory component 

src/frontend/tests/extended/regression/generalBugs-shard-7.spec.ts
Improve input handling in the regression test by replacing placeholder selectors with data-testid attributes for better reliability and clarity.
=> test: Update regression test to use data-testid for input fields

src/frontend/tests/extended/features/notifications.spec.ts
This pull request includes a minor update to the `src/frontend/tests/extended/features/notifications.spec.ts` file. The change updates test selectors to use more descriptive names for clarity.
* Updated test selectors from `disclosure-i/o` to `disclosure-input / output` and from `input_outputText Input` to `input_outputText Input` for improved readability.
=> test: Update notification test selectors for clarity

.github/workflows/nightly_build.yml
- Updated nightly_build.yml to include OPENAI_API_KEY and ANTHROPIC_API_KEY as required secrets for the Python test job, enhancing security and ensuring proper access to necessary APIs during CI execution.
=> chore: add required API key secrets for CI workflows

src/frontend/src/CustomNodes/GenericNode/components/handleRenderComponent/index.tsx, src/frontend/src/utils/reactflowUtils.ts
This pull request introduces optimizations and refactors to improve the handling of edges in the React Flow integration. The changes primarily focus on simplifying edge-related logic and enhancing code readability.
* [`src/frontend/src/CustomNodes/GenericNode/components/handleRenderComponent/index.tsx`](diffhunk://#diff-6b00d330838431fd5fd114f3ed4159196f47f74d00a65bd4d5fa2ed70cf726fbR225-R226): Refactored edge-related logic by introducing a `useFlowStore` hook to retrieve `edges` directly, reducing redundant calls to `useFlowStore.getState()` and improving code clarity. [[1]](diffhunk://#diff-6b00d330838431fd5fd114f3ed4159196f47f74d00a65bd4d5fa2ed70cf726fbR225-R226) [[2]](diffhunk://#diff-6b00d330838431fd5fd114f3ed4159196f47f74d00a65bd4d5fa2ed70cf726fbL269-R271) …
=> fix: clean edges of same type but different name when switching outputs, update color when deleting edges

src/backend/base/langflow/components/agents/mcp_component.py
Replaced instances of SharedComponentCacheService with the more generic CacheService to improve code flexibility and maintainability. This change enhances the caching mechanism's robustness and aligns with the updated service architecture.
=> refactor: update cache service type hints in MCPToolsComponent

src/backend/base/langflow/base/mcp/util.py, src/backend/base/langflow/services/settings/base.py
Replaces hardcoded MCP session manager constants with settings-driven values for max sessions, idle timeout, and cleanup interval. Improves session reuse and cleanup logic by introducing context-to-session mapping and reference counting for backward compatibility. Enhances session connectivity validation, error handling, and adds best-effort remote session termination for SSE clients. Updates settings to expose new MCP session manager tuning parameters.
=> Refactor MCP session manager for better configurability and cleanup

src/backend/tests/unit/base/mcp/test_mcp_util.py
This pull request makes a small change to the test suite by skipping the `TestMCPStdioClientWithEverythingServer` test class. This is done by adding a `pytest.mark.skip` decorator with a reason explaining the skip.
=> chore: skip mcp everything server test

src/frontend/tests/core/integrations/SaaS Pricing.spec.ts
This pull request makes a minor adjustment to the SaaS Pricing integration test. The timeout for waiting for the "built successfully" message has been increased to reduce test flakiness and accommodate longer build times.
* Increased the timeout in `withEventDeliveryModes(` in `src/frontend/tests/core/integrations/SaaS Pricing.spec.ts` from 30 seconds to 120 seconds when waiting for "built successfully".
=> fix: increase timeout on saas pricing test

src/frontend/tests/extended/regression/generalBugs-shard-3.spec.ts
This pull request makes a small adjustment to a regression test in `generalBugs-shard-3.spec.ts`. The change updates the drag-and-drop behavior to use a specific target position and removes a redundant drag operation.
* Testing improvement: The drag-and-drop action for the node with test ID `input_outputChat Output` now targets coordinates `{ x: 400, y: 100 }` instead of `{ x: 0, y: 0 }`, and the duplicate drag operation has been removed to streamline the test.
=> fix: change chatOutput drop coordinates on general bugs test

src/backend/base/langflow/services/auth/utils.py, src/backend/base/langflow/services/utils.py
This pull request improves the handling of superuser credentials in the authentication and setup logic, ensuring consistent fallback to default values when custom credentials are not provided. The main changes clarify how the system determines which superuser username and password to use, especially when auto-login is disabled.
**Superuser credential handling:**
* Updated logic in both `create_user_longterm_token` and `setup_superuser` to consistently fall back to `DEFAULT_SUPERUSER` when no custom superuser username is configured, improving reliability and clarity. [[1]](diffhunk://#diff-d31c9154fb25c0b324fd719f128f5294e2e42b6565a61db3fa6946587aa47079R22) [[2]](diffhunk://#diff-d31c9154fb25c0b324fd719f128f5294e2e42b6565a61db3fa6946587aa47079L322-R324) …
=> refactor: enhance superuser credential handling in setup process

src/frontend/src/CustomNodes/GenericNode/components/nodeIcon/index.tsx, src/frontend/src/CustomNodes/helpers/check-lucide-icons.ts, src/frontend/tests/extended/features/mcp-server.spec.ts
This pull request makes improvements to how the MCP icon is rendered and tested, ensuring better theme support and simplifying icon color handling in the UI. The most important changes are grouped below by theme.
**Theme support and icon rendering:**
* The `SvgMcpIcon` component now sets its `fill` color dynamically based on the `isDark` prop, using white for dark mode and black for light mode, instead of always using the current color.
* The automated test for the MCP icon verifies that the icon's SVG paths have the correct fill color depending on the current theme (dark or light mode).
**Codebase simplification:**
* The `NodeIcon` component no longer calculates or passes an explicit `iconColor` to `IconComponent`, simplifying the props and color management. …
=> fix: change icon color for mcp, remove color setting of icons

src/backend/base/langflow/base/models/anthropic_constants.py
This pull request makes a minor update to the Anthropic model metadata to indicate that the `claude-3-sonnet-20240229` model is now deprecated. This helps clarify the status of the model for future development and usage.
* Marked the `claude-3-sonnet-20240229` model as deprecated by adding the `deprecated=True` flag in its metadata in `src/backend/base/langflow/base/models/anthropic_constants.py`.
=> fix: deprecate claude 3 sonnet model

src/frontend/src/pages/FlowPage/components/PageComponent/index.tsx, src/frontend/src/stores/flowStore.ts
This pull request adds comprehensive locking logic to the flow editor page, ensuring that when a flow is locked (`isLocked`), users cannot perform destructive or editing actions such as deleting, dragging, pasting, or focusing nodes and edges. These changes help prevent unintended modifications in locked mode and improve the overall user experience.
**Locking and interaction prevention:**
* Prevent deletion of nodes or edges when the flow is locked by checking `isLocked` in the `handleDelete` function (`src/frontend/src/pages/FlowPage/components/PageComponent/index.tsx`).
* Prevent drag-and-drop operations when the flow is locked by checking `isLocked` in the `onDrop` handler (`src/frontend/src/pages/FlowPage/components/PageComponent/index.tsx`).
* Prevent keyboard interactions when the …
=> fix: disable keys when flow is locked

src/backend/base/langflow/api/v1/projects.py, src/backend/tests/unit/api/v1/test_projects.py
This pull request addresses a bug where flows and components associated with a project could be lost when the project was updated (e.g., renamed). The main change is a refactor in the project update logic to reliably preserve all flows and components, along with comprehensive regression tests to ensure this behavior.
* Refactored `update_project` in `projects.py` to use a single query for all flows, then split them into flows and components in Python, ensuring no loss of associations during project updates.
* Corrected the calculation of `excluded_flows` to only exclude actual flows, not components, preventing accidental removal of flows during updates.
* Added `test_update_project_preserves_flows` to verify that renaming a project does not remove its associated flows.
* Added …
=> fix: Preserve flows and components during project updates

src/lfx/pyproject.toml, uv.lock
Update the version number in `pyproject.toml` and `uv.lock` to reflect the new release.
=> chore: Bump `lfx` version to 0.1.12

src/frontend/src/modals/IOModal/components/chatView/chatInput/components/input-wrapper.tsx
This pull request refines the behavior of the `InputWrapper` component in the chat input area to improve focus management and event handling. The changes ensure that clicking outside the textarea within the input wrapper properly focuses the textarea and places the cursor at the end, while preventing unintended side effects when interacting directly with the textarea.
**Focus and event handling improvements:**
* Updated the `onClick` handler to focus the textarea and move the cursor to the end only when clicking outside the textarea, preventing unnecessary focus changes when the textarea itself is clicked.
* Modified the `onMouseDown` handler to prevent default behavior and stop propagation only when clicking outside the textarea, improving event handling and avoiding interference with …
=> fix: make input clickable on chat 

src/backend/tests/unit/test_load_components.py
This pull request makes a minor adjustment to the unit test for component loading performance. The main change is an update to the time threshold for the `get_langflow_components_list` function to allow for a longer execution time.
* Increased the allowed duration for the `get_langflow_components_list` performance test from 5 seconds to 15 seconds in `test_load_components.py`, making the test less strict about execution time.
=> test: Increase loading performance test timeout

src/backend/base/langflow/components/processing/python_repl_core.py, src/backend/tests/unit/components/tools/test_python_repl_tool.py
This pull request updates the input handling for the `PythonREPLComponent` to better support multi-line Python code input. The main change is replacing the previous code input type with a more flexible multi-line input.
**Input Handling Improvements:**
* Replaced `CodeInput` with `MultilineInput` for the `python_code` parameter in the `PythonREPLComponent` to support multi-line code execution.
* Updated the import statement to use `MultilineInput` instead of `CodeInput` from `langflow.io`.
=> fix: Make sure strings can be parsed in the python interpreter

src/backend/base/langflow/__main__.py, src/backend/base/langflow/base/data/base_file.py
Set the `log_level` variable to avoid it being None which caused the `configure` call to fail making the default `langflow run` to fail.
=> fix: Ensure `log_level` is set correctly

src/backend/base/langflow/components/nvidia/nvidia.py, src/backend/base/langflow/interface/components.py, src/backend/tests/unit/test_load_components.py
Broadly catch exception when building components on startups. This prevents a single component from crashing Langflow.
For example, if an HTTP request is made to list models from a provider, but that provider is down, we should continue.
Later on, we'll want to surface these errors to the UI somehow, but that's a larger solution.
Patch of https://github.com/langflow-ai/langflow/pull/10037
=> fix: broadly catch exceptions when building components

.github/workflows/docker-build-v2.yml, .github/workflows/docker-nightly-build.yml, .github/workflows/release.yml
fix the linux runner group name
=> ci: fix the linux runner group name

.github/workflows/docker-build-v2.yml, .github/workflows/docker-nightly-build.yml, .github/workflows/release.yml
=> ci: fix runner labels

docs/docs/Support/release-notes.mdx
This pull request makes a minor documentation fix by correcting the markdown syntax for a warning callout in the release notes. This change improves the formatting and visibility of an important security warning for users
=> docs: fix warning syntax
